// ============================================================
// LIGA MISTRZÓW 2026/27 — ZAŚLEPKOWE dane drużyn fazy ligowej, wg
// systemu koszykowego (koszyki dokładnie ze zrzutu ekranu UEFA).
// 33 zagraniczne drużyny (koszyki 1-4, bez slotu Lecha/Górnika, który
// zajmuje sam gracz) + rywale eliminacyjni (Aarhus, Fenerbahçe, pula 8
// drużyn na 2./3. rundę). Wszyscy zawodnicy mają płaski overall = OVR
// drużyny — podmień na prawdziwe składy w tym samym formacie.
// ============================================================

window.WYZWANIA_TEAMS_DATA = window.WYZWANIA_TEAMS_DATA || [];
window.WYZWANIA_TEAMS_DATA.push(
  {
    id: 'lm-psg',
    club: 'Paris Saint-Germain',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 97 (OVR drużyny = 97).
    players: [
      { name: 'Paris Zawodnik 01', position: 'GK', overall: 97, starting: true },
      { name: 'Paris Zawodnik 02', position: 'DEF', overall: 97, starting: true },
      { name: 'Paris Zawodnik 03', position: 'DEF', overall: 97, starting: true },
      { name: 'Paris Zawodnik 04', position: 'DEF', overall: 97, starting: true },
      { name: 'Paris Zawodnik 05', position: 'DEF', overall: 97, starting: true },
      { name: 'Paris Zawodnik 06', position: 'MID', overall: 97, starting: true },
      { name: 'Paris Zawodnik 07', position: 'MID', overall: 97, starting: true },
      { name: 'Paris Zawodnik 08', position: 'MID', overall: 97, starting: true },
      { name: 'Paris Zawodnik 09', position: 'MID', overall: 97, starting: true },
      { name: 'Paris Zawodnik 10', position: 'FWD', overall: 97, starting: true },
      { name: 'Paris Zawodnik 11', position: 'FWD', overall: 97, starting: true },
    ],
  },
  {
    id: 'lm-bayern',
    club: 'Bayern Monachium',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 96 (OVR drużyny = 96).
    players: [
      { name: 'Bayern Zawodnik 01', position: 'GK', overall: 96, starting: true },
      { name: 'Bayern Zawodnik 02', position: 'DEF', overall: 96, starting: true },
      { name: 'Bayern Zawodnik 03', position: 'DEF', overall: 96, starting: true },
      { name: 'Bayern Zawodnik 04', position: 'DEF', overall: 96, starting: true },
      { name: 'Bayern Zawodnik 05', position: 'DEF', overall: 96, starting: true },
      { name: 'Bayern Zawodnik 06', position: 'MID', overall: 96, starting: true },
      { name: 'Bayern Zawodnik 07', position: 'MID', overall: 96, starting: true },
      { name: 'Bayern Zawodnik 08', position: 'MID', overall: 96, starting: true },
      { name: 'Bayern Zawodnik 09', position: 'MID', overall: 96, starting: true },
      { name: 'Bayern Zawodnik 10', position: 'FWD', overall: 96, starting: true },
      { name: 'Bayern Zawodnik 11', position: 'FWD', overall: 96, starting: true },
    ],
  },
  {
    id: 'lm-real-madryt',
    club: 'Real Madryt',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 96 (OVR drużyny = 96).
    players: [
      { name: 'Real Zawodnik 01', position: 'GK', overall: 96, starting: true },
      { name: 'Real Zawodnik 02', position: 'DEF', overall: 96, starting: true },
      { name: 'Real Zawodnik 03', position: 'DEF', overall: 96, starting: true },
      { name: 'Real Zawodnik 04', position: 'DEF', overall: 96, starting: true },
      { name: 'Real Zawodnik 05', position: 'DEF', overall: 96, starting: true },
      { name: 'Real Zawodnik 06', position: 'MID', overall: 96, starting: true },
      { name: 'Real Zawodnik 07', position: 'MID', overall: 96, starting: true },
      { name: 'Real Zawodnik 08', position: 'MID', overall: 96, starting: true },
      { name: 'Real Zawodnik 09', position: 'MID', overall: 96, starting: true },
      { name: 'Real Zawodnik 10', position: 'FWD', overall: 96, starting: true },
      { name: 'Real Zawodnik 11', position: 'FWD', overall: 96, starting: true },
    ],
  },
  {
    id: 'lm-liverpool',
    club: 'Liverpool FC',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 95 (OVR drużyny = 95).
    players: [
      { name: 'Liverpool Zawodnik 01', position: 'GK', overall: 95, starting: true },
      { name: 'Liverpool Zawodnik 02', position: 'DEF', overall: 95, starting: true },
      { name: 'Liverpool Zawodnik 03', position: 'DEF', overall: 95, starting: true },
      { name: 'Liverpool Zawodnik 04', position: 'DEF', overall: 95, starting: true },
      { name: 'Liverpool Zawodnik 05', position: 'DEF', overall: 95, starting: true },
      { name: 'Liverpool Zawodnik 06', position: 'MID', overall: 95, starting: true },
      { name: 'Liverpool Zawodnik 07', position: 'MID', overall: 95, starting: true },
      { name: 'Liverpool Zawodnik 08', position: 'MID', overall: 95, starting: true },
      { name: 'Liverpool Zawodnik 09', position: 'MID', overall: 95, starting: true },
      { name: 'Liverpool Zawodnik 10', position: 'FWD', overall: 95, starting: true },
      { name: 'Liverpool Zawodnik 11', position: 'FWD', overall: 95, starting: true },
    ],
  },
  {
    id: 'lm-inter',
    club: 'Inter Mediolan',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 94 (OVR drużyny = 94).
    players: [
      { name: 'Inter Zawodnik 01', position: 'GK', overall: 94, starting: true },
      { name: 'Inter Zawodnik 02', position: 'DEF', overall: 94, starting: true },
      { name: 'Inter Zawodnik 03', position: 'DEF', overall: 94, starting: true },
      { name: 'Inter Zawodnik 04', position: 'DEF', overall: 94, starting: true },
      { name: 'Inter Zawodnik 05', position: 'DEF', overall: 94, starting: true },
      { name: 'Inter Zawodnik 06', position: 'MID', overall: 94, starting: true },
      { name: 'Inter Zawodnik 07', position: 'MID', overall: 94, starting: true },
      { name: 'Inter Zawodnik 08', position: 'MID', overall: 94, starting: true },
      { name: 'Inter Zawodnik 09', position: 'MID', overall: 94, starting: true },
      { name: 'Inter Zawodnik 10', position: 'FWD', overall: 94, starting: true },
      { name: 'Inter Zawodnik 11', position: 'FWD', overall: 94, starting: true },
    ],
  },
  {
    id: 'lm-man-city',
    club: 'Manchester City',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 94 (OVR drużyny = 94).
    players: [
      { name: 'Manchester Zawodnik 01', position: 'GK', overall: 94, starting: true },
      { name: 'Manchester Zawodnik 02', position: 'DEF', overall: 94, starting: true },
      { name: 'Manchester Zawodnik 03', position: 'DEF', overall: 94, starting: true },
      { name: 'Manchester Zawodnik 04', position: 'DEF', overall: 94, starting: true },
      { name: 'Manchester Zawodnik 05', position: 'DEF', overall: 94, starting: true },
      { name: 'Manchester Zawodnik 06', position: 'MID', overall: 94, starting: true },
      { name: 'Manchester Zawodnik 07', position: 'MID', overall: 94, starting: true },
      { name: 'Manchester Zawodnik 08', position: 'MID', overall: 94, starting: true },
      { name: 'Manchester Zawodnik 09', position: 'MID', overall: 94, starting: true },
      { name: 'Manchester Zawodnik 10', position: 'FWD', overall: 94, starting: true },
      { name: 'Manchester Zawodnik 11', position: 'FWD', overall: 94, starting: true },
    ],
  },
  {
    id: 'lm-arsenal',
    club: 'Arsenal FC',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 93 (OVR drużyny = 93).
    players: [
      { name: 'Arsenal Zawodnik 01', position: 'GK', overall: 93, starting: true },
      { name: 'Arsenal Zawodnik 02', position: 'DEF', overall: 93, starting: true },
      { name: 'Arsenal Zawodnik 03', position: 'DEF', overall: 93, starting: true },
      { name: 'Arsenal Zawodnik 04', position: 'DEF', overall: 93, starting: true },
      { name: 'Arsenal Zawodnik 05', position: 'DEF', overall: 93, starting: true },
      { name: 'Arsenal Zawodnik 06', position: 'MID', overall: 93, starting: true },
      { name: 'Arsenal Zawodnik 07', position: 'MID', overall: 93, starting: true },
      { name: 'Arsenal Zawodnik 08', position: 'MID', overall: 93, starting: true },
      { name: 'Arsenal Zawodnik 09', position: 'MID', overall: 93, starting: true },
      { name: 'Arsenal Zawodnik 10', position: 'FWD', overall: 93, starting: true },
      { name: 'Arsenal Zawodnik 11', position: 'FWD', overall: 93, starting: true },
    ],
  },
  {
    id: 'lm-barcelona',
    club: 'FC Barcelona',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 92 (OVR drużyny = 92).
    players: [
      { name: 'FC Zawodnik 01', position: 'GK', overall: 92, starting: true },
      { name: 'FC Zawodnik 02', position: 'DEF', overall: 92, starting: true },
      { name: 'FC Zawodnik 03', position: 'DEF', overall: 92, starting: true },
      { name: 'FC Zawodnik 04', position: 'DEF', overall: 92, starting: true },
      { name: 'FC Zawodnik 05', position: 'DEF', overall: 92, starting: true },
      { name: 'FC Zawodnik 06', position: 'MID', overall: 92, starting: true },
      { name: 'FC Zawodnik 07', position: 'MID', overall: 92, starting: true },
      { name: 'FC Zawodnik 08', position: 'MID', overall: 92, starting: true },
      { name: 'FC Zawodnik 09', position: 'MID', overall: 92, starting: true },
      { name: 'FC Zawodnik 10', position: 'FWD', overall: 92, starting: true },
      { name: 'FC Zawodnik 11', position: 'FWD', overall: 92, starting: true },
    ],
  },
  {
    id: 'lm-atletico',
    club: 'Atlético Madryt',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 91 (OVR drużyny = 91).
    players: [
      { name: 'Atlético Zawodnik 01', position: 'GK', overall: 91, starting: true },
      { name: 'Atlético Zawodnik 02', position: 'DEF', overall: 91, starting: true },
      { name: 'Atlético Zawodnik 03', position: 'DEF', overall: 91, starting: true },
      { name: 'Atlético Zawodnik 04', position: 'DEF', overall: 91, starting: true },
      { name: 'Atlético Zawodnik 05', position: 'DEF', overall: 91, starting: true },
      { name: 'Atlético Zawodnik 06', position: 'MID', overall: 91, starting: true },
      { name: 'Atlético Zawodnik 07', position: 'MID', overall: 91, starting: true },
      { name: 'Atlético Zawodnik 08', position: 'MID', overall: 91, starting: true },
      { name: 'Atlético Zawodnik 09', position: 'MID', overall: 91, starting: true },
      { name: 'Atlético Zawodnik 10', position: 'FWD', overall: 91, starting: true },
      { name: 'Atlético Zawodnik 11', position: 'FWD', overall: 91, starting: true },
    ],
  },
  {
    id: 'lm-borussia',
    club: 'Borussia Dortmund',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 89 (OVR drużyny = 89).
    players: [
      { name: 'Borussia Zawodnik 01', position: 'GK', overall: 89, starting: true },
      { name: 'Borussia Zawodnik 02', position: 'DEF', overall: 89, starting: true },
      { name: 'Borussia Zawodnik 03', position: 'DEF', overall: 89, starting: true },
      { name: 'Borussia Zawodnik 04', position: 'DEF', overall: 89, starting: true },
      { name: 'Borussia Zawodnik 05', position: 'DEF', overall: 89, starting: true },
      { name: 'Borussia Zawodnik 06', position: 'MID', overall: 89, starting: true },
      { name: 'Borussia Zawodnik 07', position: 'MID', overall: 89, starting: true },
      { name: 'Borussia Zawodnik 08', position: 'MID', overall: 89, starting: true },
      { name: 'Borussia Zawodnik 09', position: 'MID', overall: 89, starting: true },
      { name: 'Borussia Zawodnik 10', position: 'FWD', overall: 89, starting: true },
      { name: 'Borussia Zawodnik 11', position: 'FWD', overall: 89, starting: true },
    ],
  },
  {
    id: 'lm-roma',
    club: 'AS Roma',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 88 (OVR drużyny = 88).
    players: [
      { name: 'AS Zawodnik 01', position: 'GK', overall: 88, starting: true },
      { name: 'AS Zawodnik 02', position: 'DEF', overall: 88, starting: true },
      { name: 'AS Zawodnik 03', position: 'DEF', overall: 88, starting: true },
      { name: 'AS Zawodnik 04', position: 'DEF', overall: 88, starting: true },
      { name: 'AS Zawodnik 05', position: 'DEF', overall: 88, starting: true },
      { name: 'AS Zawodnik 06', position: 'MID', overall: 88, starting: true },
      { name: 'AS Zawodnik 07', position: 'MID', overall: 88, starting: true },
      { name: 'AS Zawodnik 08', position: 'MID', overall: 88, starting: true },
      { name: 'AS Zawodnik 09', position: 'MID', overall: 88, starting: true },
      { name: 'AS Zawodnik 10', position: 'FWD', overall: 88, starting: true },
      { name: 'AS Zawodnik 11', position: 'FWD', overall: 88, starting: true },
    ],
  },
  {
    id: 'lm-sporting',
    club: 'Sporting CP',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 87 (OVR drużyny = 87).
    players: [
      { name: 'Sporting Zawodnik 01', position: 'GK', overall: 87, starting: true },
      { name: 'Sporting Zawodnik 02', position: 'DEF', overall: 87, starting: true },
      { name: 'Sporting Zawodnik 03', position: 'DEF', overall: 87, starting: true },
      { name: 'Sporting Zawodnik 04', position: 'DEF', overall: 87, starting: true },
      { name: 'Sporting Zawodnik 05', position: 'DEF', overall: 87, starting: true },
      { name: 'Sporting Zawodnik 06', position: 'MID', overall: 87, starting: true },
      { name: 'Sporting Zawodnik 07', position: 'MID', overall: 87, starting: true },
      { name: 'Sporting Zawodnik 08', position: 'MID', overall: 87, starting: true },
      { name: 'Sporting Zawodnik 09', position: 'MID', overall: 87, starting: true },
      { name: 'Sporting Zawodnik 10', position: 'FWD', overall: 87, starting: true },
      { name: 'Sporting Zawodnik 11', position: 'FWD', overall: 87, starting: true },
    ],
  },
  {
    id: 'lm-aston-villa',
    club: 'Aston Villa',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 87 (OVR drużyny = 87).
    players: [
      { name: 'Aston Zawodnik 01', position: 'GK', overall: 87, starting: true },
      { name: 'Aston Zawodnik 02', position: 'DEF', overall: 87, starting: true },
      { name: 'Aston Zawodnik 03', position: 'DEF', overall: 87, starting: true },
      { name: 'Aston Zawodnik 04', position: 'DEF', overall: 87, starting: true },
      { name: 'Aston Zawodnik 05', position: 'DEF', overall: 87, starting: true },
      { name: 'Aston Zawodnik 06', position: 'MID', overall: 87, starting: true },
      { name: 'Aston Zawodnik 07', position: 'MID', overall: 87, starting: true },
      { name: 'Aston Zawodnik 08', position: 'MID', overall: 87, starting: true },
      { name: 'Aston Zawodnik 09', position: 'MID', overall: 87, starting: true },
      { name: 'Aston Zawodnik 10', position: 'FWD', overall: 87, starting: true },
      { name: 'Aston Zawodnik 11', position: 'FWD', overall: 87, starting: true },
    ],
  },
  {
    id: 'lm-porto',
    club: 'FC Porto',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 86 (OVR drużyny = 86).
    players: [
      { name: 'FC Zawodnik 01', position: 'GK', overall: 86, starting: true },
      { name: 'FC Zawodnik 02', position: 'DEF', overall: 86, starting: true },
      { name: 'FC Zawodnik 03', position: 'DEF', overall: 86, starting: true },
      { name: 'FC Zawodnik 04', position: 'DEF', overall: 86, starting: true },
      { name: 'FC Zawodnik 05', position: 'DEF', overall: 86, starting: true },
      { name: 'FC Zawodnik 06', position: 'MID', overall: 86, starting: true },
      { name: 'FC Zawodnik 07', position: 'MID', overall: 86, starting: true },
      { name: 'FC Zawodnik 08', position: 'MID', overall: 86, starting: true },
      { name: 'FC Zawodnik 09', position: 'MID', overall: 86, starting: true },
      { name: 'FC Zawodnik 10', position: 'FWD', overall: 86, starting: true },
      { name: 'FC Zawodnik 11', position: 'FWD', overall: 86, starting: true },
    ],
  },
  {
    id: 'lm-man-utd',
    club: 'Manchester United',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 86 (OVR drużyny = 86).
    players: [
      { name: 'Manchester Zawodnik 01', position: 'GK', overall: 86, starting: true },
      { name: 'Manchester Zawodnik 02', position: 'DEF', overall: 86, starting: true },
      { name: 'Manchester Zawodnik 03', position: 'DEF', overall: 86, starting: true },
      { name: 'Manchester Zawodnik 04', position: 'DEF', overall: 86, starting: true },
      { name: 'Manchester Zawodnik 05', position: 'DEF', overall: 86, starting: true },
      { name: 'Manchester Zawodnik 06', position: 'MID', overall: 86, starting: true },
      { name: 'Manchester Zawodnik 07', position: 'MID', overall: 86, starting: true },
      { name: 'Manchester Zawodnik 08', position: 'MID', overall: 86, starting: true },
      { name: 'Manchester Zawodnik 09', position: 'MID', overall: 86, starting: true },
      { name: 'Manchester Zawodnik 10', position: 'FWD', overall: 86, starting: true },
      { name: 'Manchester Zawodnik 11', position: 'FWD', overall: 86, starting: true },
    ],
  },
  {
    id: 'lm-brugge',
    club: 'Club Brugge',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 85 (OVR drużyny = 85).
    players: [
      { name: 'Club Zawodnik 01', position: 'GK', overall: 85, starting: true },
      { name: 'Club Zawodnik 02', position: 'DEF', overall: 85, starting: true },
      { name: 'Club Zawodnik 03', position: 'DEF', overall: 85, starting: true },
      { name: 'Club Zawodnik 04', position: 'DEF', overall: 85, starting: true },
      { name: 'Club Zawodnik 05', position: 'DEF', overall: 85, starting: true },
      { name: 'Club Zawodnik 06', position: 'MID', overall: 85, starting: true },
      { name: 'Club Zawodnik 07', position: 'MID', overall: 85, starting: true },
      { name: 'Club Zawodnik 08', position: 'MID', overall: 85, starting: true },
      { name: 'Club Zawodnik 09', position: 'MID', overall: 85, starting: true },
      { name: 'Club Zawodnik 10', position: 'FWD', overall: 85, starting: true },
      { name: 'Club Zawodnik 11', position: 'FWD', overall: 85, starting: true },
    ],
  },
  {
    id: 'lm-betis',
    club: 'Real Betis',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 85 (OVR drużyny = 85).
    players: [
      { name: 'Real Zawodnik 01', position: 'GK', overall: 85, starting: true },
      { name: 'Real Zawodnik 02', position: 'DEF', overall: 85, starting: true },
      { name: 'Real Zawodnik 03', position: 'DEF', overall: 85, starting: true },
      { name: 'Real Zawodnik 04', position: 'DEF', overall: 85, starting: true },
      { name: 'Real Zawodnik 05', position: 'DEF', overall: 85, starting: true },
      { name: 'Real Zawodnik 06', position: 'MID', overall: 85, starting: true },
      { name: 'Real Zawodnik 07', position: 'MID', overall: 85, starting: true },
      { name: 'Real Zawodnik 08', position: 'MID', overall: 85, starting: true },
      { name: 'Real Zawodnik 09', position: 'MID', overall: 85, starting: true },
      { name: 'Real Zawodnik 10', position: 'FWD', overall: 85, starting: true },
      { name: 'Real Zawodnik 11', position: 'FWD', overall: 85, starting: true },
    ],
  },
  {
    id: 'lm-psv',
    club: 'PSV Eindhoven',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 84 (OVR drużyny = 84).
    players: [
      { name: 'PSV Zawodnik 01', position: 'GK', overall: 84, starting: true },
      { name: 'PSV Zawodnik 02', position: 'DEF', overall: 84, starting: true },
      { name: 'PSV Zawodnik 03', position: 'DEF', overall: 84, starting: true },
      { name: 'PSV Zawodnik 04', position: 'DEF', overall: 84, starting: true },
      { name: 'PSV Zawodnik 05', position: 'DEF', overall: 84, starting: true },
      { name: 'PSV Zawodnik 06', position: 'MID', overall: 84, starting: true },
      { name: 'PSV Zawodnik 07', position: 'MID', overall: 84, starting: true },
      { name: 'PSV Zawodnik 08', position: 'MID', overall: 84, starting: true },
      { name: 'PSV Zawodnik 09', position: 'MID', overall: 84, starting: true },
      { name: 'PSV Zawodnik 10', position: 'FWD', overall: 84, starting: true },
      { name: 'PSV Zawodnik 11', position: 'FWD', overall: 84, starting: true },
    ],
  },
  {
    id: 'lm-feyenoord',
    club: 'Feyenoord Rotterdam',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 82 (OVR drużyny = 82).
    players: [
      { name: 'Feyenoord Zawodnik 01', position: 'GK', overall: 82, starting: true },
      { name: 'Feyenoord Zawodnik 02', position: 'DEF', overall: 82, starting: true },
      { name: 'Feyenoord Zawodnik 03', position: 'DEF', overall: 82, starting: true },
      { name: 'Feyenoord Zawodnik 04', position: 'DEF', overall: 82, starting: true },
      { name: 'Feyenoord Zawodnik 05', position: 'DEF', overall: 82, starting: true },
      { name: 'Feyenoord Zawodnik 06', position: 'MID', overall: 82, starting: true },
      { name: 'Feyenoord Zawodnik 07', position: 'MID', overall: 82, starting: true },
      { name: 'Feyenoord Zawodnik 08', position: 'MID', overall: 82, starting: true },
      { name: 'Feyenoord Zawodnik 09', position: 'MID', overall: 82, starting: true },
      { name: 'Feyenoord Zawodnik 10', position: 'FWD', overall: 82, starting: true },
      { name: 'Feyenoord Zawodnik 11', position: 'FWD', overall: 82, starting: true },
    ],
  },
  {
    id: 'lm-lille',
    club: 'Lille OSC',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 81 (OVR drużyny = 81).
    players: [
      { name: 'Lille Zawodnik 01', position: 'GK', overall: 81, starting: true },
      { name: 'Lille Zawodnik 02', position: 'DEF', overall: 81, starting: true },
      { name: 'Lille Zawodnik 03', position: 'DEF', overall: 81, starting: true },
      { name: 'Lille Zawodnik 04', position: 'DEF', overall: 81, starting: true },
      { name: 'Lille Zawodnik 05', position: 'DEF', overall: 81, starting: true },
      { name: 'Lille Zawodnik 06', position: 'MID', overall: 81, starting: true },
      { name: 'Lille Zawodnik 07', position: 'MID', overall: 81, starting: true },
      { name: 'Lille Zawodnik 08', position: 'MID', overall: 81, starting: true },
      { name: 'Lille Zawodnik 09', position: 'MID', overall: 81, starting: true },
      { name: 'Lille Zawodnik 10', position: 'FWD', overall: 81, starting: true },
      { name: 'Lille Zawodnik 11', position: 'FWD', overall: 81, starting: true },
    ],
  },
  {
    id: 'lm-lyon',
    club: 'Olympique Lyon',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 81 (OVR drużyny = 81).
    players: [
      { name: 'Olympique Zawodnik 01', position: 'GK', overall: 81, starting: true },
      { name: 'Olympique Zawodnik 02', position: 'DEF', overall: 81, starting: true },
      { name: 'Olympique Zawodnik 03', position: 'DEF', overall: 81, starting: true },
      { name: 'Olympique Zawodnik 04', position: 'DEF', overall: 81, starting: true },
      { name: 'Olympique Zawodnik 05', position: 'DEF', overall: 81, starting: true },
      { name: 'Olympique Zawodnik 06', position: 'MID', overall: 81, starting: true },
      { name: 'Olympique Zawodnik 07', position: 'MID', overall: 81, starting: true },
      { name: 'Olympique Zawodnik 08', position: 'MID', overall: 81, starting: true },
      { name: 'Olympique Zawodnik 09', position: 'MID', overall: 81, starting: true },
      { name: 'Olympique Zawodnik 10', position: 'FWD', overall: 81, starting: true },
      { name: 'Olympique Zawodnik 11', position: 'FWD', overall: 81, starting: true },
    ],
  },
  {
    id: 'lm-bodo',
    club: 'Bodø/Glimt',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 80 (OVR drużyny = 80).
    players: [
      { name: 'Bodø/Glimt Zawodnik 01', position: 'GK', overall: 80, starting: true },
      { name: 'Bodø/Glimt Zawodnik 02', position: 'DEF', overall: 80, starting: true },
      { name: 'Bodø/Glimt Zawodnik 03', position: 'DEF', overall: 80, starting: true },
      { name: 'Bodø/Glimt Zawodnik 04', position: 'DEF', overall: 80, starting: true },
      { name: 'Bodø/Glimt Zawodnik 05', position: 'DEF', overall: 80, starting: true },
      { name: 'Bodø/Glimt Zawodnik 06', position: 'MID', overall: 80, starting: true },
      { name: 'Bodø/Glimt Zawodnik 07', position: 'MID', overall: 80, starting: true },
      { name: 'Bodø/Glimt Zawodnik 08', position: 'MID', overall: 80, starting: true },
      { name: 'Bodø/Glimt Zawodnik 09', position: 'MID', overall: 80, starting: true },
      { name: 'Bodø/Glimt Zawodnik 10', position: 'FWD', overall: 80, starting: true },
      { name: 'Bodø/Glimt Zawodnik 11', position: 'FWD', overall: 80, starting: true },
    ],
  },
  {
    id: 'lm-napoli',
    club: 'SSC Napoli',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 80 (OVR drużyny = 80).
    players: [
      { name: 'SSC Zawodnik 01', position: 'GK', overall: 80, starting: true },
      { name: 'SSC Zawodnik 02', position: 'DEF', overall: 80, starting: true },
      { name: 'SSC Zawodnik 03', position: 'DEF', overall: 80, starting: true },
      { name: 'SSC Zawodnik 04', position: 'DEF', overall: 80, starting: true },
      { name: 'SSC Zawodnik 05', position: 'DEF', overall: 80, starting: true },
      { name: 'SSC Zawodnik 06', position: 'MID', overall: 80, starting: true },
      { name: 'SSC Zawodnik 07', position: 'MID', overall: 80, starting: true },
      { name: 'SSC Zawodnik 08', position: 'MID', overall: 80, starting: true },
      { name: 'SSC Zawodnik 09', position: 'MID', overall: 80, starting: true },
      { name: 'SSC Zawodnik 10', position: 'FWD', overall: 80, starting: true },
      { name: 'SSC Zawodnik 11', position: 'FWD', overall: 80, starting: true },
    ],
  },
  {
    id: 'lm-leipzig',
    club: 'RB Leipzig',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 79 (OVR drużyny = 79).
    players: [
      { name: 'RB Zawodnik 01', position: 'GK', overall: 79, starting: true },
      { name: 'RB Zawodnik 02', position: 'DEF', overall: 79, starting: true },
      { name: 'RB Zawodnik 03', position: 'DEF', overall: 79, starting: true },
      { name: 'RB Zawodnik 04', position: 'DEF', overall: 79, starting: true },
      { name: 'RB Zawodnik 05', position: 'DEF', overall: 79, starting: true },
      { name: 'RB Zawodnik 06', position: 'MID', overall: 79, starting: true },
      { name: 'RB Zawodnik 07', position: 'MID', overall: 79, starting: true },
      { name: 'RB Zawodnik 08', position: 'MID', overall: 79, starting: true },
      { name: 'RB Zawodnik 09', position: 'MID', overall: 79, starting: true },
      { name: 'RB Zawodnik 10', position: 'FWD', overall: 79, starting: true },
      { name: 'RB Zawodnik 11', position: 'FWD', overall: 79, starting: true },
    ],
  },
  {
    id: 'lm-villarreal',
    club: 'Villarreal CF',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 79 (OVR drużyny = 79).
    players: [
      { name: 'Villarreal Zawodnik 01', position: 'GK', overall: 79, starting: true },
      { name: 'Villarreal Zawodnik 02', position: 'DEF', overall: 79, starting: true },
      { name: 'Villarreal Zawodnik 03', position: 'DEF', overall: 79, starting: true },
      { name: 'Villarreal Zawodnik 04', position: 'DEF', overall: 79, starting: true },
      { name: 'Villarreal Zawodnik 05', position: 'DEF', overall: 79, starting: true },
      { name: 'Villarreal Zawodnik 06', position: 'MID', overall: 79, starting: true },
      { name: 'Villarreal Zawodnik 07', position: 'MID', overall: 79, starting: true },
      { name: 'Villarreal Zawodnik 08', position: 'MID', overall: 79, starting: true },
      { name: 'Villarreal Zawodnik 09', position: 'MID', overall: 79, starting: true },
      { name: 'Villarreal Zawodnik 10', position: 'FWD', overall: 79, starting: true },
      { name: 'Villarreal Zawodnik 11', position: 'FWD', overall: 79, starting: true },
    ],
  },
  {
    id: 'lm-shakhtar',
    club: 'Shakhtar Donieck',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 77 (OVR drużyny = 77).
    players: [
      { name: 'Shakhtar Zawodnik 01', position: 'GK', overall: 77, starting: true },
      { name: 'Shakhtar Zawodnik 02', position: 'DEF', overall: 77, starting: true },
      { name: 'Shakhtar Zawodnik 03', position: 'DEF', overall: 77, starting: true },
      { name: 'Shakhtar Zawodnik 04', position: 'DEF', overall: 77, starting: true },
      { name: 'Shakhtar Zawodnik 05', position: 'DEF', overall: 77, starting: true },
      { name: 'Shakhtar Zawodnik 06', position: 'MID', overall: 77, starting: true },
      { name: 'Shakhtar Zawodnik 07', position: 'MID', overall: 77, starting: true },
      { name: 'Shakhtar Zawodnik 08', position: 'MID', overall: 77, starting: true },
      { name: 'Shakhtar Zawodnik 09', position: 'MID', overall: 77, starting: true },
      { name: 'Shakhtar Zawodnik 10', position: 'FWD', overall: 77, starting: true },
      { name: 'Shakhtar Zawodnik 11', position: 'FWD', overall: 77, starting: true },
    ],
  },
  {
    id: 'lm-galatasaray',
    club: 'Galatasaray Stambuł',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 77 (OVR drużyny = 77).
    players: [
      { name: 'Galatasaray Zawodnik 01', position: 'GK', overall: 77, starting: true },
      { name: 'Galatasaray Zawodnik 02', position: 'DEF', overall: 77, starting: true },
      { name: 'Galatasaray Zawodnik 03', position: 'DEF', overall: 77, starting: true },
      { name: 'Galatasaray Zawodnik 04', position: 'DEF', overall: 77, starting: true },
      { name: 'Galatasaray Zawodnik 05', position: 'DEF', overall: 77, starting: true },
      { name: 'Galatasaray Zawodnik 06', position: 'MID', overall: 77, starting: true },
      { name: 'Galatasaray Zawodnik 07', position: 'MID', overall: 77, starting: true },
      { name: 'Galatasaray Zawodnik 08', position: 'MID', overall: 77, starting: true },
      { name: 'Galatasaray Zawodnik 09', position: 'MID', overall: 77, starting: true },
      { name: 'Galatasaray Zawodnik 10', position: 'FWD', overall: 77, starting: true },
      { name: 'Galatasaray Zawodnik 11', position: 'FWD', overall: 77, starting: true },
    ],
  },
  {
    id: 'lm-crvena',
    club: 'Crvena zvezda',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 70 (OVR drużyny = 70).
    players: [
      { name: 'Crvena Zawodnik 01', position: 'GK', overall: 70, starting: true },
      { name: 'Crvena Zawodnik 02', position: 'DEF', overall: 70, starting: true },
      { name: 'Crvena Zawodnik 03', position: 'DEF', overall: 70, starting: true },
      { name: 'Crvena Zawodnik 04', position: 'DEF', overall: 70, starting: true },
      { name: 'Crvena Zawodnik 05', position: 'DEF', overall: 70, starting: true },
      { name: 'Crvena Zawodnik 06', position: 'MID', overall: 70, starting: true },
      { name: 'Crvena Zawodnik 07', position: 'MID', overall: 70, starting: true },
      { name: 'Crvena Zawodnik 08', position: 'MID', overall: 70, starting: true },
      { name: 'Crvena Zawodnik 09', position: 'MID', overall: 70, starting: true },
      { name: 'Crvena Zawodnik 10', position: 'FWD', overall: 70, starting: true },
      { name: 'Crvena Zawodnik 11', position: 'FWD', overall: 70, starting: true },
    ],
  },
  {
    id: 'lm-dinamo-zg',
    club: 'Dinamo Zagrzeb',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 70 (OVR drużyny = 70).
    players: [
      { name: 'Dinamo Zawodnik 01', position: 'GK', overall: 70, starting: true },
      { name: 'Dinamo Zawodnik 02', position: 'DEF', overall: 70, starting: true },
      { name: 'Dinamo Zawodnik 03', position: 'DEF', overall: 70, starting: true },
      { name: 'Dinamo Zawodnik 04', position: 'DEF', overall: 70, starting: true },
      { name: 'Dinamo Zawodnik 05', position: 'DEF', overall: 70, starting: true },
      { name: 'Dinamo Zawodnik 06', position: 'MID', overall: 70, starting: true },
      { name: 'Dinamo Zawodnik 07', position: 'MID', overall: 70, starting: true },
      { name: 'Dinamo Zawodnik 08', position: 'MID', overall: 70, starting: true },
      { name: 'Dinamo Zawodnik 09', position: 'MID', overall: 70, starting: true },
      { name: 'Dinamo Zawodnik 10', position: 'FWD', overall: 70, starting: true },
      { name: 'Dinamo Zawodnik 11', position: 'FWD', overall: 70, starting: true },
    ],
  },
  {
    id: 'lm-celtic',
    club: 'Celtic FC',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 72 (OVR drużyny = 72).
    players: [
      { name: 'Celtic Zawodnik 01', position: 'GK', overall: 72, starting: true },
      { name: 'Celtic Zawodnik 02', position: 'DEF', overall: 72, starting: true },
      { name: 'Celtic Zawodnik 03', position: 'DEF', overall: 72, starting: true },
      { name: 'Celtic Zawodnik 04', position: 'DEF', overall: 72, starting: true },
      { name: 'Celtic Zawodnik 05', position: 'DEF', overall: 72, starting: true },
      { name: 'Celtic Zawodnik 06', position: 'MID', overall: 72, starting: true },
      { name: 'Celtic Zawodnik 07', position: 'MID', overall: 72, starting: true },
      { name: 'Celtic Zawodnik 08', position: 'MID', overall: 72, starting: true },
      { name: 'Celtic Zawodnik 09', position: 'MID', overall: 72, starting: true },
      { name: 'Celtic Zawodnik 10', position: 'FWD', overall: 72, starting: true },
      { name: 'Celtic Zawodnik 11', position: 'FWD', overall: 72, starting: true },
    ],
  },
  {
    id: 'lm-slavia',
    club: 'Slavia Praga',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 71 (OVR drużyny = 71).
    players: [
      { name: 'Slavia Zawodnik 01', position: 'GK', overall: 71, starting: true },
      { name: 'Slavia Zawodnik 02', position: 'DEF', overall: 71, starting: true },
      { name: 'Slavia Zawodnik 03', position: 'DEF', overall: 71, starting: true },
      { name: 'Slavia Zawodnik 04', position: 'DEF', overall: 71, starting: true },
      { name: 'Slavia Zawodnik 05', position: 'DEF', overall: 71, starting: true },
      { name: 'Slavia Zawodnik 06', position: 'MID', overall: 71, starting: true },
      { name: 'Slavia Zawodnik 07', position: 'MID', overall: 71, starting: true },
      { name: 'Slavia Zawodnik 08', position: 'MID', overall: 71, starting: true },
      { name: 'Slavia Zawodnik 09', position: 'MID', overall: 71, starting: true },
      { name: 'Slavia Zawodnik 10', position: 'FWD', overall: 71, starting: true },
      { name: 'Slavia Zawodnik 11', position: 'FWD', overall: 71, starting: true },
    ],
  },
  {
    id: 'lm-slovan-ba',
    club: 'Slovan Bratysława',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 66 (OVR drużyny = 66).
    players: [
      { name: 'Slovan Zawodnik 01', position: 'GK', overall: 66, starting: true },
      { name: 'Slovan Zawodnik 02', position: 'DEF', overall: 66, starting: true },
      { name: 'Slovan Zawodnik 03', position: 'DEF', overall: 66, starting: true },
      { name: 'Slovan Zawodnik 04', position: 'DEF', overall: 66, starting: true },
      { name: 'Slovan Zawodnik 05', position: 'DEF', overall: 66, starting: true },
      { name: 'Slovan Zawodnik 06', position: 'MID', overall: 66, starting: true },
      { name: 'Slovan Zawodnik 07', position: 'MID', overall: 66, starting: true },
      { name: 'Slovan Zawodnik 08', position: 'MID', overall: 66, starting: true },
      { name: 'Slovan Zawodnik 09', position: 'MID', overall: 66, starting: true },
      { name: 'Slovan Zawodnik 10', position: 'FWD', overall: 66, starting: true },
      { name: 'Slovan Zawodnik 11', position: 'FWD', overall: 66, starting: true },
    ],
  },
  {
    id: 'lm-stuttgart',
    club: 'VfB Stuttgart',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 74 (OVR drużyny = 74).
    players: [
      { name: 'VfB Zawodnik 01', position: 'GK', overall: 74, starting: true },
      { name: 'VfB Zawodnik 02', position: 'DEF', overall: 74, starting: true },
      { name: 'VfB Zawodnik 03', position: 'DEF', overall: 74, starting: true },
      { name: 'VfB Zawodnik 04', position: 'DEF', overall: 74, starting: true },
      { name: 'VfB Zawodnik 05', position: 'DEF', overall: 74, starting: true },
      { name: 'VfB Zawodnik 06', position: 'MID', overall: 74, starting: true },
      { name: 'VfB Zawodnik 07', position: 'MID', overall: 74, starting: true },
      { name: 'VfB Zawodnik 08', position: 'MID', overall: 74, starting: true },
      { name: 'VfB Zawodnik 09', position: 'MID', overall: 74, starting: true },
      { name: 'VfB Zawodnik 10', position: 'FWD', overall: 74, starting: true },
      { name: 'VfB Zawodnik 11', position: 'FWD', overall: 74, starting: true },
    ],
  },
  {
    id: 'lm-como',
    club: 'Como 1907',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 68 (OVR drużyny = 68).
    players: [
      { name: 'Como Zawodnik 01', position: 'GK', overall: 68, starting: true },
      { name: 'Como Zawodnik 02', position: 'DEF', overall: 68, starting: true },
      { name: 'Como Zawodnik 03', position: 'DEF', overall: 68, starting: true },
      { name: 'Como Zawodnik 04', position: 'DEF', overall: 68, starting: true },
      { name: 'Como Zawodnik 05', position: 'DEF', overall: 68, starting: true },
      { name: 'Como Zawodnik 06', position: 'MID', overall: 68, starting: true },
      { name: 'Como Zawodnik 07', position: 'MID', overall: 68, starting: true },
      { name: 'Como Zawodnik 08', position: 'MID', overall: 68, starting: true },
      { name: 'Como Zawodnik 09', position: 'MID', overall: 68, starting: true },
      { name: 'Como Zawodnik 10', position: 'FWD', overall: 68, starting: true },
      { name: 'Como Zawodnik 11', position: 'FWD', overall: 68, starting: true },
    ],
  },
  {
    id: 'lm-lens',
    club: 'RC Lens',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 71 (OVR drużyny = 71).
    players: [
      { name: 'RC Zawodnik 01', position: 'GK', overall: 71, starting: true },
      { name: 'RC Zawodnik 02', position: 'DEF', overall: 71, starting: true },
      { name: 'RC Zawodnik 03', position: 'DEF', overall: 71, starting: true },
      { name: 'RC Zawodnik 04', position: 'DEF', overall: 71, starting: true },
      { name: 'RC Zawodnik 05', position: 'DEF', overall: 71, starting: true },
      { name: 'RC Zawodnik 06', position: 'MID', overall: 71, starting: true },
      { name: 'RC Zawodnik 07', position: 'MID', overall: 71, starting: true },
      { name: 'RC Zawodnik 08', position: 'MID', overall: 71, starting: true },
      { name: 'RC Zawodnik 09', position: 'MID', overall: 71, starting: true },
      { name: 'RC Zawodnik 10', position: 'FWD', overall: 71, starting: true },
      { name: 'RC Zawodnik 11', position: 'FWD', overall: 71, starting: true },
    ],
  },
  {
    id: 'lm2-aarhus',
    club: 'Aarhus GF',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 74 (OVR drużyny = 74).
    players: [
      { name: 'Aarhus Zawodnik 01', position: 'GK', overall: 74, starting: true },
      { name: 'Aarhus Zawodnik 02', position: 'DEF', overall: 74, starting: true },
      { name: 'Aarhus Zawodnik 03', position: 'DEF', overall: 74, starting: true },
      { name: 'Aarhus Zawodnik 04', position: 'DEF', overall: 74, starting: true },
      { name: 'Aarhus Zawodnik 05', position: 'DEF', overall: 74, starting: true },
      { name: 'Aarhus Zawodnik 06', position: 'MID', overall: 74, starting: true },
      { name: 'Aarhus Zawodnik 07', position: 'MID', overall: 74, starting: true },
      { name: 'Aarhus Zawodnik 08', position: 'MID', overall: 74, starting: true },
      { name: 'Aarhus Zawodnik 09', position: 'MID', overall: 74, starting: true },
      { name: 'Aarhus Zawodnik 10', position: 'FWD', overall: 74, starting: true },
      { name: 'Aarhus Zawodnik 11', position: 'FWD', overall: 74, starting: true },
    ],
  },
  {
    id: 'lm2-fenerbahce',
    club: 'Fenerbahçe',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 88 (OVR drużyny = 88).
    players: [
      { name: 'Fenerbahçe Zawodnik 01', position: 'GK', overall: 88, starting: true },
      { name: 'Fenerbahçe Zawodnik 02', position: 'DEF', overall: 88, starting: true },
      { name: 'Fenerbahçe Zawodnik 03', position: 'DEF', overall: 88, starting: true },
      { name: 'Fenerbahçe Zawodnik 04', position: 'DEF', overall: 88, starting: true },
      { name: 'Fenerbahçe Zawodnik 05', position: 'DEF', overall: 88, starting: true },
      { name: 'Fenerbahçe Zawodnik 06', position: 'MID', overall: 88, starting: true },
      { name: 'Fenerbahçe Zawodnik 07', position: 'MID', overall: 88, starting: true },
      { name: 'Fenerbahçe Zawodnik 08', position: 'MID', overall: 88, starting: true },
      { name: 'Fenerbahçe Zawodnik 09', position: 'MID', overall: 88, starting: true },
      { name: 'Fenerbahçe Zawodnik 10', position: 'FWD', overall: 88, starting: true },
      { name: 'Fenerbahçe Zawodnik 11', position: 'FWD', overall: 88, starting: true },
    ],
  },
  {
    id: 'lm2-pool-maccabi',
    club: 'Maccabi Tel Aviv',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 73 (OVR drużyny = 73).
    players: [
      { name: 'Maccabi Zawodnik 01', position: 'GK', overall: 73, starting: true },
      { name: 'Maccabi Zawodnik 02', position: 'DEF', overall: 73, starting: true },
      { name: 'Maccabi Zawodnik 03', position: 'DEF', overall: 73, starting: true },
      { name: 'Maccabi Zawodnik 04', position: 'DEF', overall: 73, starting: true },
      { name: 'Maccabi Zawodnik 05', position: 'DEF', overall: 73, starting: true },
      { name: 'Maccabi Zawodnik 06', position: 'MID', overall: 73, starting: true },
      { name: 'Maccabi Zawodnik 07', position: 'MID', overall: 73, starting: true },
      { name: 'Maccabi Zawodnik 08', position: 'MID', overall: 73, starting: true },
      { name: 'Maccabi Zawodnik 09', position: 'MID', overall: 73, starting: true },
      { name: 'Maccabi Zawodnik 10', position: 'FWD', overall: 73, starting: true },
      { name: 'Maccabi Zawodnik 11', position: 'FWD', overall: 73, starting: true },
    ],
  },
  {
    id: 'lm2-pool-ludogorets',
    club: 'Ludogorets Razgrad',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 74 (OVR drużyny = 74).
    players: [
      { name: 'Ludogorets Zawodnik 01', position: 'GK', overall: 74, starting: true },
      { name: 'Ludogorets Zawodnik 02', position: 'DEF', overall: 74, starting: true },
      { name: 'Ludogorets Zawodnik 03', position: 'DEF', overall: 74, starting: true },
      { name: 'Ludogorets Zawodnik 04', position: 'DEF', overall: 74, starting: true },
      { name: 'Ludogorets Zawodnik 05', position: 'DEF', overall: 74, starting: true },
      { name: 'Ludogorets Zawodnik 06', position: 'MID', overall: 74, starting: true },
      { name: 'Ludogorets Zawodnik 07', position: 'MID', overall: 74, starting: true },
      { name: 'Ludogorets Zawodnik 08', position: 'MID', overall: 74, starting: true },
      { name: 'Ludogorets Zawodnik 09', position: 'MID', overall: 74, starting: true },
      { name: 'Ludogorets Zawodnik 10', position: 'FWD', overall: 74, starting: true },
      { name: 'Ludogorets Zawodnik 11', position: 'FWD', overall: 74, starting: true },
    ],
  },
  {
    id: 'lm2-pool-malmo',
    club: 'Malmö FF',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 72 (OVR drużyny = 72).
    players: [
      { name: 'Malmö Zawodnik 01', position: 'GK', overall: 72, starting: true },
      { name: 'Malmö Zawodnik 02', position: 'DEF', overall: 72, starting: true },
      { name: 'Malmö Zawodnik 03', position: 'DEF', overall: 72, starting: true },
      { name: 'Malmö Zawodnik 04', position: 'DEF', overall: 72, starting: true },
      { name: 'Malmö Zawodnik 05', position: 'DEF', overall: 72, starting: true },
      { name: 'Malmö Zawodnik 06', position: 'MID', overall: 72, starting: true },
      { name: 'Malmö Zawodnik 07', position: 'MID', overall: 72, starting: true },
      { name: 'Malmö Zawodnik 08', position: 'MID', overall: 72, starting: true },
      { name: 'Malmö Zawodnik 09', position: 'MID', overall: 72, starting: true },
      { name: 'Malmö Zawodnik 10', position: 'FWD', overall: 72, starting: true },
      { name: 'Malmö Zawodnik 11', position: 'FWD', overall: 72, starting: true },
    ],
  },
  {
    id: 'lm2-pool-hjk',
    club: 'HJK Helsinki',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 68 (OVR drużyny = 68).
    players: [
      { name: 'HJK Zawodnik 01', position: 'GK', overall: 68, starting: true },
      { name: 'HJK Zawodnik 02', position: 'DEF', overall: 68, starting: true },
      { name: 'HJK Zawodnik 03', position: 'DEF', overall: 68, starting: true },
      { name: 'HJK Zawodnik 04', position: 'DEF', overall: 68, starting: true },
      { name: 'HJK Zawodnik 05', position: 'DEF', overall: 68, starting: true },
      { name: 'HJK Zawodnik 06', position: 'MID', overall: 68, starting: true },
      { name: 'HJK Zawodnik 07', position: 'MID', overall: 68, starting: true },
      { name: 'HJK Zawodnik 08', position: 'MID', overall: 68, starting: true },
      { name: 'HJK Zawodnik 09', position: 'MID', overall: 68, starting: true },
      { name: 'HJK Zawodnik 10', position: 'FWD', overall: 68, starting: true },
      { name: 'HJK Zawodnik 11', position: 'FWD', overall: 68, starting: true },
    ],
  },
  {
    id: 'lm2-pool-zrinjski',
    club: 'Zrinjski Mostar',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 67 (OVR drużyny = 67).
    players: [
      { name: 'Zrinjski Zawodnik 01', position: 'GK', overall: 67, starting: true },
      { name: 'Zrinjski Zawodnik 02', position: 'DEF', overall: 67, starting: true },
      { name: 'Zrinjski Zawodnik 03', position: 'DEF', overall: 67, starting: true },
      { name: 'Zrinjski Zawodnik 04', position: 'DEF', overall: 67, starting: true },
      { name: 'Zrinjski Zawodnik 05', position: 'DEF', overall: 67, starting: true },
      { name: 'Zrinjski Zawodnik 06', position: 'MID', overall: 67, starting: true },
      { name: 'Zrinjski Zawodnik 07', position: 'MID', overall: 67, starting: true },
      { name: 'Zrinjski Zawodnik 08', position: 'MID', overall: 67, starting: true },
      { name: 'Zrinjski Zawodnik 09', position: 'MID', overall: 67, starting: true },
      { name: 'Zrinjski Zawodnik 10', position: 'FWD', overall: 67, starting: true },
      { name: 'Zrinjski Zawodnik 11', position: 'FWD', overall: 67, starting: true },
    ],
  },
  {
    id: 'lm2-pool-servette',
    club: 'Servette Genève',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 71 (OVR drużyny = 71).
    players: [
      { name: 'Servette Zawodnik 01', position: 'GK', overall: 71, starting: true },
      { name: 'Servette Zawodnik 02', position: 'DEF', overall: 71, starting: true },
      { name: 'Servette Zawodnik 03', position: 'DEF', overall: 71, starting: true },
      { name: 'Servette Zawodnik 04', position: 'DEF', overall: 71, starting: true },
      { name: 'Servette Zawodnik 05', position: 'DEF', overall: 71, starting: true },
      { name: 'Servette Zawodnik 06', position: 'MID', overall: 71, starting: true },
      { name: 'Servette Zawodnik 07', position: 'MID', overall: 71, starting: true },
      { name: 'Servette Zawodnik 08', position: 'MID', overall: 71, starting: true },
      { name: 'Servette Zawodnik 09', position: 'MID', overall: 71, starting: true },
      { name: 'Servette Zawodnik 10', position: 'FWD', overall: 71, starting: true },
      { name: 'Servette Zawodnik 11', position: 'FWD', overall: 71, starting: true },
    ],
  },
  {
    id: 'lm2-pool-shamrock',
    club: 'Shamrock Rovers',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 66 (OVR drużyny = 66).
    players: [
      { name: 'Shamrock Zawodnik 01', position: 'GK', overall: 66, starting: true },
      { name: 'Shamrock Zawodnik 02', position: 'DEF', overall: 66, starting: true },
      { name: 'Shamrock Zawodnik 03', position: 'DEF', overall: 66, starting: true },
      { name: 'Shamrock Zawodnik 04', position: 'DEF', overall: 66, starting: true },
      { name: 'Shamrock Zawodnik 05', position: 'DEF', overall: 66, starting: true },
      { name: 'Shamrock Zawodnik 06', position: 'MID', overall: 66, starting: true },
      { name: 'Shamrock Zawodnik 07', position: 'MID', overall: 66, starting: true },
      { name: 'Shamrock Zawodnik 08', position: 'MID', overall: 66, starting: true },
      { name: 'Shamrock Zawodnik 09', position: 'MID', overall: 66, starting: true },
      { name: 'Shamrock Zawodnik 10', position: 'FWD', overall: 66, starting: true },
      { name: 'Shamrock Zawodnik 11', position: 'FWD', overall: 66, starting: true },
    ],
  },
  {
    id: 'lm2-pool-kups',
    club: 'KuPS Kuopio',
    context: 'Liga Mistrzów 2026/27 — faza ligowa',
    coach: '',
    // ZAŚLEPKA testowa — płaski overall 65 (OVR drużyny = 65).
    players: [
      { name: 'KuPS Zawodnik 01', position: 'GK', overall: 65, starting: true },
      { name: 'KuPS Zawodnik 02', position: 'DEF', overall: 65, starting: true },
      { name: 'KuPS Zawodnik 03', position: 'DEF', overall: 65, starting: true },
      { name: 'KuPS Zawodnik 04', position: 'DEF', overall: 65, starting: true },
      { name: 'KuPS Zawodnik 05', position: 'DEF', overall: 65, starting: true },
      { name: 'KuPS Zawodnik 06', position: 'MID', overall: 65, starting: true },
      { name: 'KuPS Zawodnik 07', position: 'MID', overall: 65, starting: true },
      { name: 'KuPS Zawodnik 08', position: 'MID', overall: 65, starting: true },
      { name: 'KuPS Zawodnik 09', position: 'MID', overall: 65, starting: true },
      { name: 'KuPS Zawodnik 10', position: 'FWD', overall: 65, starting: true },
      { name: 'KuPS Zawodnik 11', position: 'FWD', overall: 65, starting: true },
    ],
  },
);
