// ============================================================
// LIGA MISTRZÓW 2026/27 — 54 drużyny (fazy ligowej + puli eliminacyjnej).
// Skala overallu: 50-120 (przeskalowana, żeby czołówka europejska wyraźnie
// przebijała szczyt Ekstraklasy). AEK Ateny, Omonia Nikozja, LASK Linz
// dobudowane na potrzeby dokładnej ścieżki eliminacyjnej Lecha.
// ============================================================

window.WYZWANIA_TEAMS_DATA = window.WYZWANIA_TEAMS_DATA || [];
window.WYZWANIA_TEAMS_DATA.push(
  {
    id: 'lm-psg',
    club: 'Paris Saint-Germain',
    players: [
      { name: 'Lucas Chevalier', position: 'GK', overall: 105, starting: true },
      { name: 'Achraf Hakimi', position: 'DEF', overall: 117, starting: true },
      { name: 'Marquinhos', position: 'DEF', overall: 110, starting: true },
      { name: 'Nuno Mendes', position: 'DEF', overall: 102, starting: true },
      { name: 'Willian Pacho', position: 'DEF', overall: 99, starting: true },
      { name: 'Vitinha', position: 'MID', overall: 107, starting: true },
      { name: 'Joao Neves', position: 'MID', overall: 103, starting: true },
      { name: 'Fabian Ruiz', position: 'MID', overall: 102, starting: true },
      { name: 'Warren Zaire-Emery', position: 'MID', overall: 100, starting: true },
      { name: 'Ousmane Dembele', position: 'FWD', overall: 115, starting: true },
      { name: 'Bradley Barcola', position: 'FWD', overall: 99, starting: true },
      { name: 'Matvey Safonov', position: 'GK', overall: 88, starting: false },
      { name: 'Lucas Beraldo', position: 'DEF', overall: 89, starting: false },
      { name: 'Lucas Hernandez', position: 'DEF', overall: 93, starting: false },
      { name: 'Kang-in Lee', position: 'MID', overall: 91, starting: false },
      { name: 'Senny Mayulu', position: 'MID', overall: 87, starting: false },
      { name: 'Goncalo Ramos', position: 'FWD', overall: 96, starting: false },
      { name: 'Desire Doue', position: 'FWD', overall: 103, starting: false },
    ],
  },
  {
    id: 'lm-bayern',
    club: 'Bayern Monachium',
    players: [
      { name: 'Manuel Neuer', position: 'GK', overall: 100, starting: true },
      { name: 'Dayot Upamecano', position: 'DEF', overall: 102, starting: true },
      { name: 'Kim Min-jae', position: 'DEF', overall: 103, starting: true },
      { name: 'Josip Stanisic', position: 'DEF', overall: 92, starting: true },
      { name: 'Alphonso Davies', position: 'DEF', overall: 100, starting: true },
      { name: 'Joshua Kimmich', position: 'MID', overall: 105, starting: true },
      { name: 'Konrad Laimer', position: 'MID', overall: 97, starting: true },
      { name: 'Jamal Musiala', position: 'MID', overall: 115, starting: true },
      { name: 'Michael Olise', position: 'MID', overall: 102, starting: true },
      { name: 'Harry Kane', position: 'FWD', overall: 110, starting: true },
      { name: 'Serge Gnabry', position: 'FWD', overall: 93, starting: true },
      { name: 'Jonas Urbig', position: 'GK', overall: 84, starting: false },
      { name: 'Nicolas Seiwald', position: 'DEF', overall: 89, starting: false },
      { name: 'Tarek Buchmann', position: 'DEF', overall: 84, starting: false },
      { name: 'Aleksandar Pavlovic', position: 'MID', overall: 93, starting: false },
      { name: 'Leon Goretzka', position: 'MID', overall: 96, starting: false },
      { name: 'Nick Woltemade', position: 'FWD', overall: 95, starting: false },
      { name: 'Jonathan Asp Jensen', position: 'FWD', overall: 83, starting: false },
    ],
  },
  {
    id: 'lm-real-madryt',
    club: 'Real Madryt',
    players: [
      { name: 'Thibaut Courtois', position: 'GK', overall: 107, starting: true },
      { name: 'Dean Huijsen', position: 'DEF', overall: 96, starting: true },
      { name: 'Antonio Rudiger', position: 'DEF', overall: 102, starting: true },
      { name: 'Trent Alexander-Arnold', position: 'DEF', overall: 102, starting: true },
      { name: 'Ferland Mendy', position: 'DEF', overall: 93, starting: true },
      { name: 'Jude Bellingham', position: 'MID', overall: 113, starting: true },
      { name: 'Federico Valverde', position: 'MID', overall: 108, starting: true },
      { name: 'Aurelien Tchouameni', position: 'MID', overall: 102, starting: true },
      { name: 'Eduardo Camavinga', position: 'MID', overall: 99, starting: true },
      { name: 'Kylian Mbappe', position: 'FWD', overall: 118, starting: true },
      { name: 'Vinicius Junior', position: 'FWD', overall: 117, starting: true },
      { name: 'Andriy Lunin', position: 'GK', overall: 87, starting: false },
      { name: 'Eder Militao', position: 'DEF', overall: 96, starting: false },
      { name: 'Alvaro Carreras', position: 'DEF', overall: 89, starting: false },
      { name: 'Arda Guler', position: 'MID', overall: 100, starting: false },
      { name: 'Dani Ceballos', position: 'MID', overall: 89, starting: false },
      { name: 'Rodrygo', position: 'FWD', overall: 102, starting: false },
      { name: 'Endrick', position: 'FWD', overall: 92, starting: false },
    ],
  },
  {
    id: 'lm-liverpool',
    club: 'Liverpool FC',
    players: [
      { name: 'Alisson', position: 'GK', overall: 110, starting: true },
      { name: 'Virgil van Dijk', position: 'DEF', overall: 108, starting: true },
      { name: 'Ibrahima Konate', position: 'DEF', overall: 100, starting: true },
      { name: 'Milos Kerkez', position: 'DEF', overall: 93, starting: true },
      { name: 'Jeremie Frimpong', position: 'DEF', overall: 93, starting: true },
      { name: 'Ryan Gravenberch', position: 'MID', overall: 100, starting: true },
      { name: 'Alexis Mac Allister', position: 'MID', overall: 103, starting: true },
      { name: 'Dominik Szoboszlai', position: 'MID', overall: 100, starting: true },
      { name: 'Florian Wirtz', position: 'MID', overall: 110, starting: true },
      { name: 'Mohamed Salah', position: 'FWD', overall: 113, starting: true },
      { name: 'Hugo Ekitike', position: 'FWD', overall: 96, starting: true },
      { name: 'Giorgi Mamardashvili', position: 'GK', overall: 89, starting: false },
      { name: 'Andrew Robertson', position: 'DEF', overall: 96, starting: false },
      { name: 'Joe Gomez', position: 'DEF', overall: 89, starting: false },
      { name: 'Curtis Jones', position: 'MID', overall: 91, starting: false },
      { name: 'Wataru Endo', position: 'MID', overall: 88, starting: false },
      { name: 'Cody Gakpo', position: 'FWD', overall: 102, starting: false },
      { name: 'Federico Chiesa', position: 'FWD', overall: 93, starting: false },
    ],
  },
  {
    id: 'lm-inter',
    club: 'Inter Mediolan',
    players: [
      { name: 'Yann Sommer', position: 'GK', overall: 96, starting: true },
      { name: 'Alessandro Bastoni', position: 'DEF', overall: 105, starting: true },
      { name: 'Francesco Acerbi', position: 'DEF', overall: 93, starting: true },
      { name: 'Benjamin Pavard', position: 'DEF', overall: 95, starting: true },
      { name: 'Federico Dimarco', position: 'DEF', overall: 100, starting: true },
      { name: 'Nicolo Barella', position: 'MID', overall: 105, starting: true },
      { name: 'Hakan Calhanoglu', position: 'MID', overall: 102, starting: true },
      { name: 'Piotr Zielinski', position: 'MID', overall: 99, starting: true },
      { name: 'Henrikh Mkhitaryan', position: 'MID', overall: 92, starting: true },
      { name: 'Lautaro Martinez', position: 'FWD', overall: 107, starting: true },
      { name: 'Marcus Thuram', position: 'FWD', overall: 103, starting: true },
      { name: 'Josep Martinez', position: 'GK', overall: 84, starting: false },
      { name: 'Yann Bisseck', position: 'DEF', overall: 89, starting: false },
      { name: 'Matteo Darmian', position: 'DEF', overall: 85, starting: false },
      { name: 'Kristjan Asllani', position: 'MID', overall: 87, starting: false },
      { name: 'Petar Sucic', position: 'MID', overall: 91, starting: false },
      { name: 'Mehdi Taremi', position: 'FWD', overall: 93, starting: false },
      { name: 'Ange-Yoan Bonny', position: 'FWD', overall: 88, starting: false },
    ],
  },
  {
    id: 'lm-man-city',
    club: 'Manchester City',
    players: [
      { name: 'Ederson', position: 'GK', overall: 100, starting: true },
      { name: 'Ruben Dias', position: 'DEF', overall: 105, starting: true },
      { name: 'Josko Gvardiol', position: 'DEF', overall: 107, starting: true },
      { name: 'Rico Lewis', position: 'DEF', overall: 92, starting: true },
      { name: 'Nathan Ake', position: 'DEF', overall: 97, starting: true },
      { name: 'Rodri', position: 'MID', overall: 118, starting: true },
      { name: 'Mateo Kovacic', position: 'MID', overall: 97, starting: true },
      { name: 'Bernardo Silva', position: 'MID', overall: 103, starting: true },
      { name: 'Phil Foden', position: 'MID', overall: 103, starting: true },
      { name: 'Erling Haaland', position: 'FWD', overall: 120, starting: true },
      { name: 'Jeremy Doku', position: 'FWD', overall: 103, starting: true },
      { name: 'Marcus Bettinelli', position: 'GK', overall: 78, starting: false },
      { name: 'Manuel Akanji', position: 'DEF', overall: 99, starting: false },
      { name: 'Nico Gonzalez', position: 'DEF', overall: 87, starting: false },
      { name: 'Tijjani Reijnders', position: 'MID', overall: 99, starting: false },
      { name: 'Savinho', position: 'MID', overall: 93, starting: false },
      { name: 'Omar Marmoush', position: 'FWD', overall: 100, starting: false },
      { name: 'Oscar Bobb', position: 'FWD', overall: 89, starting: false },
    ],
  },
  {
    id: 'lm-arsenal',
    club: 'Arsenal FC',
    players: [
      { name: 'David Raya', position: 'GK', overall: 100, starting: true },
      { name: 'William Saliba', position: 'DEF', overall: 105, starting: true },
      { name: 'Gabriel Magalhaes', position: 'DEF', overall: 103, starting: true },
      { name: 'Jurrien Timber', position: 'DEF', overall: 100, starting: true },
      { name: 'Riccardo Calafiori', position: 'DEF', overall: 96, starting: true },
      { name: 'Declan Rice', position: 'MID', overall: 107, starting: true },
      { name: 'Martin Zubimendi', position: 'MID', overall: 96, starting: true },
      { name: 'Martin Odegaard', position: 'MID', overall: 105, starting: true },
      { name: 'Bukayo Saka', position: 'MID', overall: 110, starting: true },
      { name: 'Viktor Gyokeres', position: 'FWD', overall: 103, starting: true },
      { name: 'Gabriel Martinelli', position: 'FWD', overall: 96, starting: true },
      { name: 'Kepa Arrizabalaga', position: 'GK', overall: 83, starting: false },
      { name: 'Jakub Kiwior', position: 'DEF', overall: 89, starting: false },
      { name: 'Ben White', position: 'DEF', overall: 93, starting: false },
      { name: 'Mikel Merino', position: 'MID', overall: 92, starting: false },
      { name: 'Eberechi Eze', position: 'MID', overall: 100, starting: false },
      { name: 'Leandro Trossard', position: 'FWD', overall: 93, starting: false },
      { name: 'Kai Havertz', position: 'FWD', overall: 100, starting: false },
    ],
  },
  {
    id: 'lm-barcelona',
    club: 'FC Barcelona',
    players: [
      { name: 'Joan Garcia', position: 'GK', overall: 96, starting: true },
      { name: 'Pau Cubarsi', position: 'DEF', overall: 102, starting: true },
      { name: 'Ronald Araujo', position: 'DEF', overall: 100, starting: true },
      { name: 'Jules Kounde', position: 'DEF', overall: 100, starting: true },
      { name: 'Alejandro Balde', position: 'DEF', overall: 96, starting: true },
      { name: 'Pedri', position: 'MID', overall: 115, starting: true },
      { name: 'Frenkie de Jong', position: 'MID', overall: 103, starting: true },
      { name: 'Gavi', position: 'MID', overall: 100, starting: true },
      { name: 'Dani Olmo', position: 'MID', overall: 100, starting: true },
      { name: 'Lamine Yamal', position: 'FWD', overall: 113, starting: true },
      { name: 'Robert Lewandowski', position: 'FWD', overall: 108, starting: true },
      { name: 'Wojciech Szczesny', position: 'GK', overall: 84, starting: false },
      { name: 'Eric Garcia', position: 'DEF', overall: 89, starting: false },
      { name: 'Gerard Martin', position: 'DEF', overall: 83, starting: false },
      { name: 'Marc Casado', position: 'MID', overall: 88, starting: false },
      { name: 'Fermin Lopez', position: 'MID', overall: 93, starting: false },
      { name: 'Ferran Torres', position: 'FWD', overall: 93, starting: false },
      { name: 'Marcus Rashford', position: 'FWD', overall: 93, starting: false },
    ],
  },
  {
    id: 'lm-atletico',
    club: 'Atlético Madryt',
    players: [
      { name: 'Jan Oblak', position: 'GK', overall: 102, starting: true },
      { name: 'Jose Maria Gimenez', position: 'DEF', overall: 97, starting: true },
      { name: 'Clement Lenglet', position: 'DEF', overall: 91, starting: true },
      { name: 'Robin Le Normand', position: 'DEF', overall: 96, starting: true },
      { name: 'Marc Pubill', position: 'DEF', overall: 89, starting: true },
      { name: 'Koke', position: 'MID', overall: 93, starting: true },
      { name: 'Pablo Barrios', position: 'MID', overall: 93, starting: true },
      { name: 'Rodrigo De Paul', position: 'MID', overall: 99, starting: true },
      { name: 'Giuliano Simeone', position: 'MID', overall: 89, starting: true },
      { name: 'Julian Alvarez', position: 'FWD', overall: 107, starting: true },
      { name: 'Alexander Sorloth', position: 'FWD', overall: 96, starting: true },
      { name: 'Juan Musso', position: 'GK', overall: 84, starting: false },
      { name: 'Nahuel Molina', position: 'DEF', overall: 91, starting: false },
      { name: 'Javi Galan', position: 'DEF', overall: 87, starting: false },
      { name: 'Conor Gallagher', position: 'MID', overall: 89, starting: false },
      { name: 'Thiago Almada', position: 'MID', overall: 92, starting: false },
      { name: 'Antoine Griezmann', position: 'FWD', overall: 102, starting: false },
      { name: 'Giacomo Raspadori', position: 'FWD', overall: 91, starting: false },
    ],
  },
  {
    id: 'lm-borussia',
    club: 'Borussia Dortmund',
    players: [
      { name: 'Gregor Kobel', position: 'GK', overall: 100, starting: true },
      { name: 'Nico Schlotterbeck', position: 'DEF', overall: 96, starting: true },
      { name: 'Waldemar Anton', position: 'DEF', overall: 91, starting: true },
      { name: 'Julian Ryerson', position: 'DEF', overall: 92, starting: true },
      { name: 'Ramy Bensebaini', position: 'DEF', overall: 93, starting: true },
      { name: 'Felix Nmecha', position: 'MID', overall: 93, starting: true },
      { name: 'Pascal Gross', position: 'MID', overall: 89, starting: true },
      { name: 'Jobe Bellingham', position: 'MID', overall: 93, starting: true },
      { name: 'Carney Chukwuemeka', position: 'MID', overall: 89, starting: true },
      { name: 'Serhou Guirassy', position: 'FWD', overall: 99, starting: true },
      { name: 'Karim Adeyemi', position: 'FWD', overall: 93, starting: true },
      { name: 'Alexander Meyer', position: 'GK', overall: 75, starting: false },
      { name: 'Yan Couto', position: 'DEF', overall: 87, starting: false },
      { name: 'Niklas Sule', position: 'DEF', overall: 88, starting: false },
      { name: 'Marcel Sabitzer', position: 'MID', overall: 89, starting: false },
      { name: 'Daniel Svensson', position: 'MID', overall: 84, starting: false },
      { name: 'Maximilian Beier', position: 'FWD', overall: 91, starting: false },
      { name: 'Jamie Gittens', position: 'FWD', overall: 93, starting: false },
    ],
  },
  {
    id: 'lm-roma',
    club: 'AS Roma',
    players: [
      { name: 'Mile Svilar', position: 'GK', overall: 96, starting: true },
      { name: 'Evan Ndicka', position: 'DEF', overall: 96, starting: true },
      { name: 'Gianluca Mancini', position: 'DEF', overall: 92, starting: true },
      { name: 'Wesley', position: 'DEF', overall: 91, starting: true },
      { name: 'Devyne Rensch', position: 'DEF', overall: 87, starting: true },
      { name: 'Manu Kone', position: 'MID', overall: 93, starting: true },
      { name: 'Bryan Cristante', position: 'MID', overall: 89, starting: true },
      { name: 'Lorenzo Pellegrini', position: 'MID', overall: 92, starting: true },
      { name: 'Neil El Aynaoui', position: 'MID', overall: 91, starting: true },
      { name: 'Artem Dovbyk', position: 'FWD', overall: 93, starting: true },
      { name: 'Matias Soule', position: 'FWD', overall: 96, starting: true },
      { name: 'Mile Zalewski', position: 'GK', overall: 73, starting: false },
      { name: 'Zeki Celik', position: 'DEF', overall: 88, starting: false },
      { name: 'Mario Hermoso', position: 'DEF', overall: 87, starting: false },
      { name: 'Leandro Paredes', position: 'MID', overall: 88, starting: false },
      { name: 'Niccolo Pisilli', position: 'MID', overall: 83, starting: false },
      { name: 'Evan Ferguson', position: 'FWD', overall: 89, starting: false },
      { name: 'Eldor Shomurodov', position: 'FWD', overall: 84, starting: false },
    ],
  },
  {
    id: 'lm-sporting',
    club: 'Sporting CP',
    players: [
      { name: 'Franco Israel', position: 'GK', overall: 91, starting: true },
      { name: 'Goncalo Inacio', position: 'DEF', overall: 96, starting: true },
      { name: 'Ousmane Diomande', position: 'DEF', overall: 96, starting: true },
      { name: 'Matheus Reis', position: 'DEF', overall: 88, starting: true },
      { name: 'Eduardo Quaresma', position: 'DEF', overall: 87, starting: true },
      { name: 'Hidemasa Morita', position: 'MID', overall: 89, starting: true },
      { name: 'Pedro Goncalves', position: 'MID', overall: 96, starting: true },
      { name: 'Geovany Quenda', position: 'MID', overall: 93, starting: true },
      { name: 'Alisson Santos', position: 'MID', overall: 85, starting: true },
      { name: 'Francisco Trincao', position: 'FWD', overall: 96, starting: true },
      { name: 'Luis Suarez', position: 'FWD', overall: 88, starting: true },
      { name: 'Diego Callai', position: 'GK', overall: 73, starting: false },
      { name: 'Ivanildo Fernandes', position: 'DEF', overall: 78, starting: false },
      { name: 'Esgaio', position: 'DEF', overall: 80, starting: false },
      { name: 'Daniel Braganca', position: 'MID', overall: 83, starting: false },
      { name: 'Morten Hjulmand', position: 'MID', overall: 91, starting: false },
      { name: 'Conrad Harder', position: 'FWD', overall: 87, starting: false },
      { name: 'Alisson Rocha', position: 'FWD', overall: 80, starting: false },
    ],
  },
  {
    id: 'lm-aston-villa',
    club: 'Aston Villa',
    players: [
      { name: 'Emiliano Martinez', position: 'GK', overall: 100, starting: true },
      { name: 'Ezri Konsa', position: 'DEF', overall: 93, starting: true },
      { name: 'Pau Torres', position: 'DEF', overall: 93, starting: true },
      { name: 'Lucas Digne', position: 'DEF', overall: 91, starting: true },
      { name: 'Matty Cash', position: 'DEF', overall: 91, starting: true },
      { name: 'Youri Tielemans', position: 'MID', overall: 93, starting: true },
      { name: 'Boubacar Kamara', position: 'MID', overall: 92, starting: true },
      { name: 'Amadou Onana', position: 'MID', overall: 95, starting: true },
      { name: 'Morgan Rogers', position: 'MID', overall: 96, starting: true },
      { name: 'Ollie Watkins', position: 'FWD', overall: 99, starting: true },
      { name: 'Evann Guessand', position: 'FWD', overall: 89, starting: true },
      { name: 'Marco Bizot', position: 'GK', overall: 78, starting: false },
      { name: 'Ian Maatsen', position: 'DEF', overall: 87, starting: false },
      { name: 'Axel Disasi', position: 'DEF', overall: 84, starting: false },
      { name: 'John McGinn', position: 'MID', overall: 91, starting: false },
      { name: 'Jacob Ramsey', position: 'MID', overall: 87, starting: false },
      { name: 'Donyell Malen', position: 'FWD', overall: 91, starting: false },
      { name: 'Jadon Sancho', position: 'FWD', overall: 89, starting: false },
    ],
  },
  {
    id: 'lm-porto',
    club: 'FC Porto',
    players: [
      { name: 'Diogo Costa', position: 'GK', overall: 100, starting: true },
      { name: 'Ivan Ordets', position: 'DEF', overall: 87, starting: true },
      { name: 'Nehuen Perez', position: 'DEF', overall: 88, starting: true },
      { name: 'Zaidu Sanusi', position: 'DEF', overall: 84, starting: true },
      { name: 'Alberto Costa', position: 'DEF', overall: 85, starting: true },
      { name: 'Victor Froholdt', position: 'MID', overall: 87, starting: true },
      { name: 'Alan Varela', position: 'MID', overall: 91, starting: true },
      { name: 'Stephen Eustaquio', position: 'MID', overall: 89, starting: true },
      { name: 'Pepe', position: 'MID', overall: 83, starting: true },
      { name: 'Samu Aghehowa', position: 'FWD', overall: 93, starting: true },
      { name: 'Deniz Gul', position: 'FWD', overall: 87, starting: true },
      { name: 'Cláudio Ramos', position: 'GK', overall: 78, starting: false },
      { name: 'Martim Fernandes', position: 'DEF', overall: 78, starting: false },
      { name: 'Joao Mario', position: 'DEF', overall: 84, starting: false },
      { name: 'Gabri Veiga', position: 'MID', overall: 87, starting: false },
      { name: 'Fabio Vieira', position: 'MID', overall: 87, starting: false },
      { name: 'Rodrigo Mora', position: 'FWD', overall: 91, starting: false },
      { name: 'William Gomes', position: 'FWD', overall: 84, starting: false },
    ],
  },
  {
    id: 'lm-man-utd',
    club: 'Manchester United',
    players: [
      { name: 'Andre Onana', position: 'GK', overall: 93, starting: true },
      { name: 'Leny Yoro', position: 'DEF', overall: 91, starting: true },
      { name: 'Matthijs de Ligt', position: 'DEF', overall: 96, starting: true },
      { name: 'Noussair Mazraoui', position: 'DEF', overall: 92, starting: true },
      { name: 'Diogo Dalot', position: 'DEF', overall: 91, starting: true },
      { name: 'Casemiro', position: 'MID', overall: 92, starting: true },
      { name: 'Manuel Ugarte', position: 'MID', overall: 91, starting: true },
      { name: 'Bruno Fernandes', position: 'MID', overall: 102, starting: true },
      { name: 'Kobbie Mainoo', position: 'MID', overall: 91, starting: true },
      { name: 'Benjamin Sesko', position: 'FWD', overall: 93, starting: true },
      { name: 'Bryan Mbeumo', position: 'FWD', overall: 96, starting: true },
      { name: 'Altay Bayindir', position: 'GK', overall: 78, starting: false },
      { name: 'Lisandro Martinez', position: 'DEF', overall: 93, starting: false },
      { name: 'Ayden Heaven', position: 'DEF', overall: 78, starting: false },
      { name: 'Mason Mount', position: 'MID', overall: 87, starting: false },
      { name: 'Toby Collyer', position: 'MID', overall: 75, starting: false },
      { name: 'Matheus Cunha', position: 'FWD', overall: 96, starting: false },
      { name: 'Amad Diallo', position: 'FWD', overall: 92, starting: false },
    ],
  },
  {
    id: 'lm-brugge',
    club: 'Club Brugge',
    players: [
      { name: 'Nordin Jackers', position: 'GK', overall: 87, starting: true },
      { name: 'Brandon Mechele', position: 'DEF', overall: 91, starting: true },
      { name: 'Joel Ordonez', position: 'DEF', overall: 88, starting: true },
      { name: 'Bjorn Meijer', position: 'DEF', overall: 84, starting: true },
      { name: 'Kyriani Sabbe', position: 'DEF', overall: 85, starting: true },
      { name: 'Hans Vanaken', position: 'MID', overall: 96, starting: true },
      { name: 'Ardon Jashari', position: 'MID', overall: 93, starting: true },
      { name: 'Christos Tzolis', position: 'MID', overall: 89, starting: true },
      { name: 'Nicolo Tresoldi', position: 'MID', overall: 84, starting: true },
      { name: 'Chemsdine Talbi', position: 'FWD', overall: 91, starting: true },
      { name: 'Ferran Jutgla', position: 'FWD', overall: 87, starting: true },
      { name: 'Simon Mignolet', position: 'GK', overall: 77, starting: false },
      { name: 'Joaquin Seys', position: 'DEF', overall: 83, starting: false },
      { name: 'Maxim De Cuyper', position: 'DEF', overall: 87, starting: false },
      { name: 'Raphael Onyedika', position: 'MID', overall: 87, starting: false },
      { name: 'Romeo Vermant', position: 'MID', overall: 78, starting: false },
      { name: 'Antonio Nusa', position: 'FWD', overall: 91, starting: false },
      { name: 'Carlos Forbs', position: 'FWD', overall: 83, starting: false },
    ],
  },
  {
    id: 'lm-betis',
    club: 'Real Betis',
    players: [
      { name: 'Alvaro Valles', position: 'GK', overall: 87, starting: true },
      { name: 'Natan', position: 'DEF', overall: 88, starting: true },
      { name: 'Marc Bartra', position: 'DEF', overall: 87, starting: true },
      { name: 'Hector Bellerin', position: 'DEF', overall: 87, starting: true },
      { name: 'Ricardo Rodriguez', position: 'DEF', overall: 83, starting: true },
      { name: 'Marc Roca', position: 'MID', overall: 87, starting: true },
      { name: 'Johnny Cardoso', position: 'MID', overall: 89, starting: true },
      { name: 'Sofyan Amrabat', position: 'MID', overall: 89, starting: true },
      { name: 'Giovani Lo Celso', position: 'MID', overall: 93, starting: true },
      { name: 'Antony', position: 'FWD', overall: 96, starting: true },
      { name: 'Cedric Bakambu', position: 'FWD', overall: 84, starting: true },
      { name: 'Fran Vieites', position: 'GK', overall: 75, starting: false },
      { name: 'Diego Llorente', position: 'DEF', overall: 84, starting: false },
      { name: 'Junior Firpo', position: 'DEF', overall: 84, starting: false },
      { name: 'Pablo Fornals', position: 'MID', overall: 87, starting: false },
      { name: 'Nelson Deossa', position: 'MID', overall: 80, starting: false },
      { name: 'Chimy Avila', position: 'FWD', overall: 84, starting: false },
      { name: 'Rodrigo Riquelme', position: 'FWD', overall: 83, starting: false },
    ],
  },
  {
    id: 'lm-psv',
    club: 'PSV Eindhoven',
    players: [
      { name: 'Walter Benitez', position: 'GK', overall: 91, starting: true },
      { name: 'Olivier Boscagli', position: 'DEF', overall: 88, starting: true },
      { name: 'Rick Karsdorp', position: 'DEF', overall: 84, starting: true },
      { name: 'Ryan Flamingo', position: 'DEF', overall: 84, starting: true },
      { name: 'Sergino Dest', position: 'DEF', overall: 93, starting: true },
      { name: 'Joey Veerman', position: 'MID', overall: 89, starting: true },
      { name: 'Ismael Saibari', position: 'MID', overall: 91, starting: true },
      { name: 'Guus Til', position: 'MID', overall: 88, starting: true },
      { name: 'Malik Tillman', position: 'MID', overall: 93, starting: true },
      { name: 'Ivan Perisic', position: 'FWD', overall: 89, starting: true },
      { name: 'Esmir Bajraktarevic', position: 'FWD', overall: 83, starting: true },
      { name: 'Kjell Scherpen', position: 'GK', overall: 76, starting: false },
      { name: 'Jerdy Schouten', position: 'DEF', overall: 84, starting: false },
      { name: 'Armando Obispo', position: 'DEF', overall: 84, starting: false },
      { name: 'Johan Bakayoko', position: 'MID', overall: 87, starting: false },
      { name: 'Couhaib Driouech', position: 'MID', overall: 80, starting: false },
      { name: 'Ricardo Pepi', position: 'FWD', overall: 89, starting: false },
      { name: 'Sam Lammers', position: 'FWD', overall: 78, starting: false },
    ],
  },
  {
    id: 'lm-feyenoord',
    club: 'Feyenoord Rotterdam',
    players: [
      { name: 'Timon Wellenreuther', position: 'GK', overall: 85, starting: true },
      { name: 'David Hancko', position: 'DEF', overall: 93, starting: true },
      { name: 'Gernot Trauner', position: 'DEF', overall: 84, starting: true },
      { name: 'Bart Nieuwkoop', position: 'DEF', overall: 81, starting: true },
      { name: 'Hugo Bueno', position: 'DEF', overall: 80, starting: true },
      { name: 'Antoni Milambo', position: 'MID', overall: 87, starting: true },
      { name: 'Jordan Lotomba', position: 'MID', overall: 78, starting: true },
      { name: 'Julian Carranza', position: 'MID', overall: 83, starting: true },
      { name: 'Anis Hadj Moussa', position: 'MID', overall: 89, starting: true },
      { name: 'Ayase Ueda', position: 'FWD', overall: 88, starting: true },
      { name: 'Ibrahim Osman', position: 'FWD', overall: 84, starting: true },
      { name: 'Ivor Pandur', position: 'GK', overall: 73, starting: false },
      { name: 'Givairo Read', position: 'DEF', overall: 75, starting: false },
      { name: 'Marcos Lopez', position: 'DEF', overall: 76, starting: false },
      { name: 'Kenneth Taylor', position: 'MID', overall: 84, starting: false },
      { name: 'Igor Paixao', position: 'MID', overall: 89, starting: false },
      { name: 'Julian Neres', position: 'FWD', overall: 80, starting: false },
      { name: 'Leo Sauer', position: 'FWD', overall: 77, starting: false },
    ],
  },
  {
    id: 'lm-lille',
    club: 'Lille OSC',
    players: [
      { name: 'Berke Ozer', position: 'GK', overall: 84, starting: true },
      { name: 'Aissa Mandi', position: 'DEF', overall: 87, starting: true },
      { name: 'Tiago Santos', position: 'DEF', overall: 83, starting: true },
      { name: 'Bafode Diakite', position: 'DEF', overall: 87, starting: true },
      { name: 'Alexsandro', position: 'DEF', overall: 87, starting: true },
      { name: 'Angel Gomes', position: 'MID', overall: 91, starting: true },
      { name: 'Ayyoub Bouaddi', position: 'MID', overall: 88, starting: true },
      { name: 'Nabil Bentaleb', position: 'MID', overall: 84, starting: true },
      { name: 'Romain Perraud', position: 'MID', overall: 78, starting: true },
      { name: 'Hakon Haraldsson', position: 'FWD', overall: 87, starting: true },
      { name: 'Edon Zhegrova', position: 'FWD', overall: 87, starting: true },
      { name: 'Yanis Guermouche', position: 'GK', overall: 72, starting: false },
      { name: 'Aihem Ben Chaabane', position: 'DEF', overall: 76, starting: false },
      { name: 'Alan Virginius', position: 'DEF', overall: 75, starting: false },
      { name: 'Rafael Ratao', position: 'MID', overall: 78, starting: false },
      { name: 'Osame Sahraoui', position: 'MID', overall: 80, starting: false },
      { name: 'Matias Fernandez-Pardo', position: 'FWD', overall: 84, starting: false },
      { name: 'Ngal-ayel Mukau', position: 'FWD', overall: 76, starting: false },
    ],
  },
  {
    id: 'lm-lyon',
    club: 'Olympique Lyon',
    players: [
      { name: 'Remy Descamps', position: 'GK', overall: 83, starting: true },
      { name: 'Moussa Niakhate', position: 'DEF', overall: 88, starting: true },
      { name: 'Duje Caleta-Car', position: 'DEF', overall: 85, starting: true },
      { name: 'Nicolas Tagliafico', position: 'DEF', overall: 87, starting: true },
      { name: 'Abner', position: 'DEF', overall: 84, starting: true },
      { name: 'Corentin Tolisso', position: 'MID', overall: 89, starting: true },
      { name: 'Tanner Tessmann', position: 'MID', overall: 84, starting: true },
      { name: 'Tyler Morton', position: 'MID', overall: 84, starting: true },
      { name: 'Nemanja Matic', position: 'MID', overall: 83, starting: true },
      { name: 'Afonso Moreira', position: 'FWD', overall: 83, starting: true },
      { name: 'Georges Mikautadze', position: 'FWD', overall: 91, starting: true },
      { name: 'Dominik Greif', position: 'GK', overall: 75, starting: false },
      { name: 'Clinton Mata', position: 'DEF', overall: 76, starting: false },
      { name: 'Ainsley Lord', position: 'DEF', overall: 73, starting: false },
      { name: 'Malick Fofana', position: 'MID', overall: 89, starting: false },
      { name: 'Adam Karabec', position: 'MID', overall: 78, starting: false },
      { name: 'Martin Satriano', position: 'FWD', overall: 80, starting: false },
      { name: 'Ernest Nuamah', position: 'FWD', overall: 80, starting: false },
    ],
  },
  {
    id: 'lm-bodo',
    club: 'Bodø/Glimt',
    players: [
      { name: 'Julian Faye Lund', position: 'GK', overall: 84, starting: true },
      { name: 'Nikita Khaikin', position: 'GK', overall: 80, starting: true },
      { name: 'Fredrik Sjovold', position: 'DEF', overall: 84, starting: true },
      { name: 'Fredrik Bjorkan', position: 'DEF', overall: 85, starting: true },
      { name: 'Odin Bjortuft', position: 'DEF', overall: 83, starting: true },
      { name: 'Haitam Aleesami', position: 'DEF', overall: 84, starting: true },
      { name: 'Patrick Berg', position: 'MID', overall: 91, starting: true },
      { name: 'Sondre Auklend', position: 'MID', overall: 84, starting: true },
      { name: 'Hakon Evjen', position: 'MID', overall: 87, starting: true },
      { name: 'Ulrik Saltnes', position: 'MID', overall: 83, starting: true },
      { name: 'Jens Petter Hauge', position: 'FWD', overall: 89, starting: true },
      { name: 'Kasper Hogh', position: 'FWD', overall: 88, starting: true },
      { name: 'Jostein Gundersen', position: 'DEF', overall: 81, starting: false },
      { name: 'Villads Nielsen', position: 'DEF', overall: 78, starting: false },
      { name: 'Sondre Fet', position: 'MID', overall: 78, starting: false },
      { name: 'Anders Klynge', position: 'MID', overall: 76, starting: false },
      { name: 'Ole Didrik Blomberg', position: 'FWD', overall: 84, starting: false },
      { name: 'Ola Brynhildsen', position: 'FWD', overall: 81, starting: false },
    ],
  },
  {
    id: 'lm-napoli',
    club: 'SSC Napoli',
    players: [
      { name: 'Alex Meret', position: 'GK', overall: 89, starting: true },
      { name: 'Amir Rrahmani', position: 'DEF', overall: 88, starting: true },
      { name: 'Sam Beukema', position: 'DEF', overall: 85, starting: true },
      { name: 'Mathias Olivera', position: 'DEF', overall: 87, starting: true },
      { name: 'Giovanni Di Lorenzo', position: 'DEF', overall: 89, starting: true },
      { name: 'Stanislav Lobotka', position: 'MID', overall: 91, starting: true },
      { name: 'Scott McTominay', position: 'MID', overall: 96, starting: true },
      { name: 'Frank Anguissa', position: 'MID', overall: 89, starting: true },
      { name: 'Noa Lang', position: 'MID', overall: 89, starting: true },
      { name: 'Rasmus Hojlund', position: 'FWD', overall: 92, starting: true },
      { name: 'Lorenzo Lucca', position: 'FWD', overall: 87, starting: true },
      { name: 'Massimo Coppitelli', position: 'GK', overall: 70, starting: false },
      { name: 'Leonardo Spinazzola', position: 'DEF', overall: 80, starting: false },
      { name: 'Juan Jesus', position: 'DEF', overall: 80, starting: false },
      { name: 'Billy Gilmour', position: 'MID', overall: 83, starting: false },
      { name: 'Elia Caprile', position: 'MID', overall: 70, starting: false },
      { name: 'Romelu Lukaku', position: 'FWD', overall: 93, starting: false },
      { name: 'David Neres', position: 'FWD', overall: 87, starting: false },
    ],
  },
  {
    id: 'lm-leipzig',
    club: 'RB Leipzig',
    players: [
      { name: 'Peter Gulacsi', position: 'GK', overall: 84, starting: true },
      { name: 'Castello Lukeba', position: 'DEF', overall: 89, starting: true },
      { name: 'Mohamed Simakan', position: 'DEF', overall: 87, starting: true },
      { name: 'Ridle Baku', position: 'DEF', overall: 84, starting: true },
      { name: 'Arthur Vermeeren', position: 'DEF', overall: 84, starting: true },
      { name: 'Xavi Simons', position: 'MID', overall: 96, starting: true },
      { name: 'Kevin Kampl', position: 'MID', overall: 81, starting: true },
      { name: 'Assan Ouedraogo', position: 'MID', overall: 84, starting: true },
      { name: 'Xavier Simons', position: 'MID', overall: 84, starting: true },
      { name: 'Yan Diomande', position: 'FWD', overall: 84, starting: true },
      { name: 'Christoph Baumgartner', position: 'FWD', overall: 89, starting: true },
      { name: 'Maarten Vandevoordt', position: 'GK', overall: 77, starting: false },
      { name: 'Willi Orban', position: 'DEF', overall: 83, starting: false },
      { name: 'David Raum', position: 'DEF', overall: 89, starting: false },
      { name: 'Lois Openda', position: 'MID', overall: 91, starting: false },
      { name: 'El Chadaille Bitshiabu', position: 'MID', overall: 78, starting: false },
      { name: 'Romulo Cardoso', position: 'FWD', overall: 75, starting: false },
      { name: 'Fabio Carvalho', position: 'FWD', overall: 91, starting: false },
    ],
  },
  {
    id: 'lm-villarreal',
    club: 'Villarreal CF',
    players: [
      { name: 'Diego Conde', position: 'GK', overall: 83, starting: true },
      { name: 'Rafa Marin', position: 'DEF', overall: 84, starting: true },
      { name: 'Logan Costa', position: 'DEF', overall: 87, starting: true },
      { name: 'Sergi Cardona', position: 'DEF', overall: 80, starting: true },
      { name: 'Juan Foyth', position: 'DEF', overall: 87, starting: true },
      { name: 'Santi Comesana', position: 'MID', overall: 85, starting: true },
      { name: 'Dani Parejo', position: 'MID', overall: 89, starting: true },
      { name: 'Alberto Moleiro', position: 'MID', overall: 88, starting: true },
      { name: 'Pape Gueye', position: 'MID', overall: 85, starting: true },
      { name: 'Ayoze Perez', position: 'FWD', overall: 87, starting: true },
      { name: 'Nicolas Pepe', position: 'FWD', overall: 89, starting: true },
      { name: 'Filip Jorgensen', position: 'GK', overall: 78, starting: false },
      { name: 'Ayoze Iglesias', position: 'DEF', overall: 75, starting: false },
      { name: 'Willy Kambwala', position: 'DEF', overall: 78, starting: false },
      { name: 'Gerard Moreno', position: 'MID', overall: 84, starting: false },
      { name: 'Yeremy Pino', position: 'MID', overall: 87, starting: false },
      { name: 'Thierno Barry', position: 'FWD', overall: 83, starting: false },
      { name: 'Alex Baena', position: 'FWD', overall: 93, starting: false },
    ],
  },
  {
    id: 'lm-shakhtar',
    club: 'Shakhtar Donieck',
    players: [
      { name: 'Neheme Kobienko', position: 'GK', overall: 80, starting: true },
      { name: 'Valeriy Bondar', position: 'DEF', overall: 84, starting: true },
      { name: 'Yukhym Konoplia', position: 'DEF', overall: 80, starting: true },
      { name: 'Mykola Matvienko', position: 'DEF', overall: 83, starting: true },
      { name: 'Dodo', position: 'DEF', overall: 83, starting: true },
      { name: 'Georgiy Sudakov', position: 'MID', overall: 91, starting: true },
      { name: 'Marian Shved', position: 'MID', overall: 78, starting: true },
      { name: 'Ivan Petriak', position: 'MID', overall: 77, starting: true },
      { name: 'Kevin', position: 'MID', overall: 79, starting: true },
      { name: 'Danylo Sikan', position: 'FWD', overall: 83, starting: true },
      { name: 'Eguinaldo', position: 'FWD', overall: 78, starting: true },
      { name: 'Anatoliy Trubin', position: 'GK', overall: 72, starting: false },
      { name: 'Dmytro Kryskiv', position: 'DEF', overall: 73, starting: false },
      { name: 'Zaha Bilenkyi', position: 'DEF', overall: 70, starting: false },
      { name: 'Oleksandr Zubkov', position: 'MID', overall: 78, starting: false },
      { name: 'Pedrinho', position: 'MID', overall: 75, starting: false },
      { name: 'Lassina Traore', position: 'FWD', overall: 80, starting: false },
      { name: 'Newerton', position: 'FWD', overall: 73, starting: false },
    ],
  },
  {
    id: 'lm-galatasaray',
    club: 'Galatasaray Stambuł',
    players: [
      { name: 'Uğurcan Çakır', position: 'GK', overall: 96, starting: true },
      { name: 'Davinson Sanchez', position: 'DEF', overall: 89, starting: true },
      { name: 'Abdülkerim Bardakci', position: 'DEF', overall: 87, starting: true },
      { name: 'Eren Elmali', position: 'DEF', overall: 83, starting: true },
      { name: 'Elias Jelert', position: 'DEF', overall: 80, starting: true },
      { name: 'Lucas Torreira', position: 'MID', overall: 88, starting: true },
      { name: 'İsmail Yüksek', position: 'MID', overall: 80, starting: true },
      { name: 'Kerem Aktürkoğlu', position: 'MID', overall: 89, starting: true },
      { name: 'Yunus Akgün', position: 'MID', overall: 84, starting: true },
      { name: 'Victor Osimhen', position: 'FWD', overall: 100, starting: true },
      { name: 'Mauro Icardi', position: 'FWD', overall: 89, starting: true },
      { name: 'Günay Güvenç', position: 'GK', overall: 72, starting: false },
      { name: 'Mario Lemina', position: 'DEF', overall: 84, starting: false },
      { name: 'Roland Sallai', position: 'DEF', overall: 83, starting: false },
      { name: 'Sacha Boey', position: 'MID', overall: 84, starting: false },
      { name: 'Berkan Kutlu', position: 'MID', overall: 77, starting: false },
      { name: 'Leroy Sané', position: 'FWD', overall: 91, starting: false },
      { name: 'Baris Alper Yilmaz', position: 'FWD', overall: 87, starting: false },
    ],
  },
  {
    id: 'lm-crvena',
    club: 'Crvena zvezda',
    players: [
      { name: 'Matheus', position: 'GK', overall: 75, starting: true },
      { name: 'Mirko Ivanic', position: 'DEF', overall: 73, starting: true },
      { name: 'Nemanja Milunovic', position: 'DEF', overall: 72, starting: true },
      { name: 'Aleksa Terzic', position: 'DEF', overall: 73, starting: true },
      { name: 'Milos Degenek', position: 'DEF', overall: 78, starting: true },
      { name: 'Marko Arnautovic', position: 'MID', overall: 78, starting: true },
      { name: 'Guelor Kanga', position: 'MID', overall: 72, starting: true },
      { name: 'Marko Marin', position: 'MID', overall: 70, starting: true },
      { name: 'Rade Krunic', position: 'MID', overall: 69, starting: true },
      { name: 'Braian Rodriguez', position: 'FWD', overall: 72, starting: true },
      { name: 'Osman Bukari', position: 'FWD', overall: 75, starting: true },
      { name: 'Filip Jankovic', position: 'GK', overall: 65, starting: false },
      { name: 'Radovan Pankov', position: 'DEF', overall: 70, starting: false },
      { name: 'Bruno Duarte', position: 'DEF', overall: 68, starting: false },
      { name: 'Mihajlo Ilic', position: 'MID', overall: 66, starting: false },
      { name: 'Marko Lazetic', position: 'MID', overall: 67, starting: false },
      { name: 'Julius Ertlthaler', position: 'FWD', overall: 68, starting: false },
      { name: 'Kevin Rios', position: 'FWD', overall: 64, starting: false },
    ],
  },
  {
    id: 'lm-dinamo-zg',
    club: 'Dinamo Zagrzeb',
    players: [
      { name: 'Dominik Livakovic', position: 'GK', overall: 89, starting: true },
      { name: 'Petar Bocevski', position: 'DEF', overall: 72, starting: true },
      { name: 'Emir Sahiti', position: 'DEF', overall: 68, starting: true },
      { name: 'Filip Uremovic', position: 'DEF', overall: 75, starting: true },
      { name: 'Stefan Ristovski', position: 'DEF', overall: 72, starting: true },
      { name: 'Josip Misic', position: 'MID', overall: 77, starting: true },
      { name: 'Robert Leko', position: 'MID', overall: 70, starting: true },
      { name: 'Kristijan Jakic', position: 'MID', overall: 84, starting: true },
      { name: 'Marko Bulat', position: 'MID', overall: 69, starting: true },
      { name: 'Bruno Petkovic', position: 'FWD', overall: 78, starting: true },
      { name: 'Sandro Kulenovic', position: 'FWD', overall: 73, starting: true },
      { name: 'Ivan Nevistic', position: 'GK', overall: 76, starting: false },
      { name: 'Arnold Rupert Reijnders', position: 'DEF', overall: 68, starting: false },
      { name: 'Toni Fruk', position: 'DEF', overall: 73, starting: false },
      { name: 'Franjo Ivanovic', position: 'MID', overall: 78, starting: false },
      { name: 'Takuya Ogiwara', position: 'MID', overall: 68, starting: false },
      { name: 'Ivan Sesar', position: 'FWD', overall: 70, starting: false },
      { name: 'Marko Pjaca', position: 'FWD', overall: 75, starting: false },
    ],
  },
  {
    id: 'lm-celtic',
    club: 'Celtic FC',
    players: [
      { name: 'Kasper Schmeichel', position: 'GK', overall: 83, starting: true },
      { name: 'Anthony Ralston', position: 'DEF', overall: 75, starting: true },
      { name: 'Liam Scales', position: 'DEF', overall: 77, starting: true },
      { name: 'Gustaf Lagerbielke', position: 'DEF', overall: 75, starting: true },
      { name: 'Alistair Johnston', position: 'DEF', overall: 83, starting: true },
      { name: 'Callum McGregor', position: 'MID', overall: 83, starting: true },
      { name: 'Reo Hatate', position: 'MID', overall: 80, starting: true },
      { name: 'Arne Engels', position: 'MID', overall: 84, starting: true },
      { name: 'Daizen Maeda', position: 'MID', overall: 84, starting: true },
      { name: 'Kyogo Furuhashi', position: 'FWD', overall: 83, starting: true },
      { name: 'Johnny Kenny', position: 'FWD', overall: 75, starting: true },
      { name: 'Scott Bain', position: 'GK', overall: 68, starting: false },
      { name: 'Greg Taylor', position: 'DEF', overall: 74, starting: false },
      { name: 'Auston Trusty', position: 'DEF', overall: 75, starting: false },
      { name: 'Paulo Bernardo', position: 'MID', overall: 76, starting: false },
      { name: 'Nicolas Kuhn', position: 'MID', overall: 80, starting: false },
      { name: 'Adam Idah', position: 'FWD', overall: 78, starting: false },
      { name: 'Benjamin Nygren', position: 'FWD', overall: 77, starting: false },
    ],
  },
  {
    id: 'lm-slavia',
    club: 'Slavia Praga',
    players: [
      { name: 'Jindrich Stanek', position: 'GK', overall: 87, starting: true },
      { name: 'David Zima', position: 'DEF', overall: 84, starting: true },
      { name: 'Tomas Vlcek', position: 'DEF', overall: 73, starting: true },
      { name: 'David Doudera', position: 'DEF', overall: 78, starting: true },
      { name: 'Stepan Chaloupek', position: 'DEF', overall: 76, starting: true },
      { name: 'Lukas Provod', position: 'MID', overall: 87, starting: true },
      { name: 'Michal Sadilek', position: 'MID', overall: 83, starting: true },
      { name: 'Christos Zafeiris', position: 'MID', overall: 78, starting: true },
      { name: 'Vaclav Cerny', position: 'MID', overall: 77, starting: true },
      { name: 'Mojmir Chytil', position: 'FWD', overall: 80, starting: true },
      { name: 'Ivan Schranz', position: 'FWD', overall: 77, starting: true },
      { name: 'Marek Rodak', position: 'GK', overall: 70, starting: false },
      { name: 'Jaroslav Zeleny', position: 'DEF', overall: 73, starting: false },
      { name: 'David Jurasek', position: 'DEF', overall: 77, starting: false },
      { name: 'Oscar Dorley', position: 'MID', overall: 73, starting: false },
      { name: 'Denis Visinsky', position: 'MID', overall: 73, starting: false },
      { name: 'Tomas Chory', position: 'FWD', overall: 74, starting: false },
      { name: 'Jan Kuchta', position: 'FWD', overall: 78, starting: false },
    ],
  },
  {
    id: 'lm-slovan-ba',
    club: 'Slovan Bratysława',
    players: [
      { name: 'Adam Jendrisek II', position: 'GK', overall: 75, starting: true },
      { name: 'Kevin Wimmer', position: 'DEF', overall: 73, starting: true },
      { name: 'Denis Vavro', position: 'DEF', overall: 76, starting: true },
      { name: 'Lukas Sauer', position: 'DEF', overall: 70, starting: true },
      { name: 'Peter Kovac', position: 'DEF', overall: 68, starting: true },
      { name: 'Vladimir Weiss', position: 'MID', overall: 75, starting: true },
      { name: 'Adrian Kanik', position: 'MID', overall: 68, starting: true },
      { name: 'Tigran Barseghyan', position: 'MID', overall: 70, starting: true },
      { name: 'Isnik Alimi', position: 'MID', overall: 64, starting: true },
      { name: 'David Strelec', position: 'FWD', overall: 73, starting: true },
      { name: 'Rangelo Janga', position: 'FWD', overall: 70, starting: true },
      { name: 'Adam Jendrisek', position: 'GK', overall: 62, starting: false },
      { name: 'Erik Grendel', position: 'DEF', overall: 65, starting: false },
      { name: 'Timotej Jambor', position: 'DEF', overall: 62, starting: false },
      { name: 'Tomas Rigo', position: 'MID', overall: 66, starting: false },
      { name: 'Cheikh Sabaly', position: 'MID', overall: 64, starting: false },
      { name: 'Nino Galovic', position: 'FWD', overall: 66, starting: false },
      { name: 'Andrija Vukcevic', position: 'FWD', overall: 63, starting: false },
    ],
  },
  {
    id: 'lm-stuttgart',
    club: 'VfB Stuttgart',
    players: [
      { name: 'Alexander Nubel', position: 'GK', overall: 85, starting: true },
      { name: 'Jeff Chabot', position: 'DEF', overall: 83, starting: true },
      { name: 'Ramon Hendriks', position: 'DEF', overall: 78, starting: true },
      { name: 'Josha Vagnoman', position: 'DEF', overall: 80, starting: true },
      { name: 'Maximilian Mittelstadt', position: 'DEF', overall: 83, starting: true },
      { name: 'Angelo Stiller', position: 'MID', overall: 89, starting: true },
      { name: 'Atakan Karazor', position: 'MID', overall: 80, starting: true },
      { name: 'Chris Fuhrich', position: 'MID', overall: 78, starting: true },
      { name: 'Jamie Leweling', position: 'MID', overall: 84, starting: true },
      { name: 'Ermedin Demirovic', position: 'FWD', overall: 88, starting: true },
      { name: 'Deniz Undav', position: 'FWD', overall: 89, starting: true },
      { name: 'Fabian Bredlow', position: 'GK', overall: 68, starting: false },
      { name: 'Dan-Axel Zagadou', position: 'DEF', overall: 76, starting: false },
      { name: 'Jacob Bruun Larsen', position: 'DEF', overall: 75, starting: false },
      { name: 'Fabian Rieder', position: 'MID', overall: 83, starting: false },
      { name: 'Nikolas Nartey', position: 'MID', overall: 73, starting: false },
      { name: 'El Bilal Toure', position: 'FWD', overall: 76, starting: false },
      { name: 'Rocco Reitz', position: 'FWD', overall: 70, starting: false },
    ],
  },
  {
    id: 'lm-como',
    club: 'Como 1907',
    players: [
      { name: 'Pepe Reina', position: 'GK', overall: 70, starting: true },
      { name: 'Alberto Moreno', position: 'DEF', overall: 73, starting: true },
      { name: 'Ivan Smolcic', position: 'DEF', overall: 70, starting: true },
      { name: 'Marc-Oliver Kempf', position: 'DEF', overall: 73, starting: true },
      { name: 'Alex Valle', position: 'DEF', overall: 72, starting: true },
      { name: 'Nico Paz', position: 'MID', overall: 91, starting: true },
      { name: 'Martin Baturina', position: 'MID', overall: 89, starting: true },
      { name: 'Lucas Da Cunha', position: 'MID', overall: 75, starting: true },
      { name: 'Assane Diao', position: 'MID', overall: 84, starting: true },
      { name: 'Patrick Cutrone', position: 'FWD', overall: 75, starting: true },
      { name: 'Jesus Rodriguez', position: 'FWD', overall: 78, starting: true },
      { name: 'Jean Butez', position: 'GK', overall: 68, starting: false },
      { name: 'Alessandro Gabrielloni', position: 'DEF', overall: 65, starting: false },
      { name: 'Yan-Eteki', position: 'DEF', overall: 66, starting: false },
      { name: 'Ivan Ilic', position: 'MID', overall: 75, starting: false },
      { name: 'Jayden Addai', position: 'MID', overall: 73, starting: false },
      { name: 'Alvaro Morata', position: 'FWD', overall: 87, starting: false },
      { name: 'Anderson Esposito', position: 'FWD', overall: 66, starting: false },
    ],
  },
  {
    id: 'lm-lens',
    club: 'RC Lens',
    players: [
      { name: 'Robin Risser', position: 'GK', overall: 76, starting: true },
      { name: 'Kevin Danso', position: 'DEF', overall: 84, starting: true },
      { name: 'Facundo Medina', position: 'DEF', overall: 84, starting: true },
      { name: 'Jonathan Gradit', position: 'DEF', overall: 78, starting: true },
      { name: 'Deiver Machado', position: 'DEF', overall: 74, starting: true },
      { name: 'Adrien Thomasson', position: 'MID', overall: 77, starting: true },
      { name: 'Andy Diouf', position: 'MID', overall: 76, starting: true },
      { name: 'Angelo Fulgini', position: 'MID', overall: 73, starting: true },
      { name: 'Morgan Guilavogui', position: 'MID', overall: 72, starting: true },
      { name: 'Wesley Said', position: 'FWD', overall: 75, starting: true },
      { name: 'Florian Sotoca', position: 'FWD', overall: 76, starting: true },
      { name: 'Yehvann Diouf', position: 'GK', overall: 70, starting: false },
      { name: 'Malang Sarr', position: 'DEF', overall: 75, starting: false },
      { name: 'Facundo Marchetta', position: 'DEF', overall: 66, starting: false },
      { name: 'Alexis Michel', position: 'MID', overall: 64, starting: false },
      { name: 'Przemyslaw Frankowski', position: 'MID', overall: 78, starting: false },
      { name: 'Ivan Cavaleiro', position: 'FWD', overall: 70, starting: false },
      { name: 'Odsonne Edouard', position: 'FWD', overall: 77, starting: false },
    ],
  },
  {
    id: 'lm2-aarhus',
    club: 'Aarhus GF',
    players: [
      { name: 'Jeppe Hojbjerg', position: 'GK', overall: 75, starting: true },
      { name: 'Mads Emil Madsen', position: 'DEF', overall: 73, starting: true },
      { name: 'Marc Dal Hende', position: 'DEF', overall: 72, starting: true },
      { name: 'Sebastian Sivebaek', position: 'DEF', overall: 70, starting: true },
      { name: 'Elmehdi Ndour', position: 'DEF', overall: 73, starting: true },
      { name: 'Mathias Kjolo', position: 'MID', overall: 75, starting: true },
      { name: 'Tobias Borkeeiet', position: 'MID', overall: 70, starting: true },
      { name: 'Aske Rune Nielsen', position: 'MID', overall: 68, starting: true },
      { name: 'Mikael Anderson', position: 'MID', overall: 68, starting: true },
      { name: 'Awer Mabil', position: 'FWD', overall: 78, starting: true },
      { name: 'Patrick Mortensen', position: 'FWD', overall: 73, starting: true },
      { name: 'Alexander Ramsdal', position: 'GK', overall: 62, starting: false },
      { name: 'Christian Sorensen', position: 'DEF', overall: 64, starting: false },
      { name: 'Jakob Ahlmann', position: 'DEF', overall: 62, starting: false },
      { name: 'Franculino Dju', position: 'MID', overall: 70, starting: false },
      { name: 'Kevin Pedersen', position: 'MID', overall: 62, starting: false },
      { name: 'Jesper Lindstrom', position: 'FWD', overall: 75, starting: false },
      { name: 'Sebastian Ross', position: 'FWD', overall: 68, starting: false },
    ],
  },
  {
    id: 'lm2-fenerbahce',
    club: 'Fenerbahçe',
    players: [
      { name: 'Ederson Moraes', position: 'GK', overall: 89, starting: true },
      { name: 'Rodrigo Becao', position: 'DEF', overall: 87, starting: true },
      { name: 'Milan Skriniar', position: 'DEF', overall: 96, starting: true },
      { name: 'Bright Osayi-Samuel', position: 'DEF', overall: 85, starting: true },
      { name: 'Jayden Oosterwolde', position: 'DEF', overall: 85, starting: true },
      { name: 'Sebastian Szymanski', position: 'MID', overall: 96, starting: true },
      { name: 'Ismail Yuksek', position: 'MID', overall: 83, starting: true },
      { name: 'Fred', position: 'MID', overall: 87, starting: true },
      { name: 'Cengiz Under', position: 'MID', overall: 88, starting: true },
      { name: 'Edin Dzeko', position: 'FWD', overall: 96, starting: true },
      { name: 'Youssef En-Nesyri', position: 'FWD', overall: 92, starting: true },
      { name: 'Ted Skarabot', position: 'GK', overall: 72, starting: false },
      { name: 'Mert Muldur', position: 'DEF', overall: 84, starting: false },
      { name: 'Levent Mercan', position: 'DEF', overall: 73, starting: false },
      { name: 'Irfan Can Kahveci', position: 'MID', overall: 88, starting: false },
      { name: 'Fred Alves', position: 'MID', overall: 78, starting: false },
      { name: 'Dorgeles Nene', position: 'FWD', overall: 78, starting: false },
      { name: 'Anderson Talisca', position: 'FWD', overall: 87, starting: false },
    ],
  },
  {
    id: 'lm2-pool-maccabi',
    club: 'Maccabi Tel Aviv',
    players: [
      { name: 'Daniel Peretz', position: 'GK', overall: 79, starting: true },
      { name: 'Sean Goldberg', position: 'DEF', overall: 76, starting: true },
      { name: 'Ilay Feingold', position: 'DEF', overall: 73, starting: true },
      { name: 'Roi Kehat', position: 'DEF', overall: 72, starting: true },
      { name: 'Rami Gershon', position: 'DEF', overall: 73, starting: true },
      { name: 'Dor Peretz', position: 'MID', overall: 78, starting: true },
      { name: 'Ariel Harosh', position: 'MID', overall: 70, starting: true },
      { name: 'Yonatan Cohen', position: 'MID', overall: 70, starting: true },
      { name: 'Din David', position: 'MID', overall: 68, starting: true },
      { name: 'Dor Turgeman', position: 'FWD', overall: 77, starting: true },
      { name: 'Gadi Kinda', position: 'FWD', overall: 75, starting: true },
      { name: 'Guy Yehoshua', position: 'GK', overall: 62, starting: false },
      { name: 'Idan Nachmias', position: 'DEF', overall: 64, starting: false },
      { name: 'Or Blorian', position: 'DEF', overall: 62, starting: false },
      { name: 'Goni Naor', position: 'MID', overall: 63, starting: false },
      { name: 'Yarden Shua', position: 'MID', overall: 62, starting: false },
      { name: 'Ovidiu Bic', position: 'FWD', overall: 65, starting: false },
      { name: 'Chery Deiman', position: 'FWD', overall: 64, starting: false },
    ],
  },
  {
    id: 'lm2-pool-ludogorets',
    club: 'Ludogorets Razgrad',
    players: [
      { name: 'Yordan Iliev', position: 'GK', overall: 75, starting: true },
      { name: 'Cauly Oliveira Souza', position: 'DEF', overall: 76, starting: true },
      { name: 'Aureo Pereira', position: 'DEF', overall: 75, starting: true },
      { name: 'Rick', position: 'DEF', overall: 73, starting: true },
      { name: 'Vinicius Franco', position: 'DEF', overall: 72, starting: true },
      { name: 'Dominik Marczuk', position: 'MID', overall: 73, starting: true },
      { name: 'Fernando Gorriaran', position: 'MID', overall: 76, starting: true },
      { name: 'Filip Krastev', position: 'MID', overall: 72, starting: true },
      { name: 'Rui Modesto', position: 'MID', overall: 68, starting: true },
      { name: 'Pieros Sotiriou', position: 'FWD', overall: 77, starting: true },
      { name: 'Bare Balde', position: 'FWD', overall: 72, starting: true },
      { name: 'Sergio Padt', position: 'GK', overall: 66, starting: false },
      { name: 'Anthony Cannon', position: 'DEF', overall: 65, starting: false },
      { name: 'Kristiyan Malinov', position: 'DEF', overall: 66, starting: false },
      { name: 'Ivaylo Chochev', position: 'MID', overall: 67, starting: false },
      { name: 'Kiril Despodov', position: 'MID', overall: 73, starting: false },
      { name: 'Marlon Fernandes', position: 'FWD', overall: 68, starting: false },
      { name: 'Denislav Aleksandrov', position: 'FWD', overall: 63, starting: false },
    ],
  },
  {
    id: 'lm2-pool-malmo',
    club: 'Malmö FF',
    players: [
      { name: 'Johan Dahlin', position: 'GK', overall: 76, starting: true },
      { name: 'Anel Ahmedhodzic', position: 'DEF', overall: 76, starting: true },
      { name: 'Felix Beijmo', position: 'DEF', overall: 70, starting: true },
      { name: 'Martin Olsson', position: 'DEF', overall: 68, starting: true },
      { name: 'Franklin Tebo Usim', position: 'DEF', overall: 66, starting: true },
      { name: 'Sebastian Nanasi', position: 'MID', overall: 78, starting: true },
      { name: 'Anders Christiansen', position: 'MID', overall: 73, starting: true },
      { name: 'Veljko Birmancevic', position: 'MID', overall: 76, starting: true },
      { name: 'Erik Ahlstrand', position: 'MID', overall: 68, starting: true },
      { name: 'Sead Haksabanovic', position: 'FWD', overall: 78, starting: true },
      { name: 'Kian Benyamine', position: 'FWD', overall: 70, starting: true },
      { name: 'Jacob Rinne', position: 'GK', overall: 65, starting: false },
      { name: 'Oscar Krondahl', position: 'DEF', overall: 64, starting: false },
      { name: 'Casper Hojer', position: 'DEF', overall: 62, starting: false },
      { name: 'Oscar Pettersson', position: 'MID', overall: 64, starting: false },
      { name: 'Christoffer Nyman', position: 'MID', overall: 66, starting: false },
      { name: 'Anthony Basso', position: 'FWD', overall: 63, starting: false },
      { name: 'Alexander Bah', position: 'FWD', overall: 64, starting: false },
    ],
  },
  {
    id: 'lm2-pool-hjk',
    club: 'HJK Helsinki',
    players: [
      { name: 'Simon Skotte', position: 'GK', overall: 68, starting: true },
      { name: 'Damion Lowe', position: 'DEF', overall: 70, starting: true },
      { name: 'Nicholas Hamalainen', position: 'DEF', overall: 66, starting: true },
      { name: 'Ilmari Niskanen', position: 'DEF', overall: 68, starting: true },
      { name: 'Anthony Olusanya', position: 'DEF', overall: 66, starting: true },
      { name: 'Rasmus Karjalainen', position: 'MID', overall: 66, starting: true },
      { name: 'Jaakko Oksanen', position: 'MID', overall: 64, starting: true },
      { name: 'Mikael Soisalo', position: 'MID', overall: 66, starting: true },
      { name: 'Robert Ivanov', position: 'MID', overall: 62, starting: true },
      { name: 'Filip Faski', position: 'FWD', overall: 65, starting: true },
      { name: 'Marcus Soomets', position: 'FWD', overall: 66, starting: true },
      { name: 'Vilhelm Paalanen', position: 'GK', overall: 58, starting: false },
      { name: 'Jeremiah Streng', position: 'DEF', overall: 60, starting: false },
      { name: 'Kelvin Ofori', position: 'DEF', overall: 58, starting: false },
      { name: 'Aapo Halme', position: 'MID', overall: 58, starting: false },
      { name: 'Santeri Hostikka', position: 'MID', overall: 56, starting: false },
      { name: 'Enoch Banza', position: 'FWD', overall: 59, starting: false },
      { name: 'Roope Riski', position: 'FWD', overall: 62, starting: false },
    ],
  },
  {
    id: 'lm2-pool-zrinjski',
    club: 'Zrinjski Mostar',
    players: [
      { name: 'Vladan Kovacevic', position: 'GK', overall: 68, starting: true },
      { name: 'Igor Vinicio', position: 'DEF', overall: 64, starting: true },
      { name: 'Dario Njavro', position: 'DEF', overall: 66, starting: true },
      { name: 'Ivan Lendric', position: 'DEF', overall: 64, starting: true },
      { name: 'Vasil Sinkovski', position: 'DEF', overall: 62, starting: true },
      { name: 'Nikola Kalinic', position: 'MID', overall: 66, starting: true },
      { name: 'Milan Blagojevic', position: 'MID', overall: 64, starting: true },
      { name: 'Marin Trstenjak', position: 'MID', overall: 62, starting: true },
      { name: 'Yohan Croizet', position: 'MID', overall: 64, starting: true },
      { name: 'Zvonimir Delas', position: 'FWD', overall: 64, starting: true },
      { name: 'Ivan Tatomirovic', position: 'FWD', overall: 62, starting: true },
      { name: 'Marko Barisic', position: 'GK', overall: 55, starting: false },
      { name: 'Josip Corluka', position: 'DEF', overall: 57, starting: false },
      { name: 'Petar Misic', position: 'DEF', overall: 55, starting: false },
      { name: 'Mateo Susic', position: 'MID', overall: 55, starting: false },
      { name: 'Franjo Prce', position: 'MID', overall: 54, starting: false },
      { name: 'Danilo Bracanovic', position: 'FWD', overall: 57, starting: false },
      { name: 'Nemanja Bilbija', position: 'FWD', overall: 58, starting: false },
    ],
  },
  {
    id: 'lm2-pool-servette',
    club: 'Servette Genève',
    players: [
      { name: 'Joel Mall', position: 'GK', overall: 72, starting: true },
      { name: 'Bradley Fink', position: 'DEF', overall: 68, starting: true },
      { name: 'Steve Rouiller', position: 'DEF', overall: 65, starting: true },
      { name: 'Jules Castelletto', position: 'DEF', overall: 62, starting: true },
      { name: 'Anthony Baron', position: 'DEF', overall: 64, starting: true },
      { name: 'Alvyn Sanches', position: 'MID', overall: 75, starting: true },
      { name: 'Enzo Crivelli', position: 'MID', overall: 70, starting: true },
      { name: 'Timothe Cognat', position: 'MID', overall: 70, starting: true },
      { name: 'Dereck Kutesa', position: 'MID', overall: 68, starting: true },
      { name: 'Chris Bedia', position: 'FWD', overall: 72, starting: true },
      { name: 'Jeremy Guillemenot', position: 'FWD', overall: 67, starting: true },
      { name: 'Kevin Rehak', position: 'GK', overall: 62, starting: false },
      { name: 'Leonardo Bertone', position: 'DEF', overall: 60, starting: false },
      { name: 'Yoann Gomis', position: 'DEF', overall: 58, starting: false },
      { name: 'Amir Abrashi', position: 'MID', overall: 62, starting: false },
      { name: 'Malick Mbaye', position: 'MID', overall: 58, starting: false },
      { name: 'Nicolas Vouilloz', position: 'FWD', overall: 66, starting: false },
      { name: 'Keigo Tsunemoto', position: 'FWD', overall: 60, starting: false },
    ],
  },
  {
    id: 'lm2-pool-shamrock',
    club: 'Shamrock Rovers',
    players: [
      { name: 'Ed McGinty', position: 'GK', overall: 68, starting: true },
      { name: 'Adam Matthews', position: 'DEF', overall: 70, starting: true },
      { name: 'Lee Grace', position: 'DEF', overall: 66, starting: true },
      { name: 'Daniel Cleary', position: 'DEF', overall: 65, starting: true },
      { name: 'Trevor Clarke', position: 'DEF', overall: 66, starting: true },
      { name: 'Dylan Watts', position: 'MID', overall: 70, starting: true },
      { name: 'Jack Byrne', position: 'MID', overall: 68, starting: true },
      { name: 'Gary O Neill', position: 'MID', overall: 64, starting: true },
      { name: 'Daniel Mandroiu', position: 'MID', overall: 66, starting: true },
      { name: 'Graham Burke', position: 'FWD', overall: 68, starting: true },
      { name: 'Aidomo Emakhu', position: 'FWD', overall: 64, starting: true },
      { name: 'Todd Bazunu', position: 'GK', overall: 58, starting: false },
      { name: 'Roberto Lopes', position: 'DEF', overall: 68, starting: false },
      { name: 'Josh Honohan', position: 'DEF', overall: 58, starting: false },
      { name: 'Victor Ozhianvuna', position: 'MID', overall: 58, starting: false },
      { name: 'John O Sullivan', position: 'MID', overall: 62, starting: false },
      { name: 'Danny Grant', position: 'FWD', overall: 59, starting: false },
      { name: 'Barry Cotter', position: 'FWD', overall: 57, starting: false },
    ],
  },
  {
    id: 'lm2-pool-kups',
    club: 'KuPS Kuopio',
    players: [
      { name: 'Jere Uronen', position: 'GK', overall: 70, starting: true },
      { name: 'Jyri Pikkarainen', position: 'DEF', overall: 64, starting: true },
      { name: 'Alexander Ring', position: 'DEF', overall: 73, starting: true },
      { name: 'Verneri Valimaa', position: 'DEF', overall: 64, starting: true },
      { name: 'Alex Tamm', position: 'DEF', overall: 62, starting: true },
      { name: 'Aleksi Uotila', position: 'MID', overall: 64, starting: true },
      { name: 'Enoch Mayanja', position: 'MID', overall: 62, starting: true },
      { name: 'Iiro Jarvinen', position: 'MID', overall: 60, starting: true },
      { name: 'Anssi Enckelman', position: 'MID', overall: 58, starting: true },
      { name: 'Robert Taylor', position: 'FWD', overall: 70, starting: true },
      { name: 'Riku Riski', position: 'FWD', overall: 62, starting: true },
      { name: 'Otto Nordlund', position: 'GK', overall: 54, starting: false },
      { name: 'Jarkko Hurme', position: 'DEF', overall: 54, starting: false },
      { name: 'Aapeli Rautiainen', position: 'DEF', overall: 52, starting: false },
      { name: 'Jussi Vasara', position: 'MID', overall: 52, starting: false },
      { name: 'Toivo Rannankari', position: 'MID', overall: 50, starting: false },
      { name: 'Alpha Sila', position: 'FWD', overall: 54, starting: false },
      { name: 'Miska Ojala', position: 'FWD', overall: 58, starting: false },
    ],
  },
  {
    id: 'lm2-pool-unionsg',
    club: 'Union Saint-Gilloise',
    players: [
      { name: 'Filip Stankovic', position: 'GK', overall: 85, starting: true },
      { name: 'Christian Burgess', position: 'DEF', overall: 84, starting: true },
      { name: 'Ross Sykes', position: 'DEF', overall: 80, starting: true },
      { name: 'Guillaume Francois', position: 'DEF', overall: 78, starting: true },
      { name: 'Mamadou Barry', position: 'DEF', overall: 77, starting: true },
      { name: 'Adem Zorgane', position: 'MID', overall: 87, starting: true },
      { name: 'Anouar Ait El Hadj', position: 'MID', overall: 84, starting: true },
      { name: 'Kamiel Van de Perre', position: 'MID', overall: 78, starting: true },
      { name: 'Rob Schoofs', position: 'MID', overall: 77, starting: true },
      { name: 'Promise David', position: 'FWD', overall: 88, starting: true },
      { name: 'Kevin Rodriguez', position: 'FWD', overall: 85, starting: true },
      { name: 'Vic Chambaere', position: 'GK', overall: 68, starting: false },
      { name: 'Yari Stevens', position: 'DEF', overall: 70, starting: false },
      { name: 'Noah Stassin', position: 'DEF', overall: 68, starting: false },
      { name: 'Besfort Zeneli', position: 'MID', overall: 75, starting: false },
      { name: 'Ousseynou Niang', position: 'MID', overall: 72, starting: false },
      { name: 'Anan Khalaili', position: 'FWD', overall: 80, starting: false },
      { name: 'Mateo Biondic', position: 'FWD', overall: 70, starting: false },
    ],
  },
  {
    id: 'lm2-pool-sparta',
    club: 'Sparta Praha',
    players: [
      { name: 'Peter Vindahl', position: 'GK', overall: 83, starting: true },
      { name: 'Asger Sorensen', position: 'DEF', overall: 83, starting: true },
      { name: 'Filip Panak', position: 'DEF', overall: 78, starting: true },
      { name: 'Ladislav Krejci', position: 'DEF', overall: 84, starting: true },
      { name: 'Martin Vitik', position: 'DEF', overall: 80, starting: true },
      { name: 'Ivan Mesik', position: 'MID', overall: 81, starting: true },
      { name: 'Lukas Sadilek', position: 'MID', overall: 83, starting: true },
      { name: 'Ondrej Kusej', position: 'MID', overall: 78, starting: true },
      { name: 'Albion Rrahmani', position: 'MID', overall: 75, starting: true },
      { name: 'David Douděra II', position: 'FWD', overall: 84, starting: true },
      { name: 'Alexander Ceferin', position: 'FWD', overall: 70, starting: true },
      { name: 'Tomas Vaclik', position: 'GK', overall: 78, starting: false },
      { name: 'Dominik Plechaty', position: 'DEF', overall: 73, starting: false },
      { name: 'David Moses', position: 'DEF', overall: 72, starting: false },
      { name: 'Matej Rynes', position: 'MID', overall: 75, starting: false },
      { name: 'Indrit Tuci', position: 'MID', overall: 70, starting: false },
      { name: 'Vasil Kusej', position: 'FWD', overall: 75, starting: false },
      { name: 'Adepoju Kehinde', position: 'FWD', overall: 68, starting: false },
    ],
  },
  {
    id: 'lm2-pool-sturmgraz',
    club: 'Sturm Graz',
    players: [
      { name: 'Oliver Christensen', position: 'GK', overall: 80, starting: true },
      { name: 'Gregory Wuthrich', position: 'DEF', overall: 79, starting: true },
      { name: 'Leon Grgic', position: 'DEF', overall: 75, starting: true },
      { name: 'Kevin Ortiz', position: 'DEF', overall: 74, starting: true },
      { name: 'David Affengruber', position: 'DEF', overall: 78, starting: true },
      { name: 'Otar Kiteishvili', position: 'MID', overall: 87, starting: true },
      { name: 'Tomi Horvat', position: 'MID', overall: 76, starting: true },
      { name: 'Seedy Jatta', position: 'MID', overall: 73, starting: true },
      { name: 'William Boving', position: 'MID', overall: 77, starting: true },
      { name: 'Tochi Chukwuani', position: 'FWD', overall: 75, starting: true },
      { name: 'Jusuf Gazibegovic', position: 'FWD', overall: 72, starting: true },
      { name: 'Jan Novak', position: 'GK', overall: 65, starting: false },
      { name: 'Emir Karic', position: 'DEF', overall: 70, starting: false },
      { name: 'Bright Edomwonyi', position: 'DEF', overall: 66, starting: false },
      { name: 'Mika Biereth', position: 'MID', overall: 75, starting: false },
      { name: 'Amady Camara', position: 'MID', overall: 68, starting: false },
      { name: 'Milos Bosnjak', position: 'FWD', overall: 70, starting: false },
      { name: 'Maurice Malone', position: 'FWD', overall: 65, starting: false },
    ],
  },
  {
    id: 'lm2-pool-necnijmegen',
    club: 'NEC Nijmegen',
    players: [
      { name: 'Jasper Cillessen', position: 'GK', overall: 87, starting: true },
      { name: 'Bram Nuytinck', position: 'DEF', overall: 78, starting: true },
      { name: 'Sontje Hansen', position: 'DEF', overall: 70, starting: true },
      { name: 'Souffian El Karouani', position: 'DEF', overall: 75, starting: true },
      { name: 'Yassin Oukili', position: 'DEF', overall: 72, starting: true },
      { name: 'Elayis Tavsan', position: 'MID', overall: 77, starting: true },
      { name: 'Sylvester van der Water', position: 'MID', overall: 75, starting: true },
      { name: 'Koki Ogawa', position: 'MID', overall: 78, starting: true },
      { name: 'Ivan Marquez', position: 'MID', overall: 70, starting: true },
      { name: 'Alieu Fadera', position: 'FWD', overall: 77, starting: true },
      { name: 'Justin Lonwijk', position: 'FWD', overall: 73, starting: true },
      { name: 'Robin Roefs', position: 'GK', overall: 68, starting: false },
      { name: 'Tim Bakker', position: 'DEF', overall: 70, starting: false },
      { name: 'Ellery Balder', position: 'DEF', overall: 66, starting: false },
      { name: 'Lasse Schone', position: 'MID', overall: 68, starting: false },
      { name: 'Anas Ouahim', position: 'MID', overall: 66, starting: false },
      { name: 'Mats Deijl', position: 'FWD', overall: 68, starting: false },
      { name: 'Killian Sardella', position: 'FWD', overall: 65, starting: false },
    ],
  },
  {
    id: 'lm2-pool-sabah',
    club: 'Sabah Baku',
    players: [
      { name: 'Salahat Aghayev', position: 'GK', overall: 72, starting: true },
      { name: 'Akim Zedadka', position: 'DEF', overall: 78, starting: true },
      { name: 'Ygor Nogueira', position: 'DEF', overall: 75, starting: true },
      { name: 'Andrey Santos', position: 'DEF', overall: 72, starting: true },
      { name: 'Tymoteusz Puchacz', position: 'DEF', overall: 77, starting: true },
      { name: 'Aleksey Isayev', position: 'MID', overall: 76, starting: true },
      { name: 'Umarali Rakhmonaliev', position: 'MID', overall: 75, starting: true },
      { name: 'Khayal Aliyev', position: 'MID', overall: 77, starting: true },
      { name: 'Kaheem Parris', position: 'MID', overall: 75, starting: true },
      { name: 'Joy-Lance Mickels', position: 'FWD', overall: 83, starting: true },
      { name: 'Zinedine Ould Khaled', position: 'FWD', overall: 73, starting: true },
      { name: 'Bogdan Letic', position: 'GK', overall: 65, starting: false },
      { name: 'Amin Seydiyev', position: 'DEF', overall: 68, starting: false },
      { name: 'Steve Solvet', position: 'DEF', overall: 67, starting: false },
      { name: 'Ivan Lepinjica', position: 'MID', overall: 70, starting: false },
      { name: 'Abdulakh Khaybulayev', position: 'MID', overall: 70, starting: false },
      { name: 'Anatoliy Nuriyev', position: 'FWD', overall: 69, starting: false },
      { name: 'Ayaz Guliyev', position: 'FWD', overall: 66, starting: false },
    ],
  },
  {
    id: 'lm2-pool-hearts',
    club: 'Hearts of Midlothian',
    players: [
      { name: 'Zander Clark', position: 'GK', overall: 78, starting: true },
      { name: 'Craig Halkett', position: 'DEF', overall: 81, starting: true },
      { name: 'Stephen Kingsley', position: 'DEF', overall: 76, starting: true },
      { name: 'Jamie McCart', position: 'DEF', overall: 75, starting: true },
      { name: 'Frankie Kent', position: 'DEF', overall: 74, starting: true },
      { name: 'Beni Baningime', position: 'MID', overall: 76, starting: true },
      { name: 'Alexandros Kyziridis', position: 'MID', overall: 77, starting: true },
      { name: 'Yan Dhanda', position: 'MID', overall: 75, starting: true },
      { name: 'Blair Spittal', position: 'MID', overall: 74, starting: true },
      { name: 'Lawrence Shankland', position: 'FWD', overall: 84, starting: true },
      { name: 'Elton Kabangu', position: 'FWD', overall: 73, starting: true },
      { name: 'Alexander Schwolow', position: 'GK', overall: 70, starting: false },
      { name: 'Jordi Altena', position: 'DEF', overall: 69, starting: false },
      { name: 'Oisin McEntee', position: 'DEF', overall: 68, starting: false },
      { name: 'Cameron Devlin', position: 'MID', overall: 71, starting: false },
      { name: 'Calem Nieuwenhof', position: 'MID', overall: 68, starting: false },
      { name: 'Pierre Landry Kabore', position: 'FWD', overall: 72, starting: false },
      { name: 'Sabah Kerjota', position: 'FWD', overall: 68, starting: false },
    ],
  },
  {
    id: 'lm2-pool-aek',
    club: 'AEK Ateny',
    players: [
      { name: 'Alexandros Paschalakis', position: 'GK', overall: 80, starting: true },
      { name: 'Antonis Siopis', position: 'DEF', overall: 78, starting: true },
      { name: 'Mile Svilar II', position: 'DEF', overall: 75, starting: true },
      { name: 'Dimitris Giannoulis', position: 'DEF', overall: 78, starting: true },
      { name: 'Ehsan Hajsafi', position: 'DEF', overall: 73, starting: true },
      { name: 'Orbelin Pineda', position: 'MID', overall: 84, starting: true },
      { name: 'Ezequiel Ponce', position: 'MID', overall: 77, starting: true },
      { name: 'Sergio Araujo', position: 'MID', overall: 78, starting: true },
      { name: 'Rafa Silva', position: 'MID', overall: 89, starting: true },
      { name: 'Jesus Rodriguez II', position: 'FWD', overall: 76, starting: true },
      { name: 'Levi Garcia', position: 'FWD', overall: 74, starting: true },
      { name: 'Konstantinos Tzimas', position: 'GK', overall: 65, starting: false },
      { name: 'Zinho Gano', position: 'DEF', overall: 68, starting: false },
      { name: 'Rekik Achraf', position: 'DEF', overall: 67, starting: false },
      { name: 'Ivan Sanchez', position: 'MID', overall: 70, starting: false },
      { name: 'Pantelis Chatzidiakos', position: 'MID', overall: 69, starting: false },
      { name: 'Fotis Ioannidis', position: 'FWD', overall: 76, starting: false },
      { name: 'Sotiris Alexandropoulos', position: 'FWD', overall: 72, starting: false },
    ],
  },
  {
    id: 'lm2-pool-omonia',
    club: 'Omonia Nikozja',
    players: [
      { name: 'Fabiano Iong', position: 'GK', overall: 73, starting: true },
      { name: 'Nuno Rocha', position: 'DEF', overall: 71, starting: true },
      { name: 'Kostas Laifis', position: 'DEF', overall: 75, starting: true },
      { name: 'Marios Antoniades', position: 'DEF', overall: 72, starting: true },
      { name: 'Eloi Amagat', position: 'DEF', overall: 70, starting: true },
      { name: 'Andronikos Kakoullis', position: 'MID', overall: 70, starting: true },
      { name: 'Cillian Sheridan', position: 'MID', overall: 68, starting: true },
      { name: 'Souza', position: 'MID', overall: 73, starting: true },
      { name: 'Cedric Gogoua', position: 'MID', overall: 69, starting: true },
      { name: 'Willy Semedo', position: 'FWD', overall: 75, starting: true },
      { name: 'Nuno Da Costa', position: 'FWD', overall: 72, starting: true },
      { name: 'Milan Borjan', position: 'GK', overall: 66, starting: false },
      { name: 'Zurab Ochigava', position: 'DEF', overall: 63, starting: false },
      { name: 'Ederson Fofonka', position: 'DEF', overall: 62, starting: false },
      { name: 'Rick Rocha', position: 'MID', overall: 64, starting: false },
      { name: 'Georgios Efrem', position: 'MID', overall: 66, starting: false },
      { name: 'Giannis Kargas', position: 'FWD', overall: 66, starting: false },
      { name: 'Dailon Livramento', position: 'FWD', overall: 63, starting: false },
    ],
  },
  {
    id: 'lm2-pool-lask',
    club: 'LASK Linz',
    players: [
      { name: 'Tobias Lawal', position: 'GK', overall: 75, starting: true },
      { name: 'Andres Andrade', position: 'DEF', overall: 72, starting: true },
      { name: 'Robert Zulj', position: 'DEF', overall: 76, starting: true },
      { name: 'Sascha Horvath', position: 'DEF', overall: 71, starting: true },
      { name: 'Florian Flecker', position: 'DEF', overall: 73, starting: true },
      { name: 'Konstantin Kerschbaumer', position: 'MID', overall: 75, starting: true },
      { name: 'Bernhard Zimmermann', position: 'MID', overall: 70, starting: true },
      { name: 'Marin Ljubicic', position: 'MID', overall: 73, starting: true },
      { name: 'Moses Usor', position: 'MID', overall: 72, starting: true },
      { name: 'Sasa Kalajdzic', position: 'FWD', overall: 84, starting: true },
      { name: 'George Bello', position: 'FWD', overall: 69, starting: true },
      { name: 'Kai Sondergaard', position: 'GK', overall: 63, starting: false },
      { name: 'Lukas Grgic', position: 'DEF', overall: 65, starting: false },
      { name: 'Filip Stojkovic', position: 'DEF', overall: 66, starting: false },
      { name: 'Thomas Goiginger', position: 'MID', overall: 68, starting: false },
      { name: 'Christoph Lang', position: 'MID', overall: 67, starting: false },
      { name: 'Nikolas Kuehn', position: 'FWD', overall: 70, starting: false },
      { name: 'Ismael Gharbi II', position: 'FWD', overall: 64, starting: false },
    ],
  },
);
