// ============================================================
// SEZON 2015/16 — 16 klubów
// Część bazy TEAMS_DATA — każdy sezon w osobnym pliku.
// ============================================================

window.TEAMS_DATA = window.TEAMS_DATA || [];
window.TEAMS_DATA.push(
{
    club: "Legia Warszawa",
    season: "2015/16",
    "coaches": [{ "name": "Henning Berg" }, { "name": "Stanislav Cherchesov" }],
    players: [
      { name: "Malarz",        position: "GK",  overall: 78, apps: 19, goals: 0,  starting: true, "birthYear": 1980  },
      { name: "Kuciak",        position: "GK",  overall: 78, apps: 18, goals: 0,  starting: false, "birthYear": 1985 },

      { name: "Rzeźniczak",    position: "DEF", overall: 82, apps: 20, goals: 0,  starting: true, "birthYear": 1986  },
      { name: "Jodłowiec",     position: "DEF", overall: 88, apps: 27, goals: 4,  starting: true, "birthYear": 1985  },
      { name: "Lewczuk",       position: "DEF", overall: 78, apps: 29, goals: 1,  starting: true, "birthYear": 1985  },
      { name: "Guilherme",     position: "DEF", overall: 80, apps: 35, goals: 5,  starting: true, "birthYear": 1991  },
      { name: "Jędrzejczyk",   position: "DEF", overall: 85, apps: 16, goals: 1,  starting: false, "birthYear": 1987 },
      { name: "Hlousek",       position: "DEF", overall: 79, apps: 16, goals: 2,  starting: false, "birthYear": 1988 },
      { name: "Broź Ł.",       position: "DEF", overall: 77, apps: 20, goals: 0,  starting: false, "birthYear": 1985 },
      { name: "Brzyski",       position: "DEF", overall: 78, apps: 23, goals: 0,  starting: false, "birthYear": 1982 },
      { name: "Bereszyński",   position: "DEF", overall: 78, apps: 16, goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Makowski",      position: "DEF", overall: 62, apps: 7,  goals: 1,  starting: false, "birthYear": 1996 },

      { name: "Duda O.",       position: "MID", overall: 86, apps: 27, goals: 2,  starting: true, "birthYear": 1994  },
      { name: "Kucharczyk",    position: "MID", overall: 84, apps: 32, goals: 6,  starting: true, "birthYear": 1991  },
      { name: "Vranjes",       position: "MID", overall: 76, apps: 19, goals: 2,  starting: true, "birthYear": 1986  },
      { name: "Hamalainen",    position: "MID", overall: 78, apps: 11, goals: 3,  starting: true, "birthYear": 1986  },
      { name: "Furman",        position: "MID", overall: 72, apps: 14, goals: 2,  starting: false, "birthYear": 1992 },
      { name: "Borysiuk",      position: "MID", overall: 72, apps: 13, goals: 0,  starting: false, "birthYear": 1991 },
      { name: "Trickovski",    position: "MID", overall: 68, apps: 11, goals: 1,  starting: false, "birthYear": 1987 },
      { name: "Aleksandrov",   position: "MID", overall: 66, apps: 11, goals: 0,  starting: false, "birthYear": 1989 },
      { name: "Masłowski",     position: "MID", overall: 65, apps: 10, goals: 0,  starting: false, "birthYear": 1989 },
      { name: "Żyro",          position: "MID", overall: 68, apps: 5,  goals: 1,  starting: false, "birthYear": 1992 },

      { name: "Nikolić N.",    position: "FWD", overall: 97, apps: 37, goals: 28, starting: true, "birthYear": 1987  },
      { name: "Prijović",      position: "FWD", overall: 86, apps: 30, goals: 8,  starting: true, "birthYear": 1990  },
      { name: "Saganowski",    position: "FWD", overall: 70, apps: 7,  goals: 1,  starting: false, "birthYear": 1978 },
      { name: "Ryczkowski",    position: "FWD", overall: 62, apps: 1,  goals: 0,  starting: false, "birthYear": 1997 },
    ]
  },
{
    club: "Piast Gliwice",
    season: "2015/16",
    "coaches": [{ "name": "Radoslav Latal" }],
    players: [
      { name: "Szmatuła",      position: "GK",  overall: 82, apps: 37, goals: 0,  starting: true, "birthYear": 1981  },

      { name: "Korun",         position: "DEF", overall: 80, apps: 34, goals: 2,  starting: true, "birthYear": 1987  },
      { name: "Hebert",        position: "DEF", overall: 79, apps: 35, goals: 1,  starting: true, "birthYear": 1991  },
      { name: "Mraz",          position: "DEF", overall: 78, apps: 34, goals: 3,  starting: true, "birthYear": 1987  },
      { name: "Osyra",         position: "DEF", overall: 68, apps: 21, goals: 3,  starting: true, "birthYear": 1993  },
      { name: "Mokwa",         position: "DEF", overall: 65, apps: 20, goals: 1,  starting: false, "birthYear": 1993 },
      { name: "Moskwik",       position: "DEF", overall: 64, apps: 18, goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Ipsa",          position: "DEF", overall: 62, apps: 4,  goals: 0,  starting: false, "birthYear": 1986 },

      { name: "Vacek",         position: "MID", overall: 86, apps: 33, goals: 5,  starting: true, "birthYear": 1987  },
      { name: "Murawski R.",   position: "MID", overall: 80, apps: 35, goals: 1,  starting: true, "birthYear": 1994  },
      { name: "Zivec",         position: "MID", overall: 79, apps: 26, goals: 5,  starting: true, "birthYear": 1991  },
      { name: "Pietrowski",    position: "MID", overall: 70, apps: 34, goals: 0,  starting: true, "birthYear": 1988  },
      { name: "Badia",         position: "MID", overall: 79, apps: 30, goals: 2,  starting: false, "birthYear": 1989 },
      { name: "Szeliga B.",    position: "MID", overall: 68, apps: 25, goals: 3,  starting: false, "birthYear": 1993 },
      { name: "Bukata",        position: "MID", overall: 65, apps: 14, goals: 0,  starting: false, "birthYear": 1993 },
      { name: "Jankowski M.",  position: "MID", overall: 66, apps: 6,  goals: 2,  starting: false, "birthYear": 1990 },
      { name: "Karasauks",     position: "MID", overall: 61, apps: 2,  goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Sapała",        position: "MID", overall: 62, apps: 2,  goals: 1,  starting: false, "birthYear": 1995 },

      { name: "Nespor",        position: "FWD", overall: 82, apps: 33, goals: 11, starting: true, "birthYear": 1990  },
      { name: "Barisić",       position: "FWD", overall: 79, apps: 34, goals: 11, starting: true, "birthYear": 1986  },
      { name: "Angielski",     position: "FWD", overall: 63, apps: 4,  goals: 0,  starting: false, "birthYear": 1996 },
      { name: "Musiolik",      position: "FWD", overall: 62, apps: 5,  goals: 0,  starting: false, "birthYear": 1996 },
    ]
  },
{
    club: "Zagłębie Lubin",
    season: "2015/16",
    "coaches": [{ "name": "Piotr Stokowiec" }],
    players: [
      { name: "Polacek",       position: "GK",  overall: 70, apps: 23, goals: 0,  starting: true, "birthYear": 1990  },
      { name: "Forenc",        position: "GK",  overall: 65, apps: 15, goals: 0,  starting: false, "birthYear": 1992 },

      { name: "Todorovski",    position: "DEF", overall: 76, apps: 33, goals: 0,  starting: true, "birthYear": 1984  },
      { name: "Guldan",        position: "DEF", overall: 80, apps: 32, goals: 0,  starting: true, "birthYear": 1983  },
      { name: "Tosik",         position: "DEF", overall: 76, apps: 24, goals: 3,  starting: true, "birthYear": 1987  },
      { name: "Cotra",         position: "DEF", overall: 70, apps: 32, goals: 1,  starting: true, "birthYear": 1984  },
      { name: "Dąbrowski M.",  position: "DEF", overall: 68, apps: 30, goals: 3,  starting: false, "birthYear": 1987 },
      { name: "Jach",          position: "DEF", overall: 66, apps: 13, goals: 2,  starting: false, "birthYear": 1994 },
      { name: "Zbozień",       position: "DEF", overall: 65, apps: 15, goals: 1,  starting: false, "birthYear": 1989 },

      { name: "Janoszka",      position: "MID", overall: 78, apps: 36, goals: 7,  starting: true, "birthYear": 1987  },
      { name: "Kubicki J.",    position: "MID", overall: 72, apps: 28, goals: 4,  starting: true, "birthYear": 1995  },
      { name: "Rakowski",      position: "MID", overall: 70, apps: 27, goals: 2,  starting: true, "birthYear": 1990  },
      { name: "Piątek Ł.",     position: "MID", overall: 70, apps: 25, goals: 4,  starting: true, "birthYear": 1985  },
      { name: "Janus",         position: "MID", overall: 68, apps: 30, goals: 3,  starting: false, "birthYear": 1986 },
      { name: "Starzyński",    position: "MID", overall: 70, apps: 16, goals: 3,  starting: false, "birthYear": 1991 },
      { name: "Jagiełło F.",   position: "MID", overall: 66, apps: 4,  goals: 1,  starting: false, "birthYear": 1997 },
      { name: "Bonecki",       position: "MID", overall: 62, apps: 2,  goals: 0,  starting: false, "birthYear": 1995 },
      { name: "Żyra",          position: "MID", overall: 62, apps: 4,  goals: 0,  starting: false, "birthYear": 1998 },

      { name: "Papadopulos",   position: "FWD", overall: 75, apps: 35, goals: 8,  starting: true, "birthYear": 1985  },
      { name: "Piątek K.",     position: "FWD", overall: 76, apps: 33, goals: 6,  starting: true, "birthYear": 1995  },
      { name: "Woźniak A.",    position: "FWD", overall: 70, apps: 30, goals: 5,  starting: false, "birthYear": 1990 },
      { name: "Sobków",        position: "FWD", overall: 63, apps: 9,  goals: 1,  starting: false, "birthYear": 1997 },
    ]
  },
{
    club: "Cracovia Kraków",
    season: "2015/16",
    "coaches": [{ "name": "Jacek Zieliński" }],
    players: [
      { name: "Sandomierski",  position: "GK",  overall: 79, apps: 28, goals: 0,  starting: true, "birthYear": 1989  },
      { name: "Pilarz",        position: "GK",  overall: 68, apps: 9,  goals: 0,  starting: false, "birthYear": 1980 },

      { name: "Wołąkiewicz",   position: "DEF", overall: 78, apps: 29, goals: 0,  starting: true, "birthYear": 1985  },
      { name: "Polczak",       position: "DEF", overall: 80, apps: 31, goals: 1,  starting: true, "birthYear": 1986  },
      { name: "Wójcicki",      position: "DEF", overall: 72, apps: 30, goals: 1,  starting: true, "birthYear": 1988  },
      { name: "Deleu",         position: "DEF", overall: 77, apps: 29, goals: 1,  starting: true, "birthYear": 1984  },
      { name: "Jaroszyński",   position: "DEF", overall: 78, apps: 22, goals: 1,  starting: false, "birthYear": 1994 },
      { name: "Sretenović",    position: "DEF", overall: 66, apps: 14, goals: 0,  starting: false, "birthYear": 1985 },
      { name: "Bejan",         position: "DEF", overall: 65, apps: 11, goals: 0,  starting: false, "birthYear": 1991 },
      { name: "Rymaniak",      position: "DEF", overall: 65, apps: 11, goals: 0,  starting: false, "birthYear": 1989 },

      { name: "Cetnarski",     position: "MID", overall: 86, apps: 36, goals: 13, starting: true, "birthYear": 1988  },
      { name: "Budziński",     position: "MID", overall: 80, apps: 34, goals: 4,  starting: true, "birthYear": 1990  },
      { name: "Kapustka",      position: "MID", overall: 82, apps: 33, goals: 4,  starting: true, "birthYear": 1996  },
      { name: "Dąbrowski D.",  position: "MID", overall: 79, apps: 25, goals: 1,  starting: true, "birthYear": 1992  },
      { name: "Covilo",        position: "MID", overall: 82, apps: 29, goals: 4,  starting: false, "birthYear": 1986 },
      { name: "Dialiba",       position: "MID", overall: 76, apps: 17, goals: 2,  starting: false, "birthYear": 1988 },
      { name: "Karachanakov",  position: "MID", overall: 64, apps: 5,  goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Zejdler",       position: "MID", overall: 63, apps: 13, goals: 0,  starting: false, "birthYear": 1992 },

      { name: "Rakels",        position: "FWD", overall: 80, apps: 20, goals: 15, starting: true, "birthYear": 1992  },
      { name: "Jendrisek",     position: "FWD", overall: 79, apps: 35, goals: 13, starting: true, "birthYear": 1986  },
      { name: "Vestenicky",    position: "FWD", overall: 66, apps: 13, goals: 1,  starting: false, "birthYear": 1996 },
      { name: "Wdowiak",       position: "FWD", overall: 65, apps: 16, goals: 1,  starting: false, "birthYear": 1996 },
      { name: "Zjawiński",     position: "FWD", overall: 65, apps: 23, goals: 2,  starting: false, "birthYear": 1986 },
      { name: "Szewczyk K.",   position: "FWD", overall: 61, apps: 3,  goals: 0,  starting: false, "birthYear": 1996 },
    ]
  },
{
    club: "Lechia Gdańsk",
    season: "2015/16",
    "coaches": [{ "name": "Jerzy Brzęczek" }, { "name": "Thomas von Heesen" }, { "name": "Dawid Banaczek" }, { "name": "Piotr Nowak" }],
    players: [
      { name: "Marić V.",      position: "GK",  overall: 70, apps: 24, goals: 0,  starting: true, "birthYear": 1996  },
      { name: "Milinković-Savić",position:"GK", overall: 68, apps: 11, goals: 0,  starting: false, "birthYear": 1997 },
      { name: "Budziłek",      position: "GK",  overall: 63, apps: 2,  goals: 0,  starting: false, "birthYear": 1991 },

      { name: "Janicki",       position: "DEF", overall: 83, apps: 35, goals: 2,  starting: true, "birthYear": 1992  },
      { name: "Wawrzyniak",    position: "DEF", overall: 76, apps: 32, goals: 0,  starting: true, "birthYear": 1983  },
      { name: "Wojtkowiak",    position: "DEF", overall: 72, apps: 28, goals: 2,  starting: true, "birthYear": 1984  },
      { name: "Maloca",        position: "DEF", overall: 70, apps: 28, goals: 2,  starting: true, "birthYear": 1989  },
      { name: "Stolarski",     position: "DEF", overall: 68, apps: 21, goals: 1,  starting: false, "birthYear": 1996 },
      { name: "Gerson",        position: "DEF", overall: 66, apps: 15, goals: 1,  starting: false, "birthYear": 1992 },
      { name: "Marković N.",   position: "DEF", overall: 64, apps: 5,  goals: 0,  starting: false, "birthYear": 1987 },

      { name: "Peszko",        position: "MID", overall: 79, apps: 27, goals: 2,  starting: true, "birthYear": 1985  },
      { name: "Krasić",        position: "MID", overall: 81, apps: 23, goals: 4,  starting: true, "birthYear": 1984  },
      { name: "Mila S.",       position: "MID", overall: 74, apps: 29, goals: 2,  starting: true, "birthYear": 1982  },
      { name: "Borysiuk",      position: "MID", overall: 72, apps: 20, goals: 2,  starting: true, "birthYear": 1991  },
      { name: "Kovacević",     position: "MID", overall: 70, apps: 25, goals: 2,  starting: false, "birthYear": 1992 },
      { name: "Makuszewski",   position: "MID", overall: 70, apps: 20, goals: 3,  starting: false, "birthYear": 1989 },
      { name: "Haraslin",      position: "MID", overall: 68, apps: 20, goals: 3,  starting: false, "birthYear": 1996 },
      { name: "Łukasik",       position: "MID", overall: 68, apps: 20, goals: 1,  starting: false, "birthYear": 1991 },
      { name: "Chrapek",       position: "MID", overall: 66, apps: 14, goals: 1,  starting: false, "birthYear": 1992 },
      { name: "Mak M.",        position: "MID", overall: 68, apps: 23, goals: 6,  starting: false, "birthYear": 1991 },

      { name: "Kuświk",        position: "FWD", overall: 79, apps: 33, goals: 11, starting: true, "birthYear": 1987  },
      { name: "Flavio Paixao", position: "FWD", overall: 78, apps: 16, goals: 6,  starting: true, "birthYear": 1984  },
      { name: "Buksa",         position: "FWD", overall: 64, apps: 8,  goals: 1,  starting: false, "birthYear": 1996 },
      { name: "Marco Paixao",  position: "FWD", overall: 66, apps: 3,  goals: 0,  starting: false, "birthYear": 1984 },
    ]
  },
{
    club: "Pogoń Szczecin",
    season: "2015/16",
    "coaches": [{ "name": "Czesław Michniewicz" }],
    players: [
      { name: "Słowik",        position: "GK",  overall: 72, apps: 17, goals: 0,  starting: true, "birthYear": 1991  },
      { name: "Kudła",         position: "GK",  overall: 66, apps: 21, goals: 0,  starting: false, "birthYear": 1992 },

      { name: "Fojut",         position: "DEF", overall: 78, apps: 30, goals: 2,  starting: true, "birthYear": 1987  },
      { name: "Czerwiński",    position: "DEF", overall: 74, apps: 33, goals: 1,  starting: true, "birthYear": 1991  },
      { name: "Matras",        position: "DEF", overall: 74, apps: 35, goals: 2,  starting: true, "birthYear": 1991  },
      { name: "Lewandowski M.",position: "DEF", overall: 70, apps: 30, goals: 2,  starting: true, "birthYear": 1993  },
      { name: "Rudol",         position: "DEF", overall: 68, apps: 22, goals: 0,  starting: false, "birthYear": 1995 },
      { name: "Ricardo Nunes", position: "DEF", overall: 66, apps: 22, goals: 1,  starting: false, "birthYear": 1986 },
      { name: "Murawski S.",   position: "DEF", overall: 62, apps: 4,  goals: 1,  starting: false, "birthYear": 1994 },

      { name: "Murawski R.",   position: "MID", overall: 84, apps: 36, goals: 7,  starting: true, "birthYear": 1981  },
      { name: "Frączczak",     position: "MID", overall: 79, apps: 35, goals: 6,  starting: true, "birthYear": 1987  },
      { name: "Akahoshi",      position: "MID", overall: 72, apps: 32, goals: 5,  starting: true, "birthYear": 1986  },
      { name: "Przybecki",     position: "MID", overall: 68, apps: 30, goals: 1,  starting: true, "birthYear": 1991  },
      { name: "Gyurcsó",       position: "MID", overall: 68, apps: 14, goals: 2,  starting: false, "birthYear": 1991 },
      { name: "Danielak",      position: "MID", overall: 65, apps: 11, goals: 1,  starting: false, "birthYear": 1991 },
      { name: "Murayama",      position: "MID", overall: 66, apps: 13, goals: 3,  starting: false, "birthYear": 1989 },
      { name: "Kort D.",       position: "MID", overall: 65, apps: 10, goals: 2,  starting: false, "birthYear": 1995 },
      { name: "Walski",        position: "MID", overall: 62, apps: 7,  goals: 0,  starting: false, "birthYear": 1997 },
      { name: "Piotrowski J.", position: "MID", overall: 64, apps: 4,  goals: 0,  starting: false, "birthYear": 1997 },

      { name: "Zwoliński",     position: "FWD", overall: 74, apps: 30, goals: 8,  starting: true, "birthYear": 1993  },
      { name: "Dvalishvili",   position: "FWD", overall: 72, apps: 28, goals: 3,  starting: true, "birthYear": 1986  },
      { name: "Listkowski",    position: "FWD", overall: 64, apps: 24, goals: 0,  starting: false, "birthYear": 1998 },
      { name: "Okuszko",       position: "FWD", overall: 60, apps: 1,  goals: 0,  starting: false, "birthYear": 1995 },
    ]
  },
{
    club: "Lech Poznań",
    season: "2015/16",
    "coaches": [{ "name": "Maciej Skorża" }, { "name": "Jan Urban" }],
    players: [
      { name: "Burić",         position: "GK",  overall: 76, apps: 35, goals: 0,  starting: true, "birthYear": 1987  },
      { name: "Kotorowski",    position: "GK",  overall: 67, apps: 1,  goals: 0,  starting: false, "birthYear": 1976 },

      { name: "Kamiński M.",   position: "DEF", overall: 82, apps: 35, goals: 1,  starting: true, "birthYear": 1992  },
      { name: "Kadar",         position: "DEF", overall: 76, apps: 29, goals: 0,  starting: true, "birthYear": 1990  },
      { name: "Arajuuri",      position: "DEF", overall: 74, apps: 28, goals: 0,  starting: true, "birthYear": 1988  },
      { name: "Kędziora T.",   position: "DEF", overall: 74, apps: 24, goals: 0,  starting: true, "birthYear": 1994  },
      { name: "Ceesay",        position: "DEF", overall: 68, apps: 18, goals: 0,  starting: false, "birthYear": 1987 },
      { name: "Douglas",       position: "DEF", overall: 70, apps: 13, goals: 0,  starting: false, "birthYear": 1989 },
      { name: "Gumny",         position: "DEF", overall: 64, apps: 4,  goals: 1,  starting: false, "birthYear": 1998 },

      { name: "Trałka",        position: "MID", overall: 82, apps: 30, goals: 1,  starting: true, "birthYear": 1984  },
      { name: "Jevtić",        position: "MID", overall: 80, apps: 26, goals: 4,  starting: true, "birthYear": 1993  },
      { name: "Gajos",         position: "MID", overall: 76, apps: 28, goals: 6,  starting: true, "birthYear": 1991  },
      { name: "Linetty",       position: "MID", overall: 76, apps: 28, goals: 3,  starting: true, "birthYear": 1995  },
      { name: "Hamalainen",    position: "MID", overall: 82, apps: 15, goals: 8,  starting: false, "birthYear": 1986 },
      { name: "Pawłowski",     position: "MID", overall: 74, apps: 31, goals: 6,  starting: false, "birthYear": 1986 },
      { name: "Lovrencsics",   position: "MID", overall: 70, apps: 23, goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Tetteh",        position: "MID", overall: 68, apps: 28, goals: 0,  starting: false, "birthYear": 1990 },
      { name: "Kownacki",      position: "MID", overall: 70, apps: 24, goals: 6,  starting: false, "birthYear": 1997 },
      { name: "Dudka",         position: "MID", overall: 70, apps: 9,  goals: 0,  starting: false, "birthYear": 1983 },

      { name: "Robak",         position: "FWD", overall: 74, apps: 8,  goals: 2,  starting: true, "birthYear": 1982  },
      { name: "Formella",      position: "FWD", overall: 68, apps: 19, goals: 1,  starting: true, "birthYear": 1995  },
      { name: "Bille Nielsen", position: "FWD", overall: 68, apps: 10, goals: 3,  starting: false, "birthYear": 1988 },
      { name: "Jóźwiak",       position: "FWD", overall: 67, apps: 10, goals: 1,  starting: false, "birthYear": 1998 },
      { name: "Thomalla",      position: "FWD", overall: 64, apps: 13, goals: 0,  starting: false, "birthYear": 1992 },
    ]
  },
{
    club: "Ruch Chorzów",
    season: "2015/16",
    "coaches": [{ "name": "Waldemar Fornalik" }],
    players: [
      { name: "Putnocky",      position: "GK",  overall: 80, apps: 34, goals: 0,  starting: true, "birthYear": 1984  },
      { name: "Skaba",         position: "GK",  overall: 63, apps: 4,  goals: 0,  starting: false, "birthYear": 1984 },

      { name: "Grodzicki",     position: "DEF", overall: 76, apps: 33, goals: 0,  starting: true, "birthYear": 1983  },
      { name: "Konczkowski",   position: "DEF", overall: 72, apps: 35, goals: 0,  starting: true, "birthYear": 1993  },
      { name: "Koj",           position: "DEF", overall: 70, apps: 26, goals: 4,  starting: true, "birthYear": 1993  },
      { name: "Oleksy",        position: "DEF", overall: 68, apps: 22, goals: 2,  starting: true, "birthYear": 1991  },
      { name: "Szyndrowski",   position: "DEF", overall: 65, apps: 15, goals: 0,  starting: false, "birthYear": 1980 },
      { name: "Cichocki",      position: "DEF", overall: 64, apps: 20, goals: 0,  starting: false, "birthYear": 1992 },

      { name: "Surma",         position: "MID", overall: 76, apps: 37, goals: 1,  starting: true, "birthYear": 1977  },
      { name: "Starzyński",    position: "MID", overall: 76, apps: 36, goals: 0,  starting: true, "birthYear": 1993  },
      { name: "Zieńczuk",      position: "MID", overall: 74, apps: 32, goals: 2,  starting: true, "birthYear": 1978  },
      { name: "Lipski",        position: "MID", overall: 72, apps: 36, goals: 4,  starting: true, "birthYear": 1994  },
      { name: "Mazek",         position: "MID", overall: 66, apps: 28, goals: 3,  starting: false, "birthYear": 1994 },
      { name: "Podgórski",     position: "MID", overall: 68, apps: 26, goals: 1,  starting: false, "birthYear": 1985 },
      { name: "Iwański",       position: "MID", overall: 70, apps: 25, goals: 1,  starting: false, "birthYear": 1981 },
      { name: "Hanzel",        position: "MID", overall: 65, apps: 16, goals: 0,  starting: false, "birthYear": 1986 },
      { name: "Moneta",        position: "MID", overall: 63, apps: 13, goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Gigolaev",      position: "MID", overall: 66, apps: 9,  goals: 1,  starting: false, "birthYear": 1990 },
      { name: "Bargiel",       position: "MID", overall: 61, apps: 4,  goals: 0,  starting: false, "birthYear": 2000 },

      { name: "Stępiński M.",  position: "FWD", overall: 84, apps: 34, goals: 15, starting: true, "birthYear": 1995  },
      { name: "Efir",          position: "FWD", overall: 68, apps: 24, goals: 1,  starting: true, "birthYear": 1992  },
      { name: "Visnakovs E.",  position: "FWD", overall: 70, apps: 6,  goals: 3,  starting: false, "birthYear": 1990 },
      { name: "Siedlik",       position: "FWD", overall: 61, apps: 2,  goals: 0,  starting: false, "birthYear": 1997 },
    ]
  },
{
    club: "Wisła Kraków",
    season: "2015/16",
    "coaches": [{ "name": "Kazimierz Moskal" }, { "name": "Marcin Broniszewski" }, { "name": "Tadeusz Pawłowski" }, { "name": "Marcin Broniszewski" }, { "name": "Dariusz Wdowczyk" }],
    players: [
      { name: "Cierzniak",     position: "GK",  overall: 72, apps: 21, goals: 0,  starting: true, "birthYear": 1983  },
      { name: "Miśkiewicz",    position: "GK",  overall: 68, apps: 16, goals: 0,  starting: false, "birthYear": 1989 },

      { name: "Głowacki",      position: "DEF", overall: 78, apps: 32, goals: 1,  starting: true, "birthYear": 1979  },
      { name: "Guzmics",       position: "DEF", overall: 76, apps: 33, goals: 0,  starting: true, "birthYear": 1987  },
      { name: "Sadlok",        position: "DEF", overall: 77, apps: 27, goals: 1,  starting: true, "birthYear": 1989  },
      { name: "Jović B.",      position: "DEF", overall: 70, apps: 32, goals: 1,  starting: true, "birthYear": 1991  },
      { name: "Burliga",       position: "DEF", overall: 70, apps: 20, goals: 1,  starting: false, "birthYear": 1988 },
      { name: "Bartosz J.",    position: "DEF", overall: 63, apps: 6,  goals: 2,  starting: false, "birthYear": 1996 },
      { name: "Pietrzak R.",   position: "DEF", overall: 63, apps: 6,  goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Kujawa",        position: "DEF", overall: 61, apps: 2,  goals: 0,  starting: false, "birthYear": 1996 },

      { name: "Guerrier",      position: "MID", overall: 80, apps: 22, goals: 7,  starting: true, "birthYear": 1989  },
      { name: "Mączyński",     position: "MID", overall: 78, apps: 24, goals: 2,  starting: true, "birthYear": 1987  },
      { name: "Boguski",       position: "MID", overall: 84, apps: 36, goals: 9,  starting: true, "birthYear": 1984  },
      { name: "Popović D.",    position: "MID", overall: 72, apps: 30, goals: 4,  starting: true, "birthYear": 1989  },
      { name: "Cywka",         position: "MID", overall: 72, apps: 27, goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Wolski R.",     position: "MID", overall: 81, apps: 14, goals: 4,  starting: false, "birthYear": 1992 },
      { name: "Uryga",         position: "MID", overall: 66, apps: 24, goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Jankowski M.",  position: "MID", overall: 74, apps: 19, goals: 4,  starting: false, "birthYear": 1990 },
      { name: "Małecki",       position: "MID", overall: 66, apps: 14, goals: 2,  starting: false, "birthYear": 1988 },
      { name: "Crivellaro",    position: "MID", overall: 68, apps: 20, goals: 3,  starting: false, "birthYear": 1989 },

      { name: "Paweł Brożek",  position: "FWD", overall: 85, apps: 29, goals: 14, starting: true, "birthYear": 1983  },
      { name: "Ondrasek",      position: "FWD", overall: 76, apps: 16, goals: 6,  starting: true, "birthYear": 1988  },
      { name: "Drzazga",       position: "FWD", overall: 63, apps: 7,  goals: 0,  starting: false, "birthYear": 1995 },
    ]
  },
{
    club: "Śląsk Wrocław",
    season: "2015/16",
    "coaches": [{ "name": "Tadeusz Pawłowski" }, { "name": "Grzegorz Kowalski" }, { "name": "Romuald Szukiełowicz" }, { "name": "Mariusz Rumak" }],
    players: [
      { name: "Pawełek",       position: "GK",  overall: 72, apps: 24, goals: 0,  starting: true, "birthYear": 1981  },
      { name: "Wrąbel",        position: "GK",  overall: 64, apps: 4,  goals: 0,  starting: false, "birthYear": 1996 },
      { name: "Abramowicz",    position: "GK",  overall: 63, apps: 10, goals: 0,  starting: false, "birthYear": 1992 },

      { name: "Celeban",       position: "DEF", overall: 80, apps: 36, goals: 2,  starting: true, "birthYear": 1985  },
      { name: "Kokoszka",      position: "DEF", overall: 76, apps: 27, goals: 0,  starting: true, "birthYear": 1986  },
      { name: "Pawelec",       position: "DEF", overall: 72, apps: 27, goals: 0,  starting: true, "birthYear": 1986  },
      { name: "Zieliński P.",  position: "DEF", overall: 70, apps: 26, goals: 0,  starting: true, "birthYear": 1990  },
      { name: "Dudu Paraiba",  position: "DEF", overall: 73, apps: 24, goals: 1,  starting: false, "birthYear": 1985 },
      { name: "Dvali",         position: "DEF", overall: 66, apps: 15, goals: 1,  starting: false, "birthYear": 1995 },
      { name: "Ostrowski",     position: "DEF", overall: 66, apps: 19, goals: 2,  starting: false, "birthYear": 1982 },
      { name: "Dankowski",     position: "DEF", overall: 62, apps: 21, goals: 0,  starting: false, "birthYear": 1996 },

      { name: "Hołota",        position: "MID", overall: 76, apps: 35, goals: 4,  starting: true, "birthYear": 1991  },
      { name: "Morioka",       position: "MID", overall: 76, apps: 15, goals: 7,  starting: true, "birthYear": 1991  },
      { name: "Hateley",       position: "MID", overall: 72, apps: 29, goals: 1,  starting: true, "birthYear": 1989  },
      { name: "Gecov",         position: "MID", overall: 70, apps: 23, goals: 0,  starting: true, "birthYear": 1988  },
      { name: "Pich",          position: "MID", overall: 72, apps: 23, goals: 3,  starting: false, "birthYear": 1988 },
      { name: "Kiełb",         position: "MID", overall: 70, apps: 25, goals: 2,  starting: false, "birthYear": 1988 },
      { name: "Grajciar",      position: "MID", overall: 66, apps: 28, goals: 2,  starting: false, "birthYear": 1983 },
      { name: "Gosztonyi",     position: "MID", overall: 64, apps: 7,  goals: 2,  starting: false, "birthYear": 1990 },
      { name: "Bartkowiak",    position: "MID", overall: 62, apps: 10, goals: 1,  starting: false, "birthYear": 1997 },

      { name: "Flavio Paixao", position: "FWD", overall: 76, apps: 21, goals: 5,  starting: true, "birthYear": 1984  },
      { name: "Biliński",      position: "FWD", overall: 72, apps: 31, goals: 5,  starting: true, "birthYear": 1988  },
      { name: "Mervo",         position: "FWD", overall: 68, apps: 10, goals: 4,  starting: false, "birthYear": 1995 },
      { name: "Angielski",     position: "FWD", overall: 65, apps: 8,  goals: 0,  starting: false, "birthYear": 1981 },
    ]
  },
{
    club: "Jagiellonia Białystok",
    season: "2015/16",
    "coaches": [{ "name": "Michał Probierz" }],
    players: [
      { name: "Drągowski",     position: "GK",  overall: 86, apps: 34, goals: 0,  starting: true, "birthYear": 1997  },
      { name: "Baran K.",      position: "GK",  overall: 64, apps: 3,  goals: 0,  starting: false, "birthYear": 1990 },

      { name: "Tomasik",       position: "DEF", overall: 74, apps: 29, goals: 3,  starting: true, "birthYear": 1987  },
      { name: "Tarasovs",      position: "DEF", overall: 72, apps: 26, goals: 2,  starting: true, "birthYear": 1988  },
      { name: "Romanchuk",     position: "DEF", overall: 80, apps: 33, goals: 3,  starting: true, "birthYear": 1991  },
      { name: "Burliga",       position: "DEF", overall: 68, apps: 13, goals: 0,  starting: true, "birthYear": 1988  },
      { name: "Madera",        position: "DEF", overall: 72, apps: 23, goals: 1,  starting: false, "birthYear": 1985 },
      { name: "Guti",          position: "DEF", overall: 65, apps: 12, goals: 0,  starting: false, "birthYear": 1991 },
      { name: "Wasiluk",       position: "DEF", overall: 65, apps: 10, goals: 0,  starting: false, "birthYear": 1987 },
      { name: "Straus",        position: "DEF", overall: 63, apps: 8,  goals: 0,  starting: false, "birthYear": 1994 },

      { name: "Vassiljev",     position: "MID", overall: 86, apps: 35, goals: 7,  starting: true, "birthYear": 1984  },
      { name: "Grzyb R.",      position: "MID", overall: 77, apps: 33, goals: 1,  starting: true, "birthYear": 1983  },
      { name: "Góralski",      position: "MID", overall: 80, apps: 28, goals: 0,  starting: true, "birthYear": 1992  },
      { name: "Frankowski P.", position: "MID", overall: 79, apps: 31, goals: 6,  starting: true, "birthYear": 1995  },
      { name: "Grzelczak",     position: "MID", overall: 76, apps: 31, goals: 6,  starting: false, "birthYear": 1988 },
      { name: "Mackiewicz",    position: "MID", overall: 66, apps: 25, goals: 1,  starting: false, "birthYear": 1992 },
      { name: "Mystkowski",    position: "MID", overall: 65, apps: 15, goals: 1,  starting: false, "birthYear": 1998 },
      { name: "Szymonowicz",   position: "MID", overall: 64, apps: 8,  goals: 1,  starting: false, "birthYear": 1995 },
      { name: "Alvarinho",     position: "MID", overall: 65, apps: 10, goals: 0,  starting: false, "birthYear": 1990 },

      { name: "Świderski",     position: "FWD", overall: 76, apps: 31, goals: 4,  starting: true, "birthYear": 1997  },
      { name: "Chernykh",      position: "FWD", overall: 72, apps: 27, goals: 3,  starting: true, "birthYear": 1991  },
      { name: "Sekulski",      position: "FWD", overall: 65, apps: 9,  goals: 1,  starting: false, "birthYear": 1990 },
      { name: "Gajos",         position: "FWD", overall: 70, apps: 6,  goals: 4,  starting: false, "birthYear": 1991 },
      { name: "Giełażyn",      position: "FWD", overall: 61, apps: 2,  goals: 0,  starting: false, "birthYear": 1994 },
    ]
  },
{
    club: "Korona Kielce",
    season: "2015/16",
    "coaches": [{ "name": "Marcin Brosz" }],
    players: [
      { name: "Trela",         position: "GK",  overall: 68, apps: 19, goals: 0,  starting: true, "birthYear": 1989  },
      { name: "Małkowski Z.",  position: "GK",  overall: 67, apps: 19, goals: 0,  starting: false, "birthYear": 1978 },

      { name: "Sylwestrzak",   position: "DEF", overall: 74, apps: 34, goals: 3,  starting: true, "birthYear": 1988  },
      { name: "Gabovs",        position: "DEF", overall: 70, apps: 33, goals: 0,  starting: true, "birthYear": 1987  },
      { name: "Dejmek",        position: "DEF", overall: 70, apps: 34, goals: 0,  starting: true, "birthYear": 1988  },
      { name: "Grzelak",       position: "DEF", overall: 68, apps: 25, goals: 0,  starting: true, "birthYear": 1988  },
      { name: "Diaw",          position: "DEF", overall: 55, apps: 12, goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Rymaniak",      position: "DEF", overall: 65, apps: 12, goals: 0,  starting: false, "birthYear": 1989 },
      { name: "Dejmek R.",     position: "DEF", overall: 64, apps: 34, goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Verkhovtsov",   position: "DEF", overall: 63, apps: 6,  goals: 1,  starting: false, "birthYear": 1986 },

      { name: "Jovanović",     position: "MID", overall: 76, apps: 36, goals: 1,  starting: true, "birthYear": 1985  },
      { name: "Pawłowski B.",  position: "MID", overall: 76, apps: 27, goals: 5,  starting: true, "birthYear": 1992  },
      { name: "Sierpina",      position: "MID", overall: 72, apps: 29, goals: 1,  starting: true, "birthYear": 1988  },
      { name: "Fertovs",       position: "MID", overall: 68, apps: 29, goals: 0,  starting: true, "birthYear": 1987  },
      { name: "Cebula M.",     position: "MID", overall: 72, apps: 26, goals: 0,  starting: false, "birthYear": 1995 },
      { name: "Pilipchuk",     position: "MID", overall: 74, apps: 19, goals: 3,  starting: false, "birthYear": 1984 },
      { name: "Aankour",       position: "MID", overall: 65, apps: 27, goals: 0,  starting: false, "birthYear": 1993 },
      { name: "Sobolewski P.", position: "MID", overall: 70, apps: 11, goals: 1,  starting: false, "birthYear": 1979 },

      { name: "Cabrera",         position: "FWD", overall: 86, apps: 28, goals: 16, starting: true, "birthYear": 1987  },
      { name: "Przybyła",      position: "FWD", overall: 70, apps: 22, goals: 5,  starting: true, "birthYear": 1994  },
      { name: "Sekulski",      position: "FWD", overall: 66, apps: 9,  goals: 1,  starting: false, "birthYear": 1990 },
      { name: "Trytko",        position: "FWD", overall: 66, apps: 12, goals: 2,  starting: false, "birthYear": 1987 },
      { name: "Zając T.",      position: "FWD", overall: 62, apps: 18, goals: 0,  starting: false, "birthYear": 1995 },
    ]
  },
{
    club: "Termalica Bruk-Bet Nieciecza",
    season: "2015/16",
    "coaches": [{ "name": "Piotr Mandrysz" }],
    players: [
      { name: "Nowak S.",      position: "GK",  overall: 67, apps: 24, goals: 0,  starting: true, "birthYear": 1982  },
      { name: "Pilarz",        position: "GK",  overall: 66, apps: 8,  goals: 0,  starting: false, "birthYear": 1980 },
      { name: "Witan",         position: "GK",  overall: 62, apps: 5,  goals: 0,  starting: false, "birthYear": 1990 },

      { name: "Pleva",         position: "DEF", overall: 74, apps: 27, goals: 1,  starting: true, "birthYear": 1984  },
      { name: "Sołdecki",      position: "DEF", overall: 72, apps: 32, goals: 4,  starting: true, "birthYear": 1987  },
      { name: "Stano",         position: "DEF", overall: 70, apps: 23, goals: 1,  starting: true, "birthYear": 1977  },
      { name: "Jarecki",       position: "DEF", overall: 68, apps: 26, goals: 2,  starting: true, "birthYear": 1981  },
      { name: "Putivtsev",     position: "DEF", overall: 66, apps: 15, goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Ziajka",        position: "DEF", overall: 66, apps: 23, goals: 0,  starting: false, "birthYear": 1982 },
      { name: "Fryc",          position: "DEF", overall: 64, apps: 21, goals: 0,  starting: false, "birthYear": 1993 },
      { name: "Markowski M.",  position: "DEF", overall: 62, apps: 12, goals: 0,  starting: false, "birthYear": 1990 },

      { name: "Babiarz",       position: "MID", overall: 76, apps: 32, goals: 3,  starting: true, "birthYear": 1989  },
      { name: "Plizga",        position: "MID", overall: 74, apps: 33, goals: 4,  starting: true, "birthYear": 1985  },
      { name: "Kupczak",       position: "MID", overall: 70, apps: 33, goals: 1,  starting: true, "birthYear": 1992  },
      { name: "Foszmańczyk",   position: "MID", overall: 68, apps: 26, goals: 2,  starting: true, "birthYear": 1986  },
      { name: "Biskup",        position: "MID", overall: 66, apps: 28, goals: 2,  starting: false, "birthYear": 1983 },
      { name: "Juhar",         position: "MID", overall: 65, apps: 24, goals: 2,  starting: false, "birthYear": 1988 },
      { name: "Misak",         position: "MID", overall: 65, apps: 12, goals: 1,  starting: false, "birthYear": 1991 },
      { name: "Smuczyński",    position: "MID", overall: 63, apps: 14, goals: 1,  starting: false, "birthYear": 1995 },

      { name: "Kędziora",      position: "FWD", overall: 76, apps: 36, goals: 9,  starting: true, "birthYear": 1980  },
      { name: "Drozdowicz",    position: "FWD", overall: 65, apps: 16, goals: 1,  starting: true, "birthYear": 1986  },
      { name: "Gutkovskis",    position: "FWD", overall: 64, apps: 7,  goals: 0,  starting: false, "birthYear": 1995 },
      { name: "Wróbel J.",     position: "FWD", overall: 63, apps: 3,  goals: 0,  starting: false, "birthYear": 1993 },
      { name: "Bratanović",    position: "FWD", overall: 62, apps: 4,  goals: 0,  starting: false, "birthYear": 1992 },
    ]
  },
{
    club: "Górnik Łęczna",
    season: "2015/16",
    "coaches": [{ "name": "Yuriy Shatalov" }, { "name": "Andrzej Rybarski" }],
    players: [
      { name: "Prusak",        position: "GK",  overall: 68, apps: 20, goals: 0,  starting: true, "birthYear": 1979  },
      { name: "Bartkus",       position: "GK",  overall: 63, apps: 7,  goals: 0,  starting: false, "birthYear": 1989 },
      { name: "Rodić",         position: "GK",  overall: 63, apps: 12, goals: 0,  starting: false, "birthYear": 1987 },

      { name: "Mierzejewski",  position: "DEF", overall: 72, apps: 28, goals: 1,  starting: true, "birthYear": 1982  },
      { name: "Bozić",         position: "DEF", overall: 70, apps: 31, goals: 0,  starting: true, "birthYear": 1987  },
      { name: "Leandro",       position: "DEF", overall: 68, apps: 31, goals: 1,  starting: true, "birthYear": 1983  },
      { name: "Bielak",        position: "DEF", overall: 66, apps: 15, goals: 0,  starting: true, "birthYear": 1986  },
      { name: "Szmatiuk",      position: "DEF", overall: 66, apps: 20, goals: 0,  starting: false, "birthYear": 1980 },
      { name: "Bednarek",      position: "DEF", overall: 66, apps: 17, goals: 0,  starting: false, "birthYear": 1996 },
      { name: "Jakubik",       position: "DEF", overall: 63, apps: 7,  goals: 1,  starting: false, "birthYear": 1990 },
      { name: "Basta",         position: "DEF", overall: 62, apps: 3,  goals: 0,  starting: false, "birthYear": 1988 },

      { name: "Piesio",        position: "MID", overall: 79, apps: 35, goals: 5,  starting: true, "birthYear": 1988  },
      { name: "Bonin",         position: "MID", overall: 84, apps: 34, goals: 8,  starting: true, "birthYear": 1983  },
      { name: "Nowak T.",      position: "MID", overall: 68, apps: 31, goals: 1,  starting: true, "birthYear": 1985  },
      { name: "Tymiński",      position: "MID", overall: 68, apps: 24, goals: 0,  starting: true, "birthYear": 1990  },
      { name: "Danielewicz",   position: "MID", overall: 66, apps: 9,  goals: 1,  starting: false, "birthYear": 1991 },
      { name: "Bogusławski",   position: "MID", overall: 64, apps: 9,  goals: 0,  starting: false, "birthYear": 1993 },
      { name: "Pruchnik",      position: "MID", overall: 63, apps: 28, goals: 0,  starting: false, "birthYear": 1986 },
      { name: "Poźniak",       position: "MID", overall: 63, apps: 6,  goals: 1,  starting: false, "birthYear": 1989 },

      { name: "Śpiączka",      position: "FWD", overall: 78, apps: 35, goals: 9,  starting: true, "birthYear": 1991  },
      { name: "Świerczok",     position: "FWD", overall: 76, apps: 31, goals: 7,  starting: true, "birthYear": 1992  },
      { name: "Pitry",         position: "FWD", overall: 66, apps: 27, goals: 4,  starting: false, "birthYear": 1981 },
      { name: "Chernykh",      position: "FWD", overall: 68, apps: 6,  goals: 1,  starting: false, "birthYear": 1991 },
    ]
  },
{
    club: "Górnik Zabrze",
    season: "2015/16",
    "coaches": [{ "name": "Robert Warzycha" }, { "name": "Leszek Ojrzyński" }, { "name": "Jan Żurek" }],
    players: [
      { name: "Kasprzik",      position: "GK",  overall: 76, apps: 20, goals: 0,  starting: true, "birthYear": 1983  },
      { name: "Janukiewicz",   position: "GK",  overall: 65, apps: 12, goals: 0,  starting: false, "birthYear": 1984 },
      { name: "Przyrowski",    position: "GK",  overall: 63, apps: 5,  goals: 0,  starting: false, "birthYear": 1981 },

      { name: "Danch",         position: "DEF", overall: 72, apps: 36, goals: 2,  starting: true, "birthYear": 1987  },
      { name: "Gergel",        position: "DEF", overall: 79, apps: 36, goals: 10, starting: true, "birthYear": 1988  },
      { name: "Kopacz B.",     position: "DEF", overall: 68, apps: 28, goals: 4,  starting: true, "birthYear": 1992  },
      { name: "Vidanov",       position: "DEF", overall: 66, apps: 13, goals: 0,  starting: true, "birthYear": 1988  },
      { name: "Shevelyukhin",  position: "DEF", overall: 65, apps: 18, goals: 2,  starting: false, "birthYear": 1982 },
      { name: "Kallaste",      position: "DEF", overall: 64, apps: 15, goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Oss",           position: "DEF", overall: 62, apps: 9,  goals: 0,  starting: false, "birthYear": 1991 },
      { name: "Słodowy",       position: "DEF", overall: 62, apps: 14, goals: 0,  starting: false, "birthYear": 1991 },

      { name: "Kwiek",         position: "MID", overall: 72, apps: 26, goals: 3,  starting: true, "birthYear": 1983  },
      { name: "Madej Ł.",      position: "MID", overall: 70, apps: 29, goals: 2,  starting: true, "birthYear": 1982  },
      { name: "Steblecki",     position: "MID", overall: 68, apps: 13, goals: 2,  starting: true, "birthYear": 1992  },
      { name: "Grendel",       position: "MID", overall: 66, apps: 11, goals: 2,  starting: true, "birthYear": 1988  },
      { name: "Matuszek",      position: "MID", overall: 65, apps: 11, goals: 3,  starting: false, "birthYear": 1989 },
      { name: "Cerimagić",     position: "MID", overall: 65, apps: 18, goals: 1,  starting: false, "birthYear": 1994 },
      { name: "Sobolewski",    position: "MID", overall: 76, apps: 17, goals: 3,  starting: false, "birthYear": 1976 },
      { name: "Kurzawa",       position: "MID", overall: 75, apps: 23, goals: 1,  starting: false, "birthYear": 1993 },
      { name: "Przybylski",    position: "MID", overall: 64, apps: 20, goals: 1,  starting: false, "birthYear": 1982 },
      { name: "Iwan B.",       position: "MID", overall: 63, apps: 4,  goals: 0,  starting: false, "birthYear": 1984 },

      { name: "Korzym",        position: "FWD", overall: 68, apps: 16, goals: 2,  starting: true, "birthYear": 1988  },
      { name: "Kante",         position: "FWD", overall: 66, apps: 16, goals: 0,  starting: true, "birthYear": 1990  },
      { name: "Skrzypczak",    position: "FWD", overall: 65, apps: 22, goals: 2,  starting: false, "birthYear": 1990 },
      { name: "Urynowicz",     position: "FWD", overall: 61, apps: 3,  goals: 1,  starting: false, "birthYear": 1996 },
    ]
  },
{
    club: "Podbeskidzie Bielsko-Biała",
    season: "2015/16",
    "coaches": [{ "name": "Dariusz Kubicki" }, { "name": "Robert Podoliński" }],
    players: [
      { name: "Zubas",         position: "GK",  overall: 78, apps: 34, goals: 0,  starting: true, "birthYear": 1990  },
      { name: "Kaczmarek W.",  position: "GK",  overall: 64, apps: 4,  goals: 0,  starting: false, "birthYear": 1983 },

      { name: "Sokołowski M.", position: "DEF", overall: 74, apps: 28, goals: 2,  starting: true, "birthYear": 1978  },
      { name: "Mójta",         position: "DEF", overall: 72, apps: 31, goals: 8,  starting: true, "birthYear": 1986  },
      { name: "Kolcak",        position: "DEF", overall: 68, apps: 21, goals: 0,  starting: true, "birthYear": 1990  },
      { name: "Pazio",         position: "DEF", overall: 66, apps: 15, goals: 0,  starting: true, "birthYear": 1992  },
      { name: "Veretilo",      position: "DEF", overall: 65, apps: 10, goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Piacek",        position: "DEF", overall: 65, apps: 14, goals: 1,  starting: false, "birthYear": 1983 },
      { name: "Baranowski P.", position: "DEF", overall: 65, apps: 14, goals: 1,  starting: false, "birthYear": 1990 },
      { name: "Adu Kwame",     position: "DEF", overall: 63, apps: 13, goals: 1,  starting: false, "birthYear": 1985 },
      { name: "Nowak K.",      position: "DEF", overall: 62, apps: 21, goals: 0,  starting: false, "birthYear": 1994 },

      { name: "Kato",          position: "MID", overall: 74, apps: 35, goals: 1,  starting: true, "birthYear": 1986  },
      { name: "Możdżeń",       position: "MID", overall: 72, apps: 33, goals: 4,  starting: true, "birthYear": 1991  },
      { name: "Kowalski J.",   position: "MID", overall: 70, apps: 32, goals: 1,  starting: true, "birthYear": 1987  },
      { name: "Chmiel",        position: "MID", overall: 68, apps: 23, goals: 1,  starting: true, "birthYear": 1987  },
      { name: "Deja",          position: "MID", overall: 66, apps: 25, goals: 0,  starting: false, "birthYear": 1993 },
      { name: "Stefanik",      position: "MID", overall: 65, apps: 14, goals: 3,  starting: false, "birthYear": 1991 },
      { name: "Sloboda A.",    position: "MID", overall: 64, apps: 11, goals: 0,  starting: false, "birthYear": 1987 },
      { name: "Tarnowski",     position: "MID", overall: 63, apps: 12, goals: 0,  starting: false, "birthYear": 1990 },

      { name: "Szczepaniak",   position: "FWD", overall: 78, apps: 33, goals: 10, starting: true, "birthYear": 1991  },
      { name: "Demjan",        position: "FWD", overall: 72, apps: 33, goals: 7,  starting: true, "birthYear": 1982  },
      { name: "Jonkisz",       position: "FWD", overall: 63, apps: 12, goals: 0,  starting: false, "birthYear": 1995 },
      { name: "Korzym",        position: "FWD", overall: 64, apps: 2,  goals: 0,  starting: false, "birthYear": 1988 },
    ]
  }
);
