// ============================================================
// SEZON 2020/21 — 16 klubów
// Część bazy TEAMS_DATA — każdy sezon w osobnym pliku.
// ============================================================

window.TEAMS_DATA = window.TEAMS_DATA || [];
window.TEAMS_DATA.push(
{
    club: "Legia Warszawa",
    season: "2020/21",
    "coaches": [{ "name": "Aleksandar Vuković" }, { "name": "Czesław Michniewicz" }],
    players: [
      { name: "Boruc",         position: "GK",  overall: 76, apps: 25, goals: 0,  starting: true, "birthYear": 1980  },
      { name: "Miszta",        position: "GK",  overall: 64, apps: 6,  goals: 0,  starting: false, "birthYear": 2001 },
      { name: "Cierzniak",     position: "GK",  overall: 62, apps: 1,  goals: 0,  starting: false, "birthYear": 1983 },

      { name: "Juranović",     position: "DEF", overall: 88, apps: 26, goals: 2,  starting: true, "birthYear": 1995  },
      { name: "Mladenović",    position: "DEF", overall: 85, apps: 29, goals: 7,  starting: true, "birthYear": 1991  },
      { name: "Jędrzejczyk",   position: "DEF", overall: 82, apps: 27, goals: 7,  starting: true, "birthYear": 1987  },
      { name: "Wieteska",      position: "DEF", overall: 72, apps: 18, goals: 3,  starting: true, "birthYear": 1997  },
      { name: "Lewczuk",       position: "DEF", overall: 75, apps: 11, goals: 2,  starting: false, "birthYear": 1985 },
      { name: "Hołownia",      position: "DEF", overall: 66, apps: 9,  goals: 3,  starting: false, "birthYear": 1998 },
      { name: "Astiz",         position: "DEF", overall: 64, apps: 0,  goals: 0,  starting: false, "birthYear": 1983 },
      { name: "Vesović",       position: "DEF", overall: 66, apps: 1,  goals: 0,  starting: false, "birthYear": 1991 },
      { name: "Stolarski",     position: "DEF", overall: 64, apps: 4,  goals: 0,  starting: false, "birthYear": 1996 },
      { name: "Remy",          position: "DEF", overall: 64, apps: 3,  goals: 0,  starting: false, "birthYear": 1991 },

      { name: "Andre Martins", position: "MID", overall: 78, apps: 25, goals: 5,  starting: true, "birthYear": 1990  },
      { name: "Kapustka",      position: "MID", overall: 76, apps: 25, goals: 2,  starting: true, "birthYear": 1996  },
      { name: "Wszołek",       position: "MID", overall: 84, apps: 24, goals: 1,  starting: true, "birthYear": 1992  },
      { name: "Luquinhas",     position: "MID", overall: 86, apps: 25, goals: 4,  starting: true, "birthYear": 1996  },
      { name: "Gvilia",        position: "MID", overall: 77, apps: 19, goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Slisz",         position: "MID", overall: 76, apps: 27, goals: 4,  starting: false, "birthYear": 1999 },
      { name: "Antolić",       position: "MID", overall: 68, apps: 8,  goals: 1,  starting: false, "birthYear": 1990 },
      { name: "Valencia J.",   position: "MID", overall: 54, apps: 8,  goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Skibicki",      position: "MID", overall: 62, apps: 6,  goals: 1,  starting: false, "birthYear": 2001 },

      { name: "Pekhart",       position: "FWD", overall: 92, apps: 25, goals: 22, starting: true, "birthYear": 1989  },
      { name: "Rafa Lopes",    position: "FWD", overall: 76, apps: 20, goals: 4,  starting: true, "birthYear": 1991  },
      { name: "Kostorz",       position: "FWD", overall: 60, apps: 6,  goals: 1,  starting: false, "birthYear": 1999 },
    ]
  },
{
    club: "Raków Częstochowa",
    season: "2020/21",
    "coaches": [{ "name": "Marek Papszun" }],
    players: [
      { name: "Holec",         position: "GK",  overall: 76, apps: 16, goals: 0,  starting: true, "birthYear": 1994  },
      { name: "Szumski",       position: "GK",  overall: 68, apps: 12, goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Pindroch",      position: "GK",  overall: 60, apps: 2,  goals: 0,  starting: false, "birthYear": 1991 },

      { name: "Piątkowski",    position: "DEF", overall: 86, apps: 27, goals: 5,  starting: true, "birthYear": 2000  },
      { name: "Niewulis",      position: "DEF", overall: 70, apps: 23, goals: 4,  starting: true, "birthYear": 1989  },
      { name: "Jach",          position: "DEF", overall: 70, apps: 10, goals: 4,  starting: true, "birthYear": 1994  },
      { name: "Petrasek",      position: "DEF", overall: 84, apps: 8,  goals: 2,  starting: true, "birthYear": 1992  },
      { name: "Wilusz",        position: "DEF", overall: 74, apps: 10, goals: 1,  starting: false, "birthYear": 1988 },
      { name: "Arsenić",       position: "DEF", overall: 74, apps: 9,  goals: 2,  starting: false, "birthYear": 1994 },
      { name: "Mamić",         position: "DEF", overall: 60, apps: 0,  goals: 0,  starting: false, "birthYear": 1996 },
      { name: "Mikołajewski",  position: "DEF", overall: 60, apps: 3,  goals: 0,  starting: false, "birthYear": 1999 },

      { name: "Tudor",         position: "MID", overall: 88, apps: 29, goals: 3,  starting: true, "birthYear": 1995  },
      { name: "Ivi López",     position: "MID", overall: 92, apps: 26, goals: 9,  starting: true, "birthYear": 1994  },
      { name: "Kun P.",        position: "MID", overall: 80, apps: 29, goals: 5,  starting: true, "birthYear": 1995  },
      { name: "Cebula M.",     position: "MID", overall: 80, apps: 24, goals: 6,  starting: true, "birthYear": 1995  },
      { name: "Schwarz",       position: "MID", overall: 80, apps: 27, goals: 2,  starting: false, "birthYear": 1991 },
      { name: "Poletanović",   position: "MID", overall: 68, apps: 21, goals: 3,  starting: false, "birthYear": 1993 },
      { name: "Tijanić",       position: "MID", overall: 80, apps: 28, goals: 6,  starting: false, "birthYear": 1997 },
      { name: "Sapała",        position: "MID", overall: 70, apps: 24, goals: 5,  starting: false, "birthYear": 1995 },
      { name: "Lederman",      position: "MID", overall: 66, apps: 13, goals: 4,  starting: false, "birthYear": 2000 },
      { name: "Bartl",         position: "MID", overall: 64, apps: 11, goals: 0,  starting: false, "birthYear": 1989 },
      { name: "Papanikolaou",  position: "MID", overall: 72, apps: 7,  goals: 0,  starting: false, "birthYear": 1998 },
      { name: "Wdowiak",       position: "MID", overall: 64, apps: 9,  goals: 2,  starting: false, "birthYear": 1996 },

      { name: "Gutkovskis",    position: "FWD", overall: 78, apps: 29, goals: 7,  starting: true, "birthYear": 1995  },
      { name: "Arak",          position: "FWD", overall: 64, apps: 12, goals: 1,  starting: true, "birthYear": 1995 },
    ]
  },
{
    club: "Pogoń Szczecin",
    season: "2020/21",
    "coaches": [{ "name": "Kosta Runjaić" }],
    players: [
      { name: "Stipica",       position: "GK",  overall: 86, apps: 30, goals: 0,  starting: true, "birthYear": 1991  },

      { name: "Bartkowski",    position: "DEF", overall: 72, apps: 21, goals: 3,  starting: true, "birthYear": 1991  },
      { name: "Triantafyllopoulos",position:"DEF", overall: 80, apps: 17, goals: 3,  starting: true, "birthYear": 1993  },
      { name: "Zech",          position: "DEF", overall: 80, apps: 27, goals: 1,  starting: true, "birthYear": 1990  },
      { name: "Malec",         position: "DEF", overall: 78, apps: 20, goals: 0,  starting: true, "birthYear": 1995  },
      { name: "Mata",          position: "DEF", overall: 76, apps: 18, goals: 4,  starting: false, "birthYear": 1997 },
      { name: "Stec",          position: "DEF", overall: 66, apps: 10, goals: 2,  starting: false, "birthYear": 1994 },
      { name: "Matynia",       position: "DEF", overall: 66, apps: 14, goals: 5,  starting: false, "birthYear": 1995 },
      { name: "Mruk",          position: "DEF", overall: 58, apps: 1,  goals: 0,  starting: false, "birthYear": 2001 },

      { name: "Kucharczyk",    position: "MID", overall: 76, apps: 30, goals: 6,  starting: true, "birthYear": 1991  },
      { name: "Drygas",        position: "MID", overall: 74, apps: 27, goals: 6,  starting: true, "birthYear": 1991  },
      { name: "Kowalczyk S.",  position: "MID", overall: 74, apps: 29, goals: 7,  starting: true, "birthYear": 1998  },
      { name: "Gorgon",        position: "MID", overall: 79, apps: 24, goals: 6,  starting: true, "birthYear": 1988  },
      { name: "Dąbrowski D.",  position: "MID", overall: 78, apps: 26, goals: 5,  starting: false, "birthYear": 1992 },
      { name: "Kozłowski K.",  position: "MID", overall: 85, apps: 20, goals: 4,  starting: false, "birthYear": 2003 },
      { name: "Smoliński",     position: "MID", overall: 76, apps: 27, goals: 3,  starting: false, "birthYear": 2001 },
      { name: "Kurzawa",       position: "MID", overall: 76, apps: 10, goals: 2,  starting: false, "birthYear": 1993 },
      { name: "Hostikka",      position: "MID", overall: 62, apps: 12, goals: 0,  starting: false, "birthYear": 1997 },
      { name: "Podstawski",    position: "MID", overall: 64, apps: 20, goals: 0,  starting: false, "birthYear": 1995 },

      { name: "Zahović",       position: "FWD", overall: 72, apps: 25, goals: 3,  starting: true, "birthYear": 1995  },
      { name: "Benedyczak",    position: "FWD", overall: 68, apps: 25, goals: 4,  starting: true, "birthYear": 2000  },
      { name: "Frączczak",     position: "FWD", overall: 64, apps: 15, goals: 3,  starting: false, "birthYear": 1987 },
    ]
  },
{
    club: "Śląsk Wrocław",
    season: "2020/21",
    "coaches": [{ "name": "Vitezslav Lavicka" }, { "name": "Jacek Magiera" }],
    players: [
      { name: "Putnocky",      position: "GK",  overall: 82, apps: 19, goals: 0,  starting: true, "birthYear": 1984  },
      { name: "Szromnik",      position: "GK",  overall: 75, apps: 11, goals: 0,  starting: false, "birthYear": 1993 },

      { name: "Stiglec",       position: "DEF", overall: 79, apps: 25, goals: 4,  starting: true, "birthYear": 1990  },
      { name: "Tamas",         position: "DEF", overall: 72, apps: 24, goals: 6,  starting: true, "birthYear": 1993  },
      { name: "Puerto",        position: "DEF", overall: 83, apps: 17, goals: 5,  starting: true, "birthYear": 1993  },
      { name: "Celeban",       position: "DEF", overall: 74, apps: 14, goals: 4,  starting: true, "birthYear": 1985  },
      { name: "Bejger",        position: "DEF", overall: 74, apps: 11, goals: 2,  starting: false, "birthYear": 2002 },
      { name: "Janasik",       position: "DEF", overall: 62, apps: 17, goals: 2,  starting: false, "birthYear": 1997 },
      { name: "Cotugno",       position: "DEF", overall: 62, apps: 9,  goals: 1,  starting: false, "birthYear": 1995 },
      { name: "Pawelec",       position: "DEF", overall: 60, apps: 10, goals: 2,  starting: false, "birthYear": 1986 },

      { name: "Sobota",        position: "MID", overall: 76, apps: 28, goals: 1,  starting: true, "birthYear": 1987  },
      { name: "Pich",          position: "MID", overall: 76, apps: 30, goals: 3,  starting: true, "birthYear": 1988  },
      { name: "Pawłowski B.",  position: "MID", overall: 72, apps: 22, goals: 3,  starting: true, "birthYear": 1992  },
      { name: "Praszelik",     position: "MID", overall: 78, apps: 26, goals: 1,  starting: true, "birthYear": 2000  },
      { name: "Mączyński",     position: "MID", overall: 70, apps: 18, goals: 3,  starting: false, "birthYear": 1987 },
      { name: "Zylla",         position: "MID", overall: 64, apps: 20, goals: 2,  starting: false, "birthYear": 2000 },
      { name: "Musonda",       position: "MID", overall: 74, apps: 17, goals: 1,  starting: false, "birthYear": 1995 },
      { name: "Scalet",        position: "MID", overall: 62, apps: 14, goals: 1,  starting: false, "birthYear": 1997 },
      { name: "Poprawa",       position: "MID", overall: 60, apps: 6,  goals: 1,  starting: false, "birthYear": 1998 },
      { name: "Makowski R.",   position: "MID", overall: 60, apps: 11, goals: 0,  starting: false, "birthYear": 1996 },

      { name: "Expósito",      position: "FWD", overall: 78, apps: 27, goals: 9,  starting: true, "birthYear": 1996  },
      { name: "Piasecki",      position: "FWD", overall: 77, apps: 26, goals: 5,  starting: true, "birthYear": 1995  },
      { name: "Samiec-Talar",  position: "FWD", overall: 60, apps: 8,  goals: 0,  starting: false, "birthYear": 2001 },
    ]
  },
{
    club: "Warta Poznań",
    season: "2020/21",
    "coaches": [{ "name": "Piotr Tworek" }],
    players: [
      { name: "Lis A.",        position: "GK",  overall: 70, apps: 25, goals: 0,  starting: true, "birthYear": 1992  },

      { name: "Grzesik J.",    position: "DEF", overall: 80, apps: 27, goals: 2,  starting: true, "birthYear": 1994  },
      { name: "Ivanov",        position: "DEF", overall: 70, apps: 22, goals: 3,  starting: true, "birthYear": 1994  },
      { name: "Ławniczak",     position: "DEF", overall: 66, apps: 23, goals: 3,  starting: true, "birthYear": 1999  },
      { name: "Kieliba",       position: "DEF", overall: 79, apps: 14, goals: 4,  starting: true, "birthYear": 1990  },
      { name: "Kuzdra",        position: "DEF", overall: 74, apps: 23, goals: 3,  starting: false, "birthYear": 1997 },
      { name: "Kiełb J.",      position: "DEF", overall: 74, apps: 23, goals: 2,  starting: false, "birthYear": 1993 },
      { name: "Spychała",      position: "DEF", overall: 60, apps: 7,  goals: 1,  starting: false, "birthYear": 1998 },
      { name: "Nawrocki M.",   position: "DEF", overall: 60, apps: 3,  goals: 1,  starting: false, "birthYear": 2001 },
      { name: "Boczek",        position: "DEF", overall: 58, apps: 0,  goals: 0,  starting: false, "birthYear": 1990 },

      { name: "Trałka",        position: "MID", overall: 78, apps: 29, goals: 5,  starting: true, "birthYear": 1984  },
      { name: "Czyżycki",      position: "MID", overall: 74, apps: 22, goals: 2,  starting: true, "birthYear": 1998  },
      { name: "Jakóbowski",    position: "MID", overall: 68, apps: 23, goals: 4,  starting: true, "birthYear": 1992  },
      { name: "Kupczak",       position: "MID", overall: 66, apps: 25, goals: 1,  starting: false, "birthYear": 1992  },
      { name: "Baku",          position: "MID", overall: 86, apps: 13, goals: 6,  starting: true, "birthYear": 1998 },
      { name: "Laskowski A.",  position: "MID", overall: 64, apps: 9,  goals: 4,  starting: false, "birthYear": 1992 },
      { name: "Rodriguez M.",  position: "MID", overall: 64, apps: 13, goals: 1,  starting: false, "birthYear": 1997 },
      { name: "Handzlik",      position: "MID", overall: 60, apps: 3,  goals: 0,  starting: false, "birthYear": 1998 },
      { name: "Kopczyński",    position: "MID", overall: 62, apps: 7,  goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Rybicki",       position: "MID", overall: 60, apps: 13, goals: 0,  starting: false, "birthYear": 1993 },

      { name: "Kuzimski",      position: "FWD", overall: 76, apps: 29, goals: 7,  starting: true, "birthYear": 1991  },
      { name: "Zrelak",        position: "FWD", overall: 64, apps: 8,  goals: 1,  starting: true, "birthYear": 1994 },
      { name: "Jaroch G.",     position: "FWD", overall: 60, apps: 14, goals: 0,  starting: false, "birthYear": 1998 },
    ]
  },
{
    club: "Piast Gliwice",
    season: "2020/21",
    "coaches": [{ "name": "Waldemar Fornalik" }],
    players: [
      { name: "Plach",         position: "GK",  overall: 82, apps: 30, goals: 0,  starting: true, "birthYear": 1992  },
      { name: "Szmatuła",      position: "GK",  overall: 60, apps: 0,  goals: 0,  starting: false, "birthYear": 1981 },

      { name: "Czerwiński",    position: "DEF", overall: 84, apps: 26, goals: 4,  starting: true, "birthYear": 1991  },
      { name: "Konczkowski",   position: "DEF", overall: 70, apps: 25, goals: 1,  starting: true, "birthYear": 1993  },
      { name: "Huk",           position: "DEF", overall: 79, apps: 24, goals: 4,  starting: true, "birthYear": 1994  },
      { name: "Holubek",       position: "DEF", overall: 74, apps: 23, goals: 4,  starting: true, "birthYear": 1991  },
      { name: "Malarczyk",     position: "DEF", overall: 66, apps: 14, goals: 2,  starting: false, "birthYear": 1991 },
      { name: "Rymaniak",      position: "DEF", overall: 66, apps: 13, goals: 3,  starting: false, "birthYear": 1989 },
      { name: "Kirkeskov",     position: "DEF", overall: 66, apps: 7,  goals: 2,  starting: false, "birthYear": 1991 },
      { name: "Mokwa",         position: "DEF", overall: 58, apps: 4,  goals: 0,  starting: false, "birthYear": 1993 },

      { name: "Jodłowiec",     position: "MID", overall: 72, apps: 27, goals: 2,  starting: true, "birthYear": 1985  },
      { name: "Chrapek",       position: "MID", overall: 72, apps: 23, goals: 4,  starting: true, "birthYear": 1992  },
      { name: "Lipski",        position: "MID", overall: 70, apps: 25, goals: 4,  starting: true, "birthYear": 1994  },
      { name: "Sokołowski P.", position: "MID", overall: 68, apps: 29, goals: 4,  starting: true, "birthYear": 1994  },
      { name: "Badia",         position: "MID", overall: 76, apps: 22, goals: 3,  starting: false, "birthYear": 1989 },
      { name: "Pyrka",         position: "MID", overall: 74, apps: 23, goals: 4,  starting: false, "birthYear": 2002 },
      { name: "Milewski",      position: "MID", overall: 74, apps: 18, goals: 2,  starting: false, "birthYear": 1998 },
      { name: "Vida",          position: "MID", overall: 64, apps: 19, goals: 1,  starting: false, "birthYear": 1995 },
      { name: "Alves",         position: "MID", overall: 62, apps: 21, goals: 0,  starting: false, "birthYear": 1996 },

      { name: "Świerczok",     position: "FWD", overall: 83, apps: 23, goals: 15, starting: true, "birthYear": 1992  },
      { name: "Żyro",          position: "FWD", overall: 70, apps: 26, goals: 4,  starting: true, "birthYear": 1992  },
      { name: "Steczyk",       position: "FWD", overall: 64, apps: 26, goals: 4,  starting: false, "birthYear": 1999 },
    ]
  },
{
    club: "Lechia Gdańsk",
    season: "2020/21",
    "coaches": [{ "name": "Piotr Stokowiec" }],
    players: [
      { name: "Kuciak",        position: "GK",  overall: 84, apps: 28, goals: 0,  starting: true, "birthYear": 1985  },
      { name: "Alomerović",    position: "GK",  overall: 60, apps: 2,  goals: 2,  starting: false, "birthYear": 1991 },

      { name: "Kopacz B.",     position: "DEF", overall: 72, apps: 29, goals: 5,  starting: true, "birthYear": 1992  },
      { name: "Pietrzak R.",   position: "DEF", overall: 70, apps: 26, goals: 2,  starting: true, "birthYear": 1992  },
      { name: "Fila",          position: "DEF", overall: 70, apps: 26, goals: 4,  starting: true, "birthYear": 1998  },
      { name: "Tobers",        position: "DEF", overall: 66, apps: 17, goals: 5,  starting: true, "birthYear": 2000  },
      { name: "Nalepa M.",     position: "DEF", overall: 68, apps: 16, goals: 2,  starting: false, "birthYear": 1993 },
      { name: "Maloca",        position: "DEF", overall: 66, apps: 15, goals: 2,  starting: false, "birthYear": 1989 },

      { name: "Kubicki J.",    position: "MID", overall: 78, apps: 28, goals: 9,  starting: true, "birthYear": 1995  },
      { name: "Saief",         position: "MID", overall: 78, apps: 22, goals: 8,  starting: true, "birthYear": 1993  },
      { name: "Gajos",         position: "MID", overall: 72, apps: 28, goals: 1,  starting: true, "birthYear": 1991  },
      { name: "Conrado",       position: "MID", overall: 72, apps: 27, goals: 4,  starting: true, "birthYear": 1997  },
      { name: "Haydary",       position: "MID", overall: 66, apps: 18, goals: 4,  starting: false, "birthYear": 1998 },
      { name: "Kałuziński",    position: "MID", overall: 64, apps: 11, goals: 2,  starting: false, "birthYear": 2002 },
      { name: "Ceesay J.",     position: "MID", overall: 64, apps: 11, goals: 3,  starting: false, "birthYear": 1998 },
      { name: "Mihalik",       position: "MID", overall: 64, apps: 9,  goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Udovicić",      position: "MID", overall: 62, apps: 14, goals: 1,  starting: false, "birthYear": 1987 },
      { name: "Sopoćko",       position: "MID", overall: 58, apps: 4,  goals: 2,  starting: false, "birthYear": 1999 },
      { name: "Makowski T.",   position: "MID", overall: 58, apps: 19, goals: 3,  starting: false, "birthYear": 1999 },

      { name: "Flavio Paixao", position: "FWD", overall: 84, apps: 30, goals: 12, starting: true, "birthYear": 1984  },
      { name: "Zwoliński",     position: "FWD", overall: 74, apps: 22, goals: 6,  starting: true, "birthYear": 1993  },
      { name: "Arak",          position: "FWD", overall: 62, apps: 4,  goals: 1,  starting: false, "birthYear": 1995 },
      { name: "Żukowski",      position: "FWD", overall: 60, apps: 16, goals: 1,  starting: false, "birthYear": 2001 },
    ]
  },
{
    club: "Zagłębie Lubin",
    season: "2020/21",
    "coaches": [{ "name": "Martin Sevela" }],
    players: [
      { name: "Hładun",        position: "GK",  overall: 68, apps: 30, goals: 0,  starting: true, "birthYear": 1995  },

      { name: "Balić",         position: "DEF", overall: 78, apps: 25, goals: 10, starting: true, "birthYear": 1990  },
      { name: "Simić",         position: "DEF", overall: 74, apps: 17, goals: 4,  starting: true, "birthYear": 1996  },
      { name: "Chodyna",       position: "DEF", overall: 74, apps: 24, goals: 2,  starting: true, "birthYear": 1999  },
      { name: "Crnomarković",  position: "DEF", overall: 68, apps: 9,  goals: 1,  starting: true, "birthYear": 1993  },
      { name: "Guldan",        position: "DEF", overall: 76, apps: 14, goals: 2,  starting: false, "birthYear": 1983 },
      { name: "Wójcicki",      position: "DEF", overall: 73, apps: 11, goals: 2,  starting: false, "birthYear": 1988 },
      { name: "Kruk",          position: "DEF", overall: 60, apps: 12, goals: 4,  starting: false, "birthYear": 2000 },
      { name: "Jończy",        position: "DEF", overall: 60, apps: 11, goals: 2,  starting: false, "birthYear": 1997 },
      { name: "Bartolewski",   position: "DEF", overall: 58, apps: 10, goals: 1,  starting: false, "birthYear": 1998 },
      { name: "Oko",           position: "DEF", overall: 58, apps: 8,  goals: 2,  starting: false, "birthYear": 1997 },

      { name: "Żubrowski",     position: "MID", overall: 72, apps: 27, goals: 6,  starting: true, "birthYear": 1992  },
      { name: "Bashkirov",     position: "MID", overall: 79, apps: 25, goals: 2,  starting: true, "birthYear": 1991  },
      { name: "Starzyński",    position: "MID", overall: 77, apps: 26, goals: 7,  starting: true, "birthYear": 1991  },
      { name: "Poręba",        position: "MID", overall: 78, apps: 24, goals: 2,  starting: true, "birthYear": 2000  },
      { name: "Szysz",         position: "MID", overall: 78, apps: 30, goals: 3,  starting: false, "birthYear": 1998 },
      { name: "Stoch",         position: "MID", overall: 66, apps: 8,  goals: 2,  starting: false, "birthYear": 1989 },
      { name: "Zivec",         position: "MID", overall: 60, apps: 11, goals: 0,  starting: false, "birthYear": 1991 },
      { name: "Łakomy",        position: "MID", overall: 58, apps: 8,  goals: 0,  starting: false, "birthYear": 2001 },

      { name: "Drazić",        position: "FWD", overall: 76, apps: 22, goals: 7,  starting: true, "birthYear": 1995  },
      { name: "Mraz S.",       position: "FWD", overall: 68, apps: 27, goals: 1,  starting: true, "birthYear": 1997  },
      { name: "Sirk",          position: "FWD", overall: 62, apps: 16, goals: 2,  starting: false, "birthYear": 1993 },
      { name: "Podliński",     position: "FWD", overall: 60, apps: 12, goals: 1,  starting: false, "birthYear": 1997 },
    ]
  },
{
    club: "Jagiellonia Białystok",
    season: "2020/21",
    "coaches": [{ "name": "Bogdan Zając" }, { "name": "Rafał Grzyb" }],
    players: [
      { name: "Steinbors",     position: "GK",  overall: 78, apps: 10, goals: 0,  starting: true, "birthYear": 1985  },
      { name: "Dziekoński",    position: "GK",  overall: 70, apps: 16, goals: 0,  starting: false, "birthYear": 2003 },

      { name: "Tiru",          position: "DEF", overall: 82, apps: 25, goals: 7,  starting: true, "birthYear": 1994  },
      { name: "Augustyn",      position: "DEF", overall: 72, apps: 24, goals: 3,  starting: true, "birthYear": 1988  },
      { name: "Runje",         position: "DEF", overall: 78, apps: 15, goals: 4,  starting: true, "birthYear": 1990  },
      { name: "Kwiecień",      position: "DEF", overall: 73, apps: 12, goals: 7,  starting: true, "birthYear": 1994  },
      { name: "Wdowik",        position: "DEF", overall: 74, apps: 21, goals: 3,  starting: false, "birthYear": 2000 },
      { name: "Arsenić",       position: "DEF", overall: 60, apps: 1,  goals: 1,  starting: false, "birthYear": 1994 },
      { name: "Kadlec",        position: "DEF", overall: 60, apps: 3,  goals: 0,  starting: false, "birthYear": 1996 },
      { name: "Nastić",        position: "DEF", overall: 60, apps: 9,  goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Bodvarsson",    position: "DEF", overall: 58, apps: 13, goals: 1,  starting: false, "birthYear": 1995 },

      { name: "Romanchuk",     position: "MID", overall: 84, apps: 25, goals: 4,  starting: true, "birthYear": 1991  },
      { name: "Pospisil",      position: "MID", overall: 80, apps: 29, goals: 2,  starting: true, "birthYear": 1991  },
      { name: "Makuszewski",   position: "MID", overall: 78, apps: 23, goals: 1,  starting: true, "birthYear": 1989  },
      { name: "Twardek",       position: "MID", overall: 64, apps: 15, goals: 1,  starting: true, "birthYear": 1997  },
      { name: "Borysiuk",      position: "MID", overall: 66, apps: 15, goals: 4,  starting: false, "birthYear": 1991 },
      { name: "Mystkowski",    position: "MID", overall: 64, apps: 18, goals: 2,  starting: false, "birthYear": 1998 },
      { name: "Chernykh",      position: "MID", overall: 74, apps: 16, goals: 3,  starting: false, "birthYear": 1991 },
      { name: "Prikryl",       position: "MID", overall: 62, apps: 18, goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Camara J.",     position: "MID", overall: 62, apps: 2,  goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Wrzesiński",    position: "MID", overall: 60, apps: 7,  goals: 2,  starting: false, "birthYear": 1993 },

      { name: "Imaz",          position: "FWD", overall: 83, apps: 27, goals: 11, starting: true, "birthYear": 1990  },
      { name: "Puljić",        position: "FWD", overall: 80, apps: 25, goals: 11, starting: true, "birthYear": 1993  },
      { name: "Bida",          position: "FWD", overall: 64, apps: 17, goals: 4,  starting: false, "birthYear": 2001 },
    ]
  },
{
    club: "Górnik Zabrze",
    season: "2020/21",
    "coaches": [{ "name": "Marcin Brosz" }],
    players: [
      { name: "Chudy",         position: "GK",  overall: 70, apps: 30, goals: 0,  starting: true, "birthYear": 1989  },
      { name: "Kudła",         position: "GK",  overall: 58, apps: 0,  goals: 0,  starting: false, "birthYear": 1992 },

      { name: "Wiśniewski P.", position: "DEF", overall: 82, apps: 29, goals: 6,  starting: true, "birthYear": 1998  },
      { name: "Janza",         position: "DEF", overall: 82, apps: 28, goals: 6,  starting: true, "birthYear": 1993  },
      { name: "Masouras",      position: "DEF", overall: 78, apps: 23, goals: 4,  starting: true, "birthYear": 1996  },
      { name: "Gryszkiewicz",  position: "DEF", overall: 76, apps: 27, goals: 5,  starting: true, "birthYear": 1999  },
      { name: "Evangelou",     position: "DEF", overall: 64, apps: 9,  goals: 4,  starting: false, "birthYear": 1998 },
      { name: "Bochniewicz",   position: "DEF", overall: 70, apps: 2,  goals: 1,  starting: false, "birthYear": 1996 },
      { name: "Paluszek",      position: "DEF", overall: 60, apps: 13, goals: 0,  starting: false, "birthYear": 2001 },
      { name: "Pawłowski D.",  position: "DEF", overall: 58, apps: 10, goals: 0,  starting: false, "birthYear": 1999 },
      { name: "Michalski K.",  position: "DEF", overall: 56, apps: 3,  goals: 0,  starting: false, "birthYear": 2000 },
      { name: "Eizenchart",    position: "DEF", overall: 56, apps: 0,  goals: 0,  starting: false, "birthYear": 2001 },

      { name: "Jesus Jimenez", position: "MID", overall: 83, apps: 29, goals: 12, starting: true, "birthYear": 1993  },
      { name: "Manneh",        position: "MID", overall: 74, apps: 27, goals: 8,  starting: true, "birthYear": 1998  },
      { name: "Prochazka",     position: "MID", overall: 70, apps: 28, goals: 3,  starting: true, "birthYear": 1989  },
      { name: "Kubica",        position: "MID", overall: 66, apps: 22, goals: 4,  starting: true, "birthYear": 2000  },
      { name: "Nowak B.",      position: "MID", overall: 84, apps: 29, goals: 2,  starting: false, "birthYear": 1993 },
      { name: "Ściślak",       position: "MID", overall: 64, apps: 20, goals: 2,  starting: false, "birthYear": 2000 },
      { name: "Rostkowski",    position: "MID", overall: 58, apps: 11, goals: 0,  starting: false, "birthYear": 2000 },
      { name: "Ryczkowski",    position: "MID", overall: 68, apps: 5,  goals: 1,  starting: false, "birthYear": 1997 },
      { name: "Bainović",      position: "MID", overall: 60, apps: 7,  goals: 0,  starting: false, "birthYear": 1996 },

      { name: "Sobczyk",       position: "FWD", overall: 72, apps: 26, goals: 5,  starting: true, "birthYear": 1997  },
      { name: "Krawczyk",      position: "FWD", overall: 66, apps: 26, goals: 0,  starting: true, "birthYear": 1994  },
      { name: "Boakye",        position: "FWD", overall: 66, apps: 13, goals: 3,  starting: false, "birthYear": 1993 },
      { name: "Wolsztyński Ł.",position: "FWD", overall: 58, apps: 2,  goals: 0,  starting: false, "birthYear": 1994 },
    ]
  },
{
    club: "Lech Poznań",
    season: "2020/21",
    "coaches": [{ "name": "Dariusz Żuraw" }, { "name": "Janusz Góra" }, { "name": "Maciej Skorża" }],
    players: [
      { name: "Bednarek F.",   position: "GK",  overall: 70, apps: 15, goals: 0,  starting: true, "birthYear": 1992  },
      { name: "van der Hart",  position: "GK",  overall: 74, apps: 15, goals: 0,  starting: false, "birthYear": 1994 },

      { name: "Kravets",       position: "DEF", overall: 72, apps: 18, goals: 7,  starting: true, "birthYear": 1997  },
      { name: "Salamon",       position: "DEF", overall: 80, apps: 13, goals: 2,  starting: true, "birthYear": 1991  },
      { name: "Czerwiński A.", position: "DEF", overall: 78, apps: 25, goals: 4,  starting: true, "birthYear": 1993  },
      { name: "Puchacz",       position: "DEF", overall: 80, apps: 27, goals: 5,  starting: true, "birthYear": 1999  },
      { name: "Rogne",         position: "DEF", overall: 76, apps: 18, goals: 1,  starting: false, "birthYear": 1990 },
      { name: "Crnomarković",  position: "DEF", overall: 64, apps: 8,  goals: 3,  starting: false, "birthYear": 1993 },
      { name: "Milić",         position: "DEF", overall: 72, apps: 9,  goals: 4,  starting: false, "birthYear": 1994 },
      { name: "Butko",         position: "DEF", overall: 70, apps: 3,  goals: 0,  starting: false, "birthYear": 1991 },
      { name: "Kostevych",     position: "DEF", overall: 58, apps: 0,  goals: 0,  starting: false, "birthYear": 1992 },

      { name: "Tiba",          position: "MID", overall: 84, apps: 28, goals: 2,  starting: true, "birthYear": 1988  },
      { name: "Ramirez D.",    position: "MID", overall: 74, apps: 30, goals: 3,  starting: true, "birthYear": 1992  },
      { name: "Sykora",        position: "MID", overall: 70, apps: 22, goals: 1,  starting: false, "birthYear": 1993  },
      { name: "Kamiński J.",   position: "MID", overall: 80, apps: 28, goals: 4,  starting: true, "birthYear": 2002  },
      { name: "Skóraś",        position: "MID", overall: 85, apps: 26, goals: 3,  starting: false, "birthYear": 2000 },
      { name: "Marchwiński",   position: "MID", overall: 76, apps: 21, goals: 3,  starting: false, "birthYear": 2002 },
      { name: "Moder",         position: "MID", overall: 90, apps: 14, goals: 4,  starting: true, "birthYear": 1999 },
      { name: "Karlstrom",     position: "MID", overall: 80, apps: 16, goals: 3,  starting: false, "birthYear": 1995 },
      { name: "Muhar",         position: "MID", overall: 60, apps: 6,  goals: 1,  starting: false, "birthYear": 1996 },
      { name: "Kvekveskiri",   position: "MID", overall: 60, apps: 12, goals: 1,  starting: false, "birthYear": 1992 },

      { name: "Ishak",         position: "FWD", overall: 87, apps: 22, goals: 12, starting: true, "birthYear": 1993  },
      { name: "Johannsson",    position: "FWD", overall: 66, apps: 9,  goals: 2,  starting: true, "birthYear": 1990 },
      { name: "Kacharava",     position: "FWD", overall: 60, apps: 7,  goals: 1,  starting: false, "birthYear": 1994 },
      { name: "Awad",          position: "FWD", overall: 58, apps: 9,  goals: 1,  starting: false, "birthYear": 1997 },
    ]
  },
{
    club: "Wisła Płock",
    season: "2020/21",
    "coaches": [{ "name": "Radosław Sobolewski" }, { "name": "Maciej Bartoszek" }],
    players: [
      { name: "Kamiński K.",   position: "GK",  overall: 78, apps: 29, goals: 0,  starting: true, "birthYear": 1990  },

      { name: "Uryga",         position: "DEF", overall: 72, apps: 27, goals: 5,  starting: true, "birthYear": 1994  },
      { name: "Garcia A.",     position: "DEF", overall: 78, apps: 28, goals: 5,  starting: true, "birthYear": 1993  },
      { name: "Rzeźniczak",    position: "DEF", overall: 70, apps: 21, goals: 10, starting: true, "birthYear": 1986  },
      { name: "Zbozień",       position: "DEF", overall: 74, apps: 18, goals: 4,  starting: true, "birthYear": 1989  },
      { name: "Michalski D.",  position: "DEF", overall: 62, apps: 13, goals: 3,  starting: false, "birthYear": 1998 },
      { name: "Tomasik P.",    position: "DEF", overall: 58, apps: 14, goals: 3,  starting: false, "birthYear": 1987 },

      { name: "Szwoch",        position: "MID", overall: 79, apps: 30, goals: 6,  starting: true, "birthYear": 1993  },
      { name: "Lagator",       position: "MID", overall: 74, apps: 26, goals: 6,  starting: true, "birthYear": 1994  },
      { name: "Rasak",         position: "MID", overall: 78, apps: 26, goals: 4,  starting: true, "birthYear": 1996  },
      { name: "Kocyła",        position: "MID", overall: 74, apps: 27, goals: 3,  starting: true, "birthYear": 2002  },
      { name: "Lesniak",       position: "MID", overall: 72, apps: 26, goals: 1,  starting: false, "birthYear": 1996 },
      { name: "Gjertsen",      position: "MID", overall: 62, apps: 19, goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Merebashvili",  position: "MID", overall: 74, apps: 10, goals: 0,  starting: false, "birthYear": 1986 },
      { name: "Wolski R.",     position: "MID", overall: 72, apps: 7,  goals: 2,  starting: false, "birthYear": 1992 },
      { name: "Pyrdoł",        position: "MID", overall: 58, apps: 15, goals: 0,  starting: false, "birthYear": 1999 },

      { name: "Tuszyński",     position: "FWD", overall: 76, apps: 25, goals: 6,  starting: true, "birthYear": 1989  },
      { name: "Sheridan",      position: "FWD", overall: 62, apps: 15, goals: 1,  starting: true, "birthYear": 1989 },
      { name: "Airam",         position: "FWD", overall: 60, apps: 5,  goals: 0,  starting: false, "birthYear": 1987 },
      { name: "Lewandowski M.",position: "FWD", overall: 58, apps: 16, goals: 1,  starting: false, "birthYear": 1999 },
    ]
  },
{
    club: "Wisła Kraków",
    season: "2020/21",
    "coaches": [{ "name": "Artur Skowronek" }, { "name": "Peter Hyballa" }, { "name": "Kazimierz Kmiecik" }],
    players: [
      { name: "Lis M.",        position: "GK",  overall: 76, apps: 27, goals: 0,  starting: true, "birthYear": 1997  },

      { name: "Frydrych",      position: "DEF", overall: 83, apps: 24, goals: 8,  starting: true, "birthYear": 1990  },
      { name: "Burliga",       position: "DEF", overall: 70, apps: 22, goals: 8,  starting: true, "birthYear": 1988  },
      { name: "Savić",         position: "DEF", overall: 68, apps: 27, goals: 3,  starting: true, "birthYear": 1994  },
      { name: "Sadlok",        position: "DEF", overall: 70, apps: 25, goals: 6,  starting: true, "birthYear": 1989  },
      { name: "Mehremić",      position: "DEF", overall: 64, apps: 11, goals: 4,  starting: false, "birthYear": 1992 },
      { name: "Klemenz",       position: "DEF", overall: 62, apps: 4,  goals: 0,  starting: false, "birthYear": 1995 },
      { name: "Kone S.",       position: "DEF", overall: 62, apps: 7,  goals: 3,  starting: false, "birthYear": 1996 },
      { name: "Radaković",     position: "DEF", overall: 60, apps: 6,  goals: 1,  starting: false, "birthYear": 1994 },
      { name: "Szot",          position: "DEF", overall: 60, apps: 20, goals: 5,  starting: false, "birthYear": 2001 },

      { name: "Yeboah",        position: "MID", overall: 80, apps: 28, goals: 2,  starting: true, "birthYear": 1997  },
      { name: "Zhukov",        position: "MID", overall: 78, apps: 25, goals: 7,  starting: true, "birthYear": 1994  },
      { name: "Silva J.",      position: "MID", overall: 76, apps: 22, goals: 2,  starting: true, "birthYear": 1996  },
      { name: "Błaszczykowski",position: "MID", overall: 75, apps: 16, goals: 4,  starting: true, "birthYear": 1985  },
      { name: "Chuca",         position: "MID", overall: 66, apps: 13, goals: 3,  starting: false, "birthYear": 1997 },
      { name: "Mawutor",       position: "MID", overall: 60, apps: 7,  goals: 2,  starting: false, "birthYear": 1992 },
      { name: "Kuveljić",      position: "MID", overall: 60, apps: 12, goals: 2,  starting: false, "birthYear": 1997 },
      { name: "Boguski",       position: "MID", overall: 60, apps: 11, goals: 1,  starting: false, "birthYear": 1984 },

      { name: "Brown Forbes",  position: "FWD", overall: 76, apps: 22, goals: 7,  starting: true, "birthYear": 1991  },
      { name: "Buksa A.",      position: "FWD", overall: 64, apps: 13, goals: 1,  starting: true, "birthYear": 2003 },
      { name: "Medved",        position: "FWD", overall: 58, apps: 13, goals: 1,  starting: false, "birthYear": 1999 },
      { name: "Beqiraj",       position: "FWD", overall: 58, apps: 10, goals: 0,  starting: false, "birthYear": 1988 },
    ]
  },
{
    club: "Cracovia Kraków",
    season: "2020/21",
    "coaches": [{ "name": "Michał Probierz" }],
    players: [
      { name: "Niemczycki",    position: "GK",  overall: 78, apps: 27, goals: 0,  starting: true, "birthYear": 1999  },

      { name: "Rapa",          position: "DEF", overall: 82, apps: 30, goals: 2,  starting: true, "birthYear": 1990  },
      { name: "Rodin",         position: "DEF", overall: 78, apps: 23, goals: 4,  starting: true, "birthYear": 1996  },
      { name: "Szymonowicz",   position: "DEF", overall: 78, apps: 24, goals: 6,  starting: true, "birthYear": 1995  },
      { name: "Siplak",        position: "DEF", overall: 78, apps: 13, goals: 6,  starting: true, "birthYear": 1996  },
      { name: "Marquez I.",    position: "DEF", overall: 64, apps: 17, goals: 2,  starting: false, "birthYear": 1994 },
      { name: "Rocha",         position: "DEF", overall: 62, apps: 10, goals: 3,  starting: false, "birthYear": 1993 },
      { name: "Jablonsky",     position: "DEF", overall: 60, apps: 2,  goals: 1,  starting: false, "birthYear": 1991 },
      { name: "Ferraresso",    position: "DEF", overall: 58, apps: 8,  goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Gardawski",     position: "DEF", overall: 60, apps: 5,  goals: 2,  starting: false, "birthYear": 1990 },

      { name: "Hanca",         position: "MID", overall: 86, apps: 21, goals: 8,  starting: true, "birthYear": 1992  },
      { name: "van Amersfoort",position: "MID", overall: 80, apps: 28, goals: 6,  starting: true, "birthYear": 1996  },
      { name: "Thiago",        position: "MID", overall: 70, apps: 25, goals: 4,  starting: true, "birthYear": 1997  },
      { name: "Loshaj",        position: "MID", overall: 68, apps: 23, goals: 4,  starting: true, "birthYear": 1996  },
      { name: "Dimun",         position: "MID", overall: 66, apps: 23, goals: 3,  starting: false, "birthYear": 1996 },
      { name: "Fiolić",        position: "MID", overall: 66, apps: 19, goals: 2,  starting: false, "birthYear": 1996 },
      { name: "Sadiković",     position: "MID", overall: 64, apps: 20, goals: 2,  starting: false, "birthYear": 1995 },
      { name: "Kosecki",       position: "MID", overall: 60, apps: 8,  goals: 0,  starting: false, "birthYear": 1990 },
      { name: "Budziński",     position: "MID", overall: 58, apps: 2,  goals: 1,  starting: false, "birthYear": 1990 },
      { name: "Pik",           position: "MID", overall: 56, apps: 9,  goals: 1,  starting: false, "birthYear": 2000 },

      { name: "Alvarez M.",    position: "FWD", overall: 70, apps: 21, goals: 4,  starting: true, "birthYear": 1991  },
      { name: "Piszczek",      position: "FWD", overall: 66, apps: 22, goals: 4,  starting: true, "birthYear": 1995  },
      { name: "Vestenicky",    position: "FWD", overall: 60, apps: 11, goals: 2,  starting: false, "birthYear": 1996 },
      { name: "Rivaldinho",    position: "FWD", overall: 60, apps: 24, goals: 1,  starting: false, "birthYear": 1995 },
    ]
  },
{
    club: "Stal Mielec",
    season: "2020/21",
    "coaches": [{ "name": "Dariusz Skrzypczak" }, { "name": "Leszek Ojrzyński" }, { "name": "Włodzimierz Gąsior" }],
    players: [
      { name: "Strączek",      position: "GK",  overall: 86, apps: 25, goals: 0,  starting: true, "birthYear": 1999  },
      { name: "Gliwa",         position: "GK",  overall: 58, apps: 5,  goals: 0,  starting: false, "birthYear": 1988 },

      { name: "Flis",          position: "DEF", overall: 70, apps: 28, goals: 7,  starting: true, "birthYear": 1994  },
      { name: "Chorbadzhiyski",position: "DEF", overall: 70, apps: 20, goals: 6,  starting: true, "birthYear": 1995  },
      { name: "Getinger",      position: "DEF", overall: 86, apps: 29, goals: 6,  starting: true, "birthYear": 1988  },
      { name: "de Amo",        position: "DEF", overall: 74, apps: 12, goals: 4,  starting: true, "birthYear": 1990  },
      { name: "Granlund",      position: "DEF", overall: 60, apps: 12, goals: 2,  starting: false, "birthYear": 1989 },
      { name: "Żyro M.",       position: "DEF", overall: 62, apps: 20, goals: 6,  starting: false, "birthYear": 1998 },
      { name: "Sus",           position: "DEF", overall: 58, apps: 6,  goals: 0,  starting: false, "birthYear": 1990 },
      { name: "Kościelny",     position: "DEF", overall: 58, apps: 14, goals: 1,  starting: false, "birthYear": 1991 },

      { name: "Tomasiewicz",   position: "MID", overall: 80, apps: 29, goals: 6,  starting: true, "birthYear": 1996  },
      { name: "Domański",      position: "MID", overall: 80, apps: 30, goals: 6,  starting: true, "birthYear": 1990  },
      { name: "Matras",        position: "MID", overall: 78, apps: 27, goals: 5,  starting: true, "birthYear": 1991  },
      { name: "Forsell",       position: "MID", overall: 78, apps: 26, goals: 2,  starting: true, "birthYear": 1990  },
      { name: "Mak M.",        position: "MID", overall: 64, apps: 25, goals: 2,  starting: false, "birthYear": 1991 },
      { name: "Dadok",         position: "MID", overall: 74, apps: 24, goals: 4,  starting: false, "birthYear": 1996 },
      { name: "Prokić",        position: "MID", overall: 60, apps: 29, goals: 1,  starting: false, "birthYear": 1989 },
      { name: "Jankowski M.",  position: "MID", overall: 60, apps: 11, goals: 2,  starting: false, "birthYear": 1990 },
      { name: "Urbańczyk",     position: "MID", overall: 58, apps: 11, goals: 0,  starting: false, "birthYear": 1995 },
      { name: "Pawłowski D.",  position: "MID", overall: 56, apps: 7,  goals: 1,  starting: false, "birthYear": 1999 },

      { name: "Kolev",         position: "FWD", overall: 66, apps: 15, goals: 2,  starting: true, "birthYear": 1992  },
      { name: "Zjawiński",     position: "FWD", overall: 64, apps: 24, goals: 3,  starting: true, "birthYear": 2001 },
      { name: "Tomczyk",       position: "FWD", overall: 58, apps: 11, goals: 1,  starting: false, "birthYear": 1998 },
      { name: "Wróbel J.",     position: "FWD", overall: 56, apps: 8,  goals: 1,  starting: false, "birthYear": 1993 },
    ]
  },
{
    club: "Podbeskidzie Bielsko-Biała",
    season: "2020/21",
    "coaches": [{ "name": "Krzysztof Brede" }, { "name": "Hubert Kościukiewicz" }, { "name": "Robert Kasperczyk" }],
    players: [
      { name: "Pesković",      position: "GK",  overall: 66, apps: 22, goals: 0,  starting: true, "birthYear": 1982  },
      { name: "Polacek",       position: "GK",  overall: 56, apps: 5,  goals: 0,  starting: false, "birthYear": 1990 },
      { name: "Leszczyński R.",position: "GK",  overall: 56, apps: 3,  goals: 0,  starting: false, "birthYear": 1992 },

      { name: "Modelski",      position: "DEF", overall: 68, apps: 23, goals: 4,  starting: true, "birthYear": 1992  },
      { name: "Rundić",        position: "DEF", overall: 74, apps: 21, goals: 3,  starting: true, "birthYear": 1992  },
      { name: "Janicki R.",    position: "DEF", overall: 74, apps: 13, goals: 1,  starting: true, "birthYear": 1992  },
      { name: "Bashlai",       position: "DEF", overall: 62, apps: 15, goals: 3,  starting: true, "birthYear": 1990  },
      { name: "Komor",         position: "DEF", overall: 58, apps: 12, goals: 1,  starting: false, "birthYear": 1994 },
      { name: "Mamić",         position: "DEF", overall: 58, apps: 12, goals: 1,  starting: false, "birthYear": 1996 },
      { name: "Niepsuj",       position: "DEF", overall: 58, apps: 9,  goals: 1,  starting: false, "birthYear": 1995 },
      { name: "Gach",          position: "DEF", overall: 56, apps: 12, goals: 2,  starting: false, "birthYear": 1998 },
      { name: "Tulio",         position: "DEF", overall: 56, apps: 10, goals: 2,  starting: false, "birthYear": 1998 },

      { name: "Danielak",      position: "MID", overall: 64, apps: 26, goals: 3,  starting: true, "birthYear": 1991  },
      { name: "Ubbink",        position: "MID", overall: 62, apps: 16, goals: 1,  starting: true, "birthYear": 1993  },
      { name: "Rzuchowski",    position: "MID", overall: 62, apps: 26, goals: 3,  starting: true, "birthYear": 1993  },
      { name: "Kocsis",        position: "MID", overall: 62, apps: 19, goals: 3,  starting: false, "birthYear": 1994  },
      { name: "Miakushko",     position: "MID", overall: 60, apps: 15, goals: 2,  starting: false, "birthYear": 1993 },
      { name: "Hora",          position: "MID", overall: 60, apps: 16, goals: 3,  starting: false, "birthYear": 1991 },
      { name: "Figiel",        position: "MID", overall: 56, apps: 8,  goals: 1,  starting: false, "birthYear": 1991 },
      { name: "Sierpina",      position: "MID", overall: 66, apps: 22, goals: 1,  starting: true, "birthYear": 1988 },
      { name: "Sitek",         position: "MID", overall: 56, apps: 18, goals: 1,  starting: false, "birthYear": 2000 },

      { name: "Biliński",      position: "FWD", overall: 70, apps: 26, goals: 11, starting: true, "birthYear": 1988  },
      { name: "Roginić",       position: "FWD", overall: 62, apps: 22, goals: 6,  starting: true, "birthYear": 1995 },
      { name: "Martin Ivan",   position: "FWD", overall: 56, apps: 4,  goals: 2,  starting: false, "birthYear": 1995 },
      { name: "Wilson P.",     position: "FWD", overall: 56, apps: 13, goals: 0,  starting: false, "birthYear": 1996 },
    ]
  }
);
