// ============================================================
// SEZON 1993/94 — 17 klubów
// Część bazy TEAMS_DATA — każdy sezon w osobnym pliku.
// ============================================================

window.TEAMS_DATA = window.TEAMS_DATA || [];
window.TEAMS_DATA.push(
{
  club: "Stal Stalowa Wola",
  season: "1993/94",
    "coaches": [{ "name": "Włodzimierz Gąsior" }, { "name": "Piotr Brzeziński" }, { "name": "Adam Musiał" }],
  players: [
    { name: "Sejud",          position: "GK",  overall: 78, apps: 33, goals: 0,  starting: true, "birthYear": 1971  },
    { name: "Lis",            position: "GK",  overall: 60, apps: 1,  goals: 0,  starting: false, "birthYear": 1969 },

    { name: "Piotrowicz",     position: "DEF", overall: 75, apps: 29, goals: 1,  starting: true, "birthYear": 1963  },
    { name: "Wieprzęć",       position: "DEF", overall: 72, apps: 30, goals: 2,  starting: true, "birthYear": 1974  },
    { name: "Rybak",          position: "DEF", overall: 70, apps: 30, goals: 1,  starting: true, "birthYear": 1967  },
    { name: "Boruc",          position: "DEF", overall: 68, apps: 18, goals: 0,  starting: true, "birthYear": 1969  },
    { name: "Mścisz",         position: "DEF", overall: 65, apps: 12, goals: 0,  starting: false, "birthYear": 1973 },
    { name: "Pacoń",          position: "DEF", overall: 64, apps: 10, goals: 0,  starting: false, "birthYear": 1972 },
    { name: "Błaś",           position: "DEF", overall: 58, apps: 0,  goals: 0,  starting: false, "birthYear": 1973 },
    { name: "Kasiak",         position: "DEF", overall: 60, apps: 2,  goals: 0,  starting: false, "birthYear": 1971 },
    { name: "Michalak",       position: "DEF", overall: 55, apps: 0,  goals: 0,  starting: false, "birthYear": 1966 },

    { name: "Kawecki",        position: "MID", overall: 74, apps: 33, goals: 4,  starting: true, "birthYear": 1965  },
    { name: "Zgutczyński",    position: "MID", overall: 72, apps: 31, goals: 4,  starting: true, "birthYear": 1965  },
    { name: "Ożóg",           position: "MID", overall: 85, apps: 30, goals: 2,  starting: true, "birthYear": 1966  },
    { name: "Jurkowski",      position: "MID", overall: 69, apps: 26, goals: 1,  starting: true, "birthYear": 1970  },
    { name: "Góreczny",       position: "MID", overall: 68, apps: 23, goals: 0,  starting: false, "birthYear": 1972 },
    { name: "Szafran",        position: "MID", overall: 67, apps: 19, goals: 0,  starting: false, "birthYear": 1972 },
    { name: "Gawenda",        position: "MID", overall: 66, apps: 15, goals: 1,  starting: false, "birthYear": 1969 },
    { name: "Miszczak",       position: "MID", overall: 64, apps: 8,  goals: 0,  starting: false, "birthYear": 1968 },
    { name: "Nazimek",        position: "MID", overall: 60, apps: 1,  goals: 0,  starting: false, "birthYear": 1977 },
    { name: "Karasiński",     position: "MID", overall: 55, apps: 0,  goals: 0,  starting: false, "birthYear": 1973 },
    { name: "Krawiec",        position: "MID", overall: 55, apps: 0,  goals: 0,  starting: false, "birthYear": 1974 },

    { name: "Pikuta",         position: "FWD", overall: 75, apps: 15, goals: 5,  starting: true, "birthYear": 1972  },
    { name: "Zając",          position: "FWD", overall: 70, apps: 23, goals: 2,  starting: true, "birthYear": 1966  },
    { name: "Brytan",         position: "FWD", overall: 68, apps: 13, goals: 1,  starting: false, "birthYear": 1967 },
    { name: "Rubinkiewicz",   position: "FWD", overall: 66, apps: 11, goals: 1,  starting: false, "birthYear": 1971 },
    { name: "Sajdak",         position: "FWD", overall: 65, apps: 9,  goals: 0,  starting: false, "birthYear": 1967 },
    { name: "Siwucha",        position: "FWD", overall: 62, apps: 4,  goals: 0,  starting: false, "birthYear": 1969 },
    { name: "Ziarek",         position: "FWD", overall: 60, apps: 5,  goals: 0,  starting: false, "birthYear": 1974 },
    { name: "Karkut",         position: "FWD", overall: 58, apps: 1,  goals: 0,  starting: false, "birthYear": 1975 },
  ]
},
{
    club: "Zawisza Bydgoszcz",
    season: "1993/94",
    "coaches": [{ "name": "Bogusław Kaczmarek" }, { "name": "Dariusz Bednarek" }, { "name": "Romuald Szukiełowicz" }, { "name": "Dariusz Bednarek" }],
    players: [
      { name: "Matuszewski", position: "GK", overall: 66, apps: 29, goals: 0, starting: true, "birthYear": 1968 },
      { name: "Hilscher", position: "GK", overall: 60, apps: 2, goals: 0, starting: false, "birthYear": 1969 },
      { name: "Piechota", position: "GK", overall: 60, apps: 3, goals: 0, starting: false, "birthYear": 1974 },
      { name: "Arndt", position: "DEF", overall: 68, apps: 32, goals: 1, starting: true, "birthYear": 1964 },
      { name: "Wódkiewicz", position: "DEF", overall: 67, apps: 30, goals: 1, starting: true, "birthYear": 1971 },
      { name: "Rzepa", position: "DEF", overall: 65, apps: 32, goals: 0, starting: true, "birthYear": 1968 },
      { name: "Wesołowski", position: "DEF", overall: 65, apps: 21, goals: 0, starting: true, "birthYear": 1962 },
      { name: "Grzelak", position: "DEF", overall: 64, apps: 13, goals: 0, starting: false, "birthYear": 1973 },
      { name: "Mizia", position: "DEF", overall: 64, apps: 14, goals: 0, starting: false, "birthYear": 1965 },
      { name: "Szuflita", position: "DEF", overall: 73, apps: 20, goals: 0, starting: false, "birthYear": 1970 },
      { name: "Thiede", position: "DEF", overall: 58, apps: 2, goals: 0, starting: false, "birthYear": 1976 },
      { name: "Stefański", position: "MID", overall: 72, apps: 30, goals: 5, starting: true, "birthYear": 1968 },
      { name: "Wojciechowski", position: "MID", overall: 69, apps: 26, goals: 1, starting: true, "birthYear": 1973 },
      { name: "Kot", position: "MID", overall: 67, apps: 33, goals: 3, starting: true, "birthYear": 1968 },
      { name: "Durda", position: "MID", overall: 67, apps: 18, goals: 2, starting: true, "birthYear": 1966 },
      { name: "Kempa", position: "MID", overall: 66, apps: 29, goals: 2, starting: false, "birthYear": 1968 },
      { name: "Kołacki", position: "MID", overall: 62, apps: 4, goals: 0, starting: false, "birthYear": 1974 },
      { name: "Maleev", position: "MID", overall: 66, apps: 20, goals: 3, starting: false, "birthYear": 1968 },
      { name: "Pielesiak", position: "MID", overall: 58, apps: 1, goals: 0, starting: false, "birthYear": 1975 },
      { name: "Pawłuszek", position: "FWD", overall: 68, apps: 31, goals: 6, starting: true, "birthYear": 1970 },
      { name: "Drączkowski", position: "FWD", overall: 65, apps: 13, goals: 1, starting: false, "birthYear": 1970 },
      { name: "Stankiewicz", position: "FWD", overall: 65, apps: 12, goals: 2, starting: false, "birthYear": 1972 },
    ]
  },
{
    club: "Polonia Warszawa",
    season: "1993/94",
    "coaches": [{ "name": "Piotr Wiśnik" }, { "name": "Antoni Giedrys" }, { "name": "Stefan Majewski" }],
    players: [
      { name: "Onyszko", position: "GK", overall: 70, apps: 13, goals: 0, starting: true, "birthYear": 1974 },
      { name: "Rutkowski", position: "GK", overall: 65, apps: 16, goals: 0, starting: false, "birthYear": 1959 },
      { name: "Kwiatkowski", position: "GK", overall: 63, apps: 3, goals: 0, starting: false, "birthYear": 1966 },
      { name: "Rejent", position: "GK", overall: 62, apps: 2, goals: 0, starting: false, "birthYear": 1966 },
      { name: "Dankowski", position: "DEF", overall: 79, apps: 30, goals: 2, starting: true, "birthYear": 1960 },
      { name: "Kowalewski", position: "DEF", overall: 67, apps: 29, goals: 5, starting: true, "birthYear": 1967 },
      { name: "Filaber", position: "DEF", overall: 65, apps: 26, goals: 0, starting: true, "birthYear": 1964 },
      { name: "Wójtowicz", position: "DEF", overall: 81, apps: 13, goals: 1, starting: true, "birthYear": 1965 },
      { name: "Gałuszka", position: "DEF", overall: 74, apps: 17, goals: 0, starting: false, "birthYear": 1964 },
      { name: "Tietz", position: "DEF", overall: 64, apps: 20, goals: 0, starting: false, "birthYear": 1964 },
      { name: "Żewłakow M.", position: "DEF", overall: 72, apps: 11, goals: 0, starting: false, "birthYear": 1976 },
      { name: "Dźwigała", position: "MID", overall: 68, apps: 31, goals: 5, starting: true, "birthYear": 1969 },
      { name: "Lesiak", position: "MID", overall: 67, apps: 32, goals: 5, starting: true, "birthYear": 1968 },
      { name: "Rowicki", position: "MID", overall: 66, apps: 30, goals: 2, starting: true, "birthYear": 1970 },
      { name: "Kacprzak", position: "MID", overall: 65, apps: 22, goals: 2, starting: true, "birthYear": 1970 },
      { name: "Jagoda", position: "MID", overall: 74, apps: 11, goals: 0, starting: false, "birthYear": 1962 },
      { name: "Stromecki", position: "MID", overall: 63, apps: 11, goals: 0, starting: false, "birthYear": 1970 },
      { name: "Rocki", position: "MID", overall: 75, apps: 15, goals: 1, starting: false, "birthYear": 1974 },
      { name: "Łatka", position: "FWD", overall: 66, apps: 16, goals: 1, starting: true, "birthYear": 1962 },
      { name: "Sawa", position: "FWD", overall: 65, apps: 23, goals: 1, starting: true, "birthYear": 1975 },
      { name: "Kopeć", position: "FWD", overall: 65, apps: 16, goals: 2, starting: false, "birthYear": 1965 },
      { name: "Kobzev", position: "FWD", overall: 68, apps: 12, goals: 1, starting: false, "birthYear": 1959 },
    ]
  },
{
    club: "Siarka Tarnobrzeg",
    season: "1993/94",
    "coaches": [{ "name": "Janusz Gałek" }, { "name": "Roman Dębiński" }, { "name": "Janusz Gałek" }, { "name": "Włodzimierz Gąsior" }],
    players: [
      { name: "Paciorkowski", position: "GK", overall: 67, apps: 20, goals: 0, starting: true, "birthYear": 1968 },
      { name: "Pawlak", position: "GK", overall: 65, apps: 14, goals: 0, starting: false, "birthYear": 1970 },
      { name: "Janowski", position: "GK", overall: 60, apps: 0, goals: 0, starting: false, "birthYear": 1976 },
      { name: "Tyburski", position: "DEF", overall: 68, apps: 33, goals: 5, starting: true, "birthYear": 1960 },
      { name: "Wilczok", position: "DEF", overall: 67, apps: 28, goals: 0, starting: true, "birthYear": 1969 },
      { name: "Adamus", position: "DEF", overall: 66, apps: 24, goals: 0, starting: true, "birthYear": 1971 },
      { name: "Porębny", position: "DEF", overall: 65, apps: 22, goals: 0, starting: true, "birthYear": 1963 },
      { name: "Kiełbowicz", position: "DEF", overall: 84, apps: 20, goals: 1, starting: false, "birthYear": 1976 },
      { name: "Żuchnik", position: "DEF", overall: 75, apps: 14, goals: 0, starting: false, "birthYear": 1965 },
      { name: "Boguszewski", position: "DEF", overall: 65, apps: 7, goals: 0, starting: false, "birthYear": 1963 },
      { name: "Stefanik", position: "MID", overall: 70, apps: 19, goals: 4, starting: true, "birthYear": 1964 },
      { name: "Nieradka", position: "MID", overall: 67, apps: 24, goals: 0, starting: true, "birthYear": 1964 },
      { name: "Woźniak", position: "MID", overall: 66, apps: 18, goals: 3, starting: true, "birthYear": 1968 },
      { name: "Kukiełka", position: "MID", overall: 85, apps: 20, goals: 1, starting: true, "birthYear": 1976 },
      { name: "Berensztajn", position: "MID", overall: 78, apps: 14, goals: 1, starting: false, "birthYear": 1973 },
      { name: "Wójtowicz", position: "MID", overall: 65, apps: 10, goals: 0, starting: false, "birthYear": 1966 },
      { name: "Kucharski", position: "FWD", overall: 85, apps: 17, goals: 6, starting: true, "birthYear": 1972 },
      { name: "Ząbek", position: "FWD", overall: 66, apps: 26, goals: 0, starting: true, "birthYear": 1969 },
      { name: "Białek", position: "FWD", overall: 65, apps: 23, goals: 2, starting: false, "birthYear": 1973 },
      { name: "Przypkowski", position: "FWD", overall: 64, apps: 17, goals: 0, starting: false, "birthYear": 1975 },
    ]
  },
{
  club: "Warta Poznań",
  season: "1993/94",
    "coaches": [{ "name": "Eugeniusz Samolczyk" }, { "name": "Tadeusz Łuczak" }],
  players: [
    { name: "Pleśnierowicz",    position: "GK",  overall: 72, apps: 31, goals: 0,  starting: true, "birthYear": 1958  },
    { name: "Zajda",           position: "GK",  overall: 65, apps: 3,  goals: 0,  starting: false, "birthYear": 1963 },
    { name: "Zabiyakin",       position: "GK",  overall: 60, apps: 0,  goals: 0,  starting: false, "birthYear": 1968 },

    { name: "Jakołcewicz",     position: "DEF", overall: 84, apps: 28, goals: 1,  starting: true, "birthYear": 1961  },
    { name: "Niewiadomski",    position: "DEF", overall: 71, apps: 31, goals: 2,  starting: true, "birthYear": 1959  },
    { name: "Gajewski",        position: "DEF", overall: 70, apps: 31, goals: 1,  starting: true, "birthYear": 1969  },
    { name: "Owca",            position: "DEF", overall: 79, apps: 30, goals: 4,  starting: true, "birthYear": 1967  },
    { name: "Sidorski",        position: "DEF", overall: 68, apps: 31, goals: 2,  starting: false, "birthYear": 1967 },
    { name: "Pawlak",          position: "DEF", overall: 75, apps: 18, goals: 0,  starting: false, "birthYear": 1958 }, // Gwiazda defensywy
    { name: "Tomaszczak",      position: "DEF", overall: 62, apps: 8,  goals: 0,  starting: false, "birthYear": 1975 },
    { name: "Sytch",           position: "DEF", overall: 60, apps: 4,  goals: 0,  starting: false, "birthYear": 1971 },
    { name: "Konkiewicz",      position: "DEF", overall: 55, apps: 0,  goals: 0,  starting: false, "birthYear": 1973 },
    { name: "Żurawski",        position: "DEF", overall: 55, apps: 0,  goals: 0,  starting: false, "birthYear": 1976 },

    { name: "Iwan T.",         position: "MID", overall: 91, apps: 31, goals: 7,  starting: true, "birthYear": 1971  }, // Gwiazda zespołu
    { name: "Pawelec",         position: "MID", overall: 70, apps: 31, goals: 0,  starting: true, "birthYear": 1968  },
    { name: "Łapczyński",      position: "MID", overall: 69, apps: 28, goals: 1,  starting: true, "birthYear": 1967  },
    { name: "Kiłdanowicz",     position: "MID", overall: 68, apps: 18, goals: 2,  starting: true, "birthYear": 1969  },
    { name: "Rybarczyk",       position: "MID", overall: 66, apps: 17, goals: 0,  starting: false, "birthYear": 1974 },
    { name: "Frydryszak",      position: "MID", overall: 65, apps: 15, goals: 1,  starting: false, "birthYear": 1969 },
    { name: "Tęsiorowski",     position: "MID", overall: 65, apps: 16, goals: 0,  starting: false, "birthYear": 1962 },
    { name: "Misztur",         position: "MID", overall: 64, apps: 9,  goals: 0,  starting: false, "birthYear": 1965 },
    { name: "Miklosik",        position: "MID", overall: 62, apps: 5,  goals: 0,  starting: false, "birthYear": 1975 },
    { name: "Kucharczyk",      position: "MID", overall: 60, apps: 0,  goals: 0,  starting: false, "birthYear": 1968 },

    { name: "Prabucki",        position: "FWD", overall: 76, apps: 33, goals: 11, starting: true, "birthYear": 1968  },
    { name: "Iwan M.",         position: "FWD", overall: 66, apps: 11, goals: 0,  starting: true, "birthYear": 1968 },
    { name: "Tierling",        position: "FWD", overall: 60, apps: 3,  goals: 0,  starting: false, "birthYear": 1975 },
    { name: "Wilczyński",      position: "FWD", overall: 58, apps: 0,  goals: 0,  starting: false, "birthYear": 1974 },
  ]
},
{
    club: "Wisła Kraków",
    season: "1993/94",
    "coaches": [{ "name": "Marek Kusto" }, { "name": "Orest Lenczyk" }],
    players: [
      { name: "Sarnat", position: "GK", overall: 69, apps: 16, goals: 0, starting: true, "birthYear": 1970 },
      { name: "Szymaszek", position: "GK", overall: 68, apps: 18, goals: 0, starting: false, "birthYear": 1973 },
      { name: "Mucharski", position: "GK", overall: 65, apps: 0, goals: 0, starting: false, "birthYear": 1970 },
      { name: "Matyja", position: "DEF", overall: 70, apps: 32, goals: 1, starting: true, "birthYear": 1970 },
      { name: "Gorszkow", position: "DEF", overall: 69, apps: 31, goals: 0, starting: true, "birthYear": 1974 },
      { name: "Włodarz", position: "DEF", overall: 68, apps: 29, goals: 1, starting: true, "birthYear": 1965 },
      { name: "Kaliciak", position: "DEF", overall: 77, apps: 30, goals: 0, starting: true, "birthYear": 1975 },
      { name: "Jamróz", position: "DEF", overall: 67, apps: 20, goals: 3, starting: false, "birthYear": 1973 },
      { name: "Giszka", position: "DEF", overall: 66, apps: 24, goals: 0, starting: false, "birthYear": 1965 },
      { name: "Marzec", position: "MID", overall: 71, apps: 24, goals: 2, starting: true, "birthYear": 1969 },
      { name: "Kupidura", position: "MID", overall: 69, apps: 27, goals: 4, starting: true, "birthYear": 1974 },
      { name: "Kozak", position: "MID", overall: 68, apps: 27, goals: 1, starting: true, "birthYear": 1966 },
      { name: "Moskal", position: "MID", overall: 81, apps: 22, goals: 1, starting: true, "birthYear": 1974 },
      { name: "Lament", position: "MID", overall: 66, apps: 22, goals: 0, starting: false, "birthYear": 1971 },
      { name: "Krupa", position: "MID", overall: 65, apps: 15, goals: 0, starting: false, "birthYear": 1975 },
      { name: "Szeliga", position: "FWD", overall: 69, apps: 31, goals: 8, starting: true, "birthYear": 1968 },
      { name: "Kulawik", position: "FWD", overall: 80, apps: 28, goals: 2, starting: true, "birthYear": 1969 },
      { name: "Lewandowski", position: "FWD", overall: 83, apps: 14, goals: 7, starting: false, "birthYear": 1969 },
    ]
  },
{
    "club": "Sokół Pniewy",
    "season": "1993/94",
    "coaches": [{ "name": "Wojciech Wąsikiewicz" }, { "name": "Adam Topolski" }, { "name": "Krzysztof Pawlak" }],
    "players": [
      { "name": "Płaczkiewicz", "position": "GK", "overall": 83, "apps": 29, "goals": 0, "starting": true, "birthYear": 1962 },
      { "name": "Sidorczuk", "position": "GK", "overall": 70, "apps": 5, "goals": 0, "starting": false, "birthYear": 1967 },
      { "name": "Konieczko", "position": "DEF", "overall": 72, "apps": 32, "goals": 2, "starting": true, "birthYear": 1964 },
      { "name": "Mapeza", "position": "DEF", "overall": 89, "apps": 26, "goals": 0, "starting": true, "birthYear": 1972 },
      { "name": "Rząsa", "position": "DEF", "overall": 86, "apps": 27, "goals": 6, "starting": true, "birthYear": 1973 },
      { "name": "Kisiel", "position": "DEF", "overall": 68, "apps": 21, "goals": 0, "starting": true, "birthYear": 1969 },
      { "name": "Owczarek", "position": "DEF", "overall": 66, "apps": 14, "goals": 0, "starting": false, "birthYear": 1969 },
      { "name": "Cejrowski", "position": "DEF", "overall": 65, "apps": 12, "goals": 0, "starting": false, "birthYear": 1967 },
      { "name": "Wilk", "position": "MID", "overall": 72, "apps": 30, "goals": 2, "starting": true, "birthYear": 1969 },
      { "name": "Przerada", "position": "MID", "overall": 78, "apps": 25, "goals": 0, "starting": true, "birthYear": 1968 },
      { "name": "Kasperski", "position": "MID", "overall": 78, "apps": 25, "goals": 2, "starting": true, "birthYear": 1972 },
      { "name": "Phiri", "position": "MID", "overall": 69, "apps": 24, "goals": 0, "starting": true, "birthYear": 1962 },
      { "name": "Dyluś", "position": "MID", "overall": 83, "apps": 24, "goals": 3, "starting": true, "birthYear": 1964 },
      { "name": "Nowak", "position": "MID", "overall": 71, "apps": 21, "goals": 0, "starting": false, "birthYear": 1975 },
      { "name": "Janiak", "position": "MID", "overall": 68, "apps": 12, "goals": 3, "starting": false, "birthYear": 1973 },
      { "name": "Kurzeja", "position": "MID", "overall": 65, "apps": 12, "goals": 1, "starting": false, "birthYear": 1969 },
      { "name": "Burzawa", "position": "FWD", "overall": 95, "apps": 33, "goals": 21, "starting": true, "birthYear": 1961 }, // Król Strzelców
      { "name": "Tyszkiewicz", "position": "FWD", "overall": 70, "apps": 16, "goals": 0, "starting": false, "birthYear": 1970 },
    ]
  },
{
    "club": "Stal Mielec",
    "season": "1993/94",
    "coaches": [{ "name": "Witold Karaś" }, { "name": "Franciszek Smuda" }],
    "players": [
      { "name": "Wyparło", "position": "GK", "overall": 82, "apps": 34, "goals": 0, "starting": true, "birthYear": 1974 },
      { "name": "Bartkowski", "position": "DEF", "overall": 72, "apps": 31, "goals": 0, "starting": true, "birthYear": 1968 },
      { "name": "Tereshchenko", "position": "DEF", "overall": 71, "apps": 32, "goals": 0, "starting": true, "birthYear": 1963 },
      { "name": "Federkiewicz", "position": "DEF", "overall": 73, "apps": 26, "goals": 4, "starting": true, "birthYear": 1964 },
      { "name": "Łętocha", "position": "DEF", "overall": 70, "apps": 26, "goals": 0, "starting": true, "birthYear": 1964 },
      { "name": "Tomanek", "position": "DEF", "overall": 68, "apps": 20, "goals": 1, "starting": false, "birthYear": 1968 },
      { "name": "Tułacz", "position": "DEF", "overall": 79, "apps": 27, "goals": 1, "starting": false, "birthYear": 1969 },
      { "name": "Ruta", "position": "MID", "overall": 73, "apps": 32, "goals": 4, "starting": true, "birthYear": 1972 },
      { "name": "Barnak", "position": "MID", "overall": 71, "apps": 30, "goals": 2, "starting": true, "birthYear": 1964 },
      { "name": "Kukowski", "position": "MID", "overall": 70, "apps": 27, "goals": 1, "starting": true, "birthYear": 1969 },
      { "name": "Curzytek", "position": "MID", "overall": 67, "apps": 16, "goals": 3, "starting": true, "birthYear": 1973 },
      { "name": "Kloc", "position": "MID", "overall": 69, "apps": 16, "goals": 3, "starting": false, "birthYear": 1970 },
      { "name": "Spivak", "position": "MID", "overall": 68, "apps": 16, "goals": 0, "starting": false, "birthYear": 1975 },
      { "name": "Drożdż", "position": "MID", "overall": 64, "apps": 10, "goals": 0, "starting": false, "birthYear": 1963 },
      { "name": "Czyrek", "position": "FWD", "overall": 74, "apps": 32, "goals": 3, "starting": true, "birthYear": 1966 },
      { "name": "Bociek", "position": "FWD", "overall": 72, "apps": 25, "goals": 2, "starting": true, "birthYear": 1974 },
      { "name": "Cygan", "position": "FWD", "overall": 89, "apps": 17, "goals": 7, "starting": false, "birthYear": 1964 }, // Gwiazda ataku wiosną
      { "name": "Pilawiecki", "position": "FWD", "overall": 65, "apps": 10, "goals": 0, "starting": false, "birthYear": 1972 },
    ]
  },
{
    "club": "Lech Poznań",
    "season": "1993/94",
    "coaches": [{ "name": "Roman Jakóbczak" }, { "name": "Jan Stępczak" }],
    "players": [
      { "name": "Przybylski", "position": "GK", "overall": 72, "apps": 22, "goals": 0, "starting": true, "birthYear": 1969 },
      { "name": "Bako", "position": "GK", "overall": 81, "apps": 11, "goals": 0, "starting": false, "birthYear": 1964 },
      { "name": "Kryger", "position": "DEF", "overall": 75, "apps": 32, "goals": 2, "starting": true, "birthYear": 1968 },
      { "name": "Rzepka", "position": "DEF", "overall": 84, "apps": 31, "goals": 0, "starting": true, "birthYear": 1964 },
      { "name": "Bąk", "position": "DEF", "overall": 82, "apps": 29, "goals": 1, "starting": true, "birthYear": 1973 },
      { "name": "Wojtala", "position": "DEF", "overall": 73, "apps": 22, "goals": 1, "starting": true, "birthYear": 1972 },
      { "name": "Bereszyński", "position": "DEF", "overall": 70, "apps": 23, "goals": 0, "starting": false, "birthYear": 1969 },
      { "name": "Łukasik", "position": "DEF", "overall": 78, "apps": 14, "goals": 0, "starting": false, "birthYear": 1964 },
      { "name": "Moskal", "position": "MID", "overall": 83, "apps": 30, "goals": 2, "starting": true, "birthYear": 1967 },
      { "name": "Skrzypczak", "position": "MID", "overall": 87, "apps": 30, "goals": 8, "starting": true, "birthYear": 1967 },
      { "name": "Remień", "position": "MID", "overall": 72, "apps": 27, "goals": 2, "starting": true, "birthYear": 1968 },
      { "name": "Piskuła", "position": "MID", "overall": 70, "apps": 21, "goals": 2, "starting": true, "birthYear": 1973 },
      { "name": "Podbrożny", "position": "MID", "overall": 81, "apps": 17, "goals": 3, "starting": false, "birthYear": 1966 }, // Odszedł w styczniu
      { "name": "Kofnyt", "position": "MID", "overall": 67, "apps": 14, "goals": 0, "starting": false, "birthYear": 1964 },
      { "name": "Dembiński", "position": "FWD", "overall": 86, "apps": 34, "goals": 12, "starting": true, "birthYear": 1969 },
      { "name": "Wichniarek", "position": "FWD", "overall": 68, "apps": 17, "goals": 0, "starting": true, "birthYear": 1977 },
      { "name": "Trzeciak", "position": "FWD", "overall": 77, "apps": 17, "goals": 3, "starting": false, "birthYear": 1968 },
      { "name": "Przysiuda", "position": "FWD", "overall": 69, "apps": 13, "goals": 2, "starting": false, "birthYear": 1973 },
    ]
  },
{
    "club": "Hutnik Kraków",
    "season": "1993/94",
    "coaches": [{ "name": "Piotr Kocąb" }],
    "players": [
      { "name": "Shipovskiy", "position": "GK", "overall": 79, "apps": 29, "goals": 0, "starting": true, "birthYear": 1965 },
      { "name": "Tyrpa", "position": "GK", "overall": 65, "apps": 5, "goals": 0, "starting": false, "birthYear": 1965 },
      { "name": "Walankiewicz", "position": "DEF", "overall": 82, "apps": 32, "goals": 1, "starting": true, "birthYear": 1959 },
      { "name": "Fudali", "position": "DEF", "overall": 70, "apps": 29, "goals": 0, "starting": true, "birthYear": 1971 },
      { "name": "Romuzga", "position": "DEF", "overall": 81, "apps": 26, "goals": 0, "starting": true, "birthYear": 1971 },
      { "name": "Wojnecki", "position": "DEF", "overall": 68, "apps": 14, "goals": 0, "starting": true, "birthYear": 1975 },
      { "name": "Ziółkowski", "position": "DEF", "overall": 64, "apps": 8, "goals": 0, "starting": false, "birthYear": 1976 },
      { "name": "Bukalski", "position": "MID", "overall": 92, "apps": 33, "goals": 6, "starting": true, "birthYear": 1970 },
      { "name": "Kowalik", "position": "MID", "overall": 73, "apps": 32, "goals": 0, "starting": true, "birthYear": 1961 },
      { "name": "Kraczkiewicz", "position": "MID", "overall": 83, "apps": 32, "goals": 2, "starting": true, "birthYear": 1966 },
      { "name": "Sydorenko", "position": "MID", "overall": 71, "apps": 29, "goals": 1, "starting": true, "birthYear": 1972 },
      { "name": "Krupa G.", "position": "MID", "overall": 69, "apps": 25, "goals": 1, "starting": false, "birthYear": 1974 },
      { "name": "Krzywda", "position": "MID", "overall": 66, "apps": 8, "goals": 0, "starting": false, "birthYear": 1974 },
      { "name": "Waligóra", "position": "FWD", "overall": 86, "apps": 34, "goals": 13, "starting": true, "birthYear": 1970 },
      { "name": "Sermak", "position": "FWD", "overall": 83, "apps": 28, "goals": 4, "starting": true, "birthYear": 1962 },
      { "name": "Zięba", "position": "FWD", "overall": 71, "apps": 25, "goals": 2, "starting": false, "birthYear": 1969 },
      { "name": "Popczyński", "position": "FWD", "overall": 69, "apps": 17, "goals": 0, "starting": false, "birthYear": 1969 },
      { "name": "Adamczyk", "position": "FWD", "overall": 68, "apps": 13, "goals": 2, "starting": false, "birthYear": 1969 },
    ]
  },
{
    "club": "Ruch Chorzów",
    "season": "1993/94",
    "coaches": [{ "name": "Edward Lorens" }, { "name": "Albin Wira" }],
    "players": [
      { "name": "Lech", "position": "GK", "overall": 80, "apps": 19, "goals": 0, "starting": true, "birthYear": 1968 },
      { "name": "Kołodziejczyk", "position": "GK", "overall": 71, "apps": 16, "goals": 0, "starting": false, "birthYear": 1965 },
      { "name": "Bednarz", "position": "DEF", "overall": 85, "apps": 32, "goals": 4, "starting": true, "birthYear": 1967 },
      { "name": "Jaworski", "position": "DEF", "overall": 84, "apps": 32, "goals": 5, "starting": true, "birthYear": 1965 },
      { "name": "Wagner", "position": "DEF", "overall": 73, "apps": 32, "goals": 3, "starting": true, "birthYear": 1966 },
      { "name": "Mosór P.", "position": "DEF", "overall": 72, "apps": 31, "goals": 1, "starting": true, "birthYear": 1974 },
      { "name": "Fornalak", "position": "DEF", "overall": 71, "apps": 22, "goals": 3, "starting": false, "birthYear": 1965 },
      { "name": "Jendryczko", "position": "DEF", "overall": 67, "apps": 16, "goals": 0, "starting": false, "birthYear": 1973 },
      { "name": "Fornalik", "position": "DEF", "overall": 69, "apps": 15, "goals": 0, "starting": false, "birthYear": 1963 },
      { "name": "Dąbrowski", "position": "MID", "overall": 76, "apps": 31, "goals": 10, "starting": true, "birthYear": 1972 },
      { "name": "Gęsior", "position": "MID", "overall": 82, "apps": 28, "goals": 5, "starting": true, "birthYear": 1969 },
      { "name": "Kryger A.", "position": "MID", "overall": 71, "apps": 23, "goals": 0, "starting": true, "birthYear": 1969 },
      { "name": "Probierz", "position": "MID", "overall": 77, "apps": 15, "goals": 0, "starting": true, "birthYear": 1972 }, // Odszedł w styczniu
      { "name": "Mosór M.", "position": "MID", "overall": 68, "apps": 13, "goals": 2, "starting": false, "birthYear": 1968 },
      { "name": "Paluch", "position": "MID", "overall": 66, "apps": 9, "goals": 0, "starting": false, "birthYear": 1975 },
      { "name": "Śrutwa", "position": "FWD", "overall": 84, "apps": 31, "goals": 10, "starting": true, "birthYear": 1971 },
      { "name": "Posiłek", "position": "FWD", "overall": 68, "apps": 16, "goals": 1, "starting": false, "birthYear": 1973 },
      { "name": "Baucz", "position": "FWD", "overall": 65, "apps": 8, "goals": 1, "starting": false, "birthYear": 1974 },
    ]
  },
{
    "club": "Widzew Łódź",
    "season": "1993/94",
    "coaches": [{ "name": "Marek Woziński" }, { "name": "Władysław Stachurski" }],
    "players": [
      { "name": "Muchiński", "position": "GK", "overall": 72, "apps": 20, "goals": 0, "starting": true, "birthYear": 1966 },
      { "name": "Wojdyga", "position": "GK", "overall": 71, "apps": 11, "goals": 0, "starting": false, "birthYear": 1962 },
      { "name": "Bajor", "position": "DEF", "overall": 74, "apps": 30, "goals": 3, "starting": true, "birthYear": 1970 },
      { "name": "Łapiński", "position": "DEF", "overall": 95, "apps": 29, "goals": 1, "starting": true, "birthYear": 1969 }, // Gwiazda obrony
      { "name": "Boguś", "position": "DEF", "overall": 70, "apps": 19, "goals": 0, "starting": true, "birthYear": 1973 },
      { "name": "Bogusz", "position": "DEF", "overall": 81, "apps": 14, "goals": 0, "starting": false, "birthYear": 1974 },
      { "name": "Myśliński", "position": "DEF", "overall": 69, "apps": 13, "goals": 2, "starting": false, "birthYear": 1963 },
      { "name": "Czerwiec", "position": "MID", "overall": 87, "apps": 33, "goals": 6, "starting": true, "birthYear": 1968 },
      { "name": "Szarpak", "position": "MID", "overall": 82, "apps": 30, "goals": 3, "starting": true, "birthYear": 1971 },
      { "name": "Wyciszkiewicz", "position": "MID", "overall": 79, "apps": 29, "goals": 4, "starting": true, "birthYear": 1969 },
      { "name": "Mykhalchuk", "position": "MID", "overall": 74, "apps": 34, "goals": 3, "starting": true, "birthYear": 1967 },
      { "name": "Gula", "position": "MID", "overall": 71, "apps": 25, "goals": 1, "starting": true, "birthYear": 1972 },
      { "name": "Miąszkiewicz", "position": "MID", "overall": 70, "apps": 20, "goals": 0, "starting": false, "birthYear": 1971 },
      { "name": "Szulc", "position": "MID", "overall": 68, "apps": 13, "goals": 0, "starting": false, "birthYear": 1967 },
      { "name": "Cisek", "position": "MID", "overall": 78, "apps": 13, "goals": 2, "starting": false, "birthYear": 1963 },
      { "name": "Jóźwiak", "position": "FWD", "overall": 73, "apps": 27, "goals": 5, "starting": true, "birthYear": 1970 },
      { "name": "Małocha", "position": "FWD", "overall": 71, "apps": 17, "goals": 2, "starting": true, "birthYear": 1973 },
      { "name": "Koniarek", "position": "FWD", "overall": 84, "apps": 17, "goals": 7, "starting": false, "birthYear": 1962 },// Odszedł w styczniu
    ]
  },
{
    "club": "Pogoń Szczecin",
    "season": "1993/94",
    "coaches": [{ "name": "Romuald Szukiełowicz" }, { "name": "Jerzy Kasalik" }],
    "players": [
      { "name": "Majdan", "position": "GK", "overall": 88, "apps": 33, "goals": 0, "starting": true, "birthYear": 1972 },
      { "name": "Jaskulski", "position": "DEF", "overall": 87, "apps": 31, "goals": 2, "starting": true, "birthYear": 1967 },
      { "name": "Studziński", "position": "DEF", "overall": 72, "apps": 30, "goals": 1, "starting": true, "birthYear": 1966 },
      { "name": "Stolarczyk", "position": "DEF", "overall": 72, "apps": 30, "goals": 1, "starting": true, "birthYear": 1972 },
      { "name": "Miązek", "position": "DEF", "overall": 71, "apps": 29, "goals": 0, "starting": true, "birthYear": 1964 },
      { "name": "Pokładowski", "position": "DEF", "overall": 66, "apps": 15, "goals": 0, "starting": false, "birthYear": 1974 },
      { "name": "Kuras", "position": "MID", "overall": 74, "apps": 33, "goals": 0, "starting": true, "birthYear": 1965 },
      { "name": "Nikitin", "position": "MID", "overall": 72, "apps": 31, "goals": 1, "starting": true, "birthYear": 1968 },
      { "name": "Szubert", "position": "MID", "overall": 83, "apps": 23, "goals": 4, "starting": true, "birthYear": 1970 },
      { "name": "Latała", "position": "MID", "overall": 68, "apps": 16, "goals": 0, "starting": false, "birthYear": 1965 },
      { "name": "Wójtowicz", "position": "MID", "overall": 69, "apps": 11, "goals": 0, "starting": false, "birthYear": 1965 },
      { "name": "Oleszek", "position": "MID", "overall": 65, "apps": 8, "goals": 0, "starting": false, "birthYear": 1970 },
      { "name": "Mandrysz", "position": "MID", "overall": 77, "apps": 33, "goals": 10, "starting": true, "birthYear": 1962 }, // Kluczowy reżyser gry
      { "name": "Dymkowski", "position": "FWD", "overall": 86, "apps": 31, "goals": 10, "starting": true, "birthYear": 1970 },
      { "name": "Moskalewicz", "position": "FWD", "overall": 85, "apps": 33, "goals": 9, "starting": true, "birthYear": 1974 },
      { "name": "Bugaj", "position": "FWD", "overall": 69, "apps": 19, "goals": 1, "starting": false, "birthYear": 1970 },
    ]
  },
{
    "club": "ŁKS Łódź",
    "season": "1993/94",
    "coaches": [{ "name": "Ryszard Polak" }],
    "players": [
      { "name": "Woźniak", "position": "GK", "overall": 77, "apps": 34, "goals": 0, "starting": true, "birthYear": 1965 },
      { "name": "Leszczyński", "position": "DEF", "overall": 74, "apps": 34, "goals": 4, "starting": true, "birthYear": 1969 },
      { "name": "Bendkowski", "position": "DEF", "overall": 73, "apps": 31, "goals": 0, "starting": true, "birthYear": 1961 },
      { "name": "Chojnacki M.", "position": "DEF", "overall": 83, "apps": 31, "goals": 1, "starting": true, "birthYear": 1959 },
      { "name": "Lenart", "position": "DEF", "overall": 82, "apps": 31, "goals": 1, "starting": true, "birthYear": 1969 },
      { "name": "Krysiak", "position": "DEF", "overall": 81, "apps": 27, "goals": 3, "starting": false, "birthYear": 1969 },
      { "name": "Kościuk", "position": "DEF", "overall": 66, "apps": 11, "goals": 0, "starting": false, "birthYear": 1974 },
      { "name": "Podolski", "position": "MID", "overall": 86, "apps": 34, "goals": 10, "starting": true, "birthYear": 1966 },
      { "name": "Pawlak", "position": "MID", "overall": 73, "apps": 33, "goals": 2, "starting": true, "birthYear": 1970 },
      { "name": "Ambrożej", "position": "MID", "overall": 73, "apps": 29, "goals": 4, "starting": true, "birthYear": 1965 },
      { "name": "Wieszczycki", "position": "MID", "overall": 94, "apps": 28, "goals": 9, "starting": true, "birthYear": 1971 }, // Lider środka pola
      { "name": "Dziedzic", "position": "MID", "overall": 70, "apps": 19, "goals": 0, "starting": false, "birthYear": 1970 },
      { "name": "Nowacki", "position": "MID", "overall": 69, "apps": 16, "goals": 0, "starting": false, "birthYear": 1965 },
      { "name": "Kaczówka", "position": "MID", "overall": 80, "apps": 13, "goals": 4, "starting": false, "birthYear": 1965 },
      { "name": "Płuciennik", "position": "FWD", "overall": 80, "apps": 31, "goals": 7, "starting": true, "birthYear": 1970 },
      { "name": "Cebula", "position": "FWD", "overall": 72, "apps": 19, "goals": 1, "starting": true, "birthYear": 1966 },
      { "name": "Gałaj", "position": "FWD", "overall": 67, "apps": 9, "goals": 2, "starting": false, "birthYear": 1968 },
    ]
  },
{
    "club": "Górnik Zabrze",
    "season": "1993/94",
    "coaches": [{ "name": "Henryk Apostel" }, { "name": "Hubert Kostka" }, { "name": "Edward Lorens" }],
    "players": [
      { "name": "Kłak", "position": "GK", "overall": 75, "apps": 20, "goals": 0, "starting": true, "birthYear": 1970 },
      { "name": "Bęben", "position": "GK", "overall": 73, "apps": 15, "goals": 0, "starting": false, "birthYear": 1958 },
      { "name": "Wałdoch", "position": "DEF", "overall": 92, "apps": 33, "goals": 2, "starting": true, "birthYear": 1971 }, // Przyszły kapitan reprezentacji
      { "name": "Grembocki", "position": "DEF", "overall": 78, "apps": 29, "goals": 4, "starting": true, "birthYear": 1965 },
      { "name": "Staniek M.", "position": "DEF", "overall": 72, "apps": 25, "goals": 1, "starting": true, "birthYear": 1968 },
      { "name": "Jegor", "position": "DEF", "overall": 86, "apps": 24, "goals": 2, "starting": true, "birthYear": 1968 },
      { "name": "Hajto", "position": "DEF", "overall": 86, "apps": 21, "goals": 2, "starting": false, "birthYear": 1972 },
      { "name": "Dziuk", "position": "DEF", "overall": 66, "apps": 10, "goals": 0, "starting": false, "birthYear": 1969 },
      { "name": "Brzoza", "position": "DEF", "overall": 65, "apps": 9, "goals": 0, "starting": false, "birthYear": 1966 },
      { "name": "Koseła", "position": "MID", "overall": 81, "apps": 32, "goals": 5, "starting": true, "birthYear": 1970 },
      { "name": "Brzęczek", "position": "MID", "overall": 88, "apps": 30, "goals": 4, "starting": true, "birthYear": 1971 }, // Reżyser gry
      { "name": "Kubik", "position": "MID", "overall": 73, "apps": 28, "goals": 3, "starting": true, "birthYear": 1972 },
      { "name": "Orzeszek", "position": "MID", "overall": 83, "apps": 25, "goals": 5, "starting": true, "birthYear": 1967 },
      { "name": "Agafon", "position": "MID", "overall": 80, "apps": 17, "goals": 2, "starting": false, "birthYear": 1971 },
      { "name": "Mielcarski", "position": "FWD", "overall": 80, "apps": 23, "goals": 8, "starting": true, "birthYear": 1971 },
      { "name": "Bałuszyński", "position": "FWD", "overall": 80, "apps": 31, "goals": 7, "starting": true, "birthYear": 1972 },
      { "name": "Kraus", "position": "FWD", "overall": 72, "apps": 25, "goals": 3, "starting": false, "birthYear": 1964 },
      { "name": "Szemoński", "position": "FWD", "overall": 68, "apps": 13, "goals": 2, "starting": false, "birthYear": 1976 }
    ]
  },
{
    "club": "GKS Katowice",
    "season": "1993/94",
    "coaches": [{ "name": "Piotr Piekarczyk" }],
    "players": [
      { "name": "Jojko", "position": "GK", "overall": 77, "apps": 33, "goals": 0, "starting": true, "birthYear": 1960 },
      { "name": "Borawski", "position": "DEF", "overall": 74, "apps": 34, "goals": 2, "starting": true, "birthYear": 1967 },
      { "name": "Świerczewski M.", "position": "DEF", "overall": 90, "apps": 33, "goals": 2, "starting": true, "birthYear": 1967 },
      { "name": "Maciejewski", "position": "DEF", "overall": 82, "apps": 31, "goals": 5, "starting": true, "birthYear": 1964 },
      { "name": "Węgrzyn", "position": "DEF", "overall": 86, "apps": 31, "goals": 5, "starting": true, "birthYear": 1967 },
      { "name": "Widuch", "position": "DEF", "overall": 82, "apps": 26, "goals": 0, "starting": false, "birthYear": 1971 },
      { "name": "Wolny", "position": "MID", "overall": 76, "apps": 31, "goals": 9, "starting": true, "birthYear": 1969 },
      { "name": "Kucz", "position": "MID", "overall": 85, "apps": 34, "goals": 8, "starting": true, "birthYear": 1971 },
      { "name": "Ledwoń", "position": "MID", "overall": 94, "apps": 27, "goals": 0, "starting": true, "birthYear": 1974 },
      { "name": "Rzeźniczek", "position": "MID", "overall": 71, "apps": 25, "goals": 1, "starting": true, "birthYear": 1968 },
      { "name": "Grzesik", "position": "MID", "overall": 70, "apps": 17, "goals": 0, "starting": false, "birthYear": 1966 },
      { "name": "Karwan", "position": "MID", "overall": 74, "apps": 11, "goals": 1, "starting": false, "birthYear": 1976 },
      { "name": "Janoszka", "position": "FWD", "overall": 84, "apps": 33, "goals": 14, "starting": true, "birthYear": 1961 }, // Legendarny "Ecik"
      { "name": "Strojek", "position": "FWD", "overall": 82, "apps": 28, "goals": 1, "starting": true, "birthYear": 1964 },
      { "name": "Szczygieł", "position": "FWD", "overall": 69, "apps": 18, "goals": 2, "starting": false, "birthYear": 1975 },
    ]
  },
{
    "club": "Legia Warszawa",
    "season": "1993/94",
    "coaches": [{ "name": "Janusz Wójcik" }, { "name": "Paweł Janas" }],
    "players": [
      { "name": "Robakiewicz", "position": "GK", "overall": 85, "apps": 21, "goals": 0, "starting": true, "birthYear": 1966 },
      { "name": "Szczęsny", "position": "GK", "overall": 82, "apps": 13, "goals": 0, "starting": false, "birthYear": 1965 },
      { "name": "Kruszankin", "position": "DEF", "overall": 76, "apps": 32, "goals": 5, "starting": true, "birthYear": 1965 },
      { "name": "Mandziejewicz", "position": "DEF", "overall": 85, "apps": 32, "goals": 5, "starting": true, "birthYear": 1962 },
      { "name": "Ratajczyk", "position": "DEF", "overall": 82, "apps": 30, "goals": 0, "starting": true, "birthYear": 1973 },
      { "name": "Zieliński", "position": "DEF", "overall": 94, "apps": 29, "goals": 1, "starting": true, "birthYear": 1967 },
      { "name": "Jałocha", "position": "DEF", "overall": 85, "apps": 28, "goals": 4, "starting": true, "birthYear": 1971 },
      { "name": "Jóźwiak M.", "position": "DEF", "overall": 74, "apps": 23, "goals": 0, "starting": false, "birthYear": 1967 },
      { "name": "Pisz", "position": "MID", "overall": 98, "apps": 34, "goals": 6, "starting": true, "birthYear": 1966 }, // Generał środka pola
      { "name": "Michalski", "position": "MID", "overall": 90, "apps": 33, "goals": 8, "starting": true, "birthYear": 1969 },
      { "name": "Fedoruk", "position": "MID", "overall": 86, "apps": 32, "goals": 6, "starting": true, "birthYear": 1966 },
      { "name": "Wędzyński", "position": "MID", "overall": 72, "apps": 20, "goals": 1, "starting": false, "birthYear": 1970 },
      { "name": "Podbrożny", "position": "MID", "overall": 88, "apps": 17, "goals": 11, "starting": true, "birthYear": 1966 }, // Wielki transfer zimą
      { "name": "Grzesiak", "position": "MID", "overall": 71, "apps": 13, "goals": 5, "starting": false, "birthYear": 1965 },
      { "name": "Kowalczyk", "position": "FWD", "overall": 94, "apps": 33, "goals": 13, "starting": true, "birthYear": 1972 }, // "Kowal" u szczytu formy
      { "name": "Dziekanowski", "position": "FWD", "overall": 79, "apps": 6, "goals": 1, "starting": false, "birthYear": 1962 },
      { "name": "Śliwowski", "position": "FWD", "overall": 79, "apps": 5, "goals": 4, "starting": false, "birthYear": 1965 },
    ]
  }
);
