// ============================================================
// SEZON 2014/15 — 16 klubów
// Część bazy TEAMS_DATA — każdy sezon w osobnym pliku.
// ============================================================

window.TEAMS_DATA = window.TEAMS_DATA || [];
window.TEAMS_DATA.push(
{
    club: "Lech Poznań",
    season: "2014/15",
    "coaches": [{ "name": "Mariusz Rumak" }, { "name": "Krzysztof Chrobak" }, { "name": "Maciej Skorża" }],
    players: [
      { name: "Gostomski",     position: "GK",  overall: 76, apps: 21, goals: 0,  starting: true, "birthYear": 1988  },
      { name: "Kotorowski",    position: "GK",  overall: 68, apps: 6,  goals: 0,  starting: false, "birthYear": 1976 },

      { name: "Kamiński M.",   position: "DEF", overall: 82, apps: 36, goals: 2,  starting: true, "birthYear": 1992  },
      { name: "Arajuuri",      position: "DEF", overall: 80, apps: 24, goals: 3,  starting: true, "birthYear": 1988  },
      { name: "Douglas",       position: "DEF", overall: 80, apps: 27, goals: 3,  starting: true, "birthYear": 1989  },
      { name: "Kędziora T.",   position: "DEF", overall: 84, apps: 35, goals: 3,  starting: true, "birthYear": 1994  },
      { name: "Henriquez",     position: "DEF", overall: 70, apps: 16, goals: 0,  starting: false, "birthYear": 1981 },
      { name: "Wołąkiewicz",   position: "DEF", overall: 72, apps: 13, goals: 1,  starting: false, "birthYear": 1985 },
      { name: "Wilusz",        position: "DEF", overall: 64, apps: 8,  goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Bednarek",      position: "DEF", overall: 66, apps: 2,  goals: 1,  starting: false, "birthYear": 1996 },

      { name: "Trałka",        position: "MID", overall: 82, apps: 32, goals: 0,  starting: true, "birthYear": 1984  },
      { name: "Hamalainen",    position: "MID", overall: 92, apps: 36, goals: 13, starting: true, "birthYear": 1986  },
      { name: "Pawłowski",     position: "MID", overall: 89, apps: 33, goals: 9,  starting: true, "birthYear": 1986  },
      { name: "Jevtić",        position: "MID", overall: 80, apps: 29, goals: 7,  starting: true, "birthYear": 1993  },
      { name: "Linetty",       position: "MID", overall: 82, apps: 23, goals: 2,  starting: false, "birthYear": 1995 },
      { name: "Lovrencsics",   position: "MID", overall: 78, apps: 25, goals: 3,  starting: false, "birthYear": 1988 },
      { name: "Kownacki",      position: "MID", overall: 82, apps: 30, goals: 4,  starting: false, "birthYear": 1997 },
      { name: "Keita",         position: "MID", overall: 68, apps: 19, goals: 2,  starting: false, "birthYear": 1990 },
      { name: "Djoum",         position: "MID", overall: 65, apps: 3,  goals: 1,  starting: false, "birthYear": 1989 },

      { name: "Sadaev",        position: "FWD", overall: 79, apps: 24, goals: 5,  starting: true, "birthYear": 1989  },
      { name: "Formella",      position: "FWD", overall: 70, apps: 27, goals: 3,  starting: true, "birthYear": 1995  },
      { name: "Teodorczyk",    position: "FWD", overall: 80, apps: 4,  goals: 3,  starting: false, "birthYear": 1991 },
      { name: "Ubiparip",      position: "FWD", overall: 67, apps: 8,  goals: 3,  starting: false, "birthYear": 1988 },
    ]
  },
{
    club: "Legia Warszawa",
    season: "2014/15",
    "coaches": [{ "name": "Henning Berg" }],
    players: [
      { name: "Kuciak",        position: "GK",  overall: 90, apps: 31, goals: 0,  starting: true, "birthYear": 1985  },
      { name: "Malarz",        position: "GK",  overall: 70, apps: 5,  goals: 0,  starting: false, "birthYear": 1980 },
      { name: "Jałocha",       position: "GK",  overall: 62, apps: 3,  goals: 0,  starting: false, "birthYear": 1991 },

      { name: "Rzeźniczak",    position: "DEF", overall: 82, apps: 31, goals: 5,  starting: true, "birthYear": 1986  },
      { name: "Jodłowiec",     position: "DEF", overall: 85, apps: 31, goals: 3,  starting: true, "birthYear": 1985  },
      { name: "Broź Ł.",       position: "DEF", overall: 74, apps: 22, goals: 0,  starting: true, "birthYear": 1985  },
      { name: "Lewczuk",       position: "DEF", overall: 74, apps: 22, goals: 1,  starting: true, "birthYear": 1985  },
      { name: "Brzyski",       position: "DEF", overall: 77, apps: 25, goals: 1,  starting: false, "birthYear": 1982 },
      { name: "Astiz",         position: "DEF", overall: 70, apps: 19, goals: 1,  starting: false, "birthYear": 1983 },
      { name: "Bereszyński",   position: "DEF", overall: 68, apps: 16, goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Guilherme",     position: "DEF", overall: 66, apps: 18, goals: 1,  starting: false, "birthYear": 1991 },

      { name: "Vrdoljak",      position: "MID", overall: 82, apps: 28, goals: 4,  starting: true, "birthYear": 1983  },
      { name: "Duda O.",       position: "MID", overall: 88, apps: 27, goals: 5,  starting: true, "birthYear": 1994  },
      { name: "Żyro",          position: "MID", overall: 74, apps: 27, goals: 5,  starting: true, "birthYear": 1992  },
      { name: "Kucharczyk",    position: "MID", overall: 84, apps: 27, goals: 6,  starting: true, "birthYear": 1991  },
      { name: "Radović",       position: "MID", overall: 82, apps: 10, goals: 5,  starting: false, "birthYear": 1984 },
      { name: "Kosecki",       position: "MID", overall: 70, apps: 20, goals: 3,  starting: false, "birthYear": 1990 },
      { name: "Furman",        position: "MID", overall: 70, apps: 10, goals: 2,  starting: false, "birthYear": 1992 },
      { name: "Ryczkowski",    position: "MID", overall: 63, apps: 8,  goals: 2,  starting: false, "birthYear": 1997 },
      { name: "Masłowski",     position: "MID", overall: 65, apps: 12, goals: 0,  starting: false, "birthYear": 1989 },

      { name: "Orlando Sa",    position: "FWD", overall: 80, apps: 26, goals: 13, starting: true, "birthYear": 1988  },
      { name: "Saganowski",    position: "FWD", overall: 74, apps: 31, goals: 2,  starting: true, "birthYear": 1978  },
      { name: "Piech",         position: "FWD", overall: 68, apps: 4,  goals: 0,  starting: false, "birthYear": 1985 },
    ]
  },
{
    club: "Jagiellonia Białystok",
    season: "2014/15",
    "coaches": [{ "name": "Michał Probierz" }],
    players: [
      { name: "Drągowski",     position: "GK",  overall: 84, apps: 29, goals: 0,  starting: true, "birthYear": 1997  },
      { name: "Baran K.",      position: "GK",  overall: 66, apps: 6,  goals: 0,  starting: false, "birthYear": 1990 },
      { name: "Słowik",        position: "GK",  overall: 65, apps: 3,  goals: 0,  starting: false, "birthYear": 1991 },

      { name: "Pazdan",        position: "DEF", overall: 86, apps: 27, goals: 2,  starting: true, "birthYear": 1987  },
      { name: "Madera",        position: "DEF", overall: 76, apps: 31, goals: 0,  starting: true, "birthYear": 1985  },
      { name: "Romanchuk",     position: "DEF", overall: 72, apps: 27, goals: 4,  starting: true, "birthYear": 1991  },
      { name: "Modelski",      position: "DEF", overall: 70, apps: 26, goals: 1,  starting: true, "birthYear": 1992  },
      { name: "Wasiluk",       position: "DEF", overall: 68, apps: 20, goals: 0,  starting: false, "birthYear": 1987 },
      { name: "Tarasovs",      position: "DEF", overall: 66, apps: 15, goals: 1,  starting: false, "birthYear": 1988 },
      { name: "Baran M.",      position: "DEF", overall: 65, apps: 13, goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Straus",        position: "DEF", overall: 65, apps: 16, goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Popkhadze",     position: "DEF", overall: 64, apps: 6,  goals: 0,  starting: false, "birthYear": 1986 },

      { name: "Dzalamidze",    position: "MID", overall: 77, apps: 33, goals: 3,  starting: true, "birthYear": 1992  },
      { name: "Grzyb R.",      position: "MID", overall: 70, apps: 36, goals: 0,  starting: true, "birthYear": 1983  },
      { name: "Frankowski P.", position: "MID", overall: 70, apps: 28, goals: 3,  starting: true, "birthYear": 1995  },
      { name: "Tymiński",      position: "MID", overall: 68, apps: 20, goals: 2,  starting: true, "birthYear": 1990  },
      { name: "Mackiewicz",    position: "MID", overall: 66, apps: 17, goals: 1,  starting: false, "birthYear": 1992 },
      { name: "Quintana",      position: "MID", overall: 76, apps: 6,  goals: 1,  starting: false, "birthYear": 1987 },

      { name: "Tuszyński",     position: "FWD", overall: 82, apps: 37, goals: 15, starting: true, "birthYear": 1989  },
      { name: "Piątkowski",    position: "FWD", overall: 81, apps: 24, goals: 14, starting: true, "birthYear": 1984  },
      { name: "Gajos",         position: "FWD", overall: 72, apps: 36, goals: 8,  starting: false, "birthYear": 1991 },
      { name: "Pawłowski J.",  position: "FWD", overall: 66, apps: 21, goals: 2,  starting: false, "birthYear": 1992 },
      { name: "Savitskiy",     position: "FWD", overall: 62, apps: 5,  goals: 0,  starting: false, "birthYear": 1994 },
    ]
  },
{
    club: "Śląsk Wrocław",
    season: "2014/15",
    "coaches": [{ "name": "Tadeusz Pawłowski" }],
    players: [
      { name: "Pawełek",       position: "GK",  overall: 72, apps: 29, goals: 0,  starting: true, "birthYear": 1981  },
      { name: "Wrąbel",        position: "GK",  overall: 63, apps: 7,  goals: 0,  starting: false, "birthYear": 1996 },

      { name: "Celeban",       position: "DEF", overall: 85, apps: 37, goals: 2,  starting: true, "birthYear": 1985  },
      { name: "Dudu Paraiba",  position: "DEF", overall: 76, apps: 29, goals: 0,  starting: true, "birthYear": 1985  },
      { name: "Zieliński P.",  position: "DEF", overall: 72, apps: 35, goals: 1,  starting: true, "birthYear": 1990  },
      { name: "Hołota",        position: "DEF", overall: 70, apps: 34, goals: 0,  starting: true, "birthYear": 1991  },
      { name: "Ostrowski",     position: "DEF", overall: 68, apps: 24, goals: 2,  starting: false, "birthYear": 1982 },
      { name: "Pawelec",       position: "DEF", overall: 66, apps: 19, goals: 0,  starting: false, "birthYear": 1986 },
      { name: "Juanito",       position: "DEF", overall: 64, apps: 11, goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Grodzicki",     position: "DEF", overall: 64, apps: 4,  goals: 0,  starting: false, "birthYear": 1983 },

      { name: "Pich",          position: "MID", overall: 80, apps: 37, goals: 10, starting: true, "birthYear": 1988  },
      { name: "Danielewicz",   position: "MID", overall: 74, apps: 30, goals: 0,  starting: true, "birthYear": 1991  },
      { name: "Hateley",       position: "MID", overall: 72, apps: 30, goals: 0,  starting: true, "birthYear": 1989  },
      { name: "Droppa",        position: "MID", overall: 70, apps: 22, goals: 1,  starting: true, "birthYear": 1989  },
      { name: "Mila S.",       position: "MID", overall: 74, apps: 19, goals: 5,  starting: false, "birthYear": 1982 },
      { name: "Grajciar",      position: "MID", overall: 66, apps: 16, goals: 1,  starting: false, "birthYear": 1983 },
      { name: "Dankowski",     position: "MID", overall: 63, apps: 10, goals: 0,  starting: false, "birthYear": 1996 },
      { name: "Bartkowiak",    position: "MID", overall: 61, apps: 2,  goals: 0,  starting: false, "birthYear": 1997 },

      { name: "Flavio Paixao", position: "FWD", overall: 86, apps: 37, goals: 18, starting: true, "birthYear": 1984  },
      { name: "Marco Paixao",  position: "FWD", overall: 75, apps: 20, goals: 6,  starting: true, "birthYear": 1984  },
      { name: "M. Machaj",     position: "FWD", overall: 62, apps: 30, goals: 3,  starting: false, "birthYear": 1989 },
      { name: "Kaczmarek K.",  position: "FWD", overall: 64, apps: 7,  goals: 2,  starting: false, "birthYear": 1991 },
      { name: "Lacny",         position: "FWD", overall: 62, apps: 6,  goals: 1,  starting: false, "birthYear": 1988 },
      { name: "Angielski",     position: "FWD", overall: 62, apps: 8,  goals: 0,  starting: false, "birthYear": 1996 },
    ]
  },
{
    club: "Lechia Gdańsk",
    season: "2014/15",
    "coaches": [{ "name": "Quim Machado" }, { "name": "Tomasz Unton" }, { "name": "Jerzy Brzęczek" }],
    players: [
      { name: "Bąk M.",        position: "GK",  overall: 72, apps: 21, goals: 0,  starting: true, "birthYear": 1983  },
      { name: "Budziłek",      position: "GK",  overall: 65, apps: 7,  goals: 0,  starting: false, "birthYear": 1991 },
      { name: "Trela",         position: "GK",  overall: 64, apps: 9,  goals: 0,  starting: false, "birthYear": 1989 },

      { name: "Janicki",       position: "DEF", overall: 82, apps: 34, goals: 0,  starting: true, "birthYear": 1992  },
      { name: "Możdżeń",       position: "MID", overall: 72, apps: 24, goals: 0,  starting: true, "birthYear": 1991  },
      { name: "Leković",       position: "DEF", overall: 70, apps: 18, goals: 1,  starting: true, "birthYear": 1989  },
      { name: "Bougaidis",     position: "DEF", overall: 68, apps: 12, goals: 0,  starting: true, "birthYear": 1993  },
      { name: "Wojtkowiak",    position: "DEF", overall: 71, apps: 16, goals: 0,  starting: false, "birthYear": 1984 },
      { name: "Wawrzyniak",    position: "DEF", overall: 68, apps: 11, goals: 0,  starting: false, "birthYear": 1983 },
      { name: "Gerson",        position: "DEF", overall: 70, apps: 14, goals: 1,  starting: false, "birthYear": 1992 },
      { name: "Tiago Valente", position: "DEF", overall: 63, apps: 12, goals: 0,  starting: false, "birthYear": 1985 },

      { name: "Vranjes",       position: "MID", overall: 80, apps: 33, goals: 8,  starting: true, "birthYear": 1986  },
      { name: "Makuszewski",   position: "MID", overall: 78, apps: 34, goals: 6,  starting: true, "birthYear": 1989  },
      { name: "Borysiuk",      position: "MID", overall: 74, apps: 34, goals: 0,  starting: true, "birthYear": 1991  },
      { name: "Łukasik",       position: "MID", overall: 70, apps: 27, goals: 0,  starting: true, "birthYear": 1991  },
      { name: "Bruno Nazario", position: "MID", overall: 68, apps: 27, goals: 1,  starting: false, "birthYear": 1995 },
      { name: "Wiśniewski P.", position: "MID", overall: 70, apps: 23, goals: 6,  starting: false, "birthYear": 1982 },
      { name: "Mila S.",       position: "MID", overall: 72, apps: 16, goals: 2,  starting: false, "birthYear": 1982 },
      { name: "Pietrowski",    position: "MID", overall: 66, apps: 19, goals: 0,  starting: false, "birthYear": 1988 },

      { name: "Colak",         position: "FWD", overall: 78, apps: 30, goals: 10, starting: true, "birthYear": 1993  },
      { name: "Friesenbichler",position: "FWD", overall: 74, apps: 17, goals: 5,  starting: true, "birthYear": 1994  },
      { name: "Grzelczak",     position: "FWD", overall: 72, apps: 29, goals: 3,  starting: false, "birthYear": 1988 },
      { name: "Sadaev",        position: "FWD", overall: 70, apps: 4,  goals: 2,  starting: false, "birthYear": 1989 },
      { name: "Aleksić",       position: "FWD", overall: 63, apps: 3,  goals: 0,  starting: false, "birthYear": 1991 },
    ]
  },
{
    club: "Wisła Kraków",
    season: "2014/15",
    "coaches": [{ "name": "Franciszek Smuda" }, { "name": "Kazimierz Moskal" }],
    players: [
      { name: "Buchalik",      position: "GK",  overall: 74, apps: 36, goals: 0,  starting: true, "birthYear": 1989  },
      { name: "Miśkiewicz",    position: "GK",  overall: 68, apps: 1,  goals: 0,  starting: false, "birthYear": 1989 },

      { name: "Głowacki",      position: "DEF", overall: 81, apps: 34, goals: 1,  starting: true, "birthYear": 1979  },
      { name: "Burliga",       position: "DEF", overall: 76, apps: 33, goals: 5,  starting: true, "birthYear": 1988  },
      { name: "Sadlok",        position: "DEF", overall: 74, apps: 31, goals: 2,  starting: true, "birthYear": 1989  },
      { name: "Guzmics",       position: "DEF", overall: 72, apps: 21, goals: 0,  starting: true, "birthYear": 1987  },
      { name: "Jović B.",      position: "DEF", overall: 68, apps: 16, goals: 0,  starting: false, "birthYear": 1991 },
      { name: "Żemło",         position: "DEF", overall: 62, apps: 3,  goals: 0,  starting: false, "birthYear": 1995 },

      { name: "Stilić",        position: "MID", overall: 88, apps: 36, goals: 9,  starting: true, "birthYear": 1987  },
      { name: "Dudka",         position: "MID", overall: 78, apps: 34, goals: 0,  starting: true, "birthYear": 1983  },
      { name: "Guerrier",      position: "MID", overall: 78, apps: 23, goals: 6,  starting: true, "birthYear": 1989  },
      { name: "Garguła",       position: "MID", overall: 76, apps: 30, goals: 3,  starting: true, "birthYear": 1981  },
      { name: "Boguski",       position: "MID", overall: 70, apps: 36, goals: 5,  starting: false, "birthYear": 1984 },
      { name: "Jankowski M.",  position: "MID", overall: 70, apps: 26, goals: 3,  starting: false, "birthYear": 1990 },
      { name: "Uryga",         position: "MID", overall: 66, apps: 31, goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Barrientos",    position: "MID", overall: 66, apps: 16, goals: 1,  starting: false, "birthYear": 1990 },
      { name: "Sarki",         position: "MID", overall: 64, apps: 21, goals: 1,  starting: false, "birthYear": 1987 },
      { name: "Lech P.",       position: "MID", overall: 60, apps: 1,  goals: 0,  starting: false, "birthYear": 1995 },

      { name: "Paweł Brożek",  position: "FWD", overall: 88, apps: 35, goals: 15, starting: true, "birthYear": 1983  },
      { name: "Stępiński M.",  position: "FWD", overall: 70, apps: 25, goals: 2,  starting: true, "birthYear": 1995  },
      { name: "Zając T.",      position: "FWD", overall: 62, apps: 9,  goals: 0,  starting: false, "birthYear": 1995 },
    ]
  },
{
    club: "Górnik Zabrze",
    season: "2014/15",
    "coaches": [{ "name": "Józef Dankowski" }],
    players: [
      { name: "Steinbors",     position: "GK",  overall: 72, apps: 32, goals: 0,  starting: true, "birthYear": 1985  },
      { name: "Kasprzik",      position: "GK",  overall: 63, apps: 5,  goals: 0,  starting: false, "birthYear": 1983 },

      { name: "Gergel",        position: "DEF", overall: 79, apps: 35, goals: 6,  starting: true, "birthYear": 1988  },
      { name: "Kosznik",       position: "DEF", overall: 74, apps: 35, goals: 5,  starting: true, "birthYear": 1983  },
      { name: "Danch",         position: "DEF", overall: 70, apps: 36, goals: 1,  starting: true, "birthYear": 1987  },
      { name: "Shevelyukhin",  position: "DEF", overall: 68, apps: 30, goals: 2,  starting: true, "birthYear": 1982  },
      { name: "Magiera M.",    position: "DEF", overall: 66, apps: 25, goals: 5,  starting: false, "birthYear": 1984 },
      { name: "Gancarczyk S.", position: "DEF", overall: 64, apps: 19, goals: 0,  starting: false, "birthYear": 1981 },
      { name: "Sadzawicki",    position: "DEF", overall: 63, apps: 21, goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Augustyn",      position: "DEF", overall: 65, apps: 17, goals: 2,  starting: false, "birthYear": 1988 },

      { name: "Madej Ł.",      position: "MID", overall: 79, apps: 36, goals: 5,  starting: true, "birthYear": 1982  },
      { name: "Jez",           position: "MID", overall: 78, apps: 32, goals: 5,  starting: true, "birthYear": 1981  },
      { name: "Sobolewski",    position: "MID", overall: 79, apps: 30, goals: 0,  starting: true, "birthYear": 1976  },
      { name: "Grendel",       position: "MID", overall: 70, apps: 17, goals: 1,  starting: true, "birthYear": 1988  },
      { name: "Iwan B.",       position: "MID", overall: 68, apps: 18, goals: 2,  starting: false, "birthYear": 1984 },
      { name: "Kurzawa",       position: "MID", overall: 65, apps: 12, goals: 0,  starting: false, "birthYear": 1993 },
      { name: "Gwaze",         position: "MID", overall: 63, apps: 12, goals: 0,  starting: false, "birthYear": 1989 },
      { name: "Cerimagić",     position: "MID", overall: 62, apps: 4,  goals: 2,  starting: false, "birthYear": 1994 },

      { name: "Zachara",       position: "FWD", overall: 80, apps: 18, goals: 10, starting: true, "birthYear": 1990  },
      { name: "Łuczak W.",     position: "FWD", overall: 70, apps: 20, goals: 2,  starting: true, "birthYear": 1989  },
      { name: "Skrzypczak",    position: "FWD", overall: 66, apps: 15, goals: 2,  starting: false, "birthYear": 1990 },
      { name: "Piasecki",      position: "FWD", overall: 62, apps: 3,  goals: 0,  starting: false, "birthYear": 1995 },
      { name: "Oziębała",      position: "FWD", overall: 64, apps: 5,  goals: 0,  starting: false, "birthYear": 1986 },
    ]
  },
{
    club: "Pogoń Szczecin",
    season: "2014/15",
    "coaches": [{ "name": "Dariusz Wdowczyk" }, { "name": "Jan Kocian" }, { "name": "Czesław Michniewicz" }],
    players: [
      { name: "Janukiewicz",   position: "GK",  overall: 72, apps: 32, goals: 0,  starting: true, "birthYear": 1984  },
      { name: "Kudła",         position: "GK",  overall: 62, apps: 5,  goals: 0,  starting: false, "birthYear": 1992 },

      { name: "Matras",        position: "DEF", overall: 78, apps: 31, goals: 1,  starting: true, "birthYear": 1991  },
      { name: "Golla W.",      position: "DEF", overall: 74, apps: 34, goals: 1,  starting: true, "birthYear": 1992  },
      { name: "Rudol",         position: "DEF", overall: 70, apps: 35, goals: 0,  starting: true, "birthYear": 1995  },
      { name: "Hernani",       position: "DEF", overall: 68, apps: 22, goals: 1,  starting: true, "birthYear": 1984  },
      { name: "Ricardo Nunes", position: "DEF", overall: 74, apps: 22, goals: 0,  starting: false, "birthYear": 1986 },
      { name: "Matynia",       position: "DEF", overall: 66, apps: 23, goals: 0,  starting: false, "birthYear": 1995 },
      { name: "Dąbrowski M.",  position: "DEF", overall: 67, apps: 14, goals: 2,  starting: false, "birthYear": 1987 },
      { name: "Lewandowski M.",position: "DEF", overall: 65, apps: 5,  goals: 1,  starting: false, "birthYear": 1993 },

      { name: "Murawski",      position: "MID", overall: 78, apps: 36, goals: 3,  starting: true, "birthYear": 1981  },
      { name: "Rogalski M.",   position: "MID", overall: 74, apps: 28, goals: 2,  starting: true, "birthYear": 1983  },
      { name: "Frączczak",     position: "MID", overall: 81, apps: 34, goals: 6,  starting: true, "birthYear": 1987  },
      { name: "Bąk J.",        position: "MID", overall: 70, apps: 14, goals: 0,  starting: true, "birthYear": 1993  },
      { name: "Murayama",      position: "MID", overall: 76, apps: 17, goals: 5,  starting: false, "birthYear": 1989 },
      { name: "Akahoshi",      position: "MID", overall: 68, apps: 12, goals: 0,  starting: false, "birthYear": 1986 },
      { name: "Danielak",      position: "MID", overall: 65, apps: 11, goals: 2,  starting: false, "birthYear": 1991 },
      { name: "Kamess",        position: "MID", overall: 65, apps: 6,  goals: 2,  starting: false, "birthYear": 1988 },
      { name: "Kun",           position: "MID", overall: 64, apps: 24, goals: 1,  starting: false, "birthYear": 1993 },
      { name: "Małecki",       position: "MID", overall: 65, apps: 11, goals: 0,  starting: false, "birthYear": 1988 },

      { name: "Robak",         position: "FWD", overall: 86, apps: 17, goals: 11, starting: true, "birthYear": 1982  },
      { name: "Zwoliński",     position: "FWD", overall: 84, apps: 33, goals: 12, starting: true, "birthYear": 1993  },
      { name: "Kozłowski F.",  position: "FWD", overall: 62, apps: 2,  goals: 0,  starting: false, "birthYear": 1995 },
    ]
  },
{
    club: "Cracovia Kraków",
    season: "2014/15",
    "coaches": [{ "name": "Robert Podoliński" }, { "name": "Jacek Zieliński" }],
    players: [
      { name: "Pilarz",        position: "GK",  overall: 80, apps: 36, goals: 0,  starting: true, "birthYear": 1980  },
      { name: "Stępniowski",   position: "GK",  overall: 62, apps: 1,  goals: 0,  starting: false, "birthYear": 1992 },

      { name: "Marciniak A.",  position: "DEF", overall: 76, apps: 34, goals: 1,  starting: true, "birthYear": 1988  },
      { name: "Rymaniak",      position: "DEF", overall: 74, apps: 26, goals: 0,  starting: true, "birthYear": 1989  },
      { name: "Żytko",         position: "DEF", overall: 72, apps: 21, goals: 1,  starting: true, "birthYear": 1982  },
      { name: "Deleu",         position: "DEF", overall: 70, apps: 22, goals: 1,  starting: true, "birthYear": 1984  },
      { name: "Polczak",       position: "DEF", overall: 68, apps: 17, goals: 2,  starting: false, "birthYear": 1986 },
      { name: "Nykiel",        position: "DEF", overall: 66, apps: 17, goals: 0,  starting: false, "birthYear": 1982 },
      { name: "Jaroszyński",   position: "DEF", overall: 64, apps: 15, goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Sretenović",    position: "DEF", overall: 66, apps: 17, goals: 0,  starting: false, "birthYear": 1985 },

      { name: "Budziński",     position: "MID", overall: 83, apps: 36, goals: 9,  starting: true, "birthYear": 1990  },
      { name: "Covilo",        position: "MID", overall: 84, apps: 26, goals: 7,  starting: true, "birthYear": 1986  },
      { name: "Dąbrowski D.",  position: "MID", overall: 72, apps: 35, goals: 1,  starting: true, "birthYear": 1992  },
      { name: "Kapustka",      position: "MID", overall: 72, apps: 23, goals: 2,  starting: true, "birthYear": 1996  },
      { name: "Dialiba",       position: "MID", overall: 68, apps: 28, goals: 5,  starting: false, "birthYear": 1988 },
      { name: "Cetnarski",     position: "MID", overall: 66, apps: 16, goals: 2,  starting: false, "birthYear": 1988 },
      { name: "Armiche",       position: "MID", overall: 64, apps: 6,  goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Szeliga",       position: "MID", overall: 64, apps: 10, goals: 0,  starting: false, "birthYear": 1982 },

      { name: "Rakels",        position: "FWD", overall: 82, apps: 33, goals: 12, starting: true, "birthYear": 1992  },
      { name: "Jendrisek",     position: "FWD", overall: 74, apps: 17, goals: 4,  starting: true, "birthYear": 1986  },
      { name: "Nowak D.",      position: "FWD", overall: 68, apps: 9,  goals: 1,  starting: false, "birthYear": 1984 },
      { name: "Kita",          position: "FWD", overall: 64, apps: 12, goals: 0,  starting: false, "birthYear": 1993 },
      { name: "Wdowiak",       position: "FWD", overall: 63, apps: 12, goals: 0,  starting: false, "birthYear": 1996 },
      { name: "Zjawiński",     position: "FWD", overall: 66, apps: 26, goals: 2,  starting: false, "birthYear": 1986 },
    ]
  },
{
    club: "Ruch Chorzów",
    season: "2014/15",
    "coaches": [{ "name": "Jan Kocian" }, { "name": "Waldemar Fornalik" }],
    players: [
      { name: "Kamiński K.",   position: "GK",  overall: 68, apps: 19, goals: 0,  starting: true, "birthYear": 1990  },
      { name: "Putnocky",      position: "GK",  overall: 77, apps: 18, goals: 0,  starting: false, "birthYear": 1984 },

      { name: "Malinowski",    position: "DEF", overall: 76, apps: 22, goals: 0,  starting: true, "birthYear": 1975  },
      { name: "Konczkowski",   position: "DEF", overall: 72, apps: 30, goals: 1,  starting: true, "birthYear": 1993  },
      { name: "Grodzicki",     position: "DEF", overall: 70, apps: 14, goals: 1,  starting: true, "birthYear": 1983  },
      { name: "Stawarczyk",    position: "DEF", overall: 70, apps: 20, goals: 1,  starting: true, "birthYear": 1983  },
      { name: "Helik",         position: "DEF", overall: 68, apps: 18, goals: 1,  starting: false, "birthYear": 1995 },
      { name: "Oleksy",        position: "DEF", overall: 66, apps: 14, goals: 0,  starting: false, "birthYear": 1991 },
      { name: "Kuś M.",        position: "DEF", overall: 64, apps: 9,  goals: 2,  starting: false, "birthYear": 1981 },
      { name: "Szyndrowski",   position: "DEF", overall: 64, apps: 9,  goals: 0,  starting: false, "birthYear": 1980 },
      { name: "Dziwniel",      position: "DEF", overall: 66, apps: 17, goals: 1,  starting: false, "birthYear": 1992 },

      { name: "Surma",         position: "MID", overall: 76, apps: 37, goals: 1,  starting: true, "birthYear": 1977  },
      { name: "Starzyński",    position: "MID", overall: 78, apps: 36, goals: 8,  starting: true, "birthYear": 1991  },
      { name: "Zieńczuk",      position: "MID", overall: 74, apps: 36, goals: 1,  starting: true, "birthYear": 1978  },
      { name: "Babiarz",       position: "MID", overall: 70, apps: 36, goals: 1,  starting: true, "birthYear": 1989  },
      { name: "Gigolaev",      position: "MID", overall: 68, apps: 27, goals: 4,  starting: false, "birthYear": 1990 },
      { name: "Kowalski J.",   position: "MID", overall: 66, apps: 33, goals: 3,  starting: false, "birthYear": 1987 },
      { name: "Chovanec",      position: "MID", overall: 65, apps: 9,  goals: 0,  starting: false, "birthYear": 1984 },
      { name: "Włodyka",       position: "MID", overall: 63, apps: 3,  goals: 0,  starting: false, "birthYear": 1994 },

      { name: "Kuświk",        position: "FWD", overall: 84, apps: 35, goals: 14, starting: true, "birthYear": 1987  },
      { name: "Efir",          position: "FWD", overall: 68, apps: 28, goals: 3,  starting: true, "birthYear": 1992  },
      { name: "Visnakovs E.",  position: "FWD", overall: 72, apps: 27, goals: 3,  starting: false, "birthYear": 1990 },
      { name: "Kwiatkowski",   position: "FWD", overall: 62, apps: 2,  goals: 0,  starting: false, "birthYear": 1992 },
    ]
  },
{
    club: "Korona Kielce",
    season: "2014/15",
    "coaches": [{ "name": "Ryszard Tarasiewicz" }],
    players: [
      { name: "Cerniauskas",   position: "GK",  overall: 70, apps: 35, goals: 0,  starting: true, "birthYear": 1989  },
      { name: "Małecki W.",    position: "GK",  overall: 62, apps: 2,  goals: 0,  starting: false, "birthYear": 1990 },

      { name: "Golański",      position: "DEF", overall: 79, apps: 31, goals: 1,  starting: true, "birthYear": 1982  },
      { name: "Malarczyk",     position: "DEF", overall: 82, apps: 35, goals: 2,  starting: true, "birthYear": 1991  },
      { name: "Dejmek",        position: "DEF", overall: 78, apps: 24, goals: 3,  starting: true, "birthYear": 1988  },
      { name: "Sylwestrzak",   position: "DEF", overall: 78, apps: 28, goals: 5,  starting: true, "birthYear": 1988  },
      { name: "Leandro",       position: "DEF", overall: 66, apps: 23, goals: 1,  starting: false, "birthYear": 1983 },
      { name: "Ouattara",      position: "DEF", overall: 64, apps: 9,  goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Klemenz",       position: "DEF", overall: 62, apps: 10, goals: 0,  starting: false, "birthYear": 1995 },

      { name: "Kiełb",         position: "MID", overall: 84, apps: 34, goals: 9,  starting: true, "birthYear": 1988  },
      { name: "Jovanović",     position: "MID", overall: 76, apps: 31, goals: 1,  starting: true, "birthYear": 1985  },
      { name: "Kapo",          position: "MID", overall: 82, apps: 27, goals: 7,  starting: true, "birthYear": 1980  },
      { name: "Pilipchuk",     position: "MID", overall: 70, apps: 24, goals: 0,  starting: true, "birthYear": 1984  },
      { name: "Luis Carlos",   position: "MID", overall: 78, apps: 15, goals: 5,  starting: false, "birthYear": 1987 },
      { name: "Petrov",        position: "MID", overall: 66, apps: 12, goals: 1,  starting: false, "birthYear": 1990 },
      { name: "Fertovs",       position: "MID", overall: 64, apps: 18, goals: 0,  starting: false, "birthYear": 1987 },
      { name: "Marković V.",   position: "MID", overall: 64, apps: 11, goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Aankour",       position: "MID", overall: 63, apps: 17, goals: 0,  starting: false, "birthYear": 1993 },
      { name: "Janota",        position: "MID", overall: 68, apps: 9,  goals: 1,  starting: false, "birthYear": 1990 },

      { name: "Trytko",        position: "FWD", overall: 74, apps: 31, goals: 5,  starting: true, "birthYear": 1987  },
      { name: "Porcellis",     position: "FWD", overall: 68, apps: 15, goals: 3,  starting: true, "birthYear": 1987  },
      { name: "Khizhnichenko", position: "FWD", overall: 66, apps: 13, goals: 0,  starting: false, "birthYear": 1991 },
    ]
  },
{
    club: "Piast Gliwice",
    season: "2014/15",
    "coaches": [{ "name": "Angel Perez Garcia" }, { "name": "Krzysztof Szumski" }, { "name": "Radoslav Latal" }],
    players: [
      { name: "Szmatuła",      position: "GK",  overall: 68, apps: 18, goals: 0,  starting: true, "birthYear": 1981  },
      { name: "Cifuentes",     position: "GK",  overall: 68, apps: 15, goals: 0,  starting: false, "birthYear": 1979 },
      { name: "Rusov",         position: "GK",  overall: 63, apps: 5,  goals: 0,  starting: false, "birthYear": 1993 },

      { name: "Horvath",       position: "DEF", overall: 76, apps: 28, goals: 1,  starting: true, "birthYear": 1982  },
      { name: "Klepczyński",   position: "DEF", overall: 74, apps: 31, goals: 0,  starting: true, "birthYear": 1981  },
      { name: "Osyra",         position: "DEF", overall: 70, apps: 33, goals: 1,  starting: true, "birthYear": 1993  },
      { name: "Hebert",        position: "DEF", overall: 70, apps: 25, goals: 3,  starting: true, "birthYear": 1991  },
      { name: "Piotr Brożek",  position: "DEF", overall: 68, apps: 23, goals: 0,  starting: false, "birthYear": 1983 },
      { name: "Moskwik",       position: "DEF", overall: 64, apps: 13, goals: 2,  starting: false, "birthYear": 1992 },
      { name: "Mokwa",         position: "DEF", overall: 62, apps: 13, goals: 0,  starting: false, "birthYear": 1993 },

      { name: "Vassiljev",     position: "MID", overall: 76, apps: 25, goals: 5,  starting: true, "birthYear": 1984  },
      { name: "Podgórski",     position: "MID", overall: 74, apps: 31, goals: 2,  starting: true, "birthYear": 1985  },
      { name: "Szeliga B.",    position: "MID", overall: 72, apps: 31, goals: 5,  starting: true, "birthYear": 1993  },
      { name: "Martinez C.",   position: "MID", overall: 70, apps: 27, goals: 0,  starting: true, "birthYear": 1988  },
      { name: "Murawski R.",   position: "MID", overall: 70, apps: 29, goals: 0,  starting: false, "birthYear": 1994 },
      { name: "Hanzel",        position: "MID", overall: 68, apps: 27, goals: 1,  starting: false, "birthYear": 1986 },
      { name: "Badia",         position: "MID", overall: 66, apps: 31, goals: 4,  starting: false, "birthYear": 1989 },
      { name: "Zivec",         position: "MID", overall: 64, apps: 19, goals: 1,  starting: false, "birthYear": 1991 },
      { name: "Polak",         position: "MID", overall: 66, apps: 4,  goals: 1,  starting: false, "birthYear": 1989 },

      { name: "Wilczek",       position: "FWD", overall: 90, apps: 35, goals: 20, starting: true, "birthYear": 1988  },
      { name: "Jurado R.",     position: "FWD", overall: 76, apps: 24, goals: 4,  starting: true, "birthYear": 1986  },
      { name: "Kędziora",      position: "FWD", overall: 66, apps: 11, goals: 0,  starting: false, "birthYear": 1980 },
      { name: "Janczyk",       position: "FWD", overall: 64, apps: 3,  goals: 0,  starting: false, "birthYear": 1987 },
    ]
  },
{
    club: "Podbeskidzie Bielsko-Biała",
    season: "2014/15",
    "coaches": [{ "name": "Leszek Ojrzyński" }, { "name": "Dariusz Kubicki" }],
    players: [
      { name: "Pesković",      position: "GK",  overall: 68, apps: 21, goals: 0,  starting: true, "birthYear": 1982  },
      { name: "Zajac R.",      position: "GK",  overall: 67, apps: 16, goals: 0,  starting: false, "birthYear": 1976 },

      { name: "Konieczny",     position: "DEF", overall: 72, apps: 30, goals: 2,  starting: true, "birthYear": 1981  },
      { name: "Sokołowski M.", position: "DEF", overall: 76, apps: 31, goals: 4,  starting: true, "birthYear": 1978  },
      { name: "Górkiewicz",    position: "DEF", overall: 68, apps: 29, goals: 2,  starting: true, "birthYear": 1985  },
      { name: "Stano",         position: "DEF", overall: 68, apps: 26, goals: 2,  starting: true, "birthYear": 1977  },
      { name: "Tomasik",       position: "DEF", overall: 66, apps: 20, goals: 0,  starting: false, "birthYear": 1987 },
      { name: "Pazio",         position: "DEF", overall: 65, apps: 20, goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Kolcak",        position: "DEF", overall: 64, apps: 13, goals: 0,  starting: false, "birthYear": 1990 },
      { name: "Adu Kwame",     position: "DEF", overall: 63, apps: 18, goals: 0,  starting: false, "birthYear": 1985 },

      { name: "Chmiel",        position: "MID", overall: 76, apps: 34, goals: 9,  starting: true, "birthYear": 1987  },
      { name: "Iwański",       position: "MID", overall: 72, apps: 32, goals: 8,  starting: true, "birthYear": 1981  },
      { name: "Sloboda A.",    position: "MID", overall: 68, apps: 20, goals: 1,  starting: true, "birthYear": 1987  },
      { name: "Deja",          position: "MID", overall: 66, apps: 21, goals: 0,  starting: true, "birthYear": 1993  },
      { name: "Malinowski P.", position: "MID", overall: 66, apps: 23, goals: 1,  starting: false, "birthYear": 1984 },
      { name: "Kołodziej",     position: "MID", overall: 64, apps: 14, goals: 3,  starting: false, "birthYear": 1982 },
      { name: "Lenartowski",   position: "MID", overall: 63, apps: 9,  goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Trochim",       position: "MID", overall: 62, apps: 3,  goals: 0,  starting: false, "birthYear": 1989 },

      { name: "Demjan",        position: "FWD", overall: 70, apps: 32, goals: 4,  starting: true, "birthYear": 1982  },
      { name: "Korzym",        position: "FWD", overall: 72, apps: 21, goals: 4,  starting: true, "birthYear": 1988  },
      { name: "Śpiączka",      position: "FWD", overall: 68, apps: 23, goals: 4,  starting: false, "birthYear": 1991 },
      { name: "Cisse",         position: "FWD", overall: 63, apps: 9,  goals: 1,  starting: false, "birthYear": 1990 },
    ]
  },
{
    club: "Górnik Łęczna",
    season: "2014/15",
    "coaches": [{ "name": "Yuriy Shatalov" }],
    players: [
      { name: "Prusak",        position: "GK",  overall: 68, apps: 31, goals: 0,  starting: true, "birthYear": 1979  },
      { name: "Rodić",         position: "GK",  overall: 63, apps: 6,  goals: 0,  starting: false, "birthYear": 1987 },
      { name: "Socha P.",      position: "GK",  overall: 60, apps: 1,  goals: 0,  starting: false, "birthYear": 1991 },

      { name: "Mraz",          position: "DEF", overall: 79, apps: 33, goals: 3,  starting: true, "birthYear": 1987  },
      { name: "Bielak",        position: "DEF", overall: 70, apps: 32, goals: 1,  starting: true, "birthYear": 1986  },
      { name: "Mierzejewski",  position: "DEF", overall: 68, apps: 33, goals: 2,  starting: true, "birthYear": 1982  },
      { name: "Szmatiuk",      position: "DEF", overall: 68, apps: 33, goals: 0,  starting: true, "birthYear": 1980  },
      { name: "Bozić",         position: "DEF", overall: 66, apps: 27, goals: 0,  starting: false, "birthYear": 1987 },
      { name: "Nikitović",     position: "DEF", overall: 66, apps: 25, goals: 2,  starting: false, "birthYear": 1980 },
      { name: "Kalkowski",     position: "DEF", overall: 62, apps: 9,  goals: 1,  starting: false, "birthYear": 1989 },

      { name: "Bonin",         position: "MID", overall: 86, apps: 34, goals: 6,  starting: true, "birthYear": 1983  },
      { name: "Nowak T.",      position: "MID", overall: 70, apps: 36, goals: 3,  starting: true, "birthYear": 1985  },
      { name: "Bozok",         position: "MID", overall: 68, apps: 32, goals: 4,  starting: true, "birthYear": 1984  },
      { name: "Rudik",         position: "MID", overall: 65, apps: 15, goals: 1,  starting: true, "birthYear": 1987  },
      { name: "Burkhardt F.",  position: "MID", overall: 65, apps: 17, goals: 0,  starting: false, "birthYear": 1987 },
      { name: "Pruchnik",      position: "MID", overall: 63, apps: 12, goals: 0,  starting: false, "birthYear": 1986 },
      { name: "Szałachowski",  position: "MID", overall: 63, apps: 20, goals: 1,  starting: false, "birthYear": 1984 },
      { name: "Josu",          position: "MID", overall: 63, apps: 8,  goals: 0,  starting: false, "birthYear": 1993 },
      { name: "Tanchyk",       position: "MID", overall: 62, apps: 5,  goals: 0,  starting: false, "birthYear": 1991 },

      { name: "Chernykh",      position: "FWD", overall: 78, apps: 32, goals: 11, starting: true, "birthYear": 1991  },
      { name: "Hasani",        position: "FWD", overall: 70, apps: 29, goals: 5,  starting: true, "birthYear": 1982  },
      { name: "Razulis",       position: "FWD", overall: 63, apps: 7,  goals: 1,  starting: false, "birthYear": 1986 },
      { name: "Buzała",        position: "FWD", overall: 64, apps: 7,  goals: 1,  starting: false, "birthYear": 1985 },
    ]
  },
{
    club: "GKS Bełchatów",
    season: "2014/15",
    "coaches": [{ "name": "Kamil Kiereś" }, { "name": "Marek Zub" }, { "name": "Kamil Kiereś" }],
    players: [
      { name: "Malarz",        position: "GK",  overall: 77, apps: 19, goals: 0,  starting: true, "birthYear": 1980  },
      { name: "Trela",         position: "GK",  overall: 66, apps: 10, goals: 0,  starting: false, "birthYear": 1989 },
      { name: "Zubas",         position: "GK",  overall: 62, apps: 9,  goals: 0,  starting: false, "birthYear": 1990 },

      { name: "Telichowski",   position: "DEF", overall: 72, apps: 28, goals: 0,  starting: true, "birthYear": 1984  },
      { name: "Baran G.",      position: "DEF", overall: 70, apps: 28, goals: 0,  starting: true, "birthYear": 1982  },
      { name: "Baranowski P.", position: "DEF", overall: 68, apps: 34, goals: 1,  starting: true, "birthYear": 1990  },
      { name: "Basta",         position: "DEF", overall: 66, apps: 28, goals: 2,  starting: true, "birthYear": 1988  },
      { name: "Mójta",         position: "DEF", overall: 66, apps: 29, goals: 2,  starting: false, "birthYear": 1986 },
      { name: "Zbozień",       position: "DEF", overall: 64, apps: 13, goals: 1,  starting: false, "birthYear": 1989 },
      { name: "Flis M.",       position: "DEF", overall: 62, apps: 11, goals: 0,  starting: false, "birthYear": 1994 },

      { name: "Rachwał",       position: "MID", overall: 70, apps: 26, goals: 0,  starting: true, "birthYear": 1981  },
      { name: "Komolov",       position: "MID", overall: 68, apps: 31, goals: 2,  starting: true, "birthYear": 1989  },
      { name: "Poźniak",       position: "MID", overall: 68, apps: 20, goals: 1,  starting: true, "birthYear": 1989  },
      { name: "Małkowski",     position: "MID", overall: 68, apps: 15, goals: 1,  starting: true, "birthYear": 1985  },
      { name: "Sawala",        position: "MID", overall: 66, apps: 12, goals: 3,  starting: false, "birthYear": 1982 },
      { name: "Wacławczyk",    position: "MID", overall: 64, apps: 17, goals: 1,  starting: false, "birthYear": 1987 },
      { name: "Olszar",        position: "MID", overall: 64, apps: 13, goals: 1,  starting: false, "birthYear": 1981 },
      { name: "Szymański D.",  position: "MID", overall: 63, apps: 19, goals: 0,  starting: false, "birthYear": 1995 },

      { name: "Piech",         position: "FWD", overall: 82, apps: 15, goals: 11, starting: true, "birthYear": 1985  },
      { name: "Ślusarski",     position: "FWD", overall: 72, apps: 22, goals: 5,  starting: true, "birthYear": 1981  },
      { name: "Mak M.",        position: "FWD", overall: 65, apps: 34, goals: 2,  starting: false, "birthYear": 1991 },
      { name: "Wroński",       position: "FWD", overall: 63, apps: 24, goals: 2,  starting: false, "birthYear": 1994 },
    ]
  },
{
    club: "Zawisza Bydgoszcz",
    season: "2014/15",
    "coaches": [{ "name": "Jorge Paixao" }, { "name": "Mariusz Rumak" }],
    players: [
      { name: "Sandomierski",  position: "GK",  overall: 74, apps: 28, goals: 0,  starting: true, "birthYear": 1989  },
      { name: "Witan",         position: "GK",  overall: 62, apps: 9,  goals: 0,  starting: false, "birthYear": 1990 },

      { name: "Wójcicki",      position: "DEF", overall: 74, apps: 36, goals: 1,  starting: true, "birthYear": 1988  },
      { name: "Andre Micael",  position: "DEF", overall: 72, apps: 33, goals: 2,  starting: true, "birthYear": 1989  },
      { name: "Ziajka",        position: "DEF", overall: 70, apps: 32, goals: 0,  starting: true, "birthYear": 1982  },
      { name: "Marić",         position: "DEF", overall: 68, apps: 17, goals: 0,  starting: true, "birthYear": 1987  },
      { name: "Strąk",         position: "DEF", overall: 65, apps: 18, goals: 0,  starting: false, "birthYear": 1983 },
      { name: "Pulhac",        position: "DEF", overall: 64, apps: 7,  goals: 0,  starting: false, "birthYear": 1984 },
      { name: "Araujo",        position: "DEF", overall: 64, apps: 11, goals: 0,  starting: false, "birthYear": 1988 },
      { name: "Ciechanowski",  position: "DEF", overall: 62, apps: 4,  goals: 0,  starting: false, "birthYear": 1996 },
      { name: "Nawotczyński",  position: "DEF", overall: 62, apps: 3,  goals: 0,  starting: false, "birthYear": 1982 },

      { name: "Drygas",        position: "MID", overall: 76, apps: 33, goals: 4,  starting: true, "birthYear": 1991  },
      { name: "Alvarinho",     position: "MID", overall: 74, apps: 32, goals: 8,  starting: true, "birthYear": 1990  },
      { name: "Mica",          position: "MID", overall: 70, apps: 21, goals: 4,  starting: true, "birthYear": 1993  },
      { name: "Luis Carlos",   position: "MID", overall: 70, apps: 18, goals: 2,  starting: true, "birthYear": 1987  },
      { name: "Mayevskiy",     position: "MID", overall: 68, apps: 18, goals: 1,  starting: false, "birthYear": 1988 },
      { name: "Kamiński S.",   position: "MID", overall: 66, apps: 16, goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Pawłowski B.",  position: "MID", overall: 66, apps: 15, goals: 0,  starting: false, "birthYear": 1992 },
      { name: "Predescu",      position: "MID", overall: 65, apps: 8,  goals: 1,  starting: false, "birthYear": 1987 },
      { name: "Smektała",      position: "MID", overall: 65, apps: 7,  goals: 1,  starting: false, "birthYear": 1987 },
      { name: "Łukowski",      position: "MID", overall: 62, apps: 10, goals: 0,  starting: false, "birthYear": 1996 },

      { name: "Barisić",       position: "FWD", overall: 78, apps: 18, goals: 8,  starting: true, "birthYear": 1986  },
      { name: "Świerczok",     position: "FWD", overall: 72, apps: 14, goals: 4,  starting: true, "birthYear": 1992  },
      { name: "Jorge Kadu",    position: "FWD", overall: 68, apps: 16, goals: 2,  starting: false, "birthYear": 1991 },
      { name: "Wagner",        position: "FWD", overall: 66, apps: 18, goals: 3,  starting: false, "birthYear": 1987 },
    ]
  }
);
