// Konfiguracja aplikacji i cytaty pisarzy
const writerCongratulations = [
    "Pisanie jest łatwe. Wystarczy usiąść przed pustą kartką papieru i czekać, aż na czole wykrwawią się krople krwi.\n— Ernest Hemingway",
    "Nie ma nic do pisania. Wszystko, co musisz zrobić, to usiąść przy maszynie do pisania i krwawić.\n— Ernest Hemingway",
    "Pisanie to nie jest praca. To jest coś, co robisz, aby przetrwać.\n— Charles Bukowski",
    "Pierwszy szkic czegokolwiek jest gównem.\n— Ernest Hemingway",
    "Piszę, aby dowiedzieć się, co myślę.\n— Joan Didion",
    "Słowa są źródłem zarówno nieporozumień, jak i zrozumienia.\n— Antoine de Saint-Exupéry",
    "Pisanie jest aktem wiary, a nie sztuczką gramatyczną.\n— E.B. White",
    "Jeśli nie możesz tego jasno napisać, prawdopodobnie nie myślisz o tym jasno.\n— Saul Bellow",
    "Zamknij drzwi. Pisarz, który się boi swojego wydawcy, matki, żony, prawników - pisarz, który się boi czegokolwiek - jest stracony.\n— Philip Roth",
    "Nie możesz czekać na inspirację. Musisz za nią gonić kijem.\n— Jack London",
    "Pisanie jest odkrywaniem. Nie możesz wiedzieć, co się stanie, dopóki nie napiszesz.\n— E.L. Doctorow",
    "Jeśli historia nie wywołuje uczuć w pisarzu, nie może wywołać ich w czytelniku.\n— Roald Dahl",
    "Pisanie to jedyny sposób, w jaki mogę uporządkować chaos w mojej głowie.\n— Francesca Lia Block",
    "Nie pisz tego, co wiesz. Pisz to, co chcesz poznać.\n— Don DeLillo",
    "Każdy pierwszy szkic jest doskonały, ponieważ wszystko, co musi zrobić, to istnieć.\n— Jane Smiley",
    "Pisarstwo to samotność w towarzystwie słów.\n— William Styron",
    "Piszę po to, by uczynić życie dwukrotnym.\n— Anais Nin",
    "Pisanie książki to straszna, wyczerpująca walka, jak długi atak bolesnej choroby.\n— George Orwell",
    "Pisanie to sposób na rozmowę, gdy nikt nie pozwoli ci przerwać.\n— Fran Lebowitz",
    "Aby pisać, musisz mieć dużo czasu wolnego głowy.\n— Brenda Ueland",
    "Pisanie to odkrywanie tego, co już wiesz.\n— Flannery O'Connor",
    "Najpierw zapomnij o inspiracji. Nawyk jest trwalszy. Nawyk będzie podtrzymywał cię, czy jesteś zainspirowany, czy nie.\n— Octavia Butler",
    "Jeśli moja pisownia jest zła, nie jestem głupi. Po prostu nie mogę przeliterować.\n— Mark Twain",
    "Wypełnij swój papier wydechem serca.\n— William Wordsworth",
    "Pisanie to pokonywanie codziennego oporu.\n— Steven Pressfield",
    "Nie ma przyjemności większej niż ta, którą daje pisanie, gdy udaje się udane zdanie.\n— Barbara Tuchman",
    "Pisanie to sposób na życie dwukrotnym.\n— Catherine Drinker Bowen",
    "Każdy sekret duszy poety, każde doświadczenie jego życia, każda cecha jego umysłu jest w jego wierszach.\n— Virginia Woolf",
    "Pisanie jest aktem dumy.\n— Janet Frame",
    "Pisanie to brudna robota, ale ktoś musi to robić.\n— Rita Mae Brown",
    "Sztuka pisania polega na tym, by pozwolić, aby słowa wyszły z ciebie.\n— Natalie Goldberg",
    "Pisanie nie jest życiem, ale myślę, że czasami może być sposobem na życie.\n— Stephen King",
    "Dobrze pisać, to prawie myśleć.\n— Gustave Flaubert",
    "Pisanie to jedyny zawód, w którym nikt nie uważa cię za aroganta, jeśli mówisz, że jesteś dobry.\n— John Updike",
    "Pisanie to robienie znaczenia.\n— Robert Frost",
    "Pisanie jest samotne. To towarzystwo tylko z tym, co napisałeś.\n— James Baldwin",
    "Jeśli chcesz być pisarzem, przede wszystkim musisz robić dwie rzeczy: dużo czytać i dużo pisać.\n— Stephen King",
    "Nie ma reguły, jak pisać. Czasami przychodzi jak ciepły deszcz. Czasami jak kawałek kory z drzewa.\n— Charles Bukowski",
    "Pisanie to łagodny, intymny rozmowa między tobą a stroną.\n— Maya Angelou",
    "Jedyna zasada pisania: nie nudzić.\n— Kingsley Amis",
    "Pisanie to akt nadziei.\n— John Steinbeck",
    "Pisanie niczym się nie różni od medytacji lub modlitwy.\n— Paulo Coelho",
    "Jeśli nie masz czasu na przeczytanie, nie masz czasu ani narzędzi do pisania.\n— Stephen King",
    "Pisanie to droga do siebie.\n— Hermann Hesse",
    "Bądź sobą. Każdy inny jest już zajęty.\n— Oscar Wilde",
    "Pisanie jest łatwe: wystarczy wpatrywać się w pustą kartkę, aż na czole pojawią się krople krwi.\n— Gene Fowler",
    "Sekret dobrego pisania to mówienie prawdy.\n— Gordon Lish",
    "Zastanawiam się, czy to, co napisałem ma znaczenie dla kogokolwiek poza mną.\n— Franz Kafka",
    "Pisanie to sposób wyrażania tego, kim jesteś.\n— Muriel Spark",
    "Pisanie to tworzenie świata z niczego.\n— Margaret Atwood",
    "Pozbądź się wszystkiego, co nie jest opowieścią.\n— Anton Chekhov",
    "Pisanie jest formą terapii.\n— Graham Greene",
    "Czytamy, żeby wiedzieć, że nie jesteśmy sami.\n— C.S. Lewis",
    "Pisanie to najgłębsza forma czytania życia.\n— Marguerite Duras",
    "Pisanie wymaga ciszy, ale cisza wymaga odwagi.\n— Alice Munro",
    "Dobra proza jest jak szyba okienna.\n— George Orwell",
    "Piękno pisania polega na tym, że nie musisz czekać na odpowiedź.\n— Gabriel García Márquez",
    "Pisanie to podróż w nieznane.\n— Umberto Eco",
    "Musisz pisać książkę, która chce być napisana.\n— Madeleine L'Engle",
    "Pisanie jest łatwe. Wystarczy skreślić złe słowa.\n— Mark Twain",
    "Sztuka pisania polega na usuwaniu.\n— Ezra Pound",
    "Nigdy nie pisz o miejscu, dopóki nie opuścisz go.\n— Ernest Hemingway",
    "Pisanie to delikatna, ale mięsista sztuka.\n— Vladimir Nabokov",
    "Pisanie jest najlepszym sposobem rozmowy z ludźmi, których nie znasz.\n— Larry McMurtry",
    "Pisanie jest społecznym aktem.\n— Anne Lamott",
    "Pisanie to nie jest praca. To jest sposób życia.\n— John Irving",
    "Trudne pisanie sprawia łatwą lekturę.\n— William Zinsser",
    "Pisanie jest jak prowadzenie samochodu w nocy. Widzisz tylko to, co znajduje się w światłach reflektorów.\n— E.L. Doctorow",
    "Muszę pisać każdego dnia. Jeśli podróżuję, piszę w hotelach.\n— Graham Greene",
    "Pisanie to ekstremalna forma samotności.\n— Paul Auster",
    "Pisanie to ucieczka w fikcję.\n— Jhumpa Lahiri",
    "To, co naprawdę chcę powiedzieć, to to, że pisanie jest trudne.\n— Zadie Smith",
    "Pisanie wymaga dyscypliny i cierpliwości.\n— Haruki Murakami",
    "Pisanie jest jak medytacja. Musisz być obecny.\n— Natalie Goldberg",
    "Pisanie to praca ciężka. Dzień po dniu, słowo po słowie.\n— Octavia Butler",
    "Pisz pijany, edytuj trzeźwy.\n— Peter De Vries",
    "Nie pisz tego, co się sprzedaje. Pisz to, co kochasz.\n— Ray Bradbury",
    "Pisanie jest aktem wsłuchiwania się w to, co chce zostać powiedziane.\n— Don Murray",
    "Pisanie to sposób na porządkowanie chaosu.\n— Toni Morrison",
    "Dobry pisarz posiada nie tylko własną duszę, ale i dusze swoich przyjaciół.\n— Friedrich Nietzsche",
    "Pisanie to jedna trzecia talent, dwie trzecie dyscyplina.\n— John Irving",
    "Pisanie książek jest najbardziej samotną profesją na świecie.\n— Sinclair Lewis",
    "Pisanie nie jest o zarabianiu pieniędzy. To o czynieniu cudów.\n— Francesca Lia Block",
    "Pisanie to myślenie na papierze.\n— William Zinsser",
    "Pisanie to nieustanne przezwyciężanie własnej przeciętności.\n— Witold Gombrowicz",
    "Wszystko, co napisane, jest kłamstwem. Wszystko, co niewypowiedziane, jest prawdą.\n— Wisława Szymborska",
    "Pisanie jest przede wszystkim milczeniem.\n— Zbigniew Herbert",
    "Słowo raz wypowiedziane, jak kamień rzucony w wodę - krąg za kręgiem się rozchodzi.\n— Czesław Miłosz",
    "Pisarz musi być głosem tych, którzy nie mogą mówić.\n— Ryszard Kapuściński",
    "Pisanie to odkrywanie tajemnic, które się w nas kryją.\n— Olga Tokarczuk",
    "Literatura jest grą, którą toczymy z nieuchronnością losu.\n— Stanisław Lem",
    "Pisać - to znaczy podróżować bez trudu zmęczenia.\n— Julian Tuwim",
    "Trzeba pisać tak, jakby się było pierwszym człowiekiem, który to robi.\n— Witold Gombrowicz",
    "Pisanie jest jak oddychanie - jeśli przestanę, umrę.\n— Wisława Szymborska"
];
