// ============================================================
// KOMENTARZE — cała treść tekstowa silnika (oddzielona od logiki).
// Dwa style: classic (KLASYCZNY, log/terse) / waldemar (KOMENTATOR, narracyjny).
// Wczytywany PRZED głównym plikiem silnika (silnik_test.html).
// ============================================================

const COMMENTARY_STYLES = {
  classic: {
    goalFor: [
      '[GOL] {p} — Twoja drużyna.',
    ],
    goalAgainst: [
      '[GOL] {p} ({team}).',
    ],
    gkSaveMe: [
      '[OBRONA] {gk} broni strzał {p}.',
    ],
    gkSaveOpp: [
      '[OBRONA] Twój bramkarz {gk} broni strzał {p} ({team}).',
    ],
    missWideMe: [
      '[STRZAŁ NIECELNY] {p} — Twoja drużyna.',
    ],
    missWideOpp: [
      '[STRZAŁ NIECELNY] {p} ({team}).',
    ],
    flavor: [
      '[GRA] Piłka w środku pola, bez klarownej sytuacji.',
      '[GRA] Wymiana podań, tempo umiarkowane.',
      '[GRA] Przerwa w grze — interwencja sędziego.',
      '[GRA] Faza porządkowania linii przez obie drużyny.',
      '[GRA] Gra toczy się bez wyraźnej przewagi żadnej ze stron.',
    ],
    flavorAnegdota: [
      '[UWAGA] {p} na piłce przy linii bocznej.',
      '[UWAGA] {p} rozgrzewa się na murawie.',
      '[UWAGA] Krótka wymiana zdań z udziałem {p}.',
      '[UWAGA] {p} otrzymuje opiekę fizjoterapeuty przy linii.',
    ],
    subtypeIntro: {
      'rzut rożny': {
        me: ['[ŚREDNIE ZAGROŻENIE] Rzut rożny — Twoja drużyna.'],
        opp: ['[ŚREDNIE ZAGROŻENIE] Rzut rożny — {team}.'],
      },
      'długi wyrzut z autu': {
        me: ['[ŚREDNIE ZAGROŻENIE] Długi wyrzut z autu — Twoja drużyna.'],
        opp: ['[ŚREDNIE ZAGROŻENIE] Długi wyrzut z autu — {team}.'],
      },
      'rzut wolny z daleka': {
        me: ['[ŚREDNIE ZAGROŻENIE] Rzut wolny z dystansu — Twoja drużyna.'],
        opp: ['[ŚREDNIE ZAGROŻENIE] Rzut wolny z dystansu — {team}.'],
      },
      'akcja indywidualna': {
        me: ['[ŚREDNIE ZAGROŻENIE] Akcja indywidualna — Twoja drużyna.'],
        opp: ['[ŚREDNIE ZAGROŻENIE] Akcja indywidualna — {team}.'],
      },
      'strzał z daleka': {
        me: ['[ŚREDNIE ZAGROŻENIE] Strzał z dystansu — Twoja drużyna.'],
        opp: ['[ŚREDNIE ZAGROŻENIE] Strzał z dystansu — {team}.'],
      },
      'dośrodkowanie': {
        me: ['[ŚREDNIE ZAGROŻENIE] Dośrodkowanie — Twoja drużyna.'],
        opp: ['[ŚREDNIE ZAGROŻENIE] Dośrodkowanie — {team}.'],
      },
      'piłka na wolne pole': {
        me: ['[ŚREDNIE ZAGROŻENIE] Podanie na wolne pole — Twoja drużyna.'],
        opp: ['[ŚREDNIE ZAGROŻENIE] Podanie na wolne pole — {team}.'],
      },
      'rzut wolny tuż sprzed pola karnego': {
        me: ['[DUŻE ZAGROŻENIE] Rzut wolny tuż przed polem karnym — Twoja drużyna.'],
        opp: ['[DUŻE ZAGROŻENIE] Rzut wolny tuż przed polem karnym — {team}.'],
      },
      'drybling w polu karnym': {
        me: ['[DUŻE ZAGROŻENIE] Drybling w polu karnym — Twoja drużyna.'],
        opp: ['[DUŻE ZAGROŻENIE] Drybling w polu karnym — {team}.'],
      },
      'szybka kontra': {
        me: ['[DUŻE ZAGROŻENIE] Szybka kontra — Twoja drużyna.'],
        opp: ['[DUŻE ZAGROŻENIE] Szybka kontra — {team}.'],
      },
    },
    penaltyAward: ['[KARNY] Faul na {p}. Sędzia wskazuje na wapno.'],
    penaltyTakerMe: ['[KARNY] Wykonawca: {p}.'],
    penaltyTakerOpp: ['[KARNY] Wykonawca: {p} ({team}).'],
    penaltyScoredMe: ['[KARNY GOL] {p} — Twoja drużyna.'],
    penaltyMissedMe: ['[KARNY NIECELNY] {p} — Twoja drużyna.'],
    penaltySavedMe: ['[KARNY OBRONIONY] Bramkarz broni strzał {p}.'],
    penaltyScoredOpp: ['[KARNY GOL] {p} ({team}).'],
    penaltyMissedOpp: ['[KARNY NIECELNY] {p} ({team}).'],
    penaltySavedOpp: ['[KARNY OBRONIONY] Twój bramkarz broni strzał {p} ({team}).'],
    yellowMe: ['[ŻÓŁTA KARTKA] {p} — Twoja drużyna.'],
    yellowOpp: ['[ŻÓŁTA KARTKA] {p} ({team}).'],
    redMe: ['[CZERWONA KARTKA] {p} — Twoja drużyna. (Overall -10)'],
    redOpp: ['[CZERWONA KARTKA] {p} ({team}). (Overall -10)'],
    secondYellowMe: ['[DRUGA ŻÓŁTA → CZERWONA] {p} — Twoja drużyna. (Overall -10)'],
    secondYellowOpp: ['[DRUGA ŻÓŁTA → CZERWONA] {p} ({team}). (Overall -10)'],
    injuryMe: ['[KONTUZJA] {p} — Twoja drużyna. (Overall -{impact})'],
    injuryOpp: ['[KONTUZJA] {p} ({team}). (Overall -{impact})'],
    formaMe: ['[DOBRA FORMA] {p} — Twoja drużyna. (Overall +1)'],
    formaOpp: ['[DOBRA FORMA] {p} ({team}). (Overall +1)'],
    bruiseMe: ['[STŁUCZENIE] {p} — Twoja drużyna. (Overall -1)'],
    bruiseOpp: ['[STŁUCZENIE] {p} ({team}). (Overall -1)'],
    crampMe: ['[SKURCZ] {p} — Twoja drużyna. (Overall -1)'],
    crampOpp: ['[SKURCZ] {p} ({team}). (Overall -1)'],
    inspiredMe: ['[ŚWIETNA FORMA] {p} — Twoja drużyna. (Overall +2)'],
    inspiredOpp: ['[ŚWIETNA FORMA] {p} ({team}). (Overall +2)'],
    win: ['[WYNIK] Zwycięstwo.'],
    draw: ['[WYNIK] Remis.'],
    loss: ['[WYNIK] Porażka.'],
  },

  waldemar: {
    goalFor: [
      '{p}! I ja Wam powiem szczerze, Drodzy Państwo — o takich chwilach się marzy, kiedy człowiek kładzie się spać jako mały chłopiec z piłką pod pachą!',
      'GOL! GOL! GOL! {p} nie zawiódł, bo klasy, Drodzy Państwo, klasy się nie kupuje w markecie — klasę się buduje latami, potem i łzami!',
      '{p}… {p}! Zobaczcie tylko to zagranie — to jest praca, praca i jeszcze raz praca, a nie żaden przypadek!',
      'Ale huknął! {p} wpisuje się na listę strzelców, a stadion oszalał — oszalał kompletnie, i ja razem z nim, Drodzy Państwo!',
      'Jest! Jest! Jest ten gol! {p} pokazuje sercem, zaangażowaniem i charakterem, że w piłce nagradzana jest odwaga!',
      '{p} strzela jak z armaty — i proszę Państwa, to jest właśnie ten moment, dla którego się ten futbol kocha, bez kalkulacji, bez wyrachowania!',
      'Cudowna akcja, cudowny finisz — {p}, ukłony w Twoją stronę! Tak kończy się ciężka, mrówcza praca na treningu, której nikt nie widzi!',
      '{p} — i pustka w oczach bramkarza rywala. Bo przeciwko sercu, Drodzy Państwo, przeciwko prawdziwemu sercu trudno się gra!',
      'Bomba! Bomba! {p} wpakował to pod poprzeczkę — takich goli się nie zapomina, takich goli się nie zapomina, powtarzam, nie zapomina nigdy!',
      'I ja się pytam, Drodzy Państwo: kto powiedział, że marzenia się nie spełniają? {p} właśnie udowodnił, że się spełniają — na boisku, tu i teraz!',
      'Główka! Główka jak z armaty — {p} wyskoczył nad całą obroną, i to jest siła charakteru, nie tylko wyskoku!',
      'Przewrotka! Przewrotka, Drodzy Państwo! {p} robi coś, co zapamiętamy na lata — to jest czysta sztuka, czysta poezja futbolu!',
      '{p} przymierzył z dystansu — i huk! Piłka wpada w okienko, a bramkarz nawet nie drgnął, bo nie miał szans!',
      'Rzut wolny i… gol! {p} posyła piłkę nad murem, prosto w róg — to jest technika godna najlepszych szkółek na świecie!',
      '{p} minął jednego, drugiego, trzeciego — i spokojnie, z zimną krwią, umieścił piłkę w siatce. Klasa sama się broni!',
      'Dobitka! {p} był czujny jak jastrząb i wykorzystał odbitą piłkę — refleks, refleks i jeszcze raz refleks!',
      'Piętka! Piętka, Drodzy Państwo! {p} oszukał całą obronę jednym genialnym ruchem — to się nazywa czuć piłkę!',
      '{p} przelobował bramkarza — delikatnie, z wyczuciem, jakby malował obraz, a nie strzelał gola!',
      'Kapitalne podanie, a na końcu {p} — i jest gol! To jest właśnie ten futbol drużynowy, o którym marzy każdy trener!',
      'Karny czy nie karny, {p} i tak by to załatwił — bo dziś ma ten dzień, ten jedyny dzień, kiedy wszystko się udaje!',
      '{p} strzela z pierwszej piłki, bez przyjęcia — i to jest instynkt, Drodzy Państwo, instynktu się nie da nauczyć!',
      'Kiwnął bramkarza jak dziecko na podwórku — {p} wchodzi z piłką do pustej bramki, a stadion eksploduje!',
      '{p} uderzył z zewnętrznego podbicia — sztuka, czysta sztuka, i pięknie się to kończy, bo piłka ląduje w siatce!',
      'Rykoszet, przypadek? Może i przypadek, ale {p} był tam, gdzie trzeba — a to też jest umiejętność, Drodzy Państwo!',
      'Strzał, odbicie od poprzeczki, i {p} dobija — takich goli szuka się w każdym albumie wspomnień!',
    ],
    goalAgainst: [
      'NIESTETY. {p} ({team}) trafia, a my musimy to teraz przełknąć, jak gorzką pigułkę, Drodzy Państwo.',
      'Gol dla {team}. {p} nie wybaczył — niestety, niestety, taka jest ta piłka, czasem brutalna, czasem po prostu niesprawiedliwa.',
      'I jest gol {p} ({team}). Boli to jak zawsze, ale w piłce, tak jak w życiu, trzeba umieć przegrywać z podniesioną głową.',
      'NIESTETY. Błąd, którego być nie powinno — {p} ({team}) karze nas za chwilę nieuwagi, a chwila nieuwagi w tym sporcie kosztuje krocie.',
      '{p} ({team}) trafia do siatki. Cisza na trybunach, ale ja Wam powiem — to jeszcze nie koniec tej historii, Drodzy Państwo, nie koniec!',
      'Gol dla {team}. {p} — zimny, skuteczny, bez litości. Niestety, ta piłka bywa okrutna dla tych, którzy na chwilę przestają wierzyć.',
      'I znowu NIESTETY. {p} ({team}) pokazuje, że w tej dyscyplinie liczy się każda sekunda skupienia, każda, bez wyjątku.',
      '{p} ({team}) trafia, a ja tylko powiem: to jest lekcja, którą trzeba odrobić — do przerwy, do końca meczu, do następnego spotkania.',
      'Główka {p} ({team}) — i NIESTETY, nasza obrona zasypia w najgorszym możliwym momencie.',
      'Rzut wolny, mur nie ustawiony jak trzeba, i {p} ({team}) karze nas bezlitośnie. Niestety, taki błąd się pamięta.',
      '{p} ({team}) huknął z dystansu — NIESTETY, nasz bramkarz nie miał żadnych szans przy takim uderzeniu.',
      'Kontra, prosta jak drut, i {p} ({team}) wykańcza akcję. Niestety, straciliśmy piłkę w złym miejscu, w złym czasie.',
      'Karny wykorzystany przez {p} ({team}) — NIESTETY, ale trzeba przyznać, że egzekutor był zimny jak lód.',
      'I to jest właśnie ten moment, Drodzy Państwo, kiedy {p} ({team}) odbiera nam kontrolę nad meczem. Niestety.',
      '{p} ({team}) dobija po naszym niedokładnym wybiciu — a ja powiem tylko: szczegóły, Drodzy Państwo, w piłce liczą się szczegóły.',
      'Przewrotka {p} ({team})! I NIESTETY, nawet ja muszę przyznać, że to było piękne, choć bolesne dla nas.',
      '{p} ({team}) uderza piętą — zuchwałe, skuteczne, i NIESTETY, my znowu gonimy wynik.',
      'Rzut karny, zimna krew {p} ({team}) — NIESTETY, nasz bramkarz poszedł w złą stronę.',
      'Strzał z pierwszej piłki, bez zastanowienia — {p} ({team}) karze nas za moment wahania. Niestety.',
      '{p} ({team}) trafia po fatalnym błędzie w naszej obronie — a takich błędów, Drodzy Państwo, po prostu nie można sobie pozwalać.',
      'Główka po rzucie rożnym — {p} ({team}) wyskoczył najwyżej, a my znowu, niestety, patrzymy na piłkę w siatce.',
      'Uderzenie z zewnętrznej części stopy — {p} ({team}) zaskakuje wszystkich, łącznie z naszym bramkarzem. Niestety.',
      'Dobitka po naszej niecelnej interwencji — {p} ({team}) nie daruje takiej okazji. To boli, Drodzy Państwo.',
      'Lob nad naszym bramkarzem — {p} ({team}) pokazuje klasę, a my NIESTETY musimy uznać wyższość rywala w tym momencie.',
      'Strzał zza pola karnego, prosto w okienko — {p} ({team}) nie zostawia nam żadnych szans. Niestety, taka piłka.',
    ],
    gkSaveMe: [
      'Bramkarz {gk} czaruje! Broni strzał {p} i to jest interwencja na miarę najlepszych archiwalnych nagrań, Drodzy Państwo!',
      '{gk} ratuje sytuację — {p} musi uznać wyższość rywala, choć uderzenie, powiem szczerze, było niezłe, bardzo niezłe.',
      'Refleks {gk}! {p} uderzył mocno, z sercem, ale bramkarz był szybszy o ten jeden, jedyny ułamek sekundy.',
      '{gk} broni jak lew broni swojego stada! Kapitalna parada po strzale {p} — oklaski się należą, oklaski!',
      'Cudowna interwencja {gk}! {p} był przekonany o golu, a tu proszę — bramkarz mówi: nie dzisiaj, moi drodzy, nie dzisiaj.',
      '{gk} wyciąga rękę jak po chleb — i broni! {p} łapie się za głowę, ale takie rzeczy się w piłce zdarzają.',
      'Ale obrona! {gk} ratuje honor swojej drużyny, a {p} może żałować, że nie mierzył odrobinę wyżej albo odrobinę niżej.',
      '{gk} nie daje się zaskoczyć — {p} próbował podstępu, ale doświadczenie bramkarza okazało się silniejsze niż młodzieńczy zapał.',
      'Parada roku! {gk} rzuca się w prawy róg i wybija piłkę na róg — {p} może tylko pokiwać głową z uznaniem.',
      '{gk} czyta zamiary {p} jak otwartą księgę — i broni z pełnym spokojem, jakby to była zwykła niedzielna sytuacja.',
      'Strzał był precyzyjny, ale {gk} okazał się jeszcze bardziej precyzyjny! {p} rozkłada ręce w geście niedowierzania.',
      'Reakcja błyskawiczna — {gk} broni strzał {p} niemal odruchowo, a to właśnie odróżnia dobrych bramkarzy od wielkich.',
      '{gk} wyskakuje jak sprężyna i odbija piłkę na rzut rożny! {p} był o centymetry od gola, Drodzy Państwo, o centymetry.',
      'Instynkt bramkarski w czystej postaci — {gk} broni strzał {p}, a stadion wstrzymuje oddech na chwilę dłużej.',
      '{p} próbował przewrotki, prosto pod poprzeczkę — ale {gk} był tam, gdzie trzeba, i wybija piłkę nad bramką.',
      'Strzał głową po dośrodkowaniu — {gk} wyskakuje nad {p} i łapie piłkę pewnie w locie.',
      '{p} uderzył z woleja, mocno, technicznie — ale {gk} pokazał refleks godny najlepszych lig świata.',
      'Rzut karny w wykonaniu {p}, a {gk} odgadł kierunek — parada, na którą czekaliśmy cały mecz!',
      '{gk} broni piętą, przypadkiem czy nie — {p} musi uznać, że dzisiaj szczęście jest po drugiej stronie.',
      'Uderzenie z ostrego kąta — {p} próbował sztuki, a {gk} pokazał, że doświadczenie zawsze się liczy.',
      '{p} strzelał z bliska, niemal na pewniaka — ale {gk} zdążył zablokować piłkę własnym ciałem, bez wahania.',
      'Rykoszet i {gk} musi reagować błyskawicznie — broni po strzale {p}, choć piłka zmieniła tor w ostatniej chwili.',
      '{p} próbował lobu znad szesnastki — ambitnie, ale {gk} cofnął się w porę i złapał piłkę bez trudu.',
      'Główka {p} z bliskiej odległości — {gk} ratuje sytuację refleksem, na jaki stać tylko najlepszych.',
      '{gk} demonstruje klasę światową — broni strzał {p} z linii bramkowej, gdy piłka już zdawała się być w siatce.',
    ],
    gkSaveOpp: [
      'Twój bramkarz {gk} ratuje nas w ostatniej chwili! {p} ({team}) rozkłada ręce z niedowierzaniem, a my odetchnęliśmy z ulgą!',
      '{gk} broni! I ja Wam powiem, Drodzy Państwo — to jest właśnie ten moment, kiedy bramkarz staje się bohaterem meczu.',
      'Kapitalna interwencja {gk}! {p} ({team}) uderzył jak trzeba, ale nasz bramkarz powiedział stanowcze: nie tędy droga.',
      '{gk} ratuje skórę całej drużyny! Bez tej obrony byłoby, Drodzy Państwo, zupełnie inaczej — a tak gramy dalej.',
      'Refleks jak z bajki — {gk} broni strzał {p} ({team}) i cała ławka rezerwowych wstaje z radości!',
      '{gk} nie oddał ani centymetra! {p} ({team}) próbował, ale przeciwko takiej postawie trudno cokolwiek zdziałać.',
      'Uff, uratowani! {gk} broni po strzale {p} ({team}), a serce na trybunach na chwilę stanęło w miejscu.',
      'Parada, jakiej nie powstydziłby się żaden wielki bramkarz — {gk} mówi {p} ({team}): nie tym razem, kolego.',
      '{gk} wyczuwa niebezpieczeństwo o sekundę wcześniej niż wszyscy inni — i broni strzał {p} ({team}) w kapitalnym stylu.',
      'To jest dokładnie to, za co się płaci bramkarzom, Drodzy Państwo — {gk} broni {p} ({team}) i ratuje nas przed katastrofą.',
      '{gk} rzuca się plecami do bramki i odbija piłkę nad poprzeczkę! {p} ({team}) nie wierzy własnym oczom.',
      'Bramkarska klasa światowa — {gk} broni strzał {p} ({team}), a my znowu żyjemy w tym meczu.',
      'Ratunek w ostatniej sekundzie! {gk} wybija piłkę sprzed linii bramkowej po strzale {p} ({team}) — bohater, prawdziwy bohater!',
      '{p} ({team}) próbował przewrotki — ale {gk} zareagował błyskawicznie i wybił piłkę na róg, ratując nas przed pewnym golem.',
      'Główka po rzucie rożnym — {gk} wyskakuje najwyżej i łapie piłkę pewnie, mimo tłoku w polu karnym.',
      '{p} ({team}) uderzył z woleja, technicznie i mocno — ale {gk} pokazał refleks godny najlepszych archiwów.',
      'Rzut karny {p} ({team}) — a {gk} odgaduje kierunek! Cały stadion wstaje z miejsc, Drodzy Państwo!',
      '{gk} broni instynktownie, niemal bez zastanowienia — {p} ({team}) może tylko pokiwać głową z uznaniem.',
      'Uderzenie z ostrego kąta — {p} ({team}) próbował sztuczki, a {gk} pokazał, że doświadczenie zawsze wygrywa.',
      '{p} ({team}) strzelał niemal na pewniaka — ale {gk} zablokował piłkę własnym ciałem, bez chwili wahania.',
      'Rykoszet zmienił tor lotu piłki — {gk} musiał reagować błyskawicznie, i zrobił to po mistrzowsku.',
      '{p} ({team}) próbował lobu — ambitnie, ale {gk} cofnął się w porę i złapał piłkę pewnie w powietrzu.',
      'Główka {p} ({team}) z bliska — {gk} ratuje sytuację refleksem, jaki mają tylko najlepsi na świecie.',
      '{gk} demonstruje klasę najwyższej próby — broni strzał {p} ({team}) tuż przy linii bramkowej.',
      'Kapitalny refleks {gk}! {p} ({team}) uderzył z bliska, ale bramkarz zdążył zareagować w ostatnim ułamku sekundy.',
    ],
    missWideMe: [
      'Strzela głową! I niestety nad poprzeczką — {p} łapie się za głowę, bo to była sytuacja jak z podręcznika.',
      '{p} huknął z zewnętrznej części stopy — efektowne, przyznaję, bardzo efektowne, ale niecelne.',
      'Strzał prosto w niebo! {p} próbował podkręcić piłkę, a podkręcił chyba tylko własne nerwy.',
      '{p} przymierzał się do woleja — brawo za odwagę, Drodzy Państwo, szkoda tylko za celność.',
      'Uderzenie prosto w ręce obrońcy — {p} chyba sam nie wierzy, że nie trafił choćby w światło bramki.',
      '{p} próbował przelobować bramkarza — pomysł piękny, iście artystyczny, ale wykonanie trochę gorsze.',
      'Strzał z pierwszej piłki, {p} nie miał nawet czasu na przymiarkę — i niestety, pudło.',
      '{p} uderzył technicznie, w sam róg — ale odrobinę, tylko odrobinę zabrakło precyzji.',
      'Główka po świetnym dośrodkowaniu — {p} nie trafił w światło bramki, a sytuacja była naprawdę gotowa, gotowa do wykorzystania.',
      '{p} przymierzał się długo, może zbyt długo, Drodzy Państwo — bo obrona zdążyła zablokować to uderzenie.',
      'Przewrotka, ambitna jak sam diabeł — {p} próbował czegoś niesamowitego, ale piłka poszła daleko obok słupka.',
      '{p} strzelał z pięknej pozycji, ale zabrakło tej ostatniej krzty spokoju — piłka mija bramkę o włos.',
      'Rzut wolny bezpośredni — {p} uderzył nad murem, ale i nad poprzeczką, niestety, o pół metra za wysoko.',
      '{p} próbował efektownego uderzenia zewnętrzną częścią stopy — efekt piękny dla oka, ale dla wyniku żaden.',
      'Piętka w polu karnym! {p} chciał zaskoczyć wszystkich, i zaskoczył — tylko że piłka poleciała w aut.',
      'Strzał z pół obrotu — {p} nie zdołał kontrolować siły uderzenia, i futbolówka odlatuje wysoko nad poprzeczkę.',
      '{p} dograł sobie piłkę idealnie do uderzenia, ale w decydującym momencie zabrakło tej odrobiny koncentracji.',
      'Kapitalne wejście w pole karne, ale finalne uderzenie {p} jest zbyt lekkie — bramkarz łapie piłkę bez trudu.',
      '{p} chciał zaskoczyć bramkarza uderzeniem po ziemi w bliższy róg — ale piłka nieznacznie mija słupek.',
      'Strzał zza pola karnego, mocny, ale niecelny — {p} posyła piłkę wysoko nad poprzeczkę, ku rozpaczy kibiców.',
      'Dobitka po rykoszecie — {p} nie zdążył ustawić nogi jak trzeba, i piłka ucieka w bok.',
      '{p} próbował zaskoczyć bramkarza strzałem z ostrego kąta — ambitnie, ale bramkarz miał to pod kontrolą, choć akurat obronić by nie musiał, bo piłka minęła słupek.',
      'Uderzenie z woleja po dośrodkowaniu — {p} nie trafił idealnie w piłkę, i całe uderzenie traci na sile i celności.',
      'Sytuacja sam na sam z bramkarzem, ale {p} przestrzelił — nerwy, Drodzy Państwo, w takich momentach zawodzą nawet najlepszych.',
      'Strzał zablokowany w ostatniej chwili przez obrońcę — {p} może żałować, że nie zdecydował się na podanie.',
    ],
    missWideOpp: [
      'Uff, {p} ({team}) nie trafił! I to jest nasz mały prezent od losu w tym meczu.',
      '{p} ({team}) pudłuje z niezłej pozycji — czasem, Drodzy Państwo, piłka potrafi wybaczać.',
      'Strzał {p} ({team}) mija słupek — nasza obrona odetchnęła, choć serce podeszło do gardła.',
      '{p} ({team}) nie wykorzystał okazji — a takich okazji, powiem szczerze, nie dostaje się codziennie.',
      'Nad poprzeczką! {p} ({team}) mógł nas ukarać, ale dziś fortuna sprzyja nam.',
      '{p} ({team}) próbował uderzenia z dystansu — ambitnie, ale bez większego zagrożenia.',
      'Pudło rywala! {p} ({team}) będzie żałował tej sytuacji przez resztę meczu, mogę się o to założyć.',
      '{p} ({team}) strzelał z ostrego kąta i posłał piłkę w boczną siatkę — próba godna pochwały, skuteczność żadna.',
      'Główka {p} ({team}) po rzucie rożnym idzie niecelnie — a my znowu unikamy najgorszego.',
      '{p} ({team}) miał czas i miejsce, ale spanikował — strzał leci wysoko ponad poprzeczkę.',
      'Rzut wolny {team} — {p} uderzył w mur, i to jest kolejna okazja zmarnowana przez rywali.',
      'Dobitka {p} ({team}) po odbitej piłce trafia prosto w trybuny — szczęście dziś po naszej stronie.',
    ],
    flavor: [
      'Kiedyś, Drodzy Państwo, piłka była prostsza — dzisiaj analiza na analizie, a serce gdzieś w tym wszystkim ginie. Ale tu, na tym boisku, ono jeszcze bije.',
      'Ja Wam powiem szczerze — to jest ten rodzaj meczu, który buduje charakter, i to nie tylko zawodnikom, ale i nam, kibicom.',
      'Proszę zobaczyć na to zaangażowanie, na tę walkę o każdą piłkę — z sercem, z pasją, z prawdziwym oddaniem.',
      'Tempo rośnie, Drodzy Państwo, tempo rośnie — a ja Wam powiem, że taki futbol trzeba szanować, bo nie zawsze się go dostaje w prezencie.',
      'Trybuny żyją tym meczem, i słusznie — bo to jest właśnie ta piłka, dla której warto wracać do stadionu tydzień w tydzień.',
      'Widzę tu walkę charakterów, nie tylko nóg — a to, moi drodzy, w dzisiejszym futbolu jest towarem coraz rzadszym.',
      'Patrzę na to boisko i myślę sobie: ile tu historii się jeszcze wydarzy, zanim sędzia gwizdnie po raz ostatni.',
      'Taki mecz, Drodzy Państwo, to jest lekcja pokory dla obu drużyn — bo piłka, jak życie, bywa nieprzewidywalna.',
      'Emocje rosną z każdą minutą, i ja to czuję, mimo że siedzę tu, w tej kabinie, a nie na boisku.',
      'To jest właśnie ten futbol, o którym marzyłem jako dzieciak, kopiąc gumową piłkę na osiedlowym boisku.',
      'Widzę determinację w oczach obu drużyn — a determinacja, moi drodzy, to połowa sukcesu w tym sporcie.',
      'Piękna pogoda na piłkę, piękna atmosfera na trybunach — czego chcieć więcej, Drodzy Państwo?',
      'Ten mecz pokazuje, że futbol to nie tylko wynik — to emocje, charaktery i chwile, które zapadają w pamięć.',
      'Słyszę doping z trybun, i ja Wam powiem — to jest paliwo, prawdziwe paliwo dla zawodników na boisku.',
      'Czuję, że w tym meczu jeszcze coś się wydarzy — takie przeczucie ma się po latach oglądania tej pięknej gry.',
      'Ten poziom intensywności, Drodzy Państwo, to jest coś, czego brakuje dzisiejszemu futbolowi na co dzień — a tu mamy to z nawiązką.',
      'Obie drużyny grają otwarcie, z odwagą — a ja to szanuję, bo strach przed porażką jeszcze nikogo nie zaprowadził na szczyt.',
      'Popatrzcie na ustawienie tej drużyny — dyscyplina taktyczna godna prawdziwych profesjonalistów.',
      'To jest mecz, w którym liczy się nie tylko noga, ale i głowa — a dziś obie drużyny myślą na boisku, nie tylko biegają.',
      'Widzę tu szacunek między zawodnikami, mimo ostrej walki — a to, moi drodzy, jest esencja sportu.',
      'Jaka atmosfera, jaka energia! Stadion żyje tym meczem od pierwszej do ostatniej minuty.',
      'Ten futbol przypomina mi czasy, kiedy liczyła się gra, a nie statystyki i procenty posiadania piłki.',
      'Widać, że obie drużyny przygotowały się do tego meczu z pełną powagą — szacunek dla sztabów szkoleniowych.',
      'To jest ta piłka, którą kocham — bez kalkulacji, z pełnym zaangażowaniem, od pierwszej do ostatniej minuty.',
      'Publiczność dopisała, atmosfera dopisała — teraz tylko czekamy na to, co jeszcze przyniesie ten mecz.',
      'Widzę w oczach zawodników głód zwycięstwa — a taki głód, Drodzy Państwo, jest bezcenny.',
      'Ten mecz to prawdziwa uczta dla oka — dynamika, tempo, i ani chwili nudy.',
      'Trener na ławce nie usiedzi na miejscu — widać, że emocje udzielają się wszystkim, łącznie ze sztabem.',
      'Obie drużyny szanują piłkę, szanują rywala — a to buduje piękny, wartościowy mecz.',
      'Czuję w powietrzu, że coś się szykuje — takie przeczucia rzadko mnie zawodzą, Drodzy Państwo.',
      'To jest właśnie ten rodzaj rywalizacji, który przywraca wiarę w to, że sport potrafi jednoczyć ludzi.',
      'Spójrzcie na zaangażowanie kibiców — bez nich, Drodzy Państwo, ten stadion byłby tylko pustym budynkiem.',
      'Tempo gry nie zwalnia ani na chwilę — obie drużyny grają tak, jakby to był mecz o wszystko.',
      'Widzę tu prawdziwą pasję, nie tylko profesjonalizm — a pasja, moi drodzy, jest tym, co odróżnia dobrych od wielkich.',
      'Ten mecz zasługuje na miejsce w kronikach klubowych — taka intensywność zdarza się rzadko.',
      'Obie ławki trenerskie żyją każdą akcją — widać, jak wiele ten mecz dla nich znaczy.',
      'To jest futbol w najczystszej postaci — walka, determinacja, i odrobina magii w każdej akcji.',
      'Kibice śpiewają nieprzerwanie — a taki doping, Drodzy Państwo, potrafi przenosić góry.',
      'Widzę, że obie drużyny grają z pełnym szacunkiem do rywala, ale bez cienia strachu.',
      'Ten mecz to lekcja dla młodych zawodników — tak wygląda prawdziwe zaangażowanie na boisku.',
      'Emocje na trybunach sięgają zenitu — a my, komentatorzy, mamy przywilej być tego świadkami.',
      'Ta atmosfera, ten doping, ta walka — to jest właśnie to, po co wraca się na stadiony, Drodzy Państwo.',
      'Widzę w tej grze coś więcej niż tylko rywalizację sportową — widzę pasję, która łączy pokolenia.',
      'Obie drużyny pokazują, że futbol to wciąż gra serca, nie tylko taktycznych planszy i statystyk.',
      'Ten poziom zaangażowania zawodników zasługuje na najwyższe uznanie, niezależnie od wyniku.',
      'Czuję, że kibice na długo zapamiętają ten mecz — takie emocje nie zdarzają się codziennie.',
      'To jest właśnie ten futbol, który sprawia, że wracam do tej kabiny komentatorskiej z przyjemnością od lat.',
      'Widzę tu walkę o każdy centymetr boiska — a to, Drodzy Państwo, świadczy o wielkim charakterze obu zespołów.',
      'Ta rywalizacja ma w sobie coś autentycznego — nie ma tu miejsca na udawanie, tylko czysta walka.',
      'Stadion dosłownie drży od emocji — a ja Wam powiem, że to jest właśnie ten futbol, który kochamy najbardziej.',
    ],
    flavorAnegdota: [
      '{p}… wiecie, Drodzy Państwo, ja pamiętam czasy, kiedy tacy chłopcy jak on grali na podwórku do zmroku, a mama wołała ich z okna na kolację.',
      'Patrzę na {p} i myślę sobie — ile trzeba było potu i łez, żeby dojść z małego boiska osiedlowego aż tutaj.',
      'A wiecie, że {p} zaczynał od zwykłej gumowej piłki? Dziś gra na takim poziomie, że aż chce się wierzyć w sprawiedliwość tego sportu.',
      'Kiedyś rozmawiałem z trenerem, który pamięta {p} jako dzieciaka — mówił, że już wtedy miał to coś, czego nie da się nauczyć.',
      '{p} to przykład na to, że w piłce liczy się nie tylko talent, ale i pokora — a tej pokory, Drodzy Państwo, nigdy za wiele.',
      'Ja Wam powiem szczerze — {p} to jest zawodnik, który zawsze zostaje po treningu dłużej niż inni. Takie rzeczy się w końcu opłacają.',
      'Patrzcie na {p} — to jest historia chłopca, który nie miał łatwego startu, a dziś gra na oczach tysięcy ludzi.',
      'Pamiętam pierwszy mecz {p} w seniorskiej piłce — nikt wtedy nie przypuszczał, że dojdzie tak daleko.',
      '{p} to zawodnik, który nigdy nie zapomniał, skąd wyszedł — a to buduje charakter bardziej niż jakikolwiek trening.',
      'Kiedyś świat był prosty, Drodzy Państwo — piłka, boisko, i marzenia takie jak te, które realizuje dziś {p}.',
      'Rozmawiałem kiedyś z ojcem {p} — powiedział mi, że syn od dziecka spał z piłką pod poduszką. I proszę, do czego to doprowadziło.',
      '{p} przeszedł długą drogę — od młodzieżowych rozgrywek, przez wątpliwości, aż po ten stadion, na którym dziś gra.',
      'To jest właśnie ten typ zawodnika, o którym opowiada się historie przy niedzielnym obiedzie — {p}, symbol ciężkiej pracy.',
      'Wiecie, że {p} kilka lat temu myślał o zakończeniu kariery? Dziś gra na najwyższym poziomie — to lekcja dla nas wszystkich.',
      'Patrzę na {p} i widzę w nim tę samą pasję, którą widziałem u chłopców grających na boisku z gumową bramką zamiast siatki.',
      '{p} zawsze powtarza, że sukces to suma małych, codziennych decyzji — a ja, Drodzy Państwo, w pełni się z tym zgadzam.',
      'Ciekawostka na dziś — {p} zaczynał jako zupełnie inny zawodnik, na innej pozycji, a dziś jest kluczową postacią tej drużyny.',
      'Wiecie, ile {p} musiał poświęcić, żeby tu dzisiaj stanąć? Rodzina, znajomi, wolne weekendy — to wszystko schodzi na drugi plan, kiedy w sercu jest futbol.',
    ],
    penaltyAward: [
      'Rzut karny! I serce bije mocniej, Drodzy Państwo — bo to może być moment, który zdecyduje o wszystkim.',
      'Jedenastka! Sędzia nie ma wątpliwości — a ja Wam powiem, że w takich chwilach cały stadion wstrzymuje oddech.',
      'Karny! I teraz, Drodzy Państwo, zaczyna się prawdziwy pojedynek nerwów — jeden na jeden, charakter przeciwko charakterowi.',
      'Rzut karny — i ja czuję, jak temperatura na trybunach rośnie z sekundy na sekundę.',
      'Jest karny! To jest właśnie ten moment, w którym liczy się nie tylko technika, ale i zimna krew.',
    ],
    penaltyTakerMe: [
      'Do piłki podchodzi {p} — ze spokojem, z charakterem, i ja mu szczerze kibicuję w tym momencie.',
      '{p} bierze na siebie odpowiedzialność — a to, Drodzy Państwo, wymaga prawdziwej odwagi.',
      'Widzę pewność w oczach {p} — dobry znak przed takim strzałem.',
      '{p} układa piłkę na jedenastym metrze — cały stadion zamiera w oczekiwaniu.',
    ],
    penaltyTakerOpp: [
      'Do piłki podchodzi {p} ({team}) — trzymajmy kciuki, Drodzy Państwo, trzymajmy mocno.',
      '{p} ({team}) bierze odpowiedzialność za ten strzał — zobaczymy, czy nerwy go nie zawiodą.',
      'Cała nasza nadzieja teraz w bramkarzu — {p} ({team}) układa piłkę na jedenastce.',
      '{p} ({team}) podchodzi pewnym krokiem — oby to była pewność pozorna, Drodzy Państwo.',
    ],
    introCounterMe: [
      'Kontra! Szybka, prosta, piękna w swojej prostocie — a ja Wam powiem, że takie akcje kocham najbardziej.',
      'Błyskawiczne przejście do przodu — obrona rywala zaskoczona, a my pędzimy jak burza!',
      'Kontratak, Drodzy Państwo, kontratak! Trzech na dwóch, i serce zaczyna bić szybciej.',
      'Piłka odbita, i od razu ruszamy do przodu — to jest ten futbol, który elektryzuje trybuny!',
      'Szybko, szybko! Nasza drużyna łapie rywala na przewadze liczebnej — kontra idealna!',
    ],
    introCounterOpp: [
      'Uwaga, kontra {team}! Nasza defensywa musi się teraz cofnąć szybciej niż myśli!',
      '{team} rusza z kontrą — i serce mi na chwilę zamarło, Drodzy Państwo.',
      'Groźna kontra rywala! Musimy się teraz bronić z pełną koncentracją, bo to może być bolesne.',
      'Szybkie przejście {team} do przodu — nasza obrona w niekorzystnym ustawieniu.',
      'Kontratak {team} rozwija się błyskawicznie — trzymajmy się mocno, Drodzy Państwo.',
    ],
    introFreekickMe: [
      'Rzut wolny w dogodnej pozycji — a takie sytuacje, jak mawiał mój ojciec, trzeba szanować.',
      'Twoja drużyna szykuje się do rzutu wolnego — stadion w napięciu, ja zresztą też.',
      'Rzut wolny tuż pod polem karnym — to jest okazja, której nie można zmarnować.',
      'Sędzia gwizdnął, mur ustawiony po drugiej stronie — teraz liczy się precyzja i odwaga.',
      'Świetna pozycja do rzutu wolnego — takie sytuacje kończą się czasem bramkami z kroniki towarzyskiej.',
    ],
    introFreekickOpp: [
      'Rzut wolny dla {team} w niebezpiecznej strefie — teraz liczy się mur, koncentracja i odrobina szczęścia.',
      '{team} ustawia się do rzutu wolnego — trzymajmy się mocno, Drodzy Państwo.',
      'Niebezpieczna sytuacja stałego fragmentu gry dla rywala — mur musi stać jak ściana.',
      'Sędzia wskazuje na rzut wolny dla {team} — moment, w którym nie można stracić koncentracji.',
      '{team} przygotowuje rzut wolny — a my musimy się teraz zorganizować w defensywie.',
    ],
    introCornerMe: [
      'Rzut rożny dla naszej drużyny — zamieszanie w polu karnym, a w takich momentach rodzą się bohaterowie.',
      'Wywalczyliśmy rzut rożny — teraz liczy się odwaga i dobre dośrodkowanie.',
      'Rożny dla nas! Wszyscy wysocy zawodnicy ruszają w pole karne rywala.',
      'Kolejny rzut rożny — a ja Wam powiem, że w takich sytuacjach decyduje odrobina szczęścia i dużo odwagi.',
      'Rożny dla naszej drużyny — teraz trzeba precyzyjnego dośrodkowania i odwagi w skoku.',
    ],
    introCornerOpp: [
      'Rzut rożny dla {team} — trzeba teraz pilnować każdego centymetra w polu karnym.',
      '{team} wywalcza rożnego — moment, w którym nie można stracić koncentracji ani na sekundę.',
      'Kolejny rożny dla rywala — nasza defensywa musi być czujna jak nigdy.',
      'Rożny {team} — a w takich sytuacjach, Drodzy Państwo, decydują centymetry i refleks.',
      '{team} dośrodkowuje z rogu boiska — teraz liczy się skupienie w polu karnym.',
    ],
    penaltyScoredMe: [
      '{p} nie zawodzi z jedenastu metrów — zimna krew i charakter, Drodzy Państwo, charakter przede wszystkim!',
      'Gol! {p} posyła piłkę pewnie do siatki — bramkarz nawet nie drgnął w dobrą stronę.',
      '{p} chłodno wykorzystuje karnego — to jest właśnie ta pewność siebie, którą się podziwia.',
      'Piłka w siatce! {p} pokazał nerwy ze stali, i to jest zasłużony gol.',
      '{p} nie zna litości z jedenastu metrów — precyzja i spokój w jednym.',
      'I jest gol! {p} zdejmuje ciężar z całego stadionu jednym pewnym uderzeniem.',
    ],
    penaltyMissedMe: [
      '{p} posyła piłkę nad poprzeczką… i ja Wam powiem szczerze, to boli, bo taka okazja nie trafia się codziennie.',
      'NIESTETY, {p} nie trafił z jedenastu metrów — nerwy czasem grają nam na przekór.',
      '{p} uderzył za lekko — bramkarz nawet nie musiał się wykazywać refleksem, wystarczyło stać w miejscu.',
      'Pudło z karnego! {p} będzie miał ciężką noc, ale w piłce, jak w życiu, trzeba wstać i iść dalej.',
      '{p} przestrzelił — a szkoda, bo cały stadion czekał na ten gol.',
      'Niewykorzystana szansa — {p} posyła piłkę w słupek, i to jest naprawdę bolesne dla całej drużyny.',
    ],
    penaltySavedMe: [
      'Bramkarz broni strzał {p} — niestety, dziś fortuna była po drugiej stronie.',
      '{p} uderzył nieźle, ale bramkarz rywala okazał się jeszcze lepszy — takie rzeczy się zdarzają.',
      'Kapitalna obrona po karnym {p} — czasem, Drodzy Państwo, przeciwnik po prostu zasługuje na uznanie.',
      'NIESTETY, bramkarz wyczuł kierunek strzału {p} — to jest klasa najwyższej próby po tamtej stronie.',
      '{p} nie zdołał pokonać bramkarza z jedenastu metrów — gorzka pigułka do przełknięcia.',
    ],
    penaltyScoredOpp: [
      '{p} ({team}) chłodno wykorzystuje jedenastkę — NIESTETY, nic tu nie da się zrobić.',
      'Gol z karnego dla {team}. {p} nie drżał — a my musimy to teraz przełknąć.',
      'NIESTETY, {p} ({team}) nie dał szans naszemu bramkarzowi — pewne uderzenie, pewny gol.',
      '{p} ({team}) wykorzystuje jedenastkę bez najmniejszych emocji — zimna krew rywala robi swoje.',
      'Karny wykorzystany przez {p} ({team}) — boli, ale trzeba to teraz odrobić na boisku.',
    ],
    penaltyMissedOpp: [
      '{p} ({team}) posyła piłkę nad poprzeczką — i ja Wam powiem, ulga na trybunach jest ogromna!',
      'Pudło rywala! {p} ({team}) zawiódł w kluczowym momencie — a my dostajemy drugie życie w tym meczu.',
      '{p} ({team}) nie trafił z jedenastu metrów — nerwy zawiodły, i to jest nasz mały prezent od losu.',
      'NIESTETY dla nich! {p} ({team}) przestrzelił karnego, a my odetchnęliśmy pełną piersią.',
    ],
    penaltySavedOpp: [
      'Nasz bramkarz broni rzut karny {p} ({team}) — i to jest bohaterstwo, prawdziwe bohaterstwo!',
      'Kapitalna obrona! Nasz golkiper czyta zamiary {p} ({team}) jak z otwartej księgi.',
      'Broni! Broni! Nasz bramkarz odgadł kierunek strzału {p} ({team}) — to jest klasa najwyższej próby!',
      'I to jest właśnie ten moment, w którym bramkarz staje się bohaterem całego meczu — broni po strzale {p} ({team})!',
    ],
    yellowMe: [
      '🟨 Żółta kartka dla {p} — emocje, Drodzy Państwo, emocje w piłce są nieodłączne, ale trzeba nad nimi panować.',
      '🟨 Sędzia sięga po żółty kartonik dla {p} — może i słusznie, choć zapał był tu godny pochwały.',
      '🟨 {p} na cenzurowanym — teraz musi grać z głową, żeby nie stracić więcej niż kartkę.',
      '🟨 Żółta dla {p} — czasem serce bierze górę nad rozsądkiem, i to jest ta cena.',
      '🟨 Sędzia nie miał wyjątku — {p} musiał otrzymać upomnienie za ten faul.',
      '🟨 {p} zbiera żółtą kartkę — teraz każda kolejna interwencja musi być czysta jak łza.',
    ],
    yellowOpp: [
      '🟨 Żółta kartka dla {p} ({team}) — sędzia nie odpuszcza, i chyba ma rację, Drodzy Państwo.',
      '🟨 {p} ({team}) na cenzurowanym — teraz musi grać z głową, nie tylko sercem.',
      '🟨 Sędzia upomina {p} ({team}) — słusznie, bo ten faul był niepotrzebny.',
      '🟨 Żółta dla {p} ({team}) — rywal musi teraz uważać na każdy kolejny kontakt.',
      '🟨 {p} ({team}) zbiera kartkę za zbyt emocjonalną reakcję — piłka to gra ciała, nie nerwów.',
      '🟨 Sędzia wyciąga żółty kartonik dla {p} ({team}) — i słusznie, bo cierpliwość ma swoje granice.',
    ],
    redMe: [
      '🟥 Czerwona kartka dla {p}! I ja Wam powiem szczerze — to boli, bo teraz musimy grać sercem za dwóch. (Overall -10)',
      '🟥 {p} musi opuścić boisko! Sędzia nie miał wyboru, choć nam, Drodzy Państwo, ciężko to przyjąć. (Overall -10)',
      '🟥 Czerwona dla {p} — teraz czeka nas długa, trudna walka w dziesiątkę. (Overall -10)',
      '🟥 {p} widzi czerwoną kartkę — a to jest cios, który może zaważyć na całym meczu. (Overall -10)',
      '🟥 Sędzia pokazuje czerwony kartonik {p} — trzeba teraz zebrać się w sobie i grać z jeszcze większym sercem. (Overall -10)',
      '🟥 {p} kończy mecz przedwcześnie — a my musimy teraz pokazać prawdziwy charakter drużyny. (Overall -10)',
    ],
    redOpp: [
      '🟥 Czerwona kartka dla {p} ({team})! Sprawiedliwość, Drodzy Państwo, czasem przychodzi z opóźnieniem, ale przychodzi. (Overall -10)',
      '🟥 {p} ({team}) musi zejść z boiska! Rywal osłabiony, a my dostajemy szansę, na jaką czekaliśmy. (Overall -10)',
      '🟥 Czerwona dla {p} ({team}) — sędzia nie miał litości, i słusznie. (Overall -10)',
      '🟥 {p} ({team}) widzi czerwoną kartkę — teraz to my musimy wykorzystać tę przewagę liczebną. (Overall -10)',
      '🟥 Sędzia wyrzuca {p} ({team}) z boiska — moment, który może odmienić losy tego meczu. (Overall -10)',
      '🟥 {p} ({team}) kończy dzisiejszy mecz przedwcześnie — a my dostajemy prezent, którego nie możemy zmarnować. (Overall -10)',
    ],
    secondYellowMe: [
      '🟨🟥 Druga żółta dla {p} — i to jest czerwona! Gorzka lekcja, ale w piłce, jak w życiu, za nieopanowanie się płaci. (Overall -10)',
      '🟨🟥 {p} dostaje drugą żółtą kartkę — a to oznacza czerwoną i grę w osłabieniu. (Overall -10)',
      '🟨🟥 Niepotrzebna interwencja {p}, i mamy drugą żółtą — czerwona kartka to teraz fakt. (Overall -10)',
      '🟨🟥 {p} nie nauczył się na pierwszym upomnieniu — druga żółta, czerwona, i gramy w dziesiątkę. (Overall -10)',
      '🟨🟥 Sędzia nie ma litości — druga żółta dla {p} oznacza przedwczesny koniec jego meczu. (Overall -10)',
    ],
    secondYellowOpp: [
      '🟨🟥 Druga żółta, a więc czerwona dla {p} ({team})! Rywal osłabiony, a my dostajemy szansę, o jakiej marzyliśmy. (Overall -10)',
      '🟨🟥 {p} ({team}) dostaje drugie upomnienie — czerwona kartka i osłabienie rywala. (Overall -10)',
      '🟨🟥 Nierozważna interwencja {p} ({team}) kończy się drugą żółtą — czerwona to fakt. (Overall -10)',
      '🟨🟥 {p} ({team}) nie wyciągnął wniosków z pierwszej żółtej — teraz płaci najwyższą cenę. (Overall -10)',
      '🟨🟥 Sędzia pokazuje drugą żółtą {p} ({team}) — rywal musi dokończyć mecz w osłabieniu. (Overall -10)',
    ],
    injuryOpp: [
      '🚑 {p} ({team}) skręca kostkę — i ja Wam powiem szczerze, to jest ten moment, kiedy widać, jak wysoką cenę płaci się w tym sporcie. (Overall -{impact})',
      '🚑 Uraz mięśniowy {p} ({team}) — współczuję z całego serca, bo taka kontuzja to zawsze dramat dla zawodnika. (Overall -{impact})',
      '🚑 Zderzenie głowami, Drodzy Państwo, i {p} ({team}) musi zejść z boiska. Zdrowie jest najważniejsze, zawsze to powtarzam. (Overall -{impact})',
      '🚑 {p} ({team}) łapie się za kolano — i serce mi się kraje, bo to może być poważna sprawa. (Overall -{impact})',
      '🚑 Kontuzja barku {p} ({team}) — kończy mecz przedwcześnie, a szkoda, bo dobrze dziś grał. (Overall -{impact})',
      '🚑 Skurcz mięśnia u {p} ({team}) — ciało odmawia posłuszeństwa, a to w piłce, Drodzy Państwo, zdarza się najlepszym. (Overall -{impact})',
      '🚑 {p} ({team}) upada po niefortunnym skręceniu nogi — sztab medyczny już biegnie na pomoc. (Overall -{impact})',
      '🚑 Uraz pleców {p} ({team}) — czasem ciało mówi dość, nawet jeśli serce chce grać dalej. (Overall -{impact})',
      '🚑 {p} ({team}) doznaje kontuzji łydki — i to jest ten moment, kiedy trzeba uszanować decyzję lekarza drużynowego. (Overall -{impact})',
      '🚑 Nieszczęśliwy upadek {p} ({team}) — kontuzja nadgarstka kończy jego udział w dzisiejszym spotkaniu. (Overall -{impact})',
      '🚑 {p} ({team}) czuje ból w pachwinie — schodzi z boiska, a rywal traci ważnego zawodnika. (Overall -{impact})',
      '🚑 Uraz głowy po starciu w powietrzu — {p} ({team}) musi ustąpić miejsca, bezpieczeństwo przede wszystkim. (Overall -{impact})',
    ],
    formaMe: [
      '{p} ma dziś wyjątkowy dzień — widać to w każdym zagraniu, Drodzy Państwo, w każdym! (Overall +1)',
      '{p} w znakomitej dyspozycji — i ja Wam powiem szczerze, takie dni w karierze pamięta się latami. (Overall +1)',
      'Świetny dzień {p} — pewność siebie, charakter, wszystko na swoim miejscu. (Overall +1)',
      '{p} rozkręca się z minuty na minutę — czuć, że dziś chce zapisać się w tym meczu złotymi literami. (Overall +1)',
      '{p} gra dziś jakby o klasę wyżej — takie mecze buduje się latami ciężkiej pracy. (Overall +1)',
      'Widać po {p}, że dziś wszystko układa się po jego myśli — pewność w każdym ruchu. (Overall +1)',
      '{p} jest dziś nie do zatrzymania — energia, zaangażowanie i czysta radość z gry. (Overall +1)',
      'To jest ten dzień {p}, o którym będzie opowiadał wnukom — wszystko wychodzi jak z nut. (Overall +1)',
    ],
    injuryMe: [
      '🚑 {p} skręca kostkę — i ja Wam powiem szczerze, to jest ten moment, kiedy widać, jak wysoką cenę płaci się w tym sporcie. (Overall -{impact})',
      '🚑 Uraz mięśniowy {p} — współczuję z całego serca, bo taka kontuzja to zawsze dramat dla zawodnika. (Overall -{impact})',
      '🚑 Zderzenie głowami, Drodzy Państwo, i {p} musi zejść z boiska. Zdrowie jest najważniejsze, zawsze to powtarzam. (Overall -{impact})',
      '🚑 {p} łapie się za kolano — i serce mi się kraje, bo to może być poważna sprawa. (Overall -{impact})',
      '🚑 Skurcz mięśnia u {p} — ciało odmawia posłuszeństwa, a to w piłce, Drodzy Państwo, zdarza się najlepszym. (Overall -{impact})',
      '🚑 {p} czuje ból w pachwinie — schodzi z boiska, a to ważny zawodnik dla naszej drużyny. (Overall -{impact})',
    ],
    formaOpp: [
      '{p} ({team}) ma dziś wyjątkowy dzień — widać to w każdym zagraniu, Drodzy Państwo, w każdym! (Overall +1)',
      '{p} ({team}) w znakomitej dyspozycji — i ja Wam powiem szczerze, takie dni w karierze pamięta się latami. (Overall +1)',
      'Świetny dzień {p} ({team}) — pewność siebie, charakter, wszystko na swoim miejscu. (Overall +1)',
      '{p} ({team}) rozkręca się z minuty na minutę — czuć, że dziś chce zapisać się w tym meczu złotymi literami. (Overall +1)',
    ],
    bruiseMe: [
      '🩹 {p} obrywa w starciu i ma stłuczenie — kuleje przez chwilę, ale, Drodzy Państwo, taki futbol, trzeba grać dalej. (Overall -1)',
      '🩹 Widać, że {p} coś sobie stłukł po tym kontakcie — nic groźnego, ale odrobinę mu to dziś ciąży. (Overall -1)',
      '🩹 {p} skarży się na ból po starciu — masażysta już przy linii bocznej, ale zawodnik zostaje na boisku. (Overall -1)',
    ],
    bruiseOpp: [
      '🩹 {p} ({team}) ma stłuczenie po starciu — kuleje przez chwilę, ale, Drodzy Państwo, taki futbol. (Overall -1)',
      '🩹 Widać, że {p} ({team}) coś sobie stłukł po tym kontakcie — nic groźnego, ale odrobinę mu to dziś ciąży. (Overall -1)',
      '🩹 {p} ({team}) skarży się na ból po starciu — masażysta już przy linii bocznej. (Overall -1)',
    ],
    crampMe: [
      '🦵 {p} łapie skurcz łydki — ciało mówi dość, ale duch, Drodzy Państwo, każe grać dalej. (Overall -1)',
      '🦵 Widać, jak {p} rozciąga nogę na boisku — skurcz, ale zawodnik zostaje w grze. (Overall -1)',
      '🦵 {p} chwyta się za łydkę — klasyczny skurcz, trochę tempa mu dziś ubędzie. (Overall -1)',
    ],
    crampOpp: [
      '🦵 {p} ({team}) łapie skurcz łydki — ciało mówi dość, ale duch każe grać dalej. (Overall -1)',
      '🦵 Widać, jak {p} ({team}) rozciąga nogę na boisku — skurcz, ale zawodnik zostaje w grze. (Overall -1)',
      '🦵 {p} ({team}) chwyta się za łydkę — klasyczny skurcz, trochę tempa mu dziś ubędzie. (Overall -1)',
    ],
    inspiredMe: [
      '🔥 {p} gra dziś jak uskrzydlony, Drodzy Państwo — takich dni w karierze ma się może kilka! (Overall +2)',
      '🔥 To jest zupełnie inny {p} niż zwykle — jakby ktoś włączył mu drugi bieg, którego nikt nie znał! (Overall +2)',
      '🔥 {p} unosi się dziś nad boiskiem — i ja Wam powiem szczerze, piękniej grać się chyba nie da. (Overall +2)',
    ],
    inspiredOpp: [
      '🔥 {p} ({team}) gra dziś jak uskrzydlony — takich dni w karierze ma się może kilka. (Overall +2)',
      '🔥 To jest zupełnie inny {p} ({team}) niż zwykle — jakby ktoś włączył mu drugi bieg. (Overall +2)',
      '🔥 {p} ({team}) unosi się dziś nad boiskiem — musimy na niego bardzo uważać. (Overall +2)',
    ],
    win: [
      'Co za widowisko, Drodzy Państwo! Wygrana zasłużona, wywalczona sercem, charakterem i tą odrobiną szaleństwa, bez której futbolu by nie było.',
      'Zwycięstwo! I ja Wam powiem szczerze — takie mecze zapamiętuje się na lata, tak jak zapamiętuje się smak jagodzianki z dzieciństwa.',
      'Wygrywamy, i słusznie — bo klasy, charakteru i serca w tej drużynie dziś nie brakowało, ani przez chwilę.',
      'Euforia, Drodzy Państwo, prawdziwa euforia! Taki futbol trzeba szanować, bo nie zawsze przychodzi z łatwością.',
      'Zasłużone zwycięstwo — praca, pasja i wiara w siebie znowu zostały nagrodzone. Tak to w życiu, i w piłce, powinno działać.',
      'Wygrana, o jakiej się marzy — z sercem, z charakterem, i z tą odrobiną szczęścia, która w piłce też się liczy.',
      'To jest właśnie ten moment, dla którego kocha się futbol — radość, duma i satysfakcja z dobrze wykonanej pracy.',
      'Zwycięstwo zasłużone jak mało które — drużyna pokazała, że charakter i wiara w siebie potrafią przenosić góry.',
      'Wielkie brawa dla całej drużyny — to zwycięstwo to nagroda za tygodnie ciężkiej, mrówczej pracy na treningach.',
      'Ja Wam powiem szczerze, Drodzy Państwo — takie wygrane budują fundament pod całą resztę sezonu.',
      'Zwycięstwo, które pokazuje, że w tej drużynie drzemie prawdziwy potencjał — dziś zobaczyliśmy go w pełnej krasie.',
      'To jest wygrana z gatunku tych, które zmieniają nastawienie całej szatni na resztę sezonu.',
      'Kibice mogą wracać do domu z uśmiechem — a to, Drodzy Państwo, jest bezcenne w dzisiejszych czasach.',
      'Zasłużone trzy punkty — walka, determinacja i odrobina tej piłkarskiej magii złożyły się na to zwycięstwo.',
      'Widziałem dziś drużynę, która wierzy w siebie od pierwszej do ostatniej minuty — i to, moi drodzy, procentuje.',
      'To zwycięstwo to dowód na to, że ciężka praca zawsze się opłaca, prędzej czy później.',
      'Wygrywamy z klasą, wygrywamy z charakterem — trudno o lepsze podsumowanie tego spotkania.',
      'Taki wynik to najlepsza odpowiedź na wszystkich sceptyków — drużyna pokazała serce, kiedy było trzeba.',
      'Prawdziwa radość na trybunach — to zwycięstwo było wywalczone, a nie podarowane.',
      'Ja Wam powiem, Drodzy Państwo — takie mecze przypominają, dlaczego kochamy ten sport od dziecka.',
    ],
    draw: [
      'Remis, ale ja Wam powiem — to nie jest porażka. To jest walka do ostatniej sekundy, a taką walkę trzeba szanować.',
      'Punkt do podziału po zaciętym boju — czasem sprawiedliwość ma właśnie taki smak.',
      'Remis po prawdziwej wojnie nerwów. Charaktery pokazały się z dobrej strony po obu stronach.',
      'Żadna ze stron nie odpuściła ani centymetra — i to jest właśnie ta piłka, którą kocham.',
      'Sprawiedliwy remis, Drodzy Państwo — obie drużyny zasłużyły na ten punkt swoją postawą.',
      'Remis, który smakuje jak pół sukcesu — walka do samego końca była warta obejrzenia.',
      'Punkt zdobyty w trudnych okolicznościach — a ja Wam powiem, że czasem taki remis znaczy więcej niż zwycięstwo.',
      'Obie drużyny pokazały charakter — remis jest odzwierciedleniem wyrównanej, twardej walki.',
      'Remis, Drodzy Państwo, to nie zawsze porażka ambicji — czasem to po prostu uczciwy wynik dwóch równych rywali.',
      'Nikt dziś nie odpuścił, nikt się nie poddał — remis jest nagrodą za determinację obu zespołów.',
      'To był mecz, w którym każdy centymetr trzeba było wywalczyć — remis smakuje jak połowa sukcesu.',
      'Punkt, który w dłuższej perspektywie może się okazać cenniejszy, niż się dziś wydaje.',
      'Remis po walce do ostatniego gwizdka — takie mecze budują charakter całej drużyny.',
      'Obie strony mogą być zadowolone z postawy, choć pewnie żadna nie jest w pełni zadowolona z wyniku.',
      'To jest remis, który każe wierzyć, że przy odrobinie szczęścia moglibyśmy wygrać — a to dobry prognostyk na przyszłość.',
      'Sprawiedliwość futbolowa czasem wygląda właśnie tak — remis, kiedy obie drużyny zasłużyły na tyle samo.',
      'Zacięty pojedynek zakończony podziałem punktów — trudno się nie zgodzić, że taki wynik oddaje przebieg gry.',
      'Remis, ale z podniesioną głową — bo walka, jaką dziś widzieliśmy, zasługuje na szacunek.',
      'Punkt wywalczony w trudnym meczu — a ja Wam powiem, że czasem to jest właśnie to, czego drużyna potrzebuje.',
      'Remis, który zostawia niedosyt, ale też nadzieję — bo charakter, jaki dziś pokazaliśmy, prędzej czy później zaowocuje.',
    ],
    subtypeIntro: {
      'akcja indywidualna': {
        me: [
          'Nasz zawodnik bierze sprawy w swoje ręce — mija jednego, drugiego, i wciąż jest przy piłce.',
          'Indywidualna akcja naszego zawodnika — czasem taka odwaga popłaca.',
          'Zawodnik rusza sam z piłką przy nodze — obrona rywala musi teraz zdecydować, kto go przejmie.',
          'Solowa akcja, Drodzy Państwo — piłka przyklejona do nogi, rywale zostają w tyle.',
        ],
        opp: [
          'Zawodnik {team} rusza sam z piłką — nasza obrona musi teraz zdecydować, kto go przejmie.',
          'Indywidualna akcja rywala — {team} mija kolejnego przeciwnika.',
          '{team} bierze sprawy w swoje ręce — piłka wciąż przy jego nodze, musimy reagować.',
        ],
      },
      'piłka na wolne pole': {
        me: [
          'Piłka wysyłana na wolne pole — nasz napastnik rusza w pościg za nią.',
          'Genialne podanie prostopadłe, Drodzy Państwo — piłka leci na wolną przestrzeń za obroną rywala.',
          'Podanie na wolne pole — teraz liczy się tylko szybkość naszego zawodnika.',
        ],
        opp: [
          '{team} wysyła piłkę na wolne pole za naszą obronę — trzeba gonić z całych sił.',
          'Podanie prostopadłe od {team} — piłka leci w wolną przestrzeń, groźnie.',
          'Genialne podanie {team} na wolne pole — nasza obrona musi teraz gonić.',
        ],
      },
      'długi wyrzut z autu': {
        me: [
          'Długi rzut z autu — a takie podanie potrafi czasem zaskoczyć całą obronę rywala.',
          'Zawodnik ładuje piłkę do długiego auta — w polu karnym robi się gorąco.',
          'Rzut z autu na dystans, prosto w pole karne — ambitna, odważna decyzja.',
          'Długie auto, Drodzy Państwo — czasem taka prosta rzecz przynosi najwięcej zamieszania.',
          'Piłka leci daleko po długim aucie — obrona rywala musi się teraz zorganizować.',
        ],
        opp: [
          '{team} rzuca długie auto w nasze pole karne — trzeba teraz pilnować każdego metra.',
          'Długi wrzut z autu od {team} — zamieszanie w naszym polu karnym gwarantowane.',
          '{team} sięga po prosty, ale skuteczny sposób — długie auto prosto w szesnastkę.',
          'Rzut z autu na dystans od {team} — nasza defensywa musi być czujna.',
          'Piłka leci daleko po długim aucie {team} — teraz liczy się organizacja w obronie.',
        ],
      },
      'rzut rożny': {
        me: [
          'Rzut rożny dla naszej drużyny — zamieszanie w polu karnym, a w takich momentach rodzą się bohaterowie.',
          'Wywalczyliśmy rzut rożny — teraz liczy się odwaga i dobre dośrodkowanie.',
          'Rożny dla nas! Wszyscy wysocy zawodnicy ruszają w pole karne rywala.',
          'Kolejny rzut rożny — a ja Wam powiem, że w takich sytuacjach decyduje odrobina szczęścia i dużo odwagi.',
          'Rożny dla naszej drużyny — teraz trzeba precyzyjnego dośrodkowania i odwagi w skoku.',
        ],
        opp: [
          'Rzut rożny dla {team} — trzeba teraz pilnować każdego centymetra w polu karnym.',
          '{team} wywalcza rożnego — moment, w którym nie można stracić koncentracji ani na sekundę.',
          'Kolejny rożny dla rywala — nasza defensywa musi być czujna jak nigdy.',
          'Rożny {team} — a w takich sytuacjach, Drodzy Państwo, decydują centymetry i refleks.',
          '{team} dośrodkowuje z rogu boiska — teraz liczy się skupienie w polu karnym.',
        ],
      },
      'dośrodkowanie': {
        me: [
          'Dośrodkowanie z boku — piłka leci prosto w gęstwinę zawodników w polu karnym.',
          'Zawodnik centruje z bocznej strefy — teraz liczy się kto wyskoczy najwyżej.',
          'Piękne dośrodkowanie, Drodzy Państwo — piłka wisi w powietrzu jak zaproszenie do gola.',
          'Dośrodkowanie precyzyjne, prosto na głowę napastnika — to może być groźne.',
          'Boczna akcja kończy się dośrodkowaniem — pole karne rywala w kompletnym zamieszaniu.',
        ],
        opp: [
          '{team} centruje z boku — nasza obrona musi teraz pilnować pozycji.',
          'Dośrodkowanie od {team} — piłka leci w nasze pole karne, trzeba reagować szybko.',
          '{team} dograł z bocznej strefy — teraz liczy się czujność w szesnastce.',
          'Groźne dośrodkowanie {team} — nasi obrońcy muszą wygrać ten pojedynek w powietrzu.',
          'Piłka leci z boku po dośrodkowaniu {team} — moment pełen napięcia w naszym polu karnym.',
        ],
      },
      'rzut wolny z daleka': {
        me: [
          'Rzut wolny z dystansu — a takie sytuacje czasem kończą się bramkami z kroniki towarzyskiej.',
          'Zawodnik przymierza się do rzutu wolnego z daleka — mur rywala już się ustawia.',
          'Rzut wolny spod trzydziestu metrów — odwaga i technika będą tu kluczowe.',
          'Sędzia gwizdnął, a nasz zawodnik szykuje się do strzału z dystansu.',
          'Rzut wolny z dala od bramki — trzeba precyzji i mocnego uderzenia.',
        ],
        opp: [
          'Rzut wolny dla {team} z dystansu — nasz mur musi stanąć jak ściana.',
          '{team} przygotowuje strzał z rzutu wolnego z daleka — czujność w defensywie obowiązkowa.',
          'Rzut wolny spod trzydziestu metrów dla {team} — teraz liczy się ustawienie muru.',
          '{team} szykuje się do rzutu wolnego z dystansu — trzymajmy się mocno, Drodzy Państwo.',
          'Groźna sytuacja stałego fragmentu gry — {team} strzela z daleka.',
        ],
      },
      'strzał z daleka': {
        me: [
          'Nasz zawodnik przymierza się z dystansu — czasem taka odwaga bywa nagradzana golem.',
          'Strzał zza pola karnego szykuje się — Drodzy Państwo, w takich sytuacjach bywa różnie.',
          'Zawodnik decyduje się na uderzenie z daleka — ambicja godna pochwały.',
          'Przymiarka z dystansu — czasem właśnie tak rodzą się bramki roku.',
          'Nasz zawodnik nie boi się spróbować z daleka — odwaga to połowa sukcesu w piłce.',
        ],
        opp: [
          '{p} ({team}) przymierza się z dystansu — musimy być czujni na każdy taki strzał.',
          'Zawodnik {team} próbuje szczęścia z daleka — nasz bramkarz musi być skupiony.',
          '{team} decyduje się na uderzenie zza pola karnego — groźna sytuacja się szykuje.',
          'Przymiarka z dystansu od {team} — trzeba obserwować tor lotu piłki uważnie.',
          '{team} nie boi się spróbować z daleka — a takie próby czasem bywają zdradliwe.',
        ],
      },
      'rzut wolny tuż sprzed pola karnego': {
        me: [
          'Rzut wolny tuż pod polem karnym — a takie sytuacje, jak mawiał mój ojciec, trzeba szanować.',
          'Świetna pozycja do rzutu wolnego — takie sytuacje kończą się czasem bramkami z kroniki towarzyskiej.',
          'Rzut wolny w idealnym miejscu — teraz liczy się precyzja i odrobina odwagi.',
          'Sędzia gwizdnął tuż przed polem karnym — to jest okazja, której nie można zmarnować.',
          'Rzut wolny w znakomitej pozycji — mur rywala ustawia się z niepokojem.',
        ],
        opp: [
          'Rzut wolny dla {team} w niebezpiecznej strefie — teraz liczy się mur, koncentracja i odrobina szczęścia.',
          '{team} ustawia się do rzutu wolnego — trzymajmy się mocno, Drodzy Państwo.',
          'Niebezpieczna sytuacja stałego fragmentu gry dla rywala — mur musi stać jak ściana.',
          'Sędzia wskazuje na rzut wolny dla {team} w groźnej pozycji — moment pełen napięcia.',
          '{team} przygotowuje rzut wolny tuż pod naszym polem karnym — musimy być czujni.',
        ],
      },
      'szybka kontra': {
        me: [
          'Błyskawiczna akcja naszej drużyny — obrona rywala kompletnie zaskoczona tempem!',
          'Szybko, szybko! To jest akcja, która elektryzuje cały stadion, Drodzy Państwo!',
          'Piorunujące tempo naszej gry — rywal nie nadąża za tą szybkością!',
          'Błyskawiczne przejście przez pół boiska — to jest właśnie ten futbol, który kocham najbardziej!',
          'Akcja rozwija się w oka mgnieniu — obrona rywala musi teraz gonić własne nogi!',
        ],
        opp: [
          'Błyskawiczna akcja {team}! Nasza obrona musi teraz reagować szybciej niż myśli!',
          'Piorunujące tempo rywala — {team} zaskakuje nas dynamiką tej akcji!',
          'Uwaga, szybka akcja {team}! Trzymajmy się mocno, Drodzy Państwo!',
          '{team} rusza błyskawicznie do przodu — nasza defensywa w trudnym położeniu!',
          'Groźna, szybka akcja rywala — {team} rozwija ją w mgnieniu oka!',
        ],
      },
      'drybling w polu karnym': {
        me: [
          'Popis techniki naszego lidera — takie zagrania zapamiętuje się na lata, Drodzy Państwo!',
          'To jest klasa sama w sobie — nasz zawodnik pokazuje, na co go stać w tym momencie!',
          'Prawdziwy popis umiejętności — kilka min i drybling, który elektryzuje trybuny!',
          'Nasza gwiazda bierze sprawy w swoje ręce — a raczej w swoje nogi, i to jakie nogi!',
          'Czysta magia na boisku — nasz zawodnik pokazuje, dlaczego jest liderem tej drużyny!',
        ],
        opp: [
          'Popis techniki gwiazdy {team} — musimy uważać, bo to może skończyć się groźnie.',
          'Zawodnik {team} pokazuje wielką klasę — kilka min i piłka wciąż przy jego nodze.',
          'Prawdziwy popis umiejętności lidera {team} — nasza obrona ma poważny problem.',
          'Gwiazda {team} bierze sprawy w swoje ręce — trzeba teraz podwoić czujność.',
          'Czysta magia w wykonaniu zawodnika {team} — takie zagrania bywają zabójcze dla obrony.',
        ],
      },
    },
    loss: [
      'Porażka boli, Drodzy Państwo, zawsze boli. Ale w piłce, jak w życiu, trzeba umieć przegrywać z podniesioną głową.',
      'Dziś zabrakło odrobiny szczęścia i tej ostatniej dziesiątej procenta koncentracji. To się zdarza nawet najlepszym.',
      'Rywal był dziś lepszy, i trzeba to powiedzieć wprost, bez owijania w bawełnę. Szacunek za walkę do końca.',
      'Koniec marzeń na dziś, ale nie na zawsze — bo prawdziwy charakter poznaje się właśnie po porażkach.',
      'Bolesna lekcja, ale w futbolu, jak w życiu, upadki są częścią drogi do sukcesu.',
      'Porażka, która musi zaboleć — ale ja Wam powiem, że z takich meczów rodzi się prawdziwy charakter na przyszłość.',
      'Trudny dzień dla całej drużyny — ale to właśnie po takich meczach poznaje się prawdziwych zawodników.',
      'Dziś nie było naszego dnia, Drodzy Państwo — ale jutro znowu wychodzimy na trening i pracujemy dalej.',
      'Gorzka porażka, ale nie ma co załamywać rąk — sezon jest długi, a charakter tej drużyny nie budzi wątpliwości.',
      'Rywal zasłużył na to zwycięstwo swoją postawą — trzeba to uszanować i wyciągnąć wnioski.',
      'To boli, ale ja Wam powiem szczerze — najważniejsze, żeby wstać po takim ciosie i iść dalej z podniesioną głową.',
      'Porażka, która zapewne będzie bolała jeszcze długo w szatni — ale takie mecze uczą pokory.',
      'Zabrakło dziś tej iskry, tego czegoś, co zwykle odróżnia tę drużynę od przeciętności.',
      'Trudno o pocieszenie po takiej porażce — ale prawdziwych mistrzów poznaje się po tym, jak wracają po upadkach.',
      'Dziś rywal pokazał więcej głodu zwycięstwa — a to, Drodzy Państwo, w piłce bywa decydujące.',
      'Porażka boli podwójnie po takiej walce — ale szacunek dla zaangażowania, jakie dziś widzieliśmy.',
      'To jest lekcja, którą trzeba odrobić na najbliższych treningach — bez wymówek, bez usprawiedliwień.',
      'Ciężko to przyjąć, ale futbol bywa okrutny — czasem lepsza drużyna nie wygrywa, i to trzeba zaakceptować.',
      'Smutek na trybunach, smutek w szatni — ale ja Wam powiem, że po takich meczach rodzą się największe powroty.',
      'Porażka, ale nie klęska — bo charakter i zaangażowanie, jakie dziś widzieliśmy, to fundament na przyszłość.',
    ],
  },
};

// Podtypy akcji — druga warstwa nad "średnie/wielkie zagrożenie", czysto
// kategoryzująca (possession/sfg/ind/counter) pod przyszły system cech
// trenerskich/zawodniczych (np. "ekspert od wyrzutu z autu" mógłby premiować
// TYLKO 'długi wyrzut z autu', albo trait mógłby premiować całą kategorię
// 'counter'). Na razie liczba/siła szans na gola się NIE zmienia — rand()
// nadal wybiera jeden podtyp losowo z tej listy, wagi przez powtórzenia
// wpisów ustawiają "posiadanie"/"akcja kombinacyjna" jako zdecydowanie
// najczęstsze, zgodnie ze specyfikacją.
const MEDIUM_SUBTYPES = [
  { label: 'posiadanie', category: 'possession' },
  { label: 'posiadanie', category: 'possession' },
  { label: 'posiadanie', category: 'possession' },
  { label: 'posiadanie', category: 'possession' },
  { label: 'posiadanie', category: 'possession' },
  { label: 'posiadanie', category: 'possession' },
  { label: 'posiadanie', category: 'possession' },
  { label: 'posiadanie', category: 'possession' },
  { label: 'rzut rożny', category: 'sfg' },
  { label: 'długi wyrzut z autu', category: 'sfg' },
  { label: 'rzut wolny z daleka', category: 'sfg' },
  { label: 'akcja indywidualna', category: 'ind' },
  { label: 'strzał z daleka', category: 'ind' },
  { label: 'dośrodkowanie', category: 'possession' },
  { label: 'piłka na wolne pole', category: 'counter' },
];
const HIGH_SUBTYPES = [
  { label: 'akcja kombinacyjna', category: 'possession' },
  { label: 'akcja kombinacyjna', category: 'possession' },
  { label: 'akcja kombinacyjna', category: 'possession' },
  { label: 'rzut wolny tuż sprzed pola karnego', category: 'sfg' },
  { label: 'drybling w polu karnym', category: 'ind' },
  { label: 'szybka kontra', category: 'counter' },
];
