// ============================================================
// MUNDIAL 2026 — PRAWDZIWY podział grup (losowanie 5.12.2025, Kennedy
// Center, Waszyngton) + rozstrzygnięte baraże UEFA/interkontynentalne.
// SZWECJA (ścieżka barażowa B, Grupa F) ZAMIENIONA NA POLSKĘ na życzenie.
// Składy zawodników wciąż są ZAŚLEPKĄ — płaski overall na drużynę,
// odzwierciedlający orientacyjny poziom reprezentacji, do podmiany na
// prawdziwe składy, gdy zechcesz.
// ============================================================

window.MUNDIAL26_TEAMS_DATA = window.MUNDIAL26_TEAMS_DATA || [];
window.MUNDIAL26_TEAMS_DATA.push(
  {
    id: 'm26-meksyk',
    label: 'Meksyk',
    // ZAŚLEPKA — płaski overall 83 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Meksyk Zawodnik 01', position: 'GK', overall: 83, starting: true },
      { name: 'Meksyk Zawodnik 02', position: 'DEF', overall: 83, starting: true },
      { name: 'Meksyk Zawodnik 03', position: 'DEF', overall: 83, starting: true },
      { name: 'Meksyk Zawodnik 04', position: 'DEF', overall: 83, starting: true },
      { name: 'Meksyk Zawodnik 05', position: 'DEF', overall: 83, starting: true },
      { name: 'Meksyk Zawodnik 06', position: 'MID', overall: 83, starting: true },
      { name: 'Meksyk Zawodnik 07', position: 'MID', overall: 83, starting: true },
      { name: 'Meksyk Zawodnik 08', position: 'MID', overall: 83, starting: true },
      { name: 'Meksyk Zawodnik 09', position: 'MID', overall: 83, starting: true },
      { name: 'Meksyk Zawodnik 10', position: 'FWD', overall: 83, starting: true },
      { name: 'Meksyk Zawodnik 11', position: 'FWD', overall: 83, starting: true },
    ],
  },
  {
    id: 'm26-republika-poludniowej-afryki',
    label: 'Republika Południowej Afryki',
    // ZAŚLEPKA — płaski overall 72 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Republika Zawodnik 01', position: 'GK', overall: 72, starting: true },
      { name: 'Republika Zawodnik 02', position: 'DEF', overall: 72, starting: true },
      { name: 'Republika Zawodnik 03', position: 'DEF', overall: 72, starting: true },
      { name: 'Republika Zawodnik 04', position: 'DEF', overall: 72, starting: true },
      { name: 'Republika Zawodnik 05', position: 'DEF', overall: 72, starting: true },
      { name: 'Republika Zawodnik 06', position: 'MID', overall: 72, starting: true },
      { name: 'Republika Zawodnik 07', position: 'MID', overall: 72, starting: true },
      { name: 'Republika Zawodnik 08', position: 'MID', overall: 72, starting: true },
      { name: 'Republika Zawodnik 09', position: 'MID', overall: 72, starting: true },
      { name: 'Republika Zawodnik 10', position: 'FWD', overall: 72, starting: true },
      { name: 'Republika Zawodnik 11', position: 'FWD', overall: 72, starting: true },
    ],
  },
  {
    id: 'm26-korea-poludniowa',
    label: 'Korea Południowa',
    // ZAŚLEPKA — płaski overall 78 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Korea Zawodnik 01', position: 'GK', overall: 78, starting: true },
      { name: 'Korea Zawodnik 02', position: 'DEF', overall: 78, starting: true },
      { name: 'Korea Zawodnik 03', position: 'DEF', overall: 78, starting: true },
      { name: 'Korea Zawodnik 04', position: 'DEF', overall: 78, starting: true },
      { name: 'Korea Zawodnik 05', position: 'DEF', overall: 78, starting: true },
      { name: 'Korea Zawodnik 06', position: 'MID', overall: 78, starting: true },
      { name: 'Korea Zawodnik 07', position: 'MID', overall: 78, starting: true },
      { name: 'Korea Zawodnik 08', position: 'MID', overall: 78, starting: true },
      { name: 'Korea Zawodnik 09', position: 'MID', overall: 78, starting: true },
      { name: 'Korea Zawodnik 10', position: 'FWD', overall: 78, starting: true },
      { name: 'Korea Zawodnik 11', position: 'FWD', overall: 78, starting: true },
    ],
  },
  {
    id: 'm26-czechy',
    label: 'Czechy',
    // ZAŚLEPKA — płaski overall 76 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Czechy Zawodnik 01', position: 'GK', overall: 76, starting: true },
      { name: 'Czechy Zawodnik 02', position: 'DEF', overall: 76, starting: true },
      { name: 'Czechy Zawodnik 03', position: 'DEF', overall: 76, starting: true },
      { name: 'Czechy Zawodnik 04', position: 'DEF', overall: 76, starting: true },
      { name: 'Czechy Zawodnik 05', position: 'DEF', overall: 76, starting: true },
      { name: 'Czechy Zawodnik 06', position: 'MID', overall: 76, starting: true },
      { name: 'Czechy Zawodnik 07', position: 'MID', overall: 76, starting: true },
      { name: 'Czechy Zawodnik 08', position: 'MID', overall: 76, starting: true },
      { name: 'Czechy Zawodnik 09', position: 'MID', overall: 76, starting: true },
      { name: 'Czechy Zawodnik 10', position: 'FWD', overall: 76, starting: true },
      { name: 'Czechy Zawodnik 11', position: 'FWD', overall: 76, starting: true },
    ],
  },
  {
    id: 'm26-kanada',
    label: 'Kanada',
    // ZAŚLEPKA — płaski overall 80 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Kanada Zawodnik 01', position: 'GK', overall: 80, starting: true },
      { name: 'Kanada Zawodnik 02', position: 'DEF', overall: 80, starting: true },
      { name: 'Kanada Zawodnik 03', position: 'DEF', overall: 80, starting: true },
      { name: 'Kanada Zawodnik 04', position: 'DEF', overall: 80, starting: true },
      { name: 'Kanada Zawodnik 05', position: 'DEF', overall: 80, starting: true },
      { name: 'Kanada Zawodnik 06', position: 'MID', overall: 80, starting: true },
      { name: 'Kanada Zawodnik 07', position: 'MID', overall: 80, starting: true },
      { name: 'Kanada Zawodnik 08', position: 'MID', overall: 80, starting: true },
      { name: 'Kanada Zawodnik 09', position: 'MID', overall: 80, starting: true },
      { name: 'Kanada Zawodnik 10', position: 'FWD', overall: 80, starting: true },
      { name: 'Kanada Zawodnik 11', position: 'FWD', overall: 80, starting: true },
    ],
  },
  {
    id: 'm26-bosnia-i-hercegowina',
    label: 'Bośnia i Hercegowina',
    // ZAŚLEPKA — płaski overall 75 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Bośnia Zawodnik 01', position: 'GK', overall: 75, starting: true },
      { name: 'Bośnia Zawodnik 02', position: 'DEF', overall: 75, starting: true },
      { name: 'Bośnia Zawodnik 03', position: 'DEF', overall: 75, starting: true },
      { name: 'Bośnia Zawodnik 04', position: 'DEF', overall: 75, starting: true },
      { name: 'Bośnia Zawodnik 05', position: 'DEF', overall: 75, starting: true },
      { name: 'Bośnia Zawodnik 06', position: 'MID', overall: 75, starting: true },
      { name: 'Bośnia Zawodnik 07', position: 'MID', overall: 75, starting: true },
      { name: 'Bośnia Zawodnik 08', position: 'MID', overall: 75, starting: true },
      { name: 'Bośnia Zawodnik 09', position: 'MID', overall: 75, starting: true },
      { name: 'Bośnia Zawodnik 10', position: 'FWD', overall: 75, starting: true },
      { name: 'Bośnia Zawodnik 11', position: 'FWD', overall: 75, starting: true },
    ],
  },
  {
    id: 'm26-katar',
    label: 'Katar',
    // ZAŚLEPKA — płaski overall 70 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Katar Zawodnik 01', position: 'GK', overall: 70, starting: true },
      { name: 'Katar Zawodnik 02', position: 'DEF', overall: 70, starting: true },
      { name: 'Katar Zawodnik 03', position: 'DEF', overall: 70, starting: true },
      { name: 'Katar Zawodnik 04', position: 'DEF', overall: 70, starting: true },
      { name: 'Katar Zawodnik 05', position: 'DEF', overall: 70, starting: true },
      { name: 'Katar Zawodnik 06', position: 'MID', overall: 70, starting: true },
      { name: 'Katar Zawodnik 07', position: 'MID', overall: 70, starting: true },
      { name: 'Katar Zawodnik 08', position: 'MID', overall: 70, starting: true },
      { name: 'Katar Zawodnik 09', position: 'MID', overall: 70, starting: true },
      { name: 'Katar Zawodnik 10', position: 'FWD', overall: 70, starting: true },
      { name: 'Katar Zawodnik 11', position: 'FWD', overall: 70, starting: true },
    ],
  },
  {
    id: 'm26-szwajcaria',
    label: 'Szwajcaria',
    // ZAŚLEPKA — płaski overall 85 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Szwajcaria Zawodnik 01', position: 'GK', overall: 85, starting: true },
      { name: 'Szwajcaria Zawodnik 02', position: 'DEF', overall: 85, starting: true },
      { name: 'Szwajcaria Zawodnik 03', position: 'DEF', overall: 85, starting: true },
      { name: 'Szwajcaria Zawodnik 04', position: 'DEF', overall: 85, starting: true },
      { name: 'Szwajcaria Zawodnik 05', position: 'DEF', overall: 85, starting: true },
      { name: 'Szwajcaria Zawodnik 06', position: 'MID', overall: 85, starting: true },
      { name: 'Szwajcaria Zawodnik 07', position: 'MID', overall: 85, starting: true },
      { name: 'Szwajcaria Zawodnik 08', position: 'MID', overall: 85, starting: true },
      { name: 'Szwajcaria Zawodnik 09', position: 'MID', overall: 85, starting: true },
      { name: 'Szwajcaria Zawodnik 10', position: 'FWD', overall: 85, starting: true },
      { name: 'Szwajcaria Zawodnik 11', position: 'FWD', overall: 85, starting: true },
    ],
  },
  {
    id: 'm26-brazylia',
    label: 'Brazylia',
    // ZAŚLEPKA — płaski overall 96 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Brazylia Zawodnik 01', position: 'GK', overall: 96, starting: true },
      { name: 'Brazylia Zawodnik 02', position: 'DEF', overall: 96, starting: true },
      { name: 'Brazylia Zawodnik 03', position: 'DEF', overall: 96, starting: true },
      { name: 'Brazylia Zawodnik 04', position: 'DEF', overall: 96, starting: true },
      { name: 'Brazylia Zawodnik 05', position: 'DEF', overall: 96, starting: true },
      { name: 'Brazylia Zawodnik 06', position: 'MID', overall: 96, starting: true },
      { name: 'Brazylia Zawodnik 07', position: 'MID', overall: 96, starting: true },
      { name: 'Brazylia Zawodnik 08', position: 'MID', overall: 96, starting: true },
      { name: 'Brazylia Zawodnik 09', position: 'MID', overall: 96, starting: true },
      { name: 'Brazylia Zawodnik 10', position: 'FWD', overall: 96, starting: true },
      { name: 'Brazylia Zawodnik 11', position: 'FWD', overall: 96, starting: true },
    ],
  },
  {
    id: 'm26-maroko',
    label: 'Maroko',
    // ZAŚLEPKA — płaski overall 85 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Maroko Zawodnik 01', position: 'GK', overall: 85, starting: true },
      { name: 'Maroko Zawodnik 02', position: 'DEF', overall: 85, starting: true },
      { name: 'Maroko Zawodnik 03', position: 'DEF', overall: 85, starting: true },
      { name: 'Maroko Zawodnik 04', position: 'DEF', overall: 85, starting: true },
      { name: 'Maroko Zawodnik 05', position: 'DEF', overall: 85, starting: true },
      { name: 'Maroko Zawodnik 06', position: 'MID', overall: 85, starting: true },
      { name: 'Maroko Zawodnik 07', position: 'MID', overall: 85, starting: true },
      { name: 'Maroko Zawodnik 08', position: 'MID', overall: 85, starting: true },
      { name: 'Maroko Zawodnik 09', position: 'MID', overall: 85, starting: true },
      { name: 'Maroko Zawodnik 10', position: 'FWD', overall: 85, starting: true },
      { name: 'Maroko Zawodnik 11', position: 'FWD', overall: 85, starting: true },
    ],
  },
  {
    id: 'm26-haiti',
    label: 'Haiti',
    // ZAŚLEPKA — płaski overall 64 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Haiti Zawodnik 01', position: 'GK', overall: 64, starting: true },
      { name: 'Haiti Zawodnik 02', position: 'DEF', overall: 64, starting: true },
      { name: 'Haiti Zawodnik 03', position: 'DEF', overall: 64, starting: true },
      { name: 'Haiti Zawodnik 04', position: 'DEF', overall: 64, starting: true },
      { name: 'Haiti Zawodnik 05', position: 'DEF', overall: 64, starting: true },
      { name: 'Haiti Zawodnik 06', position: 'MID', overall: 64, starting: true },
      { name: 'Haiti Zawodnik 07', position: 'MID', overall: 64, starting: true },
      { name: 'Haiti Zawodnik 08', position: 'MID', overall: 64, starting: true },
      { name: 'Haiti Zawodnik 09', position: 'MID', overall: 64, starting: true },
      { name: 'Haiti Zawodnik 10', position: 'FWD', overall: 64, starting: true },
      { name: 'Haiti Zawodnik 11', position: 'FWD', overall: 64, starting: true },
    ],
  },
  {
    id: 'm26-szkocja',
    label: 'Szkocja',
    // ZAŚLEPKA — płaski overall 78 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Szkocja Zawodnik 01', position: 'GK', overall: 78, starting: true },
      { name: 'Szkocja Zawodnik 02', position: 'DEF', overall: 78, starting: true },
      { name: 'Szkocja Zawodnik 03', position: 'DEF', overall: 78, starting: true },
      { name: 'Szkocja Zawodnik 04', position: 'DEF', overall: 78, starting: true },
      { name: 'Szkocja Zawodnik 05', position: 'DEF', overall: 78, starting: true },
      { name: 'Szkocja Zawodnik 06', position: 'MID', overall: 78, starting: true },
      { name: 'Szkocja Zawodnik 07', position: 'MID', overall: 78, starting: true },
      { name: 'Szkocja Zawodnik 08', position: 'MID', overall: 78, starting: true },
      { name: 'Szkocja Zawodnik 09', position: 'MID', overall: 78, starting: true },
      { name: 'Szkocja Zawodnik 10', position: 'FWD', overall: 78, starting: true },
      { name: 'Szkocja Zawodnik 11', position: 'FWD', overall: 78, starting: true },
    ],
  },
  {
    id: 'm26-usa',
    label: 'USA',
    // ZAŚLEPKA — płaski overall 84 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'USA Zawodnik 01', position: 'GK', overall: 84, starting: true },
      { name: 'USA Zawodnik 02', position: 'DEF', overall: 84, starting: true },
      { name: 'USA Zawodnik 03', position: 'DEF', overall: 84, starting: true },
      { name: 'USA Zawodnik 04', position: 'DEF', overall: 84, starting: true },
      { name: 'USA Zawodnik 05', position: 'DEF', overall: 84, starting: true },
      { name: 'USA Zawodnik 06', position: 'MID', overall: 84, starting: true },
      { name: 'USA Zawodnik 07', position: 'MID', overall: 84, starting: true },
      { name: 'USA Zawodnik 08', position: 'MID', overall: 84, starting: true },
      { name: 'USA Zawodnik 09', position: 'MID', overall: 84, starting: true },
      { name: 'USA Zawodnik 10', position: 'FWD', overall: 84, starting: true },
      { name: 'USA Zawodnik 11', position: 'FWD', overall: 84, starting: true },
    ],
  },
  {
    id: 'm26-paragwaj',
    label: 'Paragwaj',
    // ZAŚLEPKA — płaski overall 76 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Paragwaj Zawodnik 01', position: 'GK', overall: 76, starting: true },
      { name: 'Paragwaj Zawodnik 02', position: 'DEF', overall: 76, starting: true },
      { name: 'Paragwaj Zawodnik 03', position: 'DEF', overall: 76, starting: true },
      { name: 'Paragwaj Zawodnik 04', position: 'DEF', overall: 76, starting: true },
      { name: 'Paragwaj Zawodnik 05', position: 'DEF', overall: 76, starting: true },
      { name: 'Paragwaj Zawodnik 06', position: 'MID', overall: 76, starting: true },
      { name: 'Paragwaj Zawodnik 07', position: 'MID', overall: 76, starting: true },
      { name: 'Paragwaj Zawodnik 08', position: 'MID', overall: 76, starting: true },
      { name: 'Paragwaj Zawodnik 09', position: 'MID', overall: 76, starting: true },
      { name: 'Paragwaj Zawodnik 10', position: 'FWD', overall: 76, starting: true },
      { name: 'Paragwaj Zawodnik 11', position: 'FWD', overall: 76, starting: true },
    ],
  },
  {
    id: 'm26-australia',
    label: 'Australia',
    // ZAŚLEPKA — płaski overall 77 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Australia Zawodnik 01', position: 'GK', overall: 77, starting: true },
      { name: 'Australia Zawodnik 02', position: 'DEF', overall: 77, starting: true },
      { name: 'Australia Zawodnik 03', position: 'DEF', overall: 77, starting: true },
      { name: 'Australia Zawodnik 04', position: 'DEF', overall: 77, starting: true },
      { name: 'Australia Zawodnik 05', position: 'DEF', overall: 77, starting: true },
      { name: 'Australia Zawodnik 06', position: 'MID', overall: 77, starting: true },
      { name: 'Australia Zawodnik 07', position: 'MID', overall: 77, starting: true },
      { name: 'Australia Zawodnik 08', position: 'MID', overall: 77, starting: true },
      { name: 'Australia Zawodnik 09', position: 'MID', overall: 77, starting: true },
      { name: 'Australia Zawodnik 10', position: 'FWD', overall: 77, starting: true },
      { name: 'Australia Zawodnik 11', position: 'FWD', overall: 77, starting: true },
    ],
  },
  {
    id: 'm26-turcja',
    label: 'Turcja',
    // ZAŚLEPKA — płaski overall 81 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Turcja Zawodnik 01', position: 'GK', overall: 81, starting: true },
      { name: 'Turcja Zawodnik 02', position: 'DEF', overall: 81, starting: true },
      { name: 'Turcja Zawodnik 03', position: 'DEF', overall: 81, starting: true },
      { name: 'Turcja Zawodnik 04', position: 'DEF', overall: 81, starting: true },
      { name: 'Turcja Zawodnik 05', position: 'DEF', overall: 81, starting: true },
      { name: 'Turcja Zawodnik 06', position: 'MID', overall: 81, starting: true },
      { name: 'Turcja Zawodnik 07', position: 'MID', overall: 81, starting: true },
      { name: 'Turcja Zawodnik 08', position: 'MID', overall: 81, starting: true },
      { name: 'Turcja Zawodnik 09', position: 'MID', overall: 81, starting: true },
      { name: 'Turcja Zawodnik 10', position: 'FWD', overall: 81, starting: true },
      { name: 'Turcja Zawodnik 11', position: 'FWD', overall: 81, starting: true },
    ],
  },
  {
    id: 'm26-niemcy',
    label: 'Niemcy',
    // ZAŚLEPKA — płaski overall 90 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Niemcy Zawodnik 01', position: 'GK', overall: 90, starting: true },
      { name: 'Niemcy Zawodnik 02', position: 'DEF', overall: 90, starting: true },
      { name: 'Niemcy Zawodnik 03', position: 'DEF', overall: 90, starting: true },
      { name: 'Niemcy Zawodnik 04', position: 'DEF', overall: 90, starting: true },
      { name: 'Niemcy Zawodnik 05', position: 'DEF', overall: 90, starting: true },
      { name: 'Niemcy Zawodnik 06', position: 'MID', overall: 90, starting: true },
      { name: 'Niemcy Zawodnik 07', position: 'MID', overall: 90, starting: true },
      { name: 'Niemcy Zawodnik 08', position: 'MID', overall: 90, starting: true },
      { name: 'Niemcy Zawodnik 09', position: 'MID', overall: 90, starting: true },
      { name: 'Niemcy Zawodnik 10', position: 'FWD', overall: 90, starting: true },
      { name: 'Niemcy Zawodnik 11', position: 'FWD', overall: 90, starting: true },
    ],
  },
  {
    id: 'm26-cura-ao',
    label: 'Curaçao',
    // ZAŚLEPKA — płaski overall 63 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Curaçao Zawodnik 01', position: 'GK', overall: 63, starting: true },
      { name: 'Curaçao Zawodnik 02', position: 'DEF', overall: 63, starting: true },
      { name: 'Curaçao Zawodnik 03', position: 'DEF', overall: 63, starting: true },
      { name: 'Curaçao Zawodnik 04', position: 'DEF', overall: 63, starting: true },
      { name: 'Curaçao Zawodnik 05', position: 'DEF', overall: 63, starting: true },
      { name: 'Curaçao Zawodnik 06', position: 'MID', overall: 63, starting: true },
      { name: 'Curaçao Zawodnik 07', position: 'MID', overall: 63, starting: true },
      { name: 'Curaçao Zawodnik 08', position: 'MID', overall: 63, starting: true },
      { name: 'Curaçao Zawodnik 09', position: 'MID', overall: 63, starting: true },
      { name: 'Curaçao Zawodnik 10', position: 'FWD', overall: 63, starting: true },
      { name: 'Curaçao Zawodnik 11', position: 'FWD', overall: 63, starting: true },
    ],
  },
  {
    id: 'm26-wybrzeze-kosci-sloniowej',
    label: 'Wybrzeże Kości Słoniowej',
    // ZAŚLEPKA — płaski overall 80 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Wybrzeże Zawodnik 01', position: 'GK', overall: 80, starting: true },
      { name: 'Wybrzeże Zawodnik 02', position: 'DEF', overall: 80, starting: true },
      { name: 'Wybrzeże Zawodnik 03', position: 'DEF', overall: 80, starting: true },
      { name: 'Wybrzeże Zawodnik 04', position: 'DEF', overall: 80, starting: true },
      { name: 'Wybrzeże Zawodnik 05', position: 'DEF', overall: 80, starting: true },
      { name: 'Wybrzeże Zawodnik 06', position: 'MID', overall: 80, starting: true },
      { name: 'Wybrzeże Zawodnik 07', position: 'MID', overall: 80, starting: true },
      { name: 'Wybrzeże Zawodnik 08', position: 'MID', overall: 80, starting: true },
      { name: 'Wybrzeże Zawodnik 09', position: 'MID', overall: 80, starting: true },
      { name: 'Wybrzeże Zawodnik 10', position: 'FWD', overall: 80, starting: true },
      { name: 'Wybrzeże Zawodnik 11', position: 'FWD', overall: 80, starting: true },
    ],
  },
  {
    id: 'm26-ekwador',
    label: 'Ekwador',
    // ZAŚLEPKA — płaski overall 79 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Ekwador Zawodnik 01', position: 'GK', overall: 79, starting: true },
      { name: 'Ekwador Zawodnik 02', position: 'DEF', overall: 79, starting: true },
      { name: 'Ekwador Zawodnik 03', position: 'DEF', overall: 79, starting: true },
      { name: 'Ekwador Zawodnik 04', position: 'DEF', overall: 79, starting: true },
      { name: 'Ekwador Zawodnik 05', position: 'DEF', overall: 79, starting: true },
      { name: 'Ekwador Zawodnik 06', position: 'MID', overall: 79, starting: true },
      { name: 'Ekwador Zawodnik 07', position: 'MID', overall: 79, starting: true },
      { name: 'Ekwador Zawodnik 08', position: 'MID', overall: 79, starting: true },
      { name: 'Ekwador Zawodnik 09', position: 'MID', overall: 79, starting: true },
      { name: 'Ekwador Zawodnik 10', position: 'FWD', overall: 79, starting: true },
      { name: 'Ekwador Zawodnik 11', position: 'FWD', overall: 79, starting: true },
    ],
  },
  {
    id: 'm26-holandia',
    label: 'Holandia',
    // ZAŚLEPKA — płaski overall 89 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Holandia Zawodnik 01', position: 'GK', overall: 89, starting: true },
      { name: 'Holandia Zawodnik 02', position: 'DEF', overall: 89, starting: true },
      { name: 'Holandia Zawodnik 03', position: 'DEF', overall: 89, starting: true },
      { name: 'Holandia Zawodnik 04', position: 'DEF', overall: 89, starting: true },
      { name: 'Holandia Zawodnik 05', position: 'DEF', overall: 89, starting: true },
      { name: 'Holandia Zawodnik 06', position: 'MID', overall: 89, starting: true },
      { name: 'Holandia Zawodnik 07', position: 'MID', overall: 89, starting: true },
      { name: 'Holandia Zawodnik 08', position: 'MID', overall: 89, starting: true },
      { name: 'Holandia Zawodnik 09', position: 'MID', overall: 89, starting: true },
      { name: 'Holandia Zawodnik 10', position: 'FWD', overall: 89, starting: true },
      { name: 'Holandia Zawodnik 11', position: 'FWD', overall: 89, starting: true },
    ],
  },
  {
    id: 'm26-japonia',
    label: 'Japonia',
    // ZAŚLEPKA — płaski overall 85 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Japonia Zawodnik 01', position: 'GK', overall: 85, starting: true },
      { name: 'Japonia Zawodnik 02', position: 'DEF', overall: 85, starting: true },
      { name: 'Japonia Zawodnik 03', position: 'DEF', overall: 85, starting: true },
      { name: 'Japonia Zawodnik 04', position: 'DEF', overall: 85, starting: true },
      { name: 'Japonia Zawodnik 05', position: 'DEF', overall: 85, starting: true },
      { name: 'Japonia Zawodnik 06', position: 'MID', overall: 85, starting: true },
      { name: 'Japonia Zawodnik 07', position: 'MID', overall: 85, starting: true },
      { name: 'Japonia Zawodnik 08', position: 'MID', overall: 85, starting: true },
      { name: 'Japonia Zawodnik 09', position: 'MID', overall: 85, starting: true },
      { name: 'Japonia Zawodnik 10', position: 'FWD', overall: 85, starting: true },
      { name: 'Japonia Zawodnik 11', position: 'FWD', overall: 85, starting: true },
    ],
  },
  {
    id: 'm26-polska',
    label: 'Polska',
    // ZAŚLEPKA — płaski overall 80 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Polska Zawodnik 01', position: 'GK', overall: 80, starting: true },
      { name: 'Polska Zawodnik 02', position: 'DEF', overall: 80, starting: true },
      { name: 'Polska Zawodnik 03', position: 'DEF', overall: 80, starting: true },
      { name: 'Polska Zawodnik 04', position: 'DEF', overall: 80, starting: true },
      { name: 'Polska Zawodnik 05', position: 'DEF', overall: 80, starting: true },
      { name: 'Polska Zawodnik 06', position: 'MID', overall: 80, starting: true },
      { name: 'Polska Zawodnik 07', position: 'MID', overall: 80, starting: true },
      { name: 'Polska Zawodnik 08', position: 'MID', overall: 80, starting: true },
      { name: 'Polska Zawodnik 09', position: 'MID', overall: 80, starting: true },
      { name: 'Polska Zawodnik 10', position: 'FWD', overall: 80, starting: true },
      { name: 'Polska Zawodnik 11', position: 'FWD', overall: 80, starting: true },
    ],
  },
  {
    id: 'm26-tunezja',
    label: 'Tunezja',
    // ZAŚLEPKA — płaski overall 77 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Tunezja Zawodnik 01', position: 'GK', overall: 77, starting: true },
      { name: 'Tunezja Zawodnik 02', position: 'DEF', overall: 77, starting: true },
      { name: 'Tunezja Zawodnik 03', position: 'DEF', overall: 77, starting: true },
      { name: 'Tunezja Zawodnik 04', position: 'DEF', overall: 77, starting: true },
      { name: 'Tunezja Zawodnik 05', position: 'DEF', overall: 77, starting: true },
      { name: 'Tunezja Zawodnik 06', position: 'MID', overall: 77, starting: true },
      { name: 'Tunezja Zawodnik 07', position: 'MID', overall: 77, starting: true },
      { name: 'Tunezja Zawodnik 08', position: 'MID', overall: 77, starting: true },
      { name: 'Tunezja Zawodnik 09', position: 'MID', overall: 77, starting: true },
      { name: 'Tunezja Zawodnik 10', position: 'FWD', overall: 77, starting: true },
      { name: 'Tunezja Zawodnik 11', position: 'FWD', overall: 77, starting: true },
    ],
  },
  {
    id: 'm26-belgia',
    label: 'Belgia',
    // ZAŚLEPKA — płaski overall 88 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Belgia Zawodnik 01', position: 'GK', overall: 88, starting: true },
      { name: 'Belgia Zawodnik 02', position: 'DEF', overall: 88, starting: true },
      { name: 'Belgia Zawodnik 03', position: 'DEF', overall: 88, starting: true },
      { name: 'Belgia Zawodnik 04', position: 'DEF', overall: 88, starting: true },
      { name: 'Belgia Zawodnik 05', position: 'DEF', overall: 88, starting: true },
      { name: 'Belgia Zawodnik 06', position: 'MID', overall: 88, starting: true },
      { name: 'Belgia Zawodnik 07', position: 'MID', overall: 88, starting: true },
      { name: 'Belgia Zawodnik 08', position: 'MID', overall: 88, starting: true },
      { name: 'Belgia Zawodnik 09', position: 'MID', overall: 88, starting: true },
      { name: 'Belgia Zawodnik 10', position: 'FWD', overall: 88, starting: true },
      { name: 'Belgia Zawodnik 11', position: 'FWD', overall: 88, starting: true },
    ],
  },
  {
    id: 'm26-egipt',
    label: 'Egipt',
    // ZAŚLEPKA — płaski overall 79 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Egipt Zawodnik 01', position: 'GK', overall: 79, starting: true },
      { name: 'Egipt Zawodnik 02', position: 'DEF', overall: 79, starting: true },
      { name: 'Egipt Zawodnik 03', position: 'DEF', overall: 79, starting: true },
      { name: 'Egipt Zawodnik 04', position: 'DEF', overall: 79, starting: true },
      { name: 'Egipt Zawodnik 05', position: 'DEF', overall: 79, starting: true },
      { name: 'Egipt Zawodnik 06', position: 'MID', overall: 79, starting: true },
      { name: 'Egipt Zawodnik 07', position: 'MID', overall: 79, starting: true },
      { name: 'Egipt Zawodnik 08', position: 'MID', overall: 79, starting: true },
      { name: 'Egipt Zawodnik 09', position: 'MID', overall: 79, starting: true },
      { name: 'Egipt Zawodnik 10', position: 'FWD', overall: 79, starting: true },
      { name: 'Egipt Zawodnik 11', position: 'FWD', overall: 79, starting: true },
    ],
  },
  {
    id: 'm26-iran',
    label: 'Iran',
    // ZAŚLEPKA — płaski overall 77 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Iran Zawodnik 01', position: 'GK', overall: 77, starting: true },
      { name: 'Iran Zawodnik 02', position: 'DEF', overall: 77, starting: true },
      { name: 'Iran Zawodnik 03', position: 'DEF', overall: 77, starting: true },
      { name: 'Iran Zawodnik 04', position: 'DEF', overall: 77, starting: true },
      { name: 'Iran Zawodnik 05', position: 'DEF', overall: 77, starting: true },
      { name: 'Iran Zawodnik 06', position: 'MID', overall: 77, starting: true },
      { name: 'Iran Zawodnik 07', position: 'MID', overall: 77, starting: true },
      { name: 'Iran Zawodnik 08', position: 'MID', overall: 77, starting: true },
      { name: 'Iran Zawodnik 09', position: 'MID', overall: 77, starting: true },
      { name: 'Iran Zawodnik 10', position: 'FWD', overall: 77, starting: true },
      { name: 'Iran Zawodnik 11', position: 'FWD', overall: 77, starting: true },
    ],
  },
  {
    id: 'm26-nowa-zelandia',
    label: 'Nowa Zelandia',
    // ZAŚLEPKA — płaski overall 70 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Nowa Zawodnik 01', position: 'GK', overall: 70, starting: true },
      { name: 'Nowa Zawodnik 02', position: 'DEF', overall: 70, starting: true },
      { name: 'Nowa Zawodnik 03', position: 'DEF', overall: 70, starting: true },
      { name: 'Nowa Zawodnik 04', position: 'DEF', overall: 70, starting: true },
      { name: 'Nowa Zawodnik 05', position: 'DEF', overall: 70, starting: true },
      { name: 'Nowa Zawodnik 06', position: 'MID', overall: 70, starting: true },
      { name: 'Nowa Zawodnik 07', position: 'MID', overall: 70, starting: true },
      { name: 'Nowa Zawodnik 08', position: 'MID', overall: 70, starting: true },
      { name: 'Nowa Zawodnik 09', position: 'MID', overall: 70, starting: true },
      { name: 'Nowa Zawodnik 10', position: 'FWD', overall: 70, starting: true },
      { name: 'Nowa Zawodnik 11', position: 'FWD', overall: 70, starting: true },
    ],
  },
  {
    id: 'm26-hiszpania',
    label: 'Hiszpania',
    // ZAŚLEPKA — płaski overall 97 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Hiszpania Zawodnik 01', position: 'GK', overall: 97, starting: true },
      { name: 'Hiszpania Zawodnik 02', position: 'DEF', overall: 97, starting: true },
      { name: 'Hiszpania Zawodnik 03', position: 'DEF', overall: 97, starting: true },
      { name: 'Hiszpania Zawodnik 04', position: 'DEF', overall: 97, starting: true },
      { name: 'Hiszpania Zawodnik 05', position: 'DEF', overall: 97, starting: true },
      { name: 'Hiszpania Zawodnik 06', position: 'MID', overall: 97, starting: true },
      { name: 'Hiszpania Zawodnik 07', position: 'MID', overall: 97, starting: true },
      { name: 'Hiszpania Zawodnik 08', position: 'MID', overall: 97, starting: true },
      { name: 'Hiszpania Zawodnik 09', position: 'MID', overall: 97, starting: true },
      { name: 'Hiszpania Zawodnik 10', position: 'FWD', overall: 97, starting: true },
      { name: 'Hiszpania Zawodnik 11', position: 'FWD', overall: 97, starting: true },
    ],
  },
  {
    id: 'm26-republika-zielonego-przyladka',
    label: 'Republika Zielonego Przylądka',
    // ZAŚLEPKA — płaski overall 68 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Republika Zawodnik 01', position: 'GK', overall: 68, starting: true },
      { name: 'Republika Zawodnik 02', position: 'DEF', overall: 68, starting: true },
      { name: 'Republika Zawodnik 03', position: 'DEF', overall: 68, starting: true },
      { name: 'Republika Zawodnik 04', position: 'DEF', overall: 68, starting: true },
      { name: 'Republika Zawodnik 05', position: 'DEF', overall: 68, starting: true },
      { name: 'Republika Zawodnik 06', position: 'MID', overall: 68, starting: true },
      { name: 'Republika Zawodnik 07', position: 'MID', overall: 68, starting: true },
      { name: 'Republika Zawodnik 08', position: 'MID', overall: 68, starting: true },
      { name: 'Republika Zawodnik 09', position: 'MID', overall: 68, starting: true },
      { name: 'Republika Zawodnik 10', position: 'FWD', overall: 68, starting: true },
      { name: 'Republika Zawodnik 11', position: 'FWD', overall: 68, starting: true },
    ],
  },
  {
    id: 'm26-arabia-saudyjska',
    label: 'Arabia Saudyjska',
    // ZAŚLEPKA — płaski overall 72 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Arabia Zawodnik 01', position: 'GK', overall: 72, starting: true },
      { name: 'Arabia Zawodnik 02', position: 'DEF', overall: 72, starting: true },
      { name: 'Arabia Zawodnik 03', position: 'DEF', overall: 72, starting: true },
      { name: 'Arabia Zawodnik 04', position: 'DEF', overall: 72, starting: true },
      { name: 'Arabia Zawodnik 05', position: 'DEF', overall: 72, starting: true },
      { name: 'Arabia Zawodnik 06', position: 'MID', overall: 72, starting: true },
      { name: 'Arabia Zawodnik 07', position: 'MID', overall: 72, starting: true },
      { name: 'Arabia Zawodnik 08', position: 'MID', overall: 72, starting: true },
      { name: 'Arabia Zawodnik 09', position: 'MID', overall: 72, starting: true },
      { name: 'Arabia Zawodnik 10', position: 'FWD', overall: 72, starting: true },
      { name: 'Arabia Zawodnik 11', position: 'FWD', overall: 72, starting: true },
    ],
  },
  {
    id: 'm26-urugwaj',
    label: 'Urugwaj',
    // ZAŚLEPKA — płaski overall 87 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Urugwaj Zawodnik 01', position: 'GK', overall: 87, starting: true },
      { name: 'Urugwaj Zawodnik 02', position: 'DEF', overall: 87, starting: true },
      { name: 'Urugwaj Zawodnik 03', position: 'DEF', overall: 87, starting: true },
      { name: 'Urugwaj Zawodnik 04', position: 'DEF', overall: 87, starting: true },
      { name: 'Urugwaj Zawodnik 05', position: 'DEF', overall: 87, starting: true },
      { name: 'Urugwaj Zawodnik 06', position: 'MID', overall: 87, starting: true },
      { name: 'Urugwaj Zawodnik 07', position: 'MID', overall: 87, starting: true },
      { name: 'Urugwaj Zawodnik 08', position: 'MID', overall: 87, starting: true },
      { name: 'Urugwaj Zawodnik 09', position: 'MID', overall: 87, starting: true },
      { name: 'Urugwaj Zawodnik 10', position: 'FWD', overall: 87, starting: true },
      { name: 'Urugwaj Zawodnik 11', position: 'FWD', overall: 87, starting: true },
    ],
  },
  {
    id: 'm26-francja',
    label: 'Francja',
    // ZAŚLEPKA — płaski overall 96 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Francja Zawodnik 01', position: 'GK', overall: 96, starting: true },
      { name: 'Francja Zawodnik 02', position: 'DEF', overall: 96, starting: true },
      { name: 'Francja Zawodnik 03', position: 'DEF', overall: 96, starting: true },
      { name: 'Francja Zawodnik 04', position: 'DEF', overall: 96, starting: true },
      { name: 'Francja Zawodnik 05', position: 'DEF', overall: 96, starting: true },
      { name: 'Francja Zawodnik 06', position: 'MID', overall: 96, starting: true },
      { name: 'Francja Zawodnik 07', position: 'MID', overall: 96, starting: true },
      { name: 'Francja Zawodnik 08', position: 'MID', overall: 96, starting: true },
      { name: 'Francja Zawodnik 09', position: 'MID', overall: 96, starting: true },
      { name: 'Francja Zawodnik 10', position: 'FWD', overall: 96, starting: true },
      { name: 'Francja Zawodnik 11', position: 'FWD', overall: 96, starting: true },
    ],
  },
  {
    id: 'm26-senegal',
    label: 'Senegal',
    // ZAŚLEPKA — płaski overall 83 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Senegal Zawodnik 01', position: 'GK', overall: 83, starting: true },
      { name: 'Senegal Zawodnik 02', position: 'DEF', overall: 83, starting: true },
      { name: 'Senegal Zawodnik 03', position: 'DEF', overall: 83, starting: true },
      { name: 'Senegal Zawodnik 04', position: 'DEF', overall: 83, starting: true },
      { name: 'Senegal Zawodnik 05', position: 'DEF', overall: 83, starting: true },
      { name: 'Senegal Zawodnik 06', position: 'MID', overall: 83, starting: true },
      { name: 'Senegal Zawodnik 07', position: 'MID', overall: 83, starting: true },
      { name: 'Senegal Zawodnik 08', position: 'MID', overall: 83, starting: true },
      { name: 'Senegal Zawodnik 09', position: 'MID', overall: 83, starting: true },
      { name: 'Senegal Zawodnik 10', position: 'FWD', overall: 83, starting: true },
      { name: 'Senegal Zawodnik 11', position: 'FWD', overall: 83, starting: true },
    ],
  },
  {
    id: 'm26-irak',
    label: 'Irak',
    // ZAŚLEPKA — płaski overall 66 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Irak Zawodnik 01', position: 'GK', overall: 66, starting: true },
      { name: 'Irak Zawodnik 02', position: 'DEF', overall: 66, starting: true },
      { name: 'Irak Zawodnik 03', position: 'DEF', overall: 66, starting: true },
      { name: 'Irak Zawodnik 04', position: 'DEF', overall: 66, starting: true },
      { name: 'Irak Zawodnik 05', position: 'DEF', overall: 66, starting: true },
      { name: 'Irak Zawodnik 06', position: 'MID', overall: 66, starting: true },
      { name: 'Irak Zawodnik 07', position: 'MID', overall: 66, starting: true },
      { name: 'Irak Zawodnik 08', position: 'MID', overall: 66, starting: true },
      { name: 'Irak Zawodnik 09', position: 'MID', overall: 66, starting: true },
      { name: 'Irak Zawodnik 10', position: 'FWD', overall: 66, starting: true },
      { name: 'Irak Zawodnik 11', position: 'FWD', overall: 66, starting: true },
    ],
  },
  {
    id: 'm26-norwegia',
    label: 'Norwegia',
    // ZAŚLEPKA — płaski overall 80 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Norwegia Zawodnik 01', position: 'GK', overall: 80, starting: true },
      { name: 'Norwegia Zawodnik 02', position: 'DEF', overall: 80, starting: true },
      { name: 'Norwegia Zawodnik 03', position: 'DEF', overall: 80, starting: true },
      { name: 'Norwegia Zawodnik 04', position: 'DEF', overall: 80, starting: true },
      { name: 'Norwegia Zawodnik 05', position: 'DEF', overall: 80, starting: true },
      { name: 'Norwegia Zawodnik 06', position: 'MID', overall: 80, starting: true },
      { name: 'Norwegia Zawodnik 07', position: 'MID', overall: 80, starting: true },
      { name: 'Norwegia Zawodnik 08', position: 'MID', overall: 80, starting: true },
      { name: 'Norwegia Zawodnik 09', position: 'MID', overall: 80, starting: true },
      { name: 'Norwegia Zawodnik 10', position: 'FWD', overall: 80, starting: true },
      { name: 'Norwegia Zawodnik 11', position: 'FWD', overall: 80, starting: true },
    ],
  },
  {
    id: 'm26-argentyna',
    label: 'Argentyna',
    // ZAŚLEPKA — płaski overall 95 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Argentyna Zawodnik 01', position: 'GK', overall: 95, starting: true },
      { name: 'Argentyna Zawodnik 02', position: 'DEF', overall: 95, starting: true },
      { name: 'Argentyna Zawodnik 03', position: 'DEF', overall: 95, starting: true },
      { name: 'Argentyna Zawodnik 04', position: 'DEF', overall: 95, starting: true },
      { name: 'Argentyna Zawodnik 05', position: 'DEF', overall: 95, starting: true },
      { name: 'Argentyna Zawodnik 06', position: 'MID', overall: 95, starting: true },
      { name: 'Argentyna Zawodnik 07', position: 'MID', overall: 95, starting: true },
      { name: 'Argentyna Zawodnik 08', position: 'MID', overall: 95, starting: true },
      { name: 'Argentyna Zawodnik 09', position: 'MID', overall: 95, starting: true },
      { name: 'Argentyna Zawodnik 10', position: 'FWD', overall: 95, starting: true },
      { name: 'Argentyna Zawodnik 11', position: 'FWD', overall: 95, starting: true },
    ],
  },
  {
    id: 'm26-algieria',
    label: 'Algieria',
    // ZAŚLEPKA — płaski overall 78 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Algieria Zawodnik 01', position: 'GK', overall: 78, starting: true },
      { name: 'Algieria Zawodnik 02', position: 'DEF', overall: 78, starting: true },
      { name: 'Algieria Zawodnik 03', position: 'DEF', overall: 78, starting: true },
      { name: 'Algieria Zawodnik 04', position: 'DEF', overall: 78, starting: true },
      { name: 'Algieria Zawodnik 05', position: 'DEF', overall: 78, starting: true },
      { name: 'Algieria Zawodnik 06', position: 'MID', overall: 78, starting: true },
      { name: 'Algieria Zawodnik 07', position: 'MID', overall: 78, starting: true },
      { name: 'Algieria Zawodnik 08', position: 'MID', overall: 78, starting: true },
      { name: 'Algieria Zawodnik 09', position: 'MID', overall: 78, starting: true },
      { name: 'Algieria Zawodnik 10', position: 'FWD', overall: 78, starting: true },
      { name: 'Algieria Zawodnik 11', position: 'FWD', overall: 78, starting: true },
    ],
  },
  {
    id: 'm26-austria',
    label: 'Austria',
    // ZAŚLEPKA — płaski overall 80 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Austria Zawodnik 01', position: 'GK', overall: 80, starting: true },
      { name: 'Austria Zawodnik 02', position: 'DEF', overall: 80, starting: true },
      { name: 'Austria Zawodnik 03', position: 'DEF', overall: 80, starting: true },
      { name: 'Austria Zawodnik 04', position: 'DEF', overall: 80, starting: true },
      { name: 'Austria Zawodnik 05', position: 'DEF', overall: 80, starting: true },
      { name: 'Austria Zawodnik 06', position: 'MID', overall: 80, starting: true },
      { name: 'Austria Zawodnik 07', position: 'MID', overall: 80, starting: true },
      { name: 'Austria Zawodnik 08', position: 'MID', overall: 80, starting: true },
      { name: 'Austria Zawodnik 09', position: 'MID', overall: 80, starting: true },
      { name: 'Austria Zawodnik 10', position: 'FWD', overall: 80, starting: true },
      { name: 'Austria Zawodnik 11', position: 'FWD', overall: 80, starting: true },
    ],
  },
  {
    id: 'm26-jordania',
    label: 'Jordania',
    // ZAŚLEPKA — płaski overall 65 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Jordania Zawodnik 01', position: 'GK', overall: 65, starting: true },
      { name: 'Jordania Zawodnik 02', position: 'DEF', overall: 65, starting: true },
      { name: 'Jordania Zawodnik 03', position: 'DEF', overall: 65, starting: true },
      { name: 'Jordania Zawodnik 04', position: 'DEF', overall: 65, starting: true },
      { name: 'Jordania Zawodnik 05', position: 'DEF', overall: 65, starting: true },
      { name: 'Jordania Zawodnik 06', position: 'MID', overall: 65, starting: true },
      { name: 'Jordania Zawodnik 07', position: 'MID', overall: 65, starting: true },
      { name: 'Jordania Zawodnik 08', position: 'MID', overall: 65, starting: true },
      { name: 'Jordania Zawodnik 09', position: 'MID', overall: 65, starting: true },
      { name: 'Jordania Zawodnik 10', position: 'FWD', overall: 65, starting: true },
      { name: 'Jordania Zawodnik 11', position: 'FWD', overall: 65, starting: true },
    ],
  },
  {
    id: 'm26-portugalia',
    label: 'Portugalia',
    // ZAŚLEPKA — płaski overall 92 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Portugalia Zawodnik 01', position: 'GK', overall: 92, starting: true },
      { name: 'Portugalia Zawodnik 02', position: 'DEF', overall: 92, starting: true },
      { name: 'Portugalia Zawodnik 03', position: 'DEF', overall: 92, starting: true },
      { name: 'Portugalia Zawodnik 04', position: 'DEF', overall: 92, starting: true },
      { name: 'Portugalia Zawodnik 05', position: 'DEF', overall: 92, starting: true },
      { name: 'Portugalia Zawodnik 06', position: 'MID', overall: 92, starting: true },
      { name: 'Portugalia Zawodnik 07', position: 'MID', overall: 92, starting: true },
      { name: 'Portugalia Zawodnik 08', position: 'MID', overall: 92, starting: true },
      { name: 'Portugalia Zawodnik 09', position: 'MID', overall: 92, starting: true },
      { name: 'Portugalia Zawodnik 10', position: 'FWD', overall: 92, starting: true },
      { name: 'Portugalia Zawodnik 11', position: 'FWD', overall: 92, starting: true },
    ],
  },
  {
    id: 'm26-dr-konga',
    label: 'DR Konga',
    // ZAŚLEPKA — płaski overall 67 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'DR Zawodnik 01', position: 'GK', overall: 67, starting: true },
      { name: 'DR Zawodnik 02', position: 'DEF', overall: 67, starting: true },
      { name: 'DR Zawodnik 03', position: 'DEF', overall: 67, starting: true },
      { name: 'DR Zawodnik 04', position: 'DEF', overall: 67, starting: true },
      { name: 'DR Zawodnik 05', position: 'DEF', overall: 67, starting: true },
      { name: 'DR Zawodnik 06', position: 'MID', overall: 67, starting: true },
      { name: 'DR Zawodnik 07', position: 'MID', overall: 67, starting: true },
      { name: 'DR Zawodnik 08', position: 'MID', overall: 67, starting: true },
      { name: 'DR Zawodnik 09', position: 'MID', overall: 67, starting: true },
      { name: 'DR Zawodnik 10', position: 'FWD', overall: 67, starting: true },
      { name: 'DR Zawodnik 11', position: 'FWD', overall: 67, starting: true },
    ],
  },
  {
    id: 'm26-uzbekistan',
    label: 'Uzbekistan',
    // ZAŚLEPKA — płaski overall 69 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Uzbekistan Zawodnik 01', position: 'GK', overall: 69, starting: true },
      { name: 'Uzbekistan Zawodnik 02', position: 'DEF', overall: 69, starting: true },
      { name: 'Uzbekistan Zawodnik 03', position: 'DEF', overall: 69, starting: true },
      { name: 'Uzbekistan Zawodnik 04', position: 'DEF', overall: 69, starting: true },
      { name: 'Uzbekistan Zawodnik 05', position: 'DEF', overall: 69, starting: true },
      { name: 'Uzbekistan Zawodnik 06', position: 'MID', overall: 69, starting: true },
      { name: 'Uzbekistan Zawodnik 07', position: 'MID', overall: 69, starting: true },
      { name: 'Uzbekistan Zawodnik 08', position: 'MID', overall: 69, starting: true },
      { name: 'Uzbekistan Zawodnik 09', position: 'MID', overall: 69, starting: true },
      { name: 'Uzbekistan Zawodnik 10', position: 'FWD', overall: 69, starting: true },
      { name: 'Uzbekistan Zawodnik 11', position: 'FWD', overall: 69, starting: true },
    ],
  },
  {
    id: 'm26-kolumbia',
    label: 'Kolumbia',
    // ZAŚLEPKA — płaski overall 86 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Kolumbia Zawodnik 01', position: 'GK', overall: 86, starting: true },
      { name: 'Kolumbia Zawodnik 02', position: 'DEF', overall: 86, starting: true },
      { name: 'Kolumbia Zawodnik 03', position: 'DEF', overall: 86, starting: true },
      { name: 'Kolumbia Zawodnik 04', position: 'DEF', overall: 86, starting: true },
      { name: 'Kolumbia Zawodnik 05', position: 'DEF', overall: 86, starting: true },
      { name: 'Kolumbia Zawodnik 06', position: 'MID', overall: 86, starting: true },
      { name: 'Kolumbia Zawodnik 07', position: 'MID', overall: 86, starting: true },
      { name: 'Kolumbia Zawodnik 08', position: 'MID', overall: 86, starting: true },
      { name: 'Kolumbia Zawodnik 09', position: 'MID', overall: 86, starting: true },
      { name: 'Kolumbia Zawodnik 10', position: 'FWD', overall: 86, starting: true },
      { name: 'Kolumbia Zawodnik 11', position: 'FWD', overall: 86, starting: true },
    ],
  },
  {
    id: 'm26-anglia',
    label: 'Anglia',
    // ZAŚLEPKA — płaski overall 94 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Anglia Zawodnik 01', position: 'GK', overall: 94, starting: true },
      { name: 'Anglia Zawodnik 02', position: 'DEF', overall: 94, starting: true },
      { name: 'Anglia Zawodnik 03', position: 'DEF', overall: 94, starting: true },
      { name: 'Anglia Zawodnik 04', position: 'DEF', overall: 94, starting: true },
      { name: 'Anglia Zawodnik 05', position: 'DEF', overall: 94, starting: true },
      { name: 'Anglia Zawodnik 06', position: 'MID', overall: 94, starting: true },
      { name: 'Anglia Zawodnik 07', position: 'MID', overall: 94, starting: true },
      { name: 'Anglia Zawodnik 08', position: 'MID', overall: 94, starting: true },
      { name: 'Anglia Zawodnik 09', position: 'MID', overall: 94, starting: true },
      { name: 'Anglia Zawodnik 10', position: 'FWD', overall: 94, starting: true },
      { name: 'Anglia Zawodnik 11', position: 'FWD', overall: 94, starting: true },
    ],
  },
  {
    id: 'm26-chorwacja',
    label: 'Chorwacja',
    // ZAŚLEPKA — płaski overall 87 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Chorwacja Zawodnik 01', position: 'GK', overall: 87, starting: true },
      { name: 'Chorwacja Zawodnik 02', position: 'DEF', overall: 87, starting: true },
      { name: 'Chorwacja Zawodnik 03', position: 'DEF', overall: 87, starting: true },
      { name: 'Chorwacja Zawodnik 04', position: 'DEF', overall: 87, starting: true },
      { name: 'Chorwacja Zawodnik 05', position: 'DEF', overall: 87, starting: true },
      { name: 'Chorwacja Zawodnik 06', position: 'MID', overall: 87, starting: true },
      { name: 'Chorwacja Zawodnik 07', position: 'MID', overall: 87, starting: true },
      { name: 'Chorwacja Zawodnik 08', position: 'MID', overall: 87, starting: true },
      { name: 'Chorwacja Zawodnik 09', position: 'MID', overall: 87, starting: true },
      { name: 'Chorwacja Zawodnik 10', position: 'FWD', overall: 87, starting: true },
      { name: 'Chorwacja Zawodnik 11', position: 'FWD', overall: 87, starting: true },
    ],
  },
  {
    id: 'm26-ghana',
    label: 'Ghana',
    // ZAŚLEPKA — płaski overall 76 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Ghana Zawodnik 01', position: 'GK', overall: 76, starting: true },
      { name: 'Ghana Zawodnik 02', position: 'DEF', overall: 76, starting: true },
      { name: 'Ghana Zawodnik 03', position: 'DEF', overall: 76, starting: true },
      { name: 'Ghana Zawodnik 04', position: 'DEF', overall: 76, starting: true },
      { name: 'Ghana Zawodnik 05', position: 'DEF', overall: 76, starting: true },
      { name: 'Ghana Zawodnik 06', position: 'MID', overall: 76, starting: true },
      { name: 'Ghana Zawodnik 07', position: 'MID', overall: 76, starting: true },
      { name: 'Ghana Zawodnik 08', position: 'MID', overall: 76, starting: true },
      { name: 'Ghana Zawodnik 09', position: 'MID', overall: 76, starting: true },
      { name: 'Ghana Zawodnik 10', position: 'FWD', overall: 76, starting: true },
      { name: 'Ghana Zawodnik 11', position: 'FWD', overall: 76, starting: true },
    ],
  },
  {
    id: 'm26-panama',
    label: 'Panama',
    // ZAŚLEPKA — płaski overall 69 (poziom orientacyjny wg siły reprezentacji, do podmiany na prawdziwy skład).
    players: [
      { name: 'Panama Zawodnik 01', position: 'GK', overall: 69, starting: true },
      { name: 'Panama Zawodnik 02', position: 'DEF', overall: 69, starting: true },
      { name: 'Panama Zawodnik 03', position: 'DEF', overall: 69, starting: true },
      { name: 'Panama Zawodnik 04', position: 'DEF', overall: 69, starting: true },
      { name: 'Panama Zawodnik 05', position: 'DEF', overall: 69, starting: true },
      { name: 'Panama Zawodnik 06', position: 'MID', overall: 69, starting: true },
      { name: 'Panama Zawodnik 07', position: 'MID', overall: 69, starting: true },
      { name: 'Panama Zawodnik 08', position: 'MID', overall: 69, starting: true },
      { name: 'Panama Zawodnik 09', position: 'MID', overall: 69, starting: true },
      { name: 'Panama Zawodnik 10', position: 'FWD', overall: 69, starting: true },
      { name: 'Panama Zawodnik 11', position: 'FWD', overall: 69, starting: true },
    ],
  },
);

window.MUNDIAL26_GROUPS = {
  A: ['m26-meksyk', 'm26-republika-poludniowej-afryki', 'm26-korea-poludniowa', 'm26-czechy'],
  B: ['m26-kanada', 'm26-bosnia-i-hercegowina', 'm26-katar', 'm26-szwajcaria'],
  C: ['m26-brazylia', 'm26-maroko', 'm26-haiti', 'm26-szkocja'],
  D: ['m26-usa', 'm26-paragwaj', 'm26-australia', 'm26-turcja'],
  E: ['m26-niemcy', 'm26-cura-ao', 'm26-wybrzeze-kosci-sloniowej', 'm26-ekwador'],
  F: ['m26-holandia', 'm26-japonia', 'm26-polska', 'm26-tunezja'],
  G: ['m26-belgia', 'm26-egipt', 'm26-iran', 'm26-nowa-zelandia'],
  H: ['m26-hiszpania', 'm26-republika-zielonego-przyladka', 'm26-arabia-saudyjska', 'm26-urugwaj'],
  I: ['m26-francja', 'm26-senegal', 'm26-irak', 'm26-norwegia'],
  J: ['m26-argentyna', 'm26-algieria', 'm26-austria', 'm26-jordania'],
  K: ['m26-portugalia', 'm26-dr-konga', 'm26-uzbekistan', 'm26-kolumbia'],
  L: ['m26-anglia', 'm26-chorwacja', 'm26-ghana', 'm26-panama'],
};
