// ============================================================
// MUNDIAL2026-DANE.JS — 48 reprezentacji na Mundial 2026.
// Kadry gry: 11 podstawowych zawodników + 6 rezerwowych.
// Szwecja zastąpiona Polską (alternatywny wynik ścieżki barażowej B).
//
// WSPÓLNA SKALA OVERALLU 1–120:
// 118–120 — absolutny światowy szczyt (Messi, Mbappe, Haaland, Yamal)
// 113–117 — ścisła światowa czołówka
// 108–112 — klasa światowa
// 103–107 — gwiazda czołowego klubu i reprezentacji
//  99–102 — mocny zawodnik najlepszych lig
//  96–98  — solidny zawodnik dobrej ligi europejskiej
//  90–95  — gwiazda Ekstraklasy
//  85–89  — dobry podstawowy zawodnik Ekstraklasy
//  80–84  — przeciętny lub słabszy ligowiec
//  74–79  — poziom I ligi albo słabszych lig zagranicznych
//
// Oceny są zbilansowane także na poziomie reprezentacji: średnia
// podstawowej XI wynosi od 108,0 (Hiszpania) do 89,0 (Jordania),
// a ławka jest zwykle słabsza o około 4,5–5,5 punktu.
// ============================================================

window.MUNDIAL26_TEAMS_DATA = window.MUNDIAL26_TEAMS_DATA || [];
window.MUNDIAL26_TEAMS_DATA.push(
  {
    id: 'm26-meksyk',
    label: 'Meksyk',
    players: [
      { name: 'Guillermo Ochoa', position: 'GK', overall: 96, starting: true },
      { name: 'Israel Reyes', position: 'DEF', overall: 97, starting: true },
      { name: 'Cesar Montes', position: 'DEF', overall: 98, starting: true },
      { name: 'Johan Vasquez', position: 'DEF', overall: 97, starting: true },
      { name: 'Jesus Gallardo', position: 'DEF', overall: 96, starting: true },
      { name: 'Edson Alvarez', position: 'MID', overall: 104, starting: true },
      { name: 'Luis Chavez', position: 'MID', overall: 99, starting: true },
      { name: 'Alvaro Fidalgo', position: 'MID', overall: 98, starting: true },
      { name: 'Orbelin Pineda', position: 'MID', overall: 97, starting: true },
      { name: 'Santiago Gimenez', position: 'FWD', overall: 107, starting: true },
      { name: 'Raul Jimenez', position: 'FWD', overall: 100, starting: true },
      { name: 'Carlos Acevedo', position: 'GK', overall: 93, starting: false },
      { name: 'Jorge Sanchez', position: 'DEF', overall: 93, starting: false },
      { name: 'Mateo Chavez', position: 'DEF', overall: 92, starting: false },
      { name: 'Erik Lira', position: 'MID', overall: 92, starting: false },
      { name: 'Gilberto Mora', position: 'MID', overall: 97, starting: false },
      { name: 'Alexis Vega', position: 'FWD', overall: 94, starting: false },
    ],
  },
  {
    id: 'm26-republika-poludniowej-afryki',
    label: 'Republika Południowej Afryki',
    players: [
      { name: 'Ronwen Williams', position: 'GK', overall: 98, starting: true },
      { name: 'Khuliso Mudau', position: 'DEF', overall: 96, starting: true },
      { name: 'Nkosinathi Sibisi', position: 'DEF', overall: 94, starting: true },
      { name: 'Aubrey Modiba', position: 'DEF', overall: 95, starting: true },
      { name: 'Mbekezeli Mbokazi', position: 'DEF', overall: 93, starting: true },
      { name: 'Teboho Mokoena', position: 'MID', overall: 97, starting: true },
      { name: 'Thalente Mbatha', position: 'MID', overall: 93, starting: true },
      { name: 'Jayden Adams', position: 'MID', overall: 93, starting: true },
      { name: 'Sphephelo Sithole', position: 'MID', overall: 92, starting: true },
      { name: 'Lyle Foster', position: 'FWD', overall: 99, starting: true },
      { name: 'Themba Zwane', position: 'FWD', overall: 95, starting: true },
      { name: 'Ricardo Goss', position: 'GK', overall: 90, starting: false },
      { name: 'Bradley Cross', position: 'DEF', overall: 90, starting: false },
      { name: 'Olwethu Makhanya', position: 'DEF', overall: 89, starting: false },
      { name: 'Kamogelo Sebelebele', position: 'MID', overall: 90, starting: false },
      { name: 'Samukele Kabini', position: 'MID', overall: 87, starting: false },
      { name: 'Relebohile Mofokeng', position: 'FWD', overall: 94, starting: false },
    ],
  },
  {
    id: 'm26-korea-poludniowa',
    label: 'Korea Południowa',
    players: [
      { name: 'Jo Hyeonwoo', position: 'GK', overall: 96, starting: true },
      { name: 'Kim Minjae', position: 'DEF', overall: 106, starting: true },
      { name: 'Kim Moonhwan', position: 'DEF', overall: 95, starting: true },
      { name: 'Lee Kihyuk', position: 'DEF', overall: 95, starting: true },
      { name: 'Seol Youngwoo', position: 'DEF', overall: 94, starting: true },
      { name: 'Lee Kangin', position: 'MID', overall: 102, starting: true },
      { name: 'Hwang Inbeom', position: 'MID', overall: 98, starting: true },
      { name: 'Hwang Heechan', position: 'MID', overall: 99, starting: true },
      { name: 'Lee Jaesung', position: 'MID', overall: 96, starting: true },
      { name: 'Son Heungmin', position: 'FWD', overall: 108, starting: true },
      { name: 'Oh Hyeongyu', position: 'FWD', overall: 95, starting: true },
      { name: 'Kim Seunggyu', position: 'GK', overall: 93, starting: false },
      { name: 'Kim Taehyeon', position: 'DEF', overall: 92, starting: false },
      { name: 'Lee Taeseok', position: 'DEF', overall: 91, starting: false },
      { name: 'Yang Hyunjun', position: 'MID', overall: 95, starting: false },
      { name: 'Paik Seungho', position: 'MID', overall: 92, starting: false },
      { name: 'Cho Guesung', position: 'FWD', overall: 95, starting: false },
    ],
  },
  {
    id: 'm26-czechy',
    label: 'Czechy',
    players: [
      { name: 'Jindrich Stanek', position: 'GK', overall: 98, starting: true },
      { name: 'Vladimir Coufal', position: 'DEF', overall: 100, starting: true },
      { name: 'David Zima', position: 'DEF', overall: 96, starting: true },
      { name: 'Robin Hranac', position: 'DEF', overall: 97, starting: true },
      { name: 'Ladislav Krejci', position: 'DEF', overall: 97, starting: true },
      { name: 'Tomas Soucek', position: 'MID', overall: 102, starting: true },
      { name: 'Lukas Provod', position: 'MID', overall: 97, starting: true },
      { name: 'Pavel Sulc', position: 'MID', overall: 97, starting: true },
      { name: 'Michal Sadilek', position: 'MID', overall: 95, starting: true },
      { name: 'Patrik Schick', position: 'FWD', overall: 102, starting: true },
      { name: 'Adam Hlozek', position: 'FWD', overall: 97, starting: true },
      { name: 'Matej Kovar', position: 'GK', overall: 93, starting: false },
      { name: 'David Doudera', position: 'DEF', overall: 93, starting: false },
      { name: 'David Jurasek', position: 'DEF', overall: 93, starting: false },
      { name: 'Vladimir Darida', position: 'MID', overall: 92, starting: false },
      { name: 'Lukas Cerv', position: 'MID', overall: 91, starting: false },
      { name: 'Jan Kuchta', position: 'FWD', overall: 93, starting: false },
    ],
  },
  {
    id: 'm26-kanada',
    label: 'Kanada',
    players: [
      { name: 'Dayne St. Clair', position: 'GK', overall: 96, starting: true },
      { name: 'Alphonso Davies', position: 'DEF', overall: 106, starting: true },
      { name: 'Moise Bombito', position: 'DEF', overall: 97, starting: true },
      { name: 'Derek Cornelius', position: 'DEF', overall: 96, starting: true },
      { name: 'Richie Laryea', position: 'DEF', overall: 96, starting: true },
      { name: 'Stephen Eustaquio', position: 'MID', overall: 99, starting: true },
      { name: 'Ismael Kone', position: 'MID', overall: 98, starting: true },
      { name: 'Tajon Buchanan', position: 'MID', overall: 100, starting: true },
      { name: 'Jonathan Osorio', position: 'MID', overall: 95, starting: true },
      { name: 'Jonathan David', position: 'FWD', overall: 105, starting: true },
      { name: 'Cyle Larin', position: 'FWD', overall: 96, starting: true },
      { name: 'Maxime Crepeau', position: 'GK', overall: 93, starting: false },
      { name: 'Joel Waterman', position: 'DEF', overall: 91, starting: false },
      { name: 'Alistair Johnston', position: 'DEF', overall: 96, starting: false },
      { name: 'Mathieu Choiniere', position: 'MID', overall: 92, starting: false },
      { name: 'Jacob Shaffelburg', position: 'MID', overall: 93, starting: false },
      { name: 'Tani Oluwaseyi', position: 'FWD', overall: 93, starting: false },
    ],
  },
  {
    id: 'm26-bosnia-i-hercegowina',
    label: 'Bośnia i Hercegowina',
    players: [
      { name: 'Nikola Vasilj', position: 'GK', overall: 98, starting: true },
      { name: 'Sead Kolasinac', position: 'DEF', overall: 99, starting: true },
      { name: 'Nikola Katic', position: 'DEF', overall: 97, starting: true },
      { name: 'Tarik Muharemovic', position: 'DEF', overall: 97, starting: true },
      { name: 'Amar Dedic', position: 'DEF', overall: 97, starting: true },
      { name: 'Ivan Sunjic', position: 'MID', overall: 97, starting: true },
      { name: 'Benjamin Tahirovic', position: 'MID', overall: 96, starting: true },
      { name: 'Amir Hadziahmetovic', position: 'MID', overall: 95, starting: true },
      { name: 'Armin Gigovic', position: 'MID', overall: 94, starting: true },
      { name: 'Edin Dzeko', position: 'FWD', overall: 98, starting: true },
      { name: 'Ermedin Demirovic', position: 'FWD', overall: 99, starting: true },
      { name: 'Martin Zlomislic', position: 'GK', overall: 90, starting: false },
      { name: 'Dennis Hadzikadunic', position: 'DEF', overall: 93, starting: false },
      { name: 'Stjepan Radeljic', position: 'DEF', overall: 92, starting: false },
      { name: 'Ivan Basic', position: 'MID', overall: 90, starting: false },
      { name: 'Dzenis Burnic', position: 'MID', overall: 91, starting: false },
      { name: 'Kerim Alajbegovic', position: 'FWD', overall: 96, starting: false },
    ],
  },
  {
    id: 'm26-katar',
    label: 'Katar',
    players: [
      { name: 'Meshaal Barsham', position: 'GK', overall: 95, starting: true },
      { name: 'Boualem Khoukhi', position: 'DEF', overall: 94, starting: true },
      { name: 'Pedro Miguel', position: 'DEF', overall: 92, starting: true },
      { name: 'Lucas Mendes', position: 'DEF', overall: 91, starting: true },
      { name: 'Sultan Al-Brake', position: 'DEF', overall: 90, starting: true },
      { name: 'Karim Boudiaf', position: 'MID', overall: 93, starting: true },
      { name: 'Assim Madibo', position: 'MID', overall: 94, starting: true },
      { name: 'Abdulaziz Hatem', position: 'MID', overall: 92, starting: true },
      { name: 'Jassem Jaber', position: 'MID', overall: 91, starting: true },
      { name: 'Akram Afif', position: 'FWD', overall: 100, starting: true },
      { name: 'Almoez Ali', position: 'FWD', overall: 97, starting: true },
      { name: 'Mahmoud Abunada', position: 'GK', overall: 89, starting: false },
      { name: 'Ayoub Alawi', position: 'DEF', overall: 89, starting: false },
      { name: 'Homam Al-Amin', position: 'DEF', overall: 88, starting: false },
      { name: 'Ahmed Fathi', position: 'MID', overall: 87, starting: false },
      { name: 'Mohammed Al-Manai', position: 'MID', overall: 86, starting: false },
      { name: 'Hassan Al-Haydos', position: 'FWD', overall: 95, starting: false },
    ],
  },
  {
    id: 'm26-szwajcaria',
    label: 'Szwajcaria',
    players: [
      { name: 'Gregor Kobel', position: 'GK', overall: 105, starting: true },
      { name: 'Manuel Akanji', position: 'DEF', overall: 104, starting: true },
      { name: 'Nico Elvedi', position: 'DEF', overall: 99, starting: true },
      { name: 'Ricardo Rodriguez', position: 'DEF', overall: 97, starting: true },
      { name: 'Silvan Widmer', position: 'DEF', overall: 96, starting: true },
      { name: 'Granit Xhaka', position: 'MID', overall: 104, starting: true },
      { name: 'Remo Freuler', position: 'MID', overall: 100, starting: true },
      { name: 'Ardon Jashari', position: 'MID', overall: 99, starting: true },
      { name: 'Djibril Sow', position: 'MID', overall: 96, starting: true },
      { name: 'Ruben Vargas', position: 'FWD', overall: 97, starting: true },
      { name: 'Breel Embolo', position: 'FWD', overall: 98, starting: true },
      { name: 'Yvon Mvogo', position: 'GK', overall: 91, starting: false },
      { name: 'Eray Comert', position: 'DEF', overall: 94, starting: false },
      { name: 'Aurele Amenda', position: 'DEF', overall: 94, starting: false },
      { name: 'Fabian Rieder', position: 'MID', overall: 96, starting: false },
      { name: 'Michel Aebischer', position: 'MID', overall: 93, starting: false },
      { name: 'Zeki Amdouni', position: 'FWD', overall: 96, starting: false },
    ],
  },
  {
    id: 'm26-brazylia',
    label: 'Brazylia',
    players: [
      { name: 'Alisson', position: 'GK', overall: 109, starting: true },
      { name: 'Marquinhos', position: 'DEF', overall: 108, starting: true },
      { name: 'Gabriel Magalhaes', position: 'DEF', overall: 104, starting: true },
      { name: 'Danilo', position: 'DEF', overall: 100, starting: true },
      { name: 'Alex Sandro', position: 'DEF', overall: 98, starting: true },
      { name: 'Bruno Guimaraes', position: 'MID', overall: 108, starting: true },
      { name: 'Casemiro', position: 'MID', overall: 104, starting: true },
      { name: 'Lucas Paqueta', position: 'MID', overall: 104, starting: true },
      { name: 'Raphinha', position: 'MID', overall: 114, starting: true },
      { name: 'Vinicius Junior', position: 'FWD', overall: 118, starting: true },
      { name: 'Neymar', position: 'FWD', overall: 105, starting: true },
      { name: 'Ederson', position: 'GK', overall: 104, starting: false },
      { name: 'Wesley', position: 'DEF', overall: 99, starting: false },
      { name: 'Bremer', position: 'DEF', overall: 104, starting: false },
      { name: 'Fabinho', position: 'MID', overall: 101, starting: false },
      { name: 'Danilo Santos', position: 'MID', overall: 98, starting: false },
      { name: 'Matheus Cunha', position: 'FWD', overall: 103, starting: false },
    ],
  },
  {
    id: 'm26-maroko',
    label: 'Maroko',
    players: [
      { name: 'Yassine Bounou', position: 'GK', overall: 104, starting: true },
      { name: 'Achraf Hakimi', position: 'DEF', overall: 116, starting: true },
      { name: 'Nayef Aguerd', position: 'DEF', overall: 104, starting: true },
      { name: 'Noussair Mazraoui', position: 'DEF', overall: 104, starting: true },
      { name: 'Issa Diop', position: 'DEF', overall: 99, starting: true },
      { name: 'Azzedine Ounahi', position: 'MID', overall: 102, starting: true },
      { name: 'Sofyan Amrabat', position: 'MID', overall: 103, starting: true },
      { name: 'Bilal El Khannouss', position: 'MID', overall: 100, starting: true },
      { name: 'Ismael Saibari', position: 'MID', overall: 98, starting: true },
      { name: 'Ayoub El Kaabi', position: 'FWD', overall: 100, starting: true },
      { name: 'Brahim Diaz', position: 'FWD', overall: 109, starting: true },
      { name: 'Munir El Kajoui', position: 'GK', overall: 95, starting: false },
      { name: 'Chadi Riad', position: 'DEF', overall: 100, starting: false },
      { name: 'Zakaria El Ouahdi', position: 'DEF', overall: 96, starting: false },
      { name: 'Neil El Aynaoui', position: 'MID', overall: 100, starting: false },
      { name: 'Samir El Mourabet', position: 'MID', overall: 95, starting: false },
      { name: 'Abdessamad Ezzalzouli', position: 'FWD', overall: 102, starting: false },
    ],
  },
  {
    id: 'm26-haiti',
    label: 'Haiti',
    players: [
      { name: 'Johnny Placide', position: 'GK', overall: 93, starting: true },
      { name: 'Carlens Arcus', position: 'DEF', overall: 92, starting: true },
      { name: 'Jean-Kevin Duverne', position: 'DEF', overall: 91, starting: true },
      { name: 'Hannes Delcroix', position: 'DEF', overall: 91, starting: true },
      { name: 'Duke Lacroix', position: 'DEF', overall: 88, starting: true },
      { name: 'Jeanricner Bellegarde', position: 'MID', overall: 96, starting: true },
      { name: 'Leverton Pierre', position: 'MID', overall: 89, starting: true },
      { name: 'Carl-Fred Sainthe', position: 'MID', overall: 88, starting: true },
      { name: 'Dominique Simon', position: 'MID', overall: 86, starting: true },
      { name: 'Wilson Isidor', position: 'FWD', overall: 96, starting: true },
      { name: 'Duckens Nazon', position: 'FWD', overall: 91, starting: true },
      { name: 'Alexandre Pierre', position: 'GK', overall: 87, starting: false },
      { name: 'Ricardo Ade', position: 'DEF', overall: 87, starting: false },
      { name: 'Keeto Thermoncy', position: 'DEF', overall: 86, starting: false },
      { name: 'Jean-Jacques Danley', position: 'MID', overall: 86, starting: false },
      { name: 'Pierre Woodenski', position: 'MID', overall: 84, starting: false },
      { name: 'Derrick Etienne', position: 'FWD', overall: 89, starting: false },
    ],
  },
  {
    id: 'm26-szkocja',
    label: 'Szkocja',
    players: [
      { name: 'Craig Gordon', position: 'GK', overall: 97, starting: true },
      { name: 'Andy Robertson', position: 'DEF', overall: 103, starting: true },
      { name: 'Kieran Tierney', position: 'DEF', overall: 99, starting: true },
      { name: 'Grant Hanley', position: 'DEF', overall: 97, starting: true },
      { name: 'Scott McKenna', position: 'DEF', overall: 96, starting: true },
      { name: 'Scott McTominay', position: 'MID', overall: 105, starting: true },
      { name: 'John McGinn', position: 'MID', overall: 101, starting: true },
      { name: 'Ryan Christie', position: 'MID', overall: 98, starting: true },
      { name: 'Kenny McLean', position: 'MID', overall: 96, starting: true },
      { name: 'Che Adams', position: 'FWD', overall: 96, starting: true },
      { name: 'Lawrence Shankland', position: 'FWD', overall: 96, starting: true },
      { name: 'Angus Gunn', position: 'GK', overall: 91, starting: false },
      { name: 'Aaron Hickey', position: 'DEF', overall: 95, starting: false },
      { name: 'Anthony Ralston', position: 'DEF', overall: 91, starting: false },
      { name: 'Lewis Ferguson', position: 'MID', overall: 96, starting: false },
      { name: 'Ben Gannon-Doak', position: 'MID', overall: 94, starting: false },
      { name: 'Ross Stewart', position: 'FWD', overall: 91, starting: false },
    ],
  },
  {
    id: 'm26-usa',
    label: 'USA',
    players: [
      { name: 'Matt Turner', position: 'GK', overall: 98, starting: true },
      { name: 'Sergino Dest', position: 'DEF', overall: 101, starting: true },
      { name: 'Antonee Robinson', position: 'DEF', overall: 101, starting: true },
      { name: 'Chris Richards', position: 'DEF', overall: 99, starting: true },
      { name: 'Tim Ream', position: 'DEF', overall: 96, starting: true },
      { name: 'Tyler Adams', position: 'MID', overall: 101, starting: true },
      { name: 'Weston McKennie', position: 'MID', overall: 101, starting: true },
      { name: 'Malik Tillman', position: 'MID', overall: 99, starting: true },
      { name: 'Gio Reyna', position: 'MID', overall: 98, starting: true },
      { name: 'Christian Pulisic', position: 'FWD', overall: 108, starting: true },
      { name: 'Folarin Balogun', position: 'FWD', overall: 98, starting: true },
      { name: 'Chris Brady', position: 'GK', overall: 92, starting: false },
      { name: 'Joe Scally', position: 'DEF', overall: 96, starting: false },
      { name: 'Miles Robinson', position: 'DEF', overall: 95, starting: false },
      { name: 'Cristian Roldan', position: 'MID', overall: 94, starting: false },
      { name: 'Sebastian Berhalter', position: 'MID', overall: 92, starting: false },
      { name: 'Ricardo Pepi', position: 'FWD', overall: 98, starting: false },
    ],
  },
  {
    id: 'm26-paragwaj',
    label: 'Paragwaj',
    players: [
      { name: 'Gatito Fernandez', position: 'GK', overall: 97, starting: true },
      { name: 'Gustavo Gomez', position: 'DEF', overall: 102, starting: true },
      { name: 'Junior Alonso', position: 'DEF', overall: 97, starting: true },
      { name: 'Omar Alderete', position: 'DEF', overall: 98, starting: true },
      { name: 'Fabian Balbuena', position: 'DEF', overall: 97, starting: true },
      { name: 'Miguel Almiron', position: 'MID', overall: 102, starting: true },
      { name: 'Andres Cubas', position: 'MID', overall: 97, starting: true },
      { name: 'Diego Gomez', position: 'MID', overall: 98, starting: true },
      { name: 'Ramon Sosa', position: 'MID', overall: 96, starting: true },
      { name: 'Antonio Sanabria', position: 'FWD', overall: 96, starting: true },
      { name: 'Julio Enciso', position: 'FWD', overall: 98, starting: true },
      { name: 'Roberto Fernandez', position: 'GK', overall: 91, starting: false },
      { name: 'Jose Canale', position: 'DEF', overall: 92, starting: false },
      { name: 'Alexandro Maidana', position: 'DEF', overall: 91, starting: false },
      { name: 'Damian Bobadilla', position: 'MID', overall: 92, starting: false },
      { name: 'Braian Ojeda', position: 'MID', overall: 93, starting: false },
      { name: 'Gabriel Avalos', position: 'FWD', overall: 96, starting: false },
    ],
  },
  {
    id: 'm26-australia',
    label: 'Australia',
    players: [
      { name: 'Mathew Ryan', position: 'GK', overall: 96, starting: true },
      { name: 'Harry Souttar', position: 'DEF', overall: 99, starting: true },
      { name: 'Milos Degenek', position: 'DEF', overall: 96, starting: true },
      { name: 'Aziz Behich', position: 'DEF', overall: 95, starting: true },
      { name: 'Kye Rowles', position: 'DEF', overall: 96, starting: true },
      { name: 'Jackson Irvine', position: 'MID', overall: 98, starting: true },
      { name: 'Aiden ONeill', position: 'MID', overall: 94, starting: true },
      { name: 'Connor Metcalfe', position: 'MID', overall: 95, starting: true },
      { name: 'Ajdin Hrustic', position: 'MID', overall: 95, starting: true },
      { name: 'Mathew Leckie', position: 'FWD', overall: 95, starting: true },
      { name: 'Nestory Irankunda', position: 'FWD', overall: 97, starting: true },
      { name: 'Tom Glover', position: 'GK', overall: 89, starting: false },
      { name: 'Jordan Bos', position: 'DEF', overall: 92, starting: false },
      { name: 'Alessandro Circati', position: 'DEF', overall: 91, starting: false },
      { name: 'Cameron Devlin', position: 'MID', overall: 90, starting: false },
      { name: 'Riley McGree', position: 'MID', overall: 93, starting: false },
      { name: 'Marco Tilio', position: 'FWD', overall: 91, starting: false },
    ],
  },
  {
    id: 'm26-turcja',
    label: 'Turcja',
    players: [
      { name: 'Ugurcan Cakir', position: 'GK', overall: 100, starting: true },
      { name: 'Merih Demiral', position: 'DEF', overall: 102, starting: true },
      { name: 'Zeki Celik', position: 'DEF', overall: 97, starting: true },
      { name: 'Abdulkerim Bardakci', position: 'DEF', overall: 96, starting: true },
      { name: 'Ferdi Kadioglu', position: 'DEF', overall: 100, starting: true },
      { name: 'Hakan Calhanoglu', position: 'MID', overall: 106, starting: true },
      { name: 'Orkun Kokcu', position: 'MID', overall: 100, starting: true },
      { name: 'Salih Ozcan', position: 'MID', overall: 97, starting: true },
      { name: 'Kaan Ayhan', position: 'MID', overall: 96, starting: true },
      { name: 'Arda Guler', position: 'FWD', overall: 108, starting: true },
      { name: 'Kenan Yildiz', position: 'FWD', overall: 104, starting: true },
      { name: 'Altay Bayindir', position: 'GK', overall: 94, starting: false },
      { name: 'Caglar Soyuncu', position: 'DEF', overall: 96, starting: false },
      { name: 'Mert Muldur', position: 'DEF', overall: 95, starting: false },
      { name: 'Ismail Yuksek', position: 'MID', overall: 92, starting: false },
      { name: 'Yunus Akgun', position: 'MID', overall: 96, starting: false },
      { name: 'Kerem Akturkoglu', position: 'FWD', overall: 97, starting: false },
    ],
  },
  {
    id: 'm26-niemcy',
    label: 'Niemcy',
    players: [
      { name: 'Manuel Neuer', position: 'GK', overall: 103, starting: true },
      { name: 'Antonio Rudiger', position: 'DEF', overall: 106, starting: true },
      { name: 'Jonathan Tah', position: 'DEF', overall: 102, starting: true },
      { name: 'Joshua Kimmich', position: 'DEF', overall: 111, starting: true },
      { name: 'David Raum', position: 'DEF', overall: 100, starting: true },
      { name: 'Florian Wirtz', position: 'MID', overall: 116, starting: true },
      { name: 'Jamal Musiala', position: 'MID', overall: 116, starting: true },
      { name: 'Leon Goretzka', position: 'MID', overall: 102, starting: true },
      { name: 'Aleksandar Pavlovic', position: 'MID', overall: 98, starting: true },
      { name: 'Kai Havertz', position: 'FWD', overall: 103, starting: true },
      { name: 'Nick Woltemade', position: 'FWD', overall: 98, starting: true },
      { name: 'Oliver Baumann', position: 'GK', overall: 96, starting: false },
      { name: 'Nico Schlotterbeck', position: 'DEF', overall: 103, starting: false },
      { name: 'Waldemar Anton', position: 'DEF', overall: 100, starting: false },
      { name: 'Pascal Gross', position: 'MID', overall: 99, starting: false },
      { name: 'Angelo Stiller', position: 'MID', overall: 99, starting: false },
      { name: 'Leroy Sane', position: 'FWD', overall: 103, starting: false },
    ],
  },
  {
    id: 'm26-cura-ao',
    label: 'Curaçao',
    players: [
      { name: 'Eloy Room', position: 'GK', overall: 89, starting: true },
      { name: 'Riechedly Bazoer', position: 'DEF', overall: 93, starting: true },
      { name: 'Armando Obispo', position: 'DEF', overall: 90, starting: true },
      { name: 'Sherel Floranus', position: 'DEF', overall: 86, starting: true },
      { name: 'Joshua Brenet', position: 'DEF', overall: 89, starting: true },
      { name: 'Juninho Bacuna', position: 'MID', overall: 92, starting: true },
      { name: 'Leandro Bacuna', position: 'MID', overall: 90, starting: true },
      { name: 'Livano Comenencia', position: 'MID', overall: 87, starting: true },
      { name: 'Tyrese Noslin', position: 'MID', overall: 86, starting: true },
      { name: 'Tahith Chong', position: 'FWD', overall: 93, starting: true },
      { name: 'Jurgen Locadia', position: 'FWD', overall: 90, starting: true },
      { name: 'Tyrick Bodak', position: 'GK', overall: 85, starting: false },
      { name: 'Deveron Fonville', position: 'DEF', overall: 86, starting: false },
      { name: 'Shurandy Sambo', position: 'DEF', overall: 85, starting: false },
      { name: 'Kevin Felida', position: 'MID', overall: 84, starting: false },
      { name: 'Godfried Roemeratoe', position: 'MID', overall: 83, starting: false },
      { name: 'Gervane Kastaneer', position: 'FWD', overall: 87, starting: false },
    ],
  },
  {
    id: 'm26-wybrzeze-kosci-sloniowej',
    label: 'Wybrzeże Kości Słoniowej',
    players: [
      { name: 'Yahia Fofana', position: 'GK', overall: 98, starting: true },
      { name: 'Odilon Kossounou', position: 'DEF', overall: 102, starting: true },
      { name: 'Evan Ndicka', position: 'DEF', overall: 104, starting: true },
      { name: 'Ousmane Diomande', position: 'DEF', overall: 102, starting: true },
      { name: 'Wilfried Singo', position: 'DEF', overall: 101, starting: true },
      { name: 'Franck Kessie', position: 'MID', overall: 104, starting: true },
      { name: 'Seko Fofana', position: 'MID', overall: 100, starting: true },
      { name: 'Ibrahim Sangare', position: 'MID', overall: 101, starting: true },
      { name: 'Jean-Michael Seri', position: 'MID', overall: 98, starting: true },
      { name: 'Nicolas Pepe', position: 'FWD', overall: 100, starting: true },
      { name: 'Simon Adingra', position: 'FWD', overall: 101, starting: true },
      { name: 'Mohamed Kone', position: 'GK', overall: 91, starting: false },
      { name: 'Ghislain Konan', position: 'DEF', overall: 96, starting: false },
      { name: 'Guela Doue', position: 'DEF', overall: 95, starting: false },
      { name: 'Christ Inao Oulai', position: 'MID', overall: 95, starting: false },
      { name: 'Parfait Guiagon', position: 'MID', overall: 92, starting: false },
      { name: 'Amad Diallo', position: 'FWD', overall: 104, starting: false },
    ],
  },
  {
    id: 'm26-ekwador',
    label: 'Ekwador',
    players: [
      { name: 'Hernan Galindez', position: 'GK', overall: 99, starting: true },
      { name: 'Piero Hincapie', position: 'DEF', overall: 105, starting: true },
      { name: 'Willian Pacho', position: 'DEF', overall: 103, starting: true },
      { name: 'Felix Torres', position: 'DEF', overall: 99, starting: true },
      { name: 'Pervis Estupinan', position: 'DEF', overall: 101, starting: true },
      { name: 'Moises Caicedo', position: 'MID', overall: 108, starting: true },
      { name: 'Alan Franco', position: 'MID', overall: 98, starting: true },
      { name: 'Kendry Paez', position: 'MID', overall: 100, starting: true },
      { name: 'Jordy Alcivar', position: 'MID', overall: 96, starting: true },
      { name: 'Enner Valencia', position: 'FWD', overall: 99, starting: true },
      { name: 'Kevin Rodriguez', position: 'FWD', overall: 98, starting: true },
      { name: 'Moises Ramirez', position: 'GK', overall: 91, starting: false },
      { name: 'Joel Ordonez', position: 'DEF', overall: 98, starting: false },
      { name: 'Angelo Preciado', position: 'DEF', overall: 96, starting: false },
      { name: 'Pedro Vite', position: 'MID', overall: 95, starting: false },
      { name: 'Denil Castillo', position: 'MID', overall: 93, starting: false },
      { name: 'Gonzalo Plata', position: 'FWD', overall: 97, starting: false },
    ],
  },
  {
    id: 'm26-holandia',
    label: 'Holandia',
    players: [
      { name: 'Bart Verbruggen', position: 'GK', overall: 101, starting: true },
      { name: 'Virgil van Dijk', position: 'DEF', overall: 114, starting: true },
      { name: 'Jurrien Timber', position: 'DEF', overall: 105, starting: true },
      { name: 'Nathan Ake', position: 'DEF', overall: 101, starting: true },
      { name: 'Denzel Dumfries', position: 'DEF', overall: 103, starting: true },
      { name: 'Frenkie de Jong', position: 'MID', overall: 113, starting: true },
      { name: 'Tijjani Reijnders', position: 'MID', overall: 103, starting: true },
      { name: 'Ryan Gravenberch', position: 'MID', overall: 103, starting: true },
      { name: 'Teun Koopmeiners', position: 'MID', overall: 101, starting: true },
      { name: 'Cody Gakpo', position: 'FWD', overall: 104, starting: true },
      { name: 'Memphis Depay', position: 'FWD', overall: 102, starting: true },
      { name: 'Mark Flekken', position: 'GK', overall: 97, starting: false },
      { name: 'Micky van de Ven', position: 'DEF', overall: 103, starting: false },
      { name: 'Jan Paul van Hecke', position: 'DEF', overall: 99, starting: false },
      { name: 'Justin Kluivert', position: 'MID', overall: 100, starting: false },
      { name: 'Mats Wieffer', position: 'MID', overall: 98, starting: false },
      { name: 'Donyell Malen', position: 'FWD', overall: 100, starting: false },
    ],
  },
  {
    id: 'm26-japonia',
    label: 'Japonia',
    players: [
      { name: 'Zion Suzuki', position: 'GK', overall: 99, starting: true },
      { name: 'Takehiro Tomiyasu', position: 'DEF', overall: 104, starting: true },
      { name: 'Ko Itakura', position: 'DEF', overall: 102, starting: true },
      { name: 'Yukinari Sugawara', position: 'DEF', overall: 101, starting: true },
      { name: 'Hiroki Ito', position: 'DEF', overall: 103, starting: true },
      { name: 'Takefusa Kubo', position: 'MID', overall: 107, starting: true },
      { name: 'Wataru Endo', position: 'MID', overall: 104, starting: true },
      { name: 'Ritsu Doan', position: 'MID', overall: 104, starting: true },
      { name: 'Daichi Kamada', position: 'MID', overall: 100, starting: true },
      { name: 'Ayase Ueda', position: 'FWD', overall: 100, starting: true },
      { name: 'Junya Ito', position: 'FWD', overall: 98, starting: true },
      { name: 'Keisuke Osako', position: 'GK', overall: 92, starting: false },
      { name: 'Tsuyoshi Watanabe', position: 'DEF', overall: 97, starting: false },
      { name: 'Shogo Taniguchi', position: 'DEF', overall: 97, starting: false },
      { name: 'Kaishu Sano', position: 'MID', overall: 95, starting: false },
      { name: 'Ao Tanaka', position: 'MID', overall: 99, starting: false },
      { name: 'Daizen Maeda', position: 'FWD', overall: 99, starting: false },
    ],
  },
  {
    id: 'm26-polska',
    label: 'Polska',
    players: [
      { name: 'Kamil Grabara', position: 'GK', overall: 100, starting: true },
      { name: 'Jakub Kiwior', position: 'DEF', overall: 102, starting: true },
      { name: 'Jan Bednarek', position: 'DEF', overall: 98, starting: true },
      { name: 'Matty Cash', position: 'DEF', overall: 102, starting: true },
      { name: 'Przemyslaw Wisniewski', position: 'DEF', overall: 95, starting: true },
      { name: 'Piotr Zielinski', position: 'MID', overall: 105, starting: true },
      { name: 'Sebastian Szymanski', position: 'MID', overall: 100, starting: true },
      { name: 'Nicola Zalewski', position: 'MID', overall: 98, starting: true },
      { name: 'Jakub Kaminski', position: 'MID', overall: 99, starting: true },
      { name: 'Robert Lewandowski', position: 'FWD', overall: 113, starting: true },
      { name: 'Karol Swiderski', position: 'FWD', overall: 96, starting: true },
      { name: 'Marcin Kochalski', position: 'GK', overall: 91, starting: false },
      { name: 'Jan Ziolkowski', position: 'DEF', overall: 96, starting: false },
      { name: 'Tomasz Kedziora', position: 'DEF', overall: 92, starting: false },
      { name: 'Bartosz Slisz', position: 'MID', overall: 94, starting: false },
      { name: 'Oskar Pietuszewski', position: 'MID', overall: 94, starting: false },
      { name: 'Krzysztof Piatek', position: 'FWD', overall: 94, starting: false },
    ],
  },
  {
    id: 'm26-tunezja',
    label: 'Tunezja',
    players: [
      { name: 'Aymen Dahmen', position: 'GK', overall: 94, starting: true },
      { name: 'Montassar Talbi', position: 'DEF', overall: 96, starting: true },
      { name: 'Dylan Bronn', position: 'DEF', overall: 95, starting: true },
      { name: 'Ali Abdi', position: 'DEF', overall: 93, starting: true },
      { name: 'Yan Valery', position: 'DEF', overall: 92, starting: true },
      { name: 'Ellyes Skhiri', position: 'MID', overall: 98, starting: true },
      { name: 'Hannibal Mejbri', position: 'MID', overall: 95, starting: true },
      { name: 'Anis Ben Slimane', position: 'MID', overall: 93, starting: true },
      { name: 'Ismael Gharbi', position: 'MID', overall: 93, starting: true },
      { name: 'Elias Achouri', position: 'FWD', overall: 94, starting: true },
      { name: 'Elias Saad', position: 'FWD', overall: 91, starting: true },
      { name: 'Sabri Ben Hassan', position: 'GK', overall: 87, starting: false },
      { name: 'Omar Rekik', position: 'DEF', overall: 90, starting: false },
      { name: 'Adem Arous', position: 'DEF', overall: 89, starting: false },
      { name: 'Rani Khedira', position: 'MID', overall: 91, starting: false },
      { name: 'Mortadha Ben Ouanes', position: 'MID', overall: 88, starting: false },
      { name: 'Ayari Khalil', position: 'FWD', overall: 89, starting: false },
    ],
  },
  {
    id: 'm26-belgia',
    label: 'Belgia',
    players: [
      { name: 'Thibaut Courtois', position: 'GK', overall: 109, starting: true },
      { name: 'Zeno Debast', position: 'DEF', overall: 99, starting: true },
      { name: 'Koni De Winter', position: 'DEF', overall: 99, starting: true },
      { name: 'Arthur Theate', position: 'DEF', overall: 98, starting: true },
      { name: 'Timothy Castagne', position: 'DEF', overall: 99, starting: true },
      { name: 'Kevin De Bruyne', position: 'MID', overall: 113, starting: true },
      { name: 'Youri Tielemans', position: 'MID', overall: 101, starting: true },
      { name: 'Amadou Onana', position: 'MID', overall: 101, starting: true },
      { name: 'Hans Vanaken', position: 'MID', overall: 99, starting: true },
      { name: 'Jeremy Doku', position: 'FWD', overall: 107, starting: true },
      { name: 'Romelu Lukaku', position: 'FWD', overall: 103, starting: true },
      { name: 'Senne Lammens', position: 'GK', overall: 93, starting: false },
      { name: 'Thomas Meunier', position: 'DEF', overall: 98, starting: false },
      { name: 'Maxim De Cuyper', position: 'DEF', overall: 96, starting: false },
      { name: 'Nicolas Raskin', position: 'MID', overall: 95, starting: false },
      { name: 'Axel Witsel', position: 'MID', overall: 97, starting: false },
      { name: 'Leandro Trossard', position: 'FWD', overall: 103, starting: false },
    ],
  },
  {
    id: 'm26-egipt',
    label: 'Egipt',
    players: [
      { name: 'Mohamed El Shenawy', position: 'GK', overall: 96, starting: true },
      { name: 'Yasser Ibrahim', position: 'DEF', overall: 96, starting: true },
      { name: 'Mohamed Abdelmonem', position: 'DEF', overall: 95, starting: true },
      { name: 'Ahmed Fotouh', position: 'DEF', overall: 93, starting: true },
      { name: 'Rami Rabia', position: 'DEF', overall: 94, starting: true },
      { name: 'Emam Ashour', position: 'MID', overall: 96, starting: true },
      { name: 'Mahmoud Trezeguet', position: 'MID', overall: 97, starting: true },
      { name: 'Ahmed Zizo', position: 'MID', overall: 95, starting: true },
      { name: 'Mostafa Ziko', position: 'MID', overall: 92, starting: true },
      { name: 'Mohamed Salah', position: 'FWD', overall: 116, starting: true },
      { name: 'Omar Marmoush', position: 'FWD', overall: 108, starting: true },
      { name: 'Mostafa Shobeir', position: 'GK', overall: 93, starting: false },
      { name: 'Karim Hafez', position: 'DEF', overall: 93, starting: false },
      { name: 'Hossam Abdelmaguid', position: 'DEF', overall: 93, starting: false },
      { name: 'Mohanad Lasheen', position: 'MID', overall: 92, starting: false },
      { name: 'Marwan Attia', position: 'MID', overall: 90, starting: false },
      { name: 'Hamza Abdelkarim', position: 'FWD', overall: 94, starting: false },
    ],
  },
  {
    id: 'm26-iran',
    label: 'Iran',
    players: [
      { name: 'Alireza Beiranvand', position: 'GK', overall: 96, starting: true },
      { name: 'Hossein Kanaani', position: 'DEF', overall: 95, starting: true },
      { name: 'Milad Mohammadi', position: 'DEF', overall: 95, starting: true },
      { name: 'Ehsan Hajsafi', position: 'DEF', overall: 94, starting: true },
      { name: 'Shoja Khalilzadeh', position: 'DEF', overall: 92, starting: true },
      { name: 'Saeid Ezatolahi', position: 'MID', overall: 96, starting: true },
      { name: 'Alireza Jahanbakhsh', position: 'MID', overall: 97, starting: true },
      { name: 'Rouzbeh Cheshmi', position: 'MID', overall: 94, starting: true },
      { name: 'Mehdi Torabi', position: 'MID', overall: 94, starting: true },
      { name: 'Mehdi Taremi', position: 'FWD', overall: 103, starting: true },
      { name: 'Ali Alipour', position: 'FWD', overall: 95, starting: true },
      { name: 'Hossein Hosseini', position: 'GK', overall: 89, starting: false },
      { name: 'Ramin Rezaeian', position: 'DEF', overall: 89, starting: false },
      { name: 'Danial Eiri', position: 'DEF', overall: 88, starting: false },
      { name: 'Saman Ghoddos', position: 'MID', overall: 96, starting: false },
      { name: 'Mohammad Mohebi', position: 'MID', overall: 91, starting: false },
      { name: 'Amirhossein Hosseinzadeh', position: 'FWD', overall: 90, starting: false },
    ],
  },
  {
    id: 'm26-nowa-zelandia',
    label: 'Nowa Zelandia',
    players: [
      { name: 'Max Crocombe', position: 'GK', overall: 90, starting: true },
      { name: 'Michael Boxall', position: 'DEF', overall: 91, starting: true },
      { name: 'Liberato Cacace', position: 'DEF', overall: 94, starting: true },
      { name: 'Tim Payne', position: 'DEF', overall: 90, starting: true },
      { name: 'Finn Surman', position: 'DEF', overall: 89, starting: true },
      { name: 'Joe Bell', position: 'MID', overall: 93, starting: true },
      { name: 'Alex Rufer', position: 'MID', overall: 90, starting: true },
      { name: 'Marko Stamenic', position: 'MID', overall: 92, starting: true },
      { name: 'Ryan Thomas', position: 'MID', overall: 92, starting: true },
      { name: 'Chris Wood', position: 'FWD', overall: 99, starting: true },
      { name: 'Sarpreet Singh', position: 'FWD', overall: 92, starting: true },
      { name: 'Alex Paulsen', position: 'GK', overall: 88, starting: false },
      { name: 'Tyler Bindon', position: 'DEF', overall: 88, starting: false },
      { name: 'Nando Pijnaker', position: 'DEF', overall: 88, starting: false },
      { name: 'Lachlan Bayliss', position: 'MID', overall: 86, starting: false },
      { name: 'Callum McCowatt', position: 'MID', overall: 87, starting: false },
      { name: 'Ben Waine', position: 'FWD', overall: 88, starting: false },
    ],
  },
  {
    id: 'm26-hiszpania',
    label: 'Hiszpania',
    players: [
      { name: 'Unai Simon', position: 'GK', overall: 108, starting: true },
      { name: 'Pau Cubarsi', position: 'DEF', overall: 104, starting: true },
      { name: 'Aymeric Laporte', position: 'DEF', overall: 102, starting: true },
      { name: 'Marc Cucurella', position: 'DEF', overall: 102, starting: true },
      { name: 'Pedro Porro', position: 'DEF', overall: 100, starting: true },
      { name: 'Pedri', position: 'MID', overall: 117, starting: true },
      { name: 'Rodri', position: 'MID', overall: 120, starting: true },
      { name: 'Fabian Ruiz', position: 'MID', overall: 102, starting: true },
      { name: 'Gavi', position: 'MID', overall: 106, starting: true },
      { name: 'Lamine Yamal', position: 'FWD', overall: 119, starting: true },
      { name: 'Nico Williams', position: 'FWD', overall: 108, starting: true },
      { name: 'David Raya', position: 'GK', overall: 106, starting: false },
      { name: 'Eric Garcia', position: 'DEF', overall: 102, starting: false },
      { name: 'Marcos Llorente', position: 'DEF', overall: 101, starting: false },
      { name: 'Martin Zubimendi', position: 'MID', overall: 104, starting: false },
      { name: 'Alex Baena', position: 'MID', overall: 102, starting: false },
      { name: 'Ferran Torres', position: 'FWD', overall: 103, starting: false },
    ],
  },
  {
    id: 'm26-republika-zielonego-przyladka',
    label: 'Republika Zielonego Przylądka',
    players: [
      { name: 'Vozinha', position: 'GK', overall: 95, starting: true },
      { name: 'Roberto Lopes', position: 'DEF', overall: 95, starting: true },
      { name: 'Logan Costa', position: 'DEF', overall: 96, starting: true },
      { name: 'Sidny Lopes Cabral', position: 'DEF', overall: 91, starting: true },
      { name: 'Steven Moreira', position: 'DEF', overall: 92, starting: true },
      { name: 'Jamiro Monteiro', position: 'MID', overall: 95, starting: true },
      { name: 'Kevin Pina', position: 'MID', overall: 91, starting: true },
      { name: 'Deroy Duarte', position: 'MID', overall: 90, starting: true },
      { name: 'Yannick Semedo', position: 'MID', overall: 89, starting: true },
      { name: 'Ryan Mendes', position: 'FWD', overall: 96, starting: true },
      { name: 'Garry Rodrigues', position: 'FWD', overall: 93, starting: true },
      { name: 'Marcio da Rosa', position: 'GK', overall: 88, starting: false },
      { name: 'Wagner Pina', position: 'DEF', overall: 89, starting: false },
      { name: 'Kelvin Pires', position: 'DEF', overall: 88, starting: false },
      { name: 'Telmo Arcanjo', position: 'MID', overall: 88, starting: false },
      { name: 'Laros Duarte', position: 'MID', overall: 88, starting: false },
      { name: 'Willy Semedo', position: 'FWD', overall: 90, starting: false },
    ],
  },
  {
    id: 'm26-arabia-saudyjska',
    label: 'Arabia Saudyjska',
    players: [
      { name: 'Nawaf Al Aqidi', position: 'GK', overall: 95, starting: true },
      { name: 'Saud Abdulhamid', position: 'DEF', overall: 96, starting: true },
      { name: 'Hassan Tambakti', position: 'DEF', overall: 94, starting: true },
      { name: 'Ali Lajami', position: 'DEF', overall: 93, starting: true },
      { name: 'Abdulelah Al Amri', position: 'DEF', overall: 92, starting: true },
      { name: 'Mohamed Kanno', position: 'MID', overall: 97, starting: true },
      { name: 'Nasser Al Dawsari', position: 'MID', overall: 96, starting: true },
      { name: 'Sultan Mandash', position: 'MID', overall: 93, starting: true },
      { name: 'Abdullah Al Khaibari', position: 'MID', overall: 92, starting: true },
      { name: 'Salem Al Dawsari', position: 'FWD', overall: 98, starting: true },
      { name: 'Saleh Al Shehri', position: 'FWD', overall: 94, starting: true },
      { name: 'Mohamed Al Owais', position: 'GK', overall: 90, starting: false },
      { name: 'Ali Majrashi', position: 'DEF', overall: 89, starting: false },
      { name: 'Nawaf Boushal', position: 'DEF', overall: 88, starting: false },
      { name: 'Ziyad Al Johani', position: 'MID', overall: 90, starting: false },
      { name: 'Khalid Al Ghannam', position: 'MID', overall: 88, starting: false },
      { name: 'Abdullah Al Hamdan', position: 'FWD', overall: 92, starting: false },
    ],
  },
  {
    id: 'm26-urugwaj',
    label: 'Urugwaj',
    players: [
      { name: 'Sergio Rochet', position: 'GK', overall: 101, starting: true },
      { name: 'Ronald Araujo', position: 'DEF', overall: 109, starting: true },
      { name: 'Jose Maria Gimenez', position: 'DEF', overall: 103, starting: true },
      { name: 'Mathias Olivera', position: 'DEF', overall: 99, starting: true },
      { name: 'Guillermo Varela', position: 'DEF', overall: 97, starting: true },
      { name: 'Federico Valverde', position: 'MID', overall: 113, starting: true },
      { name: 'Manuel Ugarte', position: 'MID', overall: 104, starting: true },
      { name: 'Rodrigo Bentancur', position: 'MID', overall: 104, starting: true },
      { name: 'Nicolas de la Cruz', position: 'MID', overall: 99, starting: true },
      { name: 'Darwin Nunez', position: 'FWD', overall: 108, starting: true },
      { name: 'Giorgian de Arrascaeta', position: 'FWD', overall: 102, starting: true },
      { name: 'Fernando Muslera', position: 'GK', overall: 95, starting: false },
      { name: 'Santiago Bueno', position: 'DEF', overall: 99, starting: false },
      { name: 'Joaquin Piquerez', position: 'DEF', overall: 99, starting: false },
      { name: 'Facundo Pellistri', position: 'MID', overall: 100, starting: false },
      { name: 'Maximiliano Araujo', position: 'MID', overall: 98, starting: false },
      { name: 'Rodrigo Aguirre', position: 'FWD', overall: 97, starting: false },
    ],
  },
  {
    id: 'm26-francja',
    label: 'Francja',
    players: [
      { name: 'Mike Maignan', position: 'GK', overall: 107, starting: true },
      { name: 'William Saliba', position: 'DEF', overall: 112, starting: true },
      { name: 'Dayot Upamecano', position: 'DEF', overall: 105, starting: true },
      { name: 'Jules Kounde', position: 'DEF', overall: 104, starting: true },
      { name: 'Theo Hernandez', position: 'DEF', overall: 104, starting: true },
      { name: 'Aurelien Tchouameni', position: 'MID', overall: 106, starting: true },
      { name: 'Adrien Rabiot', position: 'MID', overall: 102, starting: true },
      { name: 'NGolo Kante', position: 'MID', overall: 102, starting: true },
      { name: 'Warren Zaire-Emery', position: 'MID', overall: 104, starting: true },
      { name: 'Kylian Mbappe', position: 'FWD', overall: 120, starting: true },
      { name: 'Ousmane Dembele', position: 'FWD', overall: 117, starting: true },
      { name: 'Brice Samba', position: 'GK', overall: 98, starting: false },
      { name: 'Lucas Hernandez', position: 'DEF', overall: 102, starting: false },
      { name: 'Ibrahima Konate', position: 'DEF', overall: 105, starting: false },
      { name: 'Manu Kone', position: 'MID', overall: 100, starting: false },
      { name: 'Rayan Cherki', position: 'MID', overall: 104, starting: false },
      { name: 'Michael Olise', position: 'FWD', overall: 106, starting: false },
    ],
  },
  {
    id: 'm26-senegal',
    label: 'Senegal',
    players: [
      { name: 'Edouard Mendy', position: 'GK', overall: 102, starting: true },
      { name: 'Kalidou Koulibaly', position: 'DEF', overall: 105, starting: true },
      { name: 'Krepin Diatta', position: 'DEF', overall: 101, starting: true },
      { name: 'Moussa Niakhate', position: 'DEF', overall: 100, starting: true },
      { name: 'Ismail Jakobs', position: 'DEF', overall: 99, starting: true },
      { name: 'Idrissa Gana Gueye', position: 'MID', overall: 101, starting: true },
      { name: 'Pape Matar Sarr', position: 'MID', overall: 103, starting: true },
      { name: 'Lamine Camara', position: 'MID', overall: 101, starting: true },
      { name: 'Pathe Ciss', position: 'MID', overall: 98, starting: true },
      { name: 'Sadio Mane', position: 'FWD', overall: 104, starting: true },
      { name: 'Nicolas Jackson', position: 'FWD', overall: 103, starting: true },
      { name: 'Mory Diaw', position: 'GK', overall: 90, starting: false },
      { name: 'Abdoulaye Seck', position: 'DEF', overall: 94, starting: false },
      { name: 'Mamadou Sarr', position: 'DEF', overall: 96, starting: false },
      { name: 'Habib Diarra', position: 'MID', overall: 99, starting: false },
      { name: 'Pape Gueye', position: 'MID', overall: 97, starting: false },
      { name: 'Iliman Ndiaye', position: 'FWD', overall: 100, starting: false },
    ],
  },
  {
    id: 'm26-irak',
    label: 'Irak',
    players: [
      { name: 'Jalal Hassan', position: 'GK', overall: 94, starting: true },
      { name: 'Hussein Ali', position: 'DEF', overall: 92, starting: true },
      { name: 'Manaf Younis', position: 'DEF', overall: 90, starting: true },
      { name: 'Zaid Tahseen', position: 'DEF', overall: 89, starting: true },
      { name: 'Merchas Doski', position: 'DEF', overall: 88, starting: true },
      { name: 'Amir Al-Ammari', position: 'MID', overall: 90, starting: true },
      { name: 'Zidane Iqbal', position: 'MID', overall: 95, starting: true },
      { name: 'Ibrahim Bayesh', position: 'MID', overall: 87, starting: true },
      { name: 'Aimar Sher', position: 'MID', overall: 86, starting: true },
      { name: 'Ali Al-Hamadi', position: 'FWD', overall: 96, starting: true },
      { name: 'Aymen Hussein', position: 'FWD', overall: 89, starting: true },
      { name: 'Fahad Talib', position: 'GK', overall: 85, starting: false },
      { name: 'Ahmed Yahya', position: 'DEF', overall: 85, starting: false },
      { name: 'Rebin Sulaka', position: 'DEF', overall: 84, starting: false },
      { name: 'Youssef Amyn', position: 'MID', overall: 86, starting: false },
      { name: 'Kevin Yakob', position: 'MID', overall: 86, starting: false },
      { name: 'Ali Jassim', position: 'FWD', overall: 90, starting: false },
    ],
  },
  {
    id: 'm26-norwegia',
    label: 'Norwegia',
    players: [
      { name: 'Orjan Nyland', position: 'GK', overall: 96, starting: true },
      { name: 'Julian Ryerson', position: 'DEF', overall: 101, starting: true },
      { name: 'Kristoffer Ajer', position: 'DEF', overall: 97, starting: true },
      { name: 'Leo Skiri Ostigard', position: 'DEF', overall: 96, starting: true },
      { name: 'David Moller Wolfe', position: 'DEF', overall: 95, starting: true },
      { name: 'Martin Odegaard', position: 'MID', overall: 112, starting: true },
      { name: 'Sander Berge', position: 'MID', overall: 97, starting: true },
      { name: 'Fredrik Aursnes', position: 'MID', overall: 96, starting: true },
      { name: 'Morten Thorsby', position: 'MID', overall: 94, starting: true },
      { name: 'Erling Haaland', position: 'FWD', overall: 120, starting: true },
      { name: 'Alexander Sorloth', position: 'FWD', overall: 102, starting: true },
      { name: 'Egil Selvik', position: 'GK', overall: 90, starting: false },
      { name: 'Torbjorn Heggem', position: 'DEF', overall: 94, starting: false },
      { name: 'Fredrik Bjorkan', position: 'DEF', overall: 93, starting: false },
      { name: 'Andreas Schjelderup', position: 'MID', overall: 99, starting: false },
      { name: 'Patrick Berg', position: 'MID', overall: 93, starting: false },
      { name: 'Jorgen Strand Larsen', position: 'FWD', overall: 101, starting: false },
    ],
  },
  {
    id: 'm26-argentyna',
    label: 'Argentyna',
    players: [
      { name: 'Emiliano Martinez', position: 'GK', overall: 107, starting: true },
      { name: 'Cristian Romero', position: 'DEF', overall: 108, starting: true },
      { name: 'Nicolas Otamendi', position: 'DEF', overall: 103, starting: true },
      { name: 'Nahuel Molina', position: 'DEF', overall: 103, starting: true },
      { name: 'Nicolas Tagliafico', position: 'DEF', overall: 100, starting: true },
      { name: 'Enzo Fernandez', position: 'MID', overall: 109, starting: true },
      { name: 'Alexis Mac Allister', position: 'MID', overall: 109, starting: true },
      { name: 'Rodrigo De Paul', position: 'MID', overall: 104, starting: true },
      { name: 'Giovani Lo Celso', position: 'MID', overall: 102, starting: true },
      { name: 'Lionel Messi', position: 'FWD', overall: 120, starting: true },
      { name: 'Julian Alvarez', position: 'FWD', overall: 112, starting: true },
      { name: 'Geronimo Rulli', position: 'GK', overall: 97, starting: false },
      { name: 'Lisandro Martinez', position: 'DEF', overall: 106, starting: false },
      { name: 'Leonardo Balerdi', position: 'DEF', overall: 100, starting: false },
      { name: 'Leandro Paredes', position: 'MID', overall: 100, starting: false },
      { name: 'Valentin Barco', position: 'MID', overall: 98, starting: false },
      { name: 'Lautaro Martinez', position: 'FWD', overall: 111, starting: false },
    ],
  },
  {
    id: 'm26-algieria',
    label: 'Algieria',
    players: [
      { name: 'Alexandre Oukidja', position: 'GK', overall: 94, starting: true },
      { name: 'Ramy Bensebaini', position: 'DEF', overall: 99, starting: true },
      { name: 'Aissa Mandi', position: 'DEF', overall: 96, starting: true },
      { name: 'Rayan Ait-Nouri', position: 'DEF', overall: 101, starting: true },
      { name: 'Jaouen Hadjam', position: 'DEF', overall: 95, starting: true },
      { name: 'Houssem Aouar', position: 'MID', overall: 96, starting: true },
      { name: 'Ibrahim Maza', position: 'MID', overall: 95, starting: true },
      { name: 'Nabil Bentaleb', position: 'MID', overall: 94, starting: true },
      { name: 'Hicham Boudaoui', position: 'MID', overall: 94, starting: true },
      { name: 'Riyad Mahrez', position: 'FWD', overall: 100, starting: true },
      { name: 'Mohamed Amine Amoura', position: 'FWD', overall: 98, starting: true },
      { name: 'Oussama Benbot', position: 'GK', overall: 89, starting: false },
      { name: 'Zinedine Belaid', position: 'DEF', overall: 90, starting: false },
      { name: 'Samir Chergui', position: 'DEF', overall: 89, starting: false },
      { name: 'Fares Chaibi', position: 'MID', overall: 94, starting: false },
      { name: 'Yacine Titraoui', position: 'MID', overall: 88, starting: false },
      { name: 'Amine Gouiri', position: 'FWD', overall: 99, starting: false },
    ],
  },
  {
    id: 'm26-austria',
    label: 'Austria',
    players: [
      { name: 'Alexander Schlager', position: 'GK', overall: 98, starting: true },
      { name: 'David Alaba', position: 'DEF', overall: 104, starting: true },
      { name: 'Kevin Danso', position: 'DEF', overall: 100, starting: true },
      { name: 'Philipp Lienhart', position: 'DEF', overall: 98, starting: true },
      { name: 'Stefan Posch', position: 'DEF', overall: 97, starting: true },
      { name: 'Konrad Laimer', position: 'MID', overall: 102, starting: true },
      { name: 'Marcel Sabitzer', position: 'MID', overall: 101, starting: true },
      { name: 'Christoph Baumgartner', position: 'MID', overall: 102, starting: true },
      { name: 'Nicolas Seiwald', position: 'MID', overall: 98, starting: true },
      { name: 'Michael Gregoritsch', position: 'FWD', overall: 97, starting: true },
      { name: 'Marko Arnautovic', position: 'FWD', overall: 98, starting: true },
      { name: 'Patrick Pentz', position: 'GK', overall: 89, starting: false },
      { name: 'Philipp Mwene', position: 'DEF', overall: 91, starting: false },
      { name: 'Alexander Prass', position: 'DEF', overall: 93, starting: false },
      { name: 'Xaver Schlager', position: 'MID', overall: 99, starting: false },
      { name: 'Florian Grillitsch', position: 'MID', overall: 98, starting: false },
      { name: 'Sasa Kalajdzic', position: 'FWD', overall: 94, starting: false },
    ],
  },
  {
    id: 'm26-jordania',
    label: 'Jordania',
    players: [
      { name: 'Yazid Abulaila', position: 'GK', overall: 90, starting: true },
      { name: 'Yazan Al Arab', position: 'DEF', overall: 88, starting: true },
      { name: 'Abdallah Nasib', position: 'DEF', overall: 87, starting: true },
      { name: 'Saleem Obaid', position: 'DEF', overall: 86, starting: true },
      { name: 'Anas Banawi', position: 'DEF', overall: 85, starting: true },
      { name: 'Mohammad Al Dawoud', position: 'MID', overall: 89, starting: true },
      { name: 'Noor Al Rawabdeh', position: 'MID', overall: 89, starting: true },
      { name: 'Amer Jamous', position: 'MID', overall: 87, starting: true },
      { name: 'Rajaei Ayed', position: 'MID', overall: 86, starting: true },
      { name: 'Mousa Al Tamari', position: 'FWD', overall: 98, starting: true },
      { name: 'Ali Olwan', position: 'FWD', overall: 94, starting: true },
      { name: 'Abdallah Al Fakhouri', position: 'GK', overall: 84, starting: false },
      { name: 'Ehsan Haddad', position: 'DEF', overall: 83, starting: false },
      { name: 'Mohannad Abu Taha', position: 'DEF', overall: 82, starting: false },
      { name: 'Ibrahim Sadeh', position: 'MID', overall: 84, starting: false },
      { name: 'Nizar Al Rashdan', position: 'MID', overall: 84, starting: false },
      { name: 'Yazan Al-Naimat', position: 'FWD', overall: 90, starting: false },
    ],
  },
  {
    id: 'm26-portugalia',
    label: 'Portugalia',
    players: [
      { name: 'Diogo Costa', position: 'GK', overall: 106, starting: true },
      { name: 'Ruben Dias', position: 'DEF', overall: 113, starting: true },
      { name: 'Nuno Mendes', position: 'DEF', overall: 103, starting: true },
      { name: 'Antonio Silva', position: 'DEF', overall: 101, starting: true },
      { name: 'Diogo Dalot', position: 'DEF', overall: 99, starting: true },
      { name: 'Vitinha', position: 'MID', overall: 114, starting: true },
      { name: 'Bruno Fernandes', position: 'MID', overall: 107, starting: true },
      { name: 'Joao Neves', position: 'MID', overall: 104, starting: true },
      { name: 'Bernardo Silva', position: 'MID', overall: 106, starting: true },
      { name: 'Cristiano Ronaldo', position: 'FWD', overall: 107, starting: true },
      { name: 'Rafael Leao', position: 'FWD', overall: 106, starting: true },
      { name: 'Jose Sa', position: 'GK', overall: 98, starting: false },
      { name: 'Goncalo Inacio', position: 'DEF', overall: 101, starting: false },
      { name: 'Joao Cancelo', position: 'DEF', overall: 102, starting: false },
      { name: 'Ruben Neves', position: 'MID', overall: 102, starting: false },
      { name: 'Matheus Nunes', position: 'MID', overall: 101, starting: false },
      { name: 'Goncalo Ramos', position: 'FWD', overall: 102, starting: false },
    ],
  },
  {
    id: 'm26-dr-konga',
    label: 'DR Konga',
    players: [
      { name: 'Lionel Mpasi', position: 'GK', overall: 93, starting: true },
      { name: 'Chancel Mbemba', position: 'DEF', overall: 100, starting: true },
      { name: 'Arthur Masuaku', position: 'DEF', overall: 97, starting: true },
      { name: 'Joris Kayembe', position: 'DEF', overall: 95, starting: true },
      { name: 'Rocky Bushiri', position: 'DEF', overall: 94, starting: true },
      { name: 'Samuel Moutoussamy', position: 'MID', overall: 96, starting: true },
      { name: 'Edo Kayembe', position: 'MID', overall: 95, starting: true },
      { name: 'Charles Pickel', position: 'MID', overall: 93, starting: true },
      { name: 'Gael Kakuta', position: 'MID', overall: 93, starting: true },
      { name: 'Cedric Bakambu', position: 'FWD', overall: 95, starting: true },
      { name: 'Yoane Wissa', position: 'FWD', overall: 100, starting: true },
      { name: 'Timothy Fayulu', position: 'GK', overall: 87, starting: false },
      { name: 'Steve Kapuadi', position: 'DEF', overall: 88, starting: false },
      { name: 'Dylan Batubinsika', position: 'DEF', overall: 88, starting: false },
      { name: 'Noah Sadiki', position: 'MID', overall: 95, starting: false },
      { name: 'Theo Bongonda', position: 'MID', overall: 93, starting: false },
      { name: 'Fiston Mayele', position: 'FWD', overall: 92, starting: false },
    ],
  },
  {
    id: 'm26-uzbekistan',
    label: 'Uzbekistan',
    players: [
      { name: 'Utkir Yusupov', position: 'GK', overall: 92, starting: true },
      { name: 'Abdukodir Khusanov', position: 'DEF', overall: 102, starting: true },
      { name: 'Rustam Ashurmatov', position: 'DEF', overall: 93, starting: true },
      { name: 'Farrukh Sayfiev', position: 'DEF', overall: 91, starting: true },
      { name: 'Sherzod Nasrullaev', position: 'DEF', overall: 90, starting: true },
      { name: 'Abbosbek Fayzullaev', position: 'MID', overall: 98, starting: true },
      { name: 'Jaloliddin Masharipov', position: 'MID', overall: 93, starting: true },
      { name: 'Jamshid Iskanderov', position: 'MID', overall: 90, starting: true },
      { name: 'Odiljon Hamrobekov', position: 'MID', overall: 89, starting: true },
      { name: 'Eldor Shomurodov', position: 'FWD', overall: 100, starting: true },
      { name: 'Igor Sergeev', position: 'FWD', overall: 91, starting: true },
      { name: 'Abduvohid Nematov', position: 'GK', overall: 88, starting: false },
      { name: 'Khojiakbar Alijonov', position: 'DEF', overall: 89, starting: false },
      { name: 'Umar Eshmurodov', position: 'DEF', overall: 88, starting: false },
      { name: 'Dostonbek Khamdamov', position: 'MID', overall: 91, starting: false },
      { name: 'Otabek Shukurov', position: 'MID', overall: 89, starting: false },
      { name: 'Azizbek Amonov', position: 'FWD', overall: 89, starting: false },
    ],
  },
  {
    id: 'm26-kolumbia',
    label: 'Kolumbia',
    players: [
      { name: 'Camilo Vargas', position: 'GK', overall: 101, starting: true },
      { name: 'Davinson Sanchez', position: 'DEF', overall: 103, starting: true },
      { name: 'Yerry Mina', position: 'DEF', overall: 102, starting: true },
      { name: 'Daniel Munoz', position: 'DEF', overall: 103, starting: true },
      { name: 'Johan Mojica', position: 'DEF', overall: 100, starting: true },
      { name: 'Jefferson Lerma', position: 'MID', overall: 101, starting: true },
      { name: 'Richard Rios', position: 'MID', overall: 103, starting: true },
      { name: 'James Rodriguez', position: 'MID', overall: 105, starting: true },
      { name: 'Jorge Carrascal', position: 'MID', overall: 100, starting: true },
      { name: 'Luis Diaz', position: 'FWD', overall: 111, starting: true },
      { name: 'Jhon Cordoba', position: 'FWD', overall: 99, starting: true },
      { name: 'David Ospina', position: 'GK', overall: 94, starting: false },
      { name: 'Jhon Lucumi', position: 'DEF', overall: 99, starting: false },
      { name: 'Santiago Arias', position: 'DEF', overall: 96, starting: false },
      { name: 'Juan Fernando Quintero', position: 'MID', overall: 98, starting: false },
      { name: 'Kevin Castano', position: 'MID', overall: 96, starting: false },
      { name: 'Jhon Arias', position: 'FWD', overall: 99, starting: false },
    ],
  },
  {
    id: 'm26-anglia',
    label: 'Anglia',
    players: [
      { name: 'Jordan Pickford', position: 'GK', overall: 104, starting: true },
      { name: 'John Stones', position: 'DEF', overall: 103, starting: true },
      { name: 'Marc Guehi', position: 'DEF', overall: 101, starting: true },
      { name: 'Reece James', position: 'DEF', overall: 103, starting: true },
      { name: 'Ezri Konsa', position: 'DEF', overall: 98, starting: true },
      { name: 'Declan Rice', position: 'MID', overall: 112, starting: true },
      { name: 'Jude Bellingham', position: 'MID', overall: 118, starting: true },
      { name: 'Eberechi Eze', position: 'MID', overall: 103, starting: true },
      { name: 'Kobbie Mainoo', position: 'MID', overall: 101, starting: true },
      { name: 'Harry Kane', position: 'FWD', overall: 116, starting: true },
      { name: 'Bukayo Saka', position: 'FWD', overall: 113, starting: true },
      { name: 'Dean Henderson', position: 'GK', overall: 101, starting: false },
      { name: 'Dan Burn', position: 'DEF', overall: 101, starting: false },
      { name: 'Djed Spence', position: 'DEF', overall: 100, starting: false },
      { name: 'Morgan Rogers', position: 'MID', overall: 102, starting: false },
      { name: 'Jordan Henderson', position: 'MID', overall: 100, starting: false },
      { name: 'Marcus Rashford', position: 'FWD', overall: 105, starting: false },
    ],
  },
  {
    id: 'm26-chorwacja',
    label: 'Chorwacja',
    players: [
      { name: 'Dominik Livakovic', position: 'GK', overall: 101, starting: true },
      { name: 'Josko Gvardiol', position: 'DEF', overall: 110, starting: true },
      { name: 'Josip Sutalo', position: 'DEF', overall: 101, starting: true },
      { name: 'Josip Stanisic', position: 'DEF', overall: 100, starting: true },
      { name: 'Marin Pongracic', position: 'DEF', overall: 98, starting: true },
      { name: 'Luka Modric', position: 'MID', overall: 105, starting: true },
      { name: 'Mateo Kovacic', position: 'MID', overall: 104, starting: true },
      { name: 'Martin Baturina', position: 'MID', overall: 100, starting: true },
      { name: 'Petar Sucic', position: 'MID', overall: 100, starting: true },
      { name: 'Ivan Perisic', position: 'FWD', overall: 99, starting: true },
      { name: 'Andrej Kramaric', position: 'FWD', overall: 99, starting: true },
      { name: 'Ivor Pandur', position: 'GK', overall: 89, starting: false },
      { name: 'Duje Caleta-Car', position: 'DEF', overall: 97, starting: false },
      { name: 'Martin Erlic', position: 'DEF', overall: 96, starting: false },
      { name: 'Nikola Vlasic', position: 'MID', overall: 99, starting: false },
      { name: 'Luka Sucic', position: 'MID', overall: 99, starting: false },
      { name: 'Ante Budimir', position: 'FWD', overall: 96, starting: false },
    ],
  },
  {
    id: 'm26-ghana',
    label: 'Ghana',
    players: [
      { name: 'Lawrence Ati-Zigi', position: 'GK', overall: 95, starting: true },
      { name: 'Alidu Seidu', position: 'DEF', overall: 95, starting: true },
      { name: 'Abdul Mumin', position: 'DEF', overall: 96, starting: true },
      { name: 'Baba Abdul Rahman', position: 'DEF', overall: 95, starting: true },
      { name: 'Gideon Mensah', position: 'DEF', overall: 93, starting: true },
      { name: 'Thomas Partey', position: 'MID', overall: 100, starting: true },
      { name: 'Elisha Owusu', position: 'MID', overall: 93, starting: true },
      { name: 'Kamaldeen Sulemana', position: 'MID', overall: 97, starting: true },
      { name: 'Abdul Fatawu Issahaku', position: 'MID', overall: 96, starting: true },
      { name: 'Inaki Williams', position: 'FWD', overall: 100, starting: true },
      { name: 'Jordan Ayew', position: 'FWD', overall: 96, starting: true },
      { name: 'Joseph Anang', position: 'GK', overall: 88, starting: false },
      { name: 'Jerome Opoku', position: 'DEF', overall: 89, starting: false },
      { name: 'Derrick Luckassen', position: 'DEF', overall: 90, starting: false },
      { name: 'Augustine Boakye', position: 'MID', overall: 91, starting: false },
      { name: 'Caleb Yirenkyi', position: 'MID', overall: 89, starting: false },
      { name: 'Antoine Semenyo', position: 'FWD', overall: 99, starting: false },
    ],
  },
  {
    id: 'm26-panama',
    label: 'Panama',
    players: [
      { name: 'Orlando Mosquera', position: 'GK', overall: 92, starting: true },
      { name: 'Cesar Blackman', position: 'DEF', overall: 90, starting: true },
      { name: 'Fidel Escobar', position: 'DEF', overall: 92, starting: true },
      { name: 'Andres Andrade', position: 'DEF', overall: 91, starting: true },
      { name: 'Amir Murillo', position: 'DEF', overall: 92, starting: true },
      { name: 'Anibal Godoy', position: 'MID', overall: 94, starting: true },
      { name: 'Adalberto Carrasquilla', position: 'MID', overall: 94, starting: true },
      { name: 'Carlos Harvey', position: 'MID', overall: 89, starting: true },
      { name: 'Cristian Martinez', position: 'MID', overall: 88, starting: true },
      { name: 'Ismael Diaz', position: 'FWD', overall: 95, starting: true },
      { name: 'Cecilio Waterman', position: 'FWD', overall: 90, starting: true },
      { name: 'Luis Mejia', position: 'GK', overall: 86, starting: false },
      { name: 'Jorge Gutierrez', position: 'DEF', overall: 86, starting: false },
      { name: 'Jose Cordoba', position: 'DEF', overall: 87, starting: false },
      { name: 'Yoel Barcenas', position: 'MID', overall: 89, starting: false },
      { name: 'Jose Luis Rodriguez', position: 'MID', overall: 87, starting: false },
      { name: 'Tomas Rodriguez', position: 'FWD', overall: 87, starting: false },
    ],
  },
);

window.MUNDIAL26_GROUPS = {
  A: ['m26-meksyk', 'm26-republika-poludniowej-afryki', 'm26-korea-poludniowa', 'm26-czechy'],
  B: ['m26-kanada', 'm26-bosnia-i-hercegowina', 'm26-katar', 'm26-szwajcaria'],
  C: ['m26-brazylia', 'm26-maroko', 'm26-haiti', 'm26-szkocja'],
  D: ['m26-usa', 'm26-paragwaj', 'm26-australia', 'm26-turcja'],
  E: ['m26-niemcy', 'm26-cura-ao', 'm26-wybrzeze-kosci-sloniowej', 'm26-ekwador'],
  F: ['m26-holandia', 'm26-japonia', 'm26-polska', 'm26-tunezja'],
  G: ['m26-belgia', 'm26-egipt', 'm26-iran', 'm26-nowa-zelandia'],
  H: ['m26-hiszpania', 'm26-republika-zielonego-przyladka', 'm26-arabia-saudyjska', 'm26-urugwaj'],
  I: ['m26-francja', 'm26-senegal', 'm26-irak', 'm26-norwegia'],
  J: ['m26-argentyna', 'm26-algieria', 'm26-austria', 'm26-jordania'],
  K: ['m26-portugalia', 'm26-dr-konga', 'm26-uzbekistan', 'm26-kolumbia'],
  L: ['m26-anglia', 'm26-chorwacja', 'm26-ghana', 'm26-panama'],
};
